// export_segy: a stored volume handed over as SEG-Y rev 1 (QI programme Q11,
// 2026-10-07; SOW section 12): stacks, attribute and inversion products and
// property volumes, by the engines' writer (engines/seismolord/segyWrite.js,
// validated by segyio read-back). Traces go out in inline then crossline
// order, one brick row of inlines at a time, straight into a multipart
// upload in the worker's work bucket; all-null traces (outside the survey)
// are left out. The result is a download link valid for 24 hours; the
// janitor deletes the file after EXPORT_RETENTION_DAYS (janitor.js).
//
// params: { volume_id, coord_scalar? (default -100) }
// The worker uses the service role, so this handler checks what RLS would:
// the volume belongs to the job's user and is complete.
import { JobFailure } from '../runJob.js';
import {
  textualHeader, binaryHeader, traceHeader, traceSamples, segyFileBytes,
} from '../../../../packages/engines/engines/seismolord/segyWrite.js';
import { assertFloat32Parent } from '../../../../src/pages/apps/Seismolord/services/attributeSurveyMeta.js';
import { storageBrickFetcher } from '../../../../packages/engines/engines/seismolord/brickCache.js';
import { v4BrickFetcher } from '../../../../packages/engines/engines/seismolord/brickCodecV4.js';
import { geomFromManifest, brickKey } from '../../../../packages/engines/engines/seismolord/sliceAssembly.js';
import { surveyAffine, ilxlToWorld } from '../../../../packages/engines/engines/seismolord/surveyGeometry.js';
import { PART_SIZE, MAX_FILE_BYTES, parseUploadId, completeXml } from '../../../../supabase/functions/qi-upload-url/logic.ts';
import { multipartWriter } from '../s3.js';

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const LINK_TTL_S = 24 * 3600;
const NULL_LIM = 1e29;
const GiB = 1024 ** 3;

export function validateExportParams(p) {
  if (!p || typeof p !== 'object') return 'Missing job settings.';
  if (!UUID.test(String(p.volume_id))) return 'volume_id is required.';
  if (p.coord_scalar != null && ![-1000, -100, -10, 1].includes(p.coord_scalar)) return 'coord_scalar must be -1000, -100, -10 or 1.';
  return null;
}

export const exportFileName = (name) => `${String(name || 'volume').replace(/[^A-Za-z0-9._-]+/g, '_').replace(/^\.+/, '').slice(0, 100) || 'volume'}.sgy`;

/** The textual header cards for a volume. */
export function exportCards({ volume, manifest, engineCommit, coordScalar }) {
  const g = manifest.geometry;
  const ap = manifest.attribute?.params || {};
  const what = manifest.attribute
    ? `${manifest.attribute.name}${ap.method ? `, ${ap.method}` : ''}${ap.product ? `, ${ap.product}` : ''}${ap.qi_class ? `, ${ap.qi_class}` : ''}`
    : 'seismic stack';
  return [
    `Petrolord Suite export of ${volume.name}`.slice(0, 76),
    `Volume ${volume.id}`,
    `Content: ${what}`.slice(0, 76),
    `Inlines ${g.il.min} to ${g.il.max} step ${g.il.step}, crosslines ${g.xl.min} to ${g.xl.max} step ${g.xl.step}`.slice(0, 76),
    `${g.ns} samples at ${g.dt_us} us, IEEE float, big-endian, SEG-Y rev 1`,
    'Inline byte 189, crossline 193, CDP X 181, CDP Y 185',
    `Coordinate scalar ${coordScalar} at byte 71${volume.crs ? `, CRS ${volume.crs}` : ''}`.slice(0, 76),
    'Null samples are written as 0; traces outside the survey are left out',
    `Engine ${engineCommit || 'unknown'}`.slice(0, 76),
    'Generated by the Petrolord seismic worker',
  ];
}

export async function exportSegy(ctx, deps) {
  const p = ctx.params || {};
  const problem = validateExportParams(p);
  if (problem) throw new JobFailure('validate_failed', problem);
  const uid = ctx.job.user_id;
  const { admin, sign, workBucket = 'seismic-work' } = deps;
  const fetchImpl = deps.fetchImpl || fetch;
  const coordScalar = p.coord_scalar ?? -100;

  const { data: vol, error } = await admin.from('seismic_volumes')
    .select('id,user_id,status,name,storage_path,crs').eq('id', p.volume_id).maybeSingle();
  if (error) throw new Error(`Could not read volume ${p.volume_id}: ${error.message}`);
  if (!vol || vol.user_id !== uid) throw new JobFailure('not_found', 'The volume was not found in your account. Server export runs on your own volumes.');
  if (vol.status !== 'ready') throw new JobFailure('validate_failed', `The volume is ${vol.status}; only a complete volume can be exported.`);
  const readManifest = deps.readManifest || (async (path) => {
    const { data, error: e } = await admin.storage.from('seismic').download(path);
    if (e) throw new Error(`Could not read the volume manifest: ${e.message}`);
    return JSON.parse(await data.text());
  });
  const manifest = await readManifest(`${vol.storage_path}/manifest.json`);
  try { assertFloat32Parent(manifest); } catch (e) { throw new JobFailure('validate_failed', e.message); }
  const geom = geomFromManifest(manifest);
  const { nIl, nXl, ns, brickSize: b } = geom;
  const [ni, nj, nk] = geom.grid;
  const dtUs = Number(manifest.geometry.dt_us);
  const g = manifest.geometry;
  const upper = segyFileBytes(ns, nIl * nXl);
  if (upper > MAX_FILE_BYTES) throw new JobFailure('too_large', `The export would be up to ${(upper / GiB).toFixed(1)} GiB; the limit is ${MAX_FILE_BYTES / GiB} GiB.`);
  const aff = surveyAffine(g);
  const fetcher = deps.makeFetcher
    ? deps.makeFetcher(manifest)
    : v4BrickFetcher(storageBrickFetcher({ supabaseUrl: deps.supabaseUrl, getToken: async () => deps.serviceRoleKey, bucket: 'seismic' }), manifest);
  const fetchBrick = async (i, j, k) => new Float32Array(await fetcher(brickKey(vol.storage_path, i, j, k)));

  const fileName = exportFileName(vol.name);
  const key = `exports/${uid}/${ctx.job.id}/${fileName}`;
  const out = await multipartWriter({ sign, bucket: workBucket, key, fetchImpl, partSize: deps.partSize || PART_SIZE, parseUploadId, completeXml });
  const write = (bytes) => out.write(bytes);
  const abort = () => out.abort();
  let total = 0;

  let traces = 0;
  try {
    await write(textualHeader(exportCards({ volume: vol, manifest, engineCommit: deps.engineCommit, coordScalar })));
    await write(binaryHeader({ dtUs, ns }));
    const trace = new Float32Array(ns);
    for (let bi = 0; bi < ni; bi++) {
      if (ctx.cancelled) { await abort(); return null; }
      // one brick row: every crossline column of these inlines
      const row = [];
      for (let bj = 0; bj < nj; bj++) row.push(await Promise.all(Array.from({ length: nk }, (_, bk) => fetchBrick(bi, bj, bk))));
      for (let li = 0; li < b && bi * b + li < nIl; li++) {
        const il = bi * b + li;
        for (let xl = 0; xl < nXl; xl++) {
          const bricks = row[Math.floor(xl / b)];
          const base = (li * b + (xl % b)) * b;
          let live = false;
          for (let s = 0; s < ns; s++) {
            const v = bricks[Math.floor(s / b)][base + (s % b)];
            trace[s] = v;
            if (!live && Math.abs(v) <= NULL_LIM) live = true;
          }
          if (!live) continue;
          const w = aff ? ilxlToWorld(aff, il, xl) : { x: 0, y: 0 };
          traces += 1;
          await write(traceHeader({ seq: traces, il: g.il.min + il * g.il.step, xl: g.xl.min + xl * g.xl.step, x: w.x, y: w.y, ns, dtUs, coordScalar }));
          await write(traceSamples(trace));
        }
      }
      ctx.progress(0.98 * ((bi + 1) / ni), `Writing inlines, ${traces} traces`);
    }
    if (!traces) throw new JobFailure('validate_failed', 'The volume has no live traces to export.');
    total = (await out.finish()).bytes;
  } catch (e) {
    await abort();
    throw e;
  }
  const expiresAt = new Date(Date.now() + LINK_TTL_S * 1000).toISOString();
  const url = await sign('GET', workBucket, key, { 'response-content-disposition': `attachment; filename="${fileName}"` }, LINK_TTL_S);
  ctx.progress(1, 'Done');
  return { volume_id: vol.id, volume_name: vol.name, bucket: workBucket, key, file_name: fileName, bytes: total, traces, url, expires_at: expiresAt };
}
