// The saved SCAL and Fluid projects the Waterflood e2e seeds into the harness
// (e2e/fixtures/waterflood/*.json), generated by the SCAL and Fluid test kits
// so they carry real kr-1 and pvt-1 blocks. UPDATE_REPORT_GOLDENS=1 rewrites them.
import fs from 'fs';
import path from 'path';
import { DEV_USER } from '@/dev/InMemorySupabase';
import { identifiedFitted, stateOf as scalStateOf } from '@/components/scalstudio/__tests__/scalTestKit';
import { goodOilBlackOil, matched, run } from '@/components/fluidstudio/__tests__/fluidTestKit';
import { validateKrContract } from '@/lib/inputProvenance/krContract';
import { validatePvtContract } from '@/lib/inputProvenance/pvtContract';

const DIR = path.join(process.cwd(), 'e2e', 'fixtures', 'waterflood');
const SCAL_ID = '5ca10000-0000-4000-8000-00000000e2e1';
const FLUID_ID = 'f1d00000-0000-4000-8000-00000000e2e1';
const TS = '2026-10-04T09:00:00.000Z';

function rows() {
  const scal = scalStateOf(identifiedFitted(), { projectId: SCAL_ID, projectName: 'Ekene E-2000 SCAL' }).contract;
  const fluid = { ...run(matched(goodOilBlackOil()), { projectName: 'Good Oil Well No. 4 PVT' }).contract, project_id: FLUID_ID };
  return {
    scal: [{ id: SCAL_ID, user_id: DEV_USER.id, project_name: 'Ekene E-2000 SCAL', inputs_data: { name: 'Ekene E-2000 SCAL', kr: scal }, created_at: TS, updated_at: TS }],
    fluid: [{ id: FLUID_ID, user_id: DEV_USER.id, project_name: 'Good Oil Well No. 4 PVT', inputs_data: { name: 'Good Oil Well No. 4 PVT', pvt: fluid }, created_at: TS, updated_at: TS }],
  };
}

it('the e2e fixtures carry valid kr-1 and pvt-1 blocks and match the kits', () => {
  const r = rows();
  expect(validateKrContract(r.scal[0].inputs_data.kr).ok).toBe(true);
  expect(validatePvtContract(r.fluid[0].inputs_data.pvt).ok).toBe(true);
  const file = (n) => path.join(DIR, n);
  if (process.env.UPDATE_REPORT_GOLDENS === '1' || !fs.existsSync(file('scal-rows.json'))) {
    fs.writeFileSync(file('scal-rows.json'), `${JSON.stringify(r.scal)}\n`);
    fs.writeFileSync(file('fluid-rows.json'), `${JSON.stringify(r.fluid)}\n`);
  }
  expect(JSON.parse(fs.readFileSync(file('scal-rows.json'), 'utf8'))).toEqual(JSON.parse(JSON.stringify(r.scal)));
  expect(JSON.parse(fs.readFileSync(file('fluid-rows.json'), 'utf8'))).toEqual(JSON.parse(JSON.stringify(r.fluid)));
});
