/**
 * FS2 gates — PR78 core vs the independent Python oracle + NIST data.
 *
 * GATE B (oracle): Z roots, lowest-Gibbs selection, ln(phi), Peneloux
 * volumes/densities and pure Psat must match goldens.json, generated by
 * tools/validation/fluidstudio/genfixtures.py. The oracle solves the
 * cubic by bracketed bisection, gets ln(phi) by residual-Helmholtz
 * quadrature and Psat by Maxwell equal areas — all routes independent
 * of this engine's Cardano / closed-form / fugacity-equality code.
 * GATE C (NIST): purePsat reproduces measured vapor pressures
 * (normal boiling points; CO2 at 0 °C) within honest per-point bands.
 * Identity gates: exact thermodynamic truths (ideal-gas limit, cubic
 * residual, split/permutation invariance, omega definition at Tr 0.7,
 * Peneloux not touching equilibrium quantities).
 */

import { COMPONENTS } from '../components';
import { R_PSIA, KtoR, degFtoR } from '../units';
import {
  kappaPR78, mixtureFromKeys, mixParams, solveCubicZ, phaseProps, purePsat,
} from '../pr78';
import goldens from './goldens.json';
import nist from './nistVaporPressure.json';

const KPA_PER_PSIA = 6.894757;

const relErr = (a, b) => Math.abs(a - b) / Math.max(Math.abs(b), 1e-300);

describe('FS2 GATE B: PR78 engine vs independent Python oracle goldens', () => {
  test('BIP matrix matches the independently transcribed oracle table', () => {
    const mix = mixtureFromKeys(goldens.bipKeys);
    expect(mix.bip).toEqual(goldens.bipMatrix);
  });

  describe.each(goldens.mixtures)('mixture $name', ({ keys, x, states }) => {
    const mix = mixtureFromKeys(keys);
    test.each(states)('$tF F / $pPsia psia', (st) => {
      const props = phaseProps(mix, x, degFtoR(st.tF), st.pPsia);
      expect(props.roots.length).toBe(st.roots.length);
      props.roots.forEach((z, i) => expect(relErr(z, st.roots[i])).toBeLessThan(1e-9));
      expect(relErr(props.zFactor, st.z)).toBeLessThan(1e-10);
      props.lnPhi.forEach((lp, i) => expect(Math.abs(lp - st.lnPhi[i])).toBeLessThan(1e-8));
      expect(relErr(props.molarVolume, st.molarVolume)).toBeLessThan(1e-9);
      expect(relErr(props.density, st.density)).toBeLessThan(1e-9);
    });
  });

  test.each(goldens.purePsat)('purePsat $key at $tR R vs Maxwell construction', ({ key, tR, psatPsia }) => {
    expect(relErr(purePsat(COMPONENTS[key], tR), psatPsia)).toBeLessThan(1e-7);
  });
});

describe('FS2 GATE C: pure vapor pressures vs NIST measurements', () => {
  test.each(nist.points)('$key at $tK K within $relTol', ({ key, tK, pKPa, relTol }) => {
    const psat = purePsat(COMPONENTS[key], KtoR(tK));
    expect(relErr(psat, pKPa / KPA_PER_PSIA)).toBeLessThan(relTol);
  });

  test('omega definition recovered at Tr = 0.7 (log10 Pr = -(1 + omega))', () => {
    for (const key of Object.keys(COMPONENTS)) {
      const c = COMPONENTS[key];
      const psat = purePsat(c, 0.7 * c.tcR);
      const omegaImplied = -Math.log10(psat / c.pcPsia) - 1;
      expect(Math.abs(omegaImplied - c.omega)).toBeLessThan(0.02);
    }
  });
});

describe('FS2 identity gates', () => {
  const mix = mixtureFromKeys(['C1', 'CO2', 'nC5']);
  const x = [0.6, 0.1, 0.3];
  const tR = degFtoR(180);

  test('kappa uses the 1978 heavy branch above omega 0.491', () => {
    expect(kappaPR78(0.3)).toBeCloseTo(0.37464 + 1.54226 * 0.3 - 0.26992 * 0.09, 12);
    const w = 0.6;
    expect(kappaPR78(w)).toBeCloseTo(
      0.379642 + 1.48503 * w - 0.164423 * w * w + 0.016666 * w ** 3, 12,
    );
  });

  test('ideal-gas limit: Z -> 1 and lnPhi -> 0 as P -> 0', () => {
    const props = phaseProps(mix, x, tR, 0.01);
    expect(Math.abs(props.zFactor - 1)).toBeLessThan(1e-4);
    props.lnPhi.forEach((lp) => expect(Math.abs(lp)).toBeLessThan(1e-3));
  });

  test('chosen root satisfies the cubic to near machine precision', () => {
    for (const p of [100, 1000, 4000]) {
      const { A, B, zFactor } = phaseProps(mix, x, tR, p);
      const res = zFactor ** 3 - (1 - B) * zFactor ** 2
        + (A - 3 * B * B - 2 * B) * zFactor - (A * B - B * B - B ** 3);
      expect(Math.abs(res)).toBeLessThan(1e-12);
    }
  });

  test('split invariance: duplicating a component leaves the state unchanged', () => {
    const pure = phaseProps(mixtureFromKeys(['C3']), [1], tR, 300);
    const split = phaseProps(
      mixtureFromKeys(['C3', 'C3b'], { C3b: { ...COMPONENTS.C3 } }),
      [0.35, 0.65], tR, 300,
    );
    expect(split.zFactor).toBeCloseTo(pure.zFactor, 12);
    expect(split.density).toBeCloseTo(pure.density, 10);
    split.lnPhi.forEach((lp) => expect(lp).toBeCloseTo(pure.lnPhi[0], 12));
  });

  test('permutation invariance: reordering components permutes lnPhi exactly', () => {
    const fwd = phaseProps(mix, x, tR, 800);
    const rev = phaseProps(mixtureFromKeys(['nC5', 'CO2', 'C1']), [0.3, 0.1, 0.6], tR, 800);
    expect(rev.zFactor).toBeCloseTo(fwd.zFactor, 12);
    expect(rev.lnPhi[0]).toBeCloseTo(fwd.lnPhi[2], 12);
    expect(rev.lnPhi[1]).toBeCloseTo(fwd.lnPhi[1], 12);
    expect(rev.lnPhi[2]).toBeCloseTo(fwd.lnPhi[0], 12);
  });

  test('Peneloux shifts volumes only: equilibrium quantities untouched', () => {
    const noShift = mixtureFromKeys(['C1', 'nC5']);
    noShift.comps = noShift.comps.map((c) => ({ ...c, shift: 0 }));
    const a = phaseProps(mixtureFromKeys(['C1', 'nC5']), [0.4, 0.6], tR, 500);
    const b = phaseProps(noShift, [0.4, 0.6], tR, 500);
    expect(a.zFactor).toBe(b.zFactor);
    a.lnPhi.forEach((lp, i) => expect(lp).toBe(b.lnPhi[i]));
    expect(a.molarVolume).not.toBe(b.molarVolume);
    expect(b.molarVolume).toBeCloseTo(b.molarVolumeEos, 12);
  });

  test('root selection: liquid and vapor branches bracket the Gibbs choice', () => {
    // binary C1/nC4 inside the three-root window (from the goldens grid)
    const bin = mixtureFromKeys(['C1', 'nC4']);
    const xb = [0.35, 0.65];
    const tRb = degFtoR(100);
    const gibbs = phaseProps(bin, xb, tRb, 100);
    const liq = phaseProps(bin, xb, tRb, 100, { root: 'min' });
    const vap = phaseProps(bin, xb, tRb, 100, { root: 'max' });
    expect(gibbs.roots.length).toBe(3);
    expect(liq.zFactor).toBeLessThan(vap.zFactor);
    expect([liq.zFactor, vap.zFactor]).toContain(gibbs.zFactor);
    const g = (p) => p.lnPhi.reduce((s, lp, i) => s + xb[i] * lp, 0);
    expect(g(gibbs)).toBeLessThanOrEqual(Math.min(g(liq), g(vap)) + 1e-14);
  });

  test('solveCubicZ handles the single-root regime', () => {
    const { A, B } = mixParams(mixtureFromKeys(['C1']), [1], degFtoR(300), 5000);
    const roots = solveCubicZ(A, B);
    expect(roots.length).toBe(1);
    expect(roots[0]).toBeGreaterThan(B);
  });

  test('R constant consistency with units.js', () => {
    expect(R_PSIA).toBeCloseTo(10.7316, 10);
  });
});
