/**
 * The model of the Reservoir Simulation report (SIM-U1; reviewer lens RL1
 * to RL12). One object for the Report tab and the PDF: identification, the
 * run's provenance, what the deck holds, the builder inputs with their
 * sources (when the case's saved builder form made the deck that ran), the
 * results, the material balance and convergence the simulator printed, the
 * limits and the flags. Everything comes from the run row, its summary.json
 * (the worker's reading of the simulator output), the deck text and the
 * saved form; nothing here simulates or recomputes a result.
 *
 * Pure.
 */
import { EMPTY_VALUE } from '@/lib/emptyValue';
import { inputRow } from '@/lib/inputProvenance/wording';
import { simUnits, displayUnitsLine, prtShow } from './simUnits.js';
import { summarizeDeck, deckSystemText } from './deckSummary.js';
import { summaryUnitSystem, lastValue, dayToIso } from './series.js';
import { krEditedKeys, THREE_PHASE_WORDS } from './builderIntakes.js';
import { pvtContractTuningText, PVT1_PB_SOURCES } from '@/lib/inputProvenance/pvtContract';
import { bhpMatch } from './bhpMatch.js';
import { AQUIFER_MODELS, AQUIFER_FACE_WORDS, aquiferEditedKeys } from './aquiferIntake.js';
import { krSetText, krCapillaryText } from '@/lib/inputProvenance/krContract';

export const REPORT_TITLE = 'Reservoir Simulation Report';
export const APP_NAME = 'Petrolord Reservoir Simulation Studio';
export const ANALYSIS_TYPE = 'Black-oil reservoir simulation, OPM Flow (finite-volume, fully implicit)';
export const IDENTIFICATION = Object.freeze([
  ['company', 'Company'], ['field', 'Field'], ['licence', 'Licence or block'], ['reservoir', 'Reservoir or zone'], ['analyst', 'Analyst'],
]);
/** The text the report prints for a quantity a summary written before the worker read the PRT does not hold. */
export const NOT_REPORTED = 'not reported by this build';
export const NOT_REPORTED_WHY = 'The run was made by a simulation worker build that did not yet read the simulator\'s PRT file. Run the case again once the worker is redeployed.';

const finite = (v) => typeof v === 'number' && Number.isFinite(v);
const text = (v) => (v != null && String(v).trim() !== '' ? String(v).trim() : '');
const fx = (v, d = 0) => (finite(v) ? Number(v).toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d }) : EMPTY_VALUE);
const g = (v, s = 4) => (finite(v) ? String(parseFloat(Number(v).toPrecision(s))) : EMPTY_VALUE);
const utc = (iso) => (iso && !Number.isNaN(Date.parse(iso)) ? `${new Date(iso).toISOString().slice(0, 19).replace('T', ' ')} UTC` : EMPTY_VALUE);

const MB_REASONS = Object.freeze({
  no_prt: 'the simulator wrote no PRT file the worker could read',
  no_fip_report: 'the deck does not ask for the fluid-in-place report (RPTSOL or RPTSCHED FIP)',
  no_well_totals: 'the deck does not ask for the well reports with the cumulative totals (RPTSCHED WELLS)',
  no_common_report: 'no report step holds both the balance sheet and the well totals',
  units_not_verified: 'the deck is in units whose PRT table labels have not been checked against a run (FIELD and METRIC have been)',
});

export const SOURCE_WORDS = Object.freeze({
  template: 'Bundled SPE benchmark template',
  upload: 'Uploaded deck files',
  generated: 'Generated by the Model Builder',
});

/**
 * Whether the saved builder form made the deck of this run: the form records
 * the SHA-256 of the deck it generated, the worker the SHA-256 of the deck it
 * ran. Equal: the inputs table applies. Otherwise the report says why not.
 */
export function formAppliesToRun(form, run, caseRow) {
  if (!form) return { applies: false, reason: 'No builder form is saved with this case.' };
  if (caseRow?.deck_source !== 'generated') return { applies: false, reason: `The deck that ran is ${String(SOURCE_WORDS[caseRow?.deck_source] || 'not a generated deck').toLowerCase()}, so the builder inputs did not make it.` };
  const made = form.lastGenerated?.deckSha256;
  if (!made) return { applies: false, reason: 'The saved builder form does not record the deck it generated (it was saved before October 2026).' };
  if (!run?.deck_sha256 || run.deck_sha256 !== made) return { applies: false, reason: 'The deck that ran differs from the last deck the builder generated (it was edited on the Deck tab, or generated again after the run).' };
  return { applies: true, reason: null };
}

function identificationPairs({ caseRow, form, organizationName, run, summary }) {
  const id = form?.identification || {};
  const pairs = [['Case', text(caseRow?.name) || EMPTY_VALUE]];
  for (const [key, label] of IDENTIFICATION) {
    let v = text(id[key]);
    if (key === 'company' && !v) v = text(organizationName);
    pairs.push([label, v || EMPTY_VALUE]);
  }
  const lastDay = summary?.days?.length ? summary.days[summary.days.length - 1] : null;
  pairs.push(['Model period', summary?.start_date ? `${String(summary.start_date).slice(0, 10)} to ${dayToIso(summary, lastDay) || EMPTY_VALUE}` : EMPTY_VALUE]);
  pairs.push(['Analysis type', ANALYSIS_TYPE]);
  pairs.push(['Run', run?.id ? `${String(run.id).slice(0, 8)} (${run.status})` : EMPTY_VALUE]);
  return pairs;
}

function provenanceRows({ caseRow, run, summary, build }) {
  const st = summary?.steps;
  const rows = [
    ['Deck file', caseRow?.deck_path ? caseRow.deck_path.split('/').pop() : EMPTY_VALUE],
    ['Deck source', `${SOURCE_WORDS[caseRow?.deck_source] || EMPTY_VALUE}${caseRow?.template_slug ? ` (${caseRow.template_slug})` : ''}`],
    ['Deck SHA-256 (as run, hashed by the worker)', text(run?.deck_sha256 || summary?.deck_sha256) || EMPTY_VALUE],
    ['Simulator', `OPM Flow ${text(run?.opm_version || summary?.opm_version) || EMPTY_VALUE} (open source, GPLv3; image pinned by digest, version asserted at build)`],
    ['Worker', text(run?.worker_id || summary?.run?.worker_id) || EMPTY_VALUE],
    ['Attempt', run?.attempt != null ? String(run.attempt) : EMPTY_VALUE],
    ['Queued', utc(run?.queued_at)],
    ['Started (claimed by the worker)', utc(run?.claimed_at)],
    ['Finished', utc(run?.finished_at)],
    ['Elapsed', finite(Number(run?.elapsed_seconds)) && run?.elapsed_seconds != null ? `${g(Number(run.elapsed_seconds), 4)} s` : EMPTY_VALUE],
    ['Exit code', run?.exit_code != null ? String(run.exit_code) : EMPTY_VALUE],
    ['Report steps, simulator time steps', st ? `${fx(st.report_steps)}, ${fx(st.time_steps)}${st.stride > 1 ? `; series thinned to ${fx(st.points)} points (1 in ${st.stride})` : ''}` : `${NOT_REPORTED} (${fx(summary?.days?.length)} points in the summary)`],
    ['Report built by', text(build) || EMPTY_VALUE],
  ];
  return rows;
}

function deckRows({ deck, run, summary, units, pvtWords, krWords, diag }) {
  const d = deck;
  const u = units;
  const rows = [];
  rows.push(['Deck unit system', `${deckSystemText(d)}; the numbers of this report are shown in ${u.system === 'si' ? 'SI' : 'oilfield'} units (${units.basis})`]);
  rows.push(['Phases', d?.phases?.length ? d.phases.join(', ') : EMPTY_VALUE]);
  const cells = d?.dims ? `${fx(d.dims.nx)} x ${fx(d.dims.ny)} x ${fx(d.dims.nz)} = ${fx(d.dims.cells)} cells` : EMPTY_VALUE;
  const active = diag?.active_cells ?? run?.active_cells;
  rows.push(['Grid', `${cells}${d?.cornerPoint ? ', corner point (COORD/ZCORN)' : ', block-centred (DX/DY/DZ/TOPS)'}; active cells ${finite(active) ? fx(active) : NOT_REPORTED}`]);
  if (diag?.pore_volume) rows.push(['Pore volume (simulator)', `${fx(prtShow('resVolume', diag.pore_volume.value, diag.pore_volume.unit, u.system))} ${u.label('resVolume')}`]);
  rows.push(['Start date', d?.start || (summary?.start_date ? String(summary.start_date).slice(0, 10) : EMPTY_VALUE)]);
  const sch = d?.schedule;
  rows.push(['Schedule', sch ? [
    sch.tstepCount ? `${fx(sch.tstepCount)} TSTEP steps, ${fx(sch.tstepDays, 1)} days` : null,
    sch.dates ? `${fx(sch.dates)} DATES (${sch.firstDate} to ${sch.lastDate})` : null,
    sch.historyControls ? 'observed rates (WCONHIST/WCONINJH) in the history phase' : 'declared controls only (no history phase)',
  ].filter(Boolean).join('; ') : EMPTY_VALUE]);
  const e = d?.equil;
  rows.push(['Initialisation (EQUIL)', e ? `datum ${fx(u.show('depth', e.datumDepth))} ${u.label('depth')} at ${fx(u.show('pressure', e.datumPressure))} ${u.label('pressure')}; OWC ${fx(u.show('depth', e.owc))} ${u.label('depth')}; GOC ${fx(u.show('depth', e.goc))} ${u.label('depth')}; depths are deck depths, positive down (TVDSS for a builder deck)` : 'not found in the main deck']);
  rows.push(['PVT tables', `${d?.tables?.filter((t) => /^PV|^DENSITY|^GRAVITY|^ROCK/.test(t)).join(', ') || 'not in the main deck'}. ${pvtWords}`]);
  rows.push(['Saturation functions', `${d?.tables?.filter((t) => /^S[WGL]|^SOF/.test(t)).join(', ') || 'not in the main deck'}. ${krWords}`]);
  rows.push(['Three-phase oil relative permeability', d?.threePhase ? `${d.threePhase}: ${threePhaseWords(d, null, false)}` : threePhaseWords(d, null, false)]);
  rows.push(['Aquifers', d?.aquifers?.length ? d.aquifers.join(', ') : 'none in the main deck']);
  rows.push(['Files included by the deck', d?.includes?.length ? `${d.includes.join(', ')} (not read by this report)` : 'none']);
  return rows;
}

/** SIM-U2-004: the aquifer of the deck that ran, in words. */
function aquiferAssumption(deck, form, applies) {
  if (!deck?.aquifers?.length) return 'No aquifer is modelled in the main deck: pressure support comes from the wells only.';
  const aq = applies && form?.aquifer?.enabled ? form.aquifer : null;
  if (!aq) return `Aquifer keywords present: ${deck.aquifers.join(', ')}; the aquifer is the deck's own.`;
  const it = aq.intake && aq.intake.model === aq.model ? aq.intake : null;
  const words = aq.model === 'fetkovich'
    ? 'Fetkovich: the influx rate is J times the aquifer pressure less the face pressure, the aquifer pressure falling as pi - We / (ct W); pseudo steady state from the start, no transient.'
    : `Carter-Tracy with the Material Balance engine's influence function (${String(aq.ct.reD ?? '').trim() ? `finite, reD ${aq.ct.reD}` : 'infinite acting'}); the permeability is written as k times the PVTW viscosity over the aquifer viscosity, so the aquifer diffuses as the Material Balance one does.`;
  return `An analytical aquifer (${deck.aquifers.join(', ')}) joined to the ${AQUIFER_FACE_WORDS[aq.face] || aq.face}${it ? `, taken from Material Balance case "${it.from?.recordName}"` : ', entered in the Model Builder'}. ${words} It starts at the equilibrium pressure at the datum. The keyword mapping is checked on Dake's Exercise 9.2 aquifer: OPM Flow's influx and the Material Balance engine's agree within 1 percent.`;
}

/** SIM-U2-003: the three-phase oil kr model of the deck that ran, in words. */
export function threePhaseWords(deck, form, applies) {
  const kw = deck?.threePhase || null;
  const chosen = applies ? form?.scal?.threePhase || '' : '';
  if (kw === 'STONE1') return `${THREE_PHASE_WORDS.stone1.report}, as the deck asks${chosen === 'stone1' ? ' (chosen in the Model Builder)' : ''}`;
  if (kw === 'STONE2') return `${THREE_PHASE_WORDS.stone2.report}, as the deck asks${chosen === 'stone2' ? ' (chosen in the Model Builder)' : ''}`;
  if (kw) return `the ${kw} model the deck asks for`;
  return `${THREE_PHASE_WORDS.default.report}${chosen === 'default' ? ', chosen in the Model Builder' : ', the deck naming no other (no STONE keyword)'}`;
}

function sourceWords(form, applies, deck) {
  if (applies && form?.pvtSource?.mode === 'fluid' && form.pvtSource.intake) {
    const f = form.pvtSource.intake.from || {};
    const c = form.pvtSource.intake.contract;
    return {
      pvt: `From Fluid Systems Studio project "${f.recordName || f.recordId}" (pvt-1, saved ${utc(f.generatedAt)}, taken ${utc(f.at)}): ${c?.model === 'eos' ? 'equation of state' : c?.model === 'lab' ? 'laboratory table' : 'black-oil correlations'}; bubble point ${g(c?.at_saturation?.pressure, 5)} psia, ${PVT1_PB_SOURCES[c?.pb_source] || 'source not stated'}; ${pvtContractTuningText(c) || 'no lab tuning'}.`,
      pvtShort: `pvt-1, Fluid Systems Studio "${f.recordName || f.recordId}"`,
    };
  }
  if (applies) {
    return {
      pvt: 'Entered in the Model Builder: black-oil correlations of Fluid Systems Studio (Standing Pb, Rs and Bo; Beggs-Robinson oil viscosity; Dranchuk-Abou-Kassem Z) from the typed API, gas gravity, temperature and GOR; PVTW typed.',
      pvtShort: 'Entered (correlations)',
    };
  }
  const note = (deck?.headerNotes || []).filter((l) => /^PVT/.test(l)).join(' ');
  return { pvt: note ? `The deck says: ${note}` : 'As written in the deck; the deck states no source.', pvtShort: 'As written in the deck' };
}

function krWordsOf(form, applies, deck) {
  if (applies && form?.krSource?.mode === 'scal' && form.krSource.intake?.contract) {
    const c = form.krSource.intake.contract;
    const f = form.krSource.intake.from || {};
    const edited = krEditedKeys(form);
    const adj = form.krSource.intake.goSwcAdjusted;
    return `From SCAL Studio project "${f.recordName || f.recordId}" (kr-1, saved ${utc(f.generatedAt)}, taken ${utc(f.at)}): oil-water ${krSetText(c, 'oil_water') || 'not stated'}; gas-oil ${krSetText(c, 'gas_oil') || 'not stated'}${adj ? ` (saved at Swc ${adj.from}, written at the oil-water Swc ${adj.to}: one connate water in the deck)` : ''}${form.scal?.pc?.enabled && c.capillary ? `; Pcow from ${krCapillaryText(c)}` : '; no capillary pressure'}.${edited.length ? ` Edited in the builder after intake: ${edited.join(', ')}.` : ''}`;
  }
  if (applies) return `Corey parameters entered in the Model Builder${form?.scal?.pc?.enabled ? '; Pcow from a typed Leverett J (Swirr taken as Swc)' : '; no capillary pressure'}.`;
  const note = (deck?.headerNotes || []).filter((l) => /^SWOF|^kr-1/.test(l)).join(' ');
  return note ? `The deck says: ${note}` : 'As written in the deck; the deck states no source.';
}

/** Builder inputs as report rows (RL1): value, unit, source. */
function inputRows(form, u) {
  const rows = [];
  const add = (label, value, kind, source) => rows.push({ ...inputRow({ label, value: value === '' || value == null ? '' : String(value), unit: kind ? u.label(kind) : '', auto: source }), key: label });
  const shown = (kind, v) => (String(v ?? '').trim() === '' ? '' : g(u.show(kind, Number(v)), 6));
  const entered = 'Entered in the Model Builder';
  const gridSrc = form.structure?.mode === 'surface' ? `Structure surface "${form.structure.surfaceName || 'unnamed'}" (Mapping), sampled at cell centres` : entered;
  // SIM-U2-007: a starting model taken from a Waterflood Design Studio pattern
  if (form.origin?.app === 'Waterflood Design Studio') {
    const o = form.origin;
    add('Starting model', `Waterflood Design Studio project "${o.recordName}", pattern ${o.pattern || 'unnamed'}: the quarter five-spot element`, null,
      `wf-forecast-1, taken ${String(o.at).slice(0, 10)}; the grid, wells and schedule below were written from it, then may have been edited here. Not in the pattern, kept from the builder: ${(o.kept || []).join('; ') || 'nothing'}`);
  }
  add('Grid NX x NY x NZ', `${form.grid.nx} x ${form.grid.ny} x ${form.grid.nz}`, null, entered);
  add('Cell size DX', form.structure?.mode === 'surface' ? shown('length', form.structure.dxFt) : shown('length', form.grid.dx), 'length', gridSrc);
  add('Cell size DY', form.structure?.mode === 'surface' ? shown('length', form.structure.dyFt) : shown('length', form.grid.dy), 'length', gridSrc);
  if (form.structure?.mode !== 'surface') add('Top depth (TVDSS)', shown('depth', form.grid.topsDepth), 'depth', entered);
  (form.grid.layers || []).slice(0, Number(form.grid.nz) || 0).forEach((l, i) => {
    add(`Layer ${i + 1}: DZ, porosity, kh, kv`, `${shown('length', l.dz)} ${u.label('length')}, ${l.poro}, ${l.permx} mD, ${l.permz} mD`, null, entered);
  });
  const fluidSrc = form.pvtSource?.mode === 'fluid' ? `pvt-1 from Fluid Systems Studio "${form.pvtSource.intake?.from?.recordName || ''}"` : entered;
  add('Oil gravity', form.fluid.api, 'api', fluidSrc);
  add('Gas gravity', form.fluid.gasSg, 'gasSg', fluidSrc);
  add('Reservoir temperature', shown('temperature', form.fluid.tempF), 'temperature', fluidSrc);
  add('Solution GOR', shown('solutionGor', form.fluid.gor), 'solutionGor', fluidSrc);
  if (form.pvtSource?.mode !== 'fluid') add('Water salinity', form.fluid.salinityPpm, 'salinity', entered);
  const waterSrc = form.pvtSource?.mode === 'fluid' ? `${fluidSrc} (PVTW at the bubble point)` : entered;
  add('Bw', form.water.bw, 'bo', waterSrc);
  add('Water compressibility', shown('compressibility', form.water.cw), 'compressibility', waterSrc);
  add('Water viscosity', form.water.muw, 'viscosity', waterSrc);
  add('PVTW reference pressure', shown('pressure', form.water.pref), 'pressure', waterSrc);
  add('Water surface density', shown('density', form.water.rhoLbFt3), 'density', entered);
  add('Rock compressibility', shown('compressibility', form.rock.cr), 'compressibility', entered);
  const krSrc = form.krSource?.mode === 'scal' ? `kr-1 from SCAL Studio "${form.krSource.intake?.from?.recordName || ''}"` : entered;
  const edited = new Set(krEditedKeys(form));
  const kr = (label, key, v) => add(label, v, null, edited.has(key) ? `${krSrc}; edited in the builder after intake` : krSrc);
  ['Swc', 'Sor', 'krwMax', 'kroMax', 'nw', 'no'].forEach((k) => kr(`Oil-water ${k}`, k, form.scal.ow[k]));
  ['Sgc', 'Sorg', 'krgMax', 'krogMax', 'ng', 'nog'].forEach((k) => kr(`Gas-oil ${k}`, k, form.scal.go[k]));
  add('Three-phase oil kr model', (THREE_PHASE_WORDS[form.scal.threePhase] || THREE_PHASE_WORDS.default).label, null,
    form.scal.threePhase ? 'Chosen in the Model Builder; written to the deck' : 'Not chosen: the simulator default, no keyword written');
  if (form.scal.pc?.enabled) {
    kr('J: a, b', 'jA', `${form.scal.pc.jA}, ${form.scal.pc.jB}`);
    kr('J: Swirr', 'swirr', String(form.scal.pc.swirr ?? '').trim() === '' ? `${form.scal.ow.Swc} (Swc)` : form.scal.pc.swirr);
    kr('Capillary rock: k, porosity', 'k_md', `${form.scal.pc.k_md} mD, ${form.scal.pc.phi}`);
    kr('IFT, contact angle', 'sigma_dyncm', `${form.scal.pc.sigma_dyncm} dyn/cm, ${form.scal.pc.thetaDeg} deg`);
  }
  add('Datum depth (TVDSS)', shown('depth', form.equil.datumDepth), 'depth', entered);
  add('Pressure at datum', shown('pressure', form.equil.datumPressure), 'pressure', entered);
  add('OWC depth (TVDSS)', shown('depth', form.equil.owc), 'depth', String(form.equil.owc ?? '').trim() ? entered : 'Blank: placed 100 ft below the grid (no water leg)');
  add('GOC depth (TVDSS)', shown('depth', form.equil.goc), 'depth', String(form.equil.goc ?? '').trim() ? entered : 'Blank: placed 100 ft above the grid (no gas cap)');
  form.wells.forEach((w) => {
    const ctl = w.type === 'producer' ? `oil ${shown('oilRate', w.rate)} ${u.label('oilRate')}, BHP min ${shown('pressure', w.bhp)} ${u.label('pressure')}`
      : w.type === 'gas_injector' ? `gas ${shown('gasRate', w.rate)} ${u.label('gasRate')}, BHP max ${shown('pressure', w.bhp)} ${u.label('pressure')}`
        : `water ${shown('waterRate', w.rate)} ${u.label('waterRate')}, BHP max ${shown('pressure', w.bhp)} ${u.label('pressure')}`;
    const where = w.trajectory?.enabled
      ? `deviated survey, wellhead ${w.trajectory.wellheadX}, ${w.trajectory.wellheadY} ft; ${w.trajectory.refKind || 'KB'} ${w.trajectory.refElevFt} ft above the datum`
      : `I ${w.i}, J ${w.j}, K ${w.k1} to ${w.k2}`;
    add(`Well ${String(w.name).toUpperCase()} (${w.type.replace('_', ' ')})`, `${where}; ${ctl}`, null,
      w.trajectory?.enabled && w.trajectory.datumSource === 'registry' ? `Entered; datum from the wells registry (${w.trajectory.wellName || 'well'})` : entered);
  });
  // SIM-U2-004: the analytical aquifer, each value with its source
  if (form.aquifer?.enabled) {
    const aq = form.aquifer;
    const it = aq.intake && aq.intake.model === aq.model ? aq.intake : null;
    const editedAq = new Set(aquiferEditedKeys(aq));
    const from = it ? `mbal-1 from Material Balance Studio case "${it.from?.recordName}"` : entered;
    const src = (key) => (it ? (editedAq.has(key) ? `${from}; edited in the builder after intake` : `${from}: ${it.sources?.[key] || 'as the case holds it'}`) : entered);
    add('Aquifer model', `${AQUIFER_MODELS[aq.model]}, joined to the ${AQUIFER_FACE_WORDS[aq.face] || aq.face}`, null, it ? from : entered);
    if (aq.model === 'fetkovich') {
      add('Aquifer water in place W', shown('resVolume', aq.fet.W_rb), 'resVolume', src('W_rb'));
      add('Aquifer productivity index J', aq.fet.J_rb_d_psi, null, src('J_rb_d_psi'));
      add('Aquifer total compressibility', shown('compressibility', aq.fet.ct_psi), 'compressibility', src('ct_psi'));
    } else {
      add('Aquifer permeability k', aq.ct.k_md, null, `${src('k_md')}; written to the deck as k x PVTW viscosity / aquifer viscosity (OPM Flow takes mu from PVTW)`);
      add('Aquifer porosity', aq.ct.phi, null, src('phi'));
      add('Aquifer thickness h', shown('length', aq.ct.h_ft), 'length', src('h_ft'));
      add('Encroachment angle', aq.ct.theta_deg, null, src('theta_deg'));
      add('Reservoir radius at the aquifer r_R', shown('length', aq.ct.r_R_ft), 'length', src('r_R_ft'));
      add('Aquifer radius ratio reD', String(aq.ct.reD ?? '').trim() === '' ? 'infinite' : aq.ct.reD, null, `${src('reD')}; the influence table AQUTAB is the Material Balance engine pD(tD)`);
      add('Aquifer water viscosity', aq.ct.muw_cp, 'viscosity', src('muw_cp'));
      add('Aquifer total compressibility', shown('compressibility', aq.ct.ct_psi), 'compressibility', src('ct_psi'));
    }
  }
  add('Wellbore radius', shown('length', '0.25'), 'length', 'Assumed by the builder for every well (not editable)');
  add('Report interval', form.schedule.reportDays, 'days', entered);
  if (form.history?.enabled && form.history.periods) {
    const bhpPoints = form.history.periods.reduce((n, p) => n + [...(p.prod || []), ...(p.inj || [])].filter((r) => Number(r.bhp) > 0).length, 0);
    add('History', `${form.history.caseName}: ${form.history.periods.length} periods, ${form.history.startDate} to ${form.history.endDate}; prediction ${form.history.predictionYears} years${bhpPoints ? `; ${bhpPoints} observed bottomhole pressures (WBHPH)` : ''}`, null,
      form.history.source === 'perwell' ? 'Per-well rate file, each well its own rates' : `Material Balance case cumulatives, allocated to producers${Object.keys(form.history.fractions || {}).length ? ` (fractions ${Object.entries(form.history.fractions).map(([k, v]) => `${k} ${v}`).join(', ')})` : ' equally'}`);
  } else {
    add('Duration', form.schedule.years, 'years', entered);
  }
  return rows;
}

function materialBalance(diag, u) {
  if (!diag) return { reported: false, text: `Material balance: ${NOT_REPORTED}. ${NOT_REPORTED_WHY}`, rows: [] };
  const mb = diag.material_balance;
  if (!mb?.computed) return { reported: false, text: `Material balance: not reported: ${MB_REASONS[mb?.reason] || mb?.reason || 'unknown reason'}.`, rows: [] };
  const kind = { oil: 'oilVolume', water: 'waterVolume', gas: 'gasVolume' };
  const rows = Object.entries(mb.phases).map(([phase, p]) => {
    const k = kind[phase];
    // SIM-U2-015: in the unit the PRT printed (FIELD or METRIC), shown in the display units
    const v = (x) => fx(prtShow(k, x, p.unit, u.system));
    return [
      `${phase[0].toUpperCase()}${phase.slice(1)} (${u.label(k)})`,
      v(p.originally_in_place), v(p.currently_in_place), v(p.produced), v(p.injected), v(p.error),
      finite(p.relative_error) ? p.relative_error.toExponential(1) : EMPTY_VALUE,
      p.within_rounding ? 'yes' : 'no',
    ];
  });
  const verdict = mb.closes
    ? `The balance closes at report step ${mb.report_step} (${mb.date}): every component's error is within the rounding of the printed tables or within ${mb.tolerance * 100} percent of what was in place.`
    : `The balance does not close at report step ${mb.report_step} (${mb.date}): at least one component's error exceeds the rounding of the printed tables and ${mb.tolerance * 100} percent of what was in place.`;
  return { reported: true, closes: mb.closes, text: verdict, rows, head: ['Component', 'Originally in place', 'In place at the end', 'Produced', 'Injected', 'Error', 'Error / original', 'Within rounding'] };
}

function convergenceRows(diag, summary) {
  if (!diag) return { reported: false, text: `Convergence: ${NOT_REPORTED}. ${NOT_REPORTED_WHY}`, rows: [] };
  if (!diag.complete) return { reported: false, text: 'Convergence: not reported: the PRT holds no end-of-run statistics (the run stopped before the end, or the simulator wrote them elsewhere).', rows: [] };
  const w = (x) => (x ? `${fx(x.total)} (wasted ${fx(x.wasted)})` : EMPTY_VALUE);
  const m = diag.messages || {};
  const rows = [
    ['Simulator time steps', fx(diag.time_steps)],
    ['Report steps', fx(summary?.steps?.report_steps)],
    ['Newton iterations', w(diag.newton_iterations)],
    ['Linear iterations', w(diag.linear_iterations)],
    ['Linearizations', w(diag.linearizations)],
    ['Time steps chopped (convergence failures)', fx(diag.chops?.count)],
    ['Messages: errors, warnings, problems', `${fx(m.errors)}, ${fx(m.warnings)}, ${fx(m.problems)}`],
    ['Simulation time (simulator clock)', finite(diag.simulation_seconds) ? `${g(diag.simulation_seconds, 3)} s` : EMPTY_VALUE],
  ];
  const chops = (diag.chops?.listed || []).map((c) => `chopped to ${g(c.to_days, 3)} days at report step ${c.report_step ?? EMPTY_VALUE}${c.reason ? `: ${c.reason}` : ''}`);
  const perStep = finite(diag.time_steps) && diag.newton_iterations ? diag.newton_iterations.total / diag.time_steps : null;
  const text = diag.chops?.count
    ? `The simulator cut ${fx(diag.chops.count)} time steps after a convergence failure and repeated them (${fx(diag.newton_iterations?.wasted)} Newton iterations wasted). The run still reached its end; the results are from the converged steps.`
    : `No time step was cut: every step converged on its first try${finite(perStep) ? `, ${g(perStep, 3)} Newton iterations per step on average` : ''}.`;
  return { reported: true, rows, text, chops };
}

/** The bottomhole pressure match as report rows (SIM-U2-001). */
function bhpMatchSection(m) {
  const f = (v) => (finite(v) ? fx(v, 1) : EMPTY_VALUE);
  if (!m.applies) return { applies: false, text: `Bottomhole pressure match: does not apply. ${m.reason}`, rows: [] };
  const rows = m.wells.map((w) => [w.well, fx(w.points), `${f(w.obsMin)} to ${f(w.obsMax)}`, f(w.rms), f(w.bias), f(w.maxAbs)]);
  rows.push(['All wells', fx(m.overall.points), EMPTY_VALUE, f(m.overall.rms), EMPTY_VALUE, EMPTY_VALUE]);
  const from = m.source === 'WBHPH'
    ? 'the run\'s WBHPH vector (the deck was not made by the builder form, so the observed periods are not known: the simulator carries the last observation forward through a period that gives none, and such a period repeats it here)'
    : `the per-well history of the builder form that made the deck that ran, the periods that carried a pressure${m.echo ? (m.echo.differ ? `; the run's WBHPH differs from it at ${m.echo.differ} of ${m.echo.checked} time steps` : `; the run's WBHPH equals it at all ${m.echo.checked} time steps (the simulator read the pressures as written)`) : '; the worker build of this run did not keep WBHPH, so the simulator\'s echo is not checked'}`;
  return {
    applies: true,
    source: m.source,
    head: ['Well', 'Points', `Observed (${m.unit})`, `RMS (${m.unit})`, `Mean, simulated minus observed (${m.unit})`, `Largest difference (${m.unit})`],
    rows,
    rms: m.overall.rms,
    echo: m.echo,
    text: `RMS mismatch ${f(m.overall.rms)} ${m.unit} over ${fx(m.overall.points)} points in ${fx(m.overall.wells)} well${m.overall.wells === 1 ? '' : 's'}. Observed bottomhole pressure from ${from}; one point per observation: the observed pressure of a history period against the simulated WBHP averaged over that period's time steps (time weighted); the residual is simulated minus observed. Absolute pressure. The observations are not controls: the producers run on their observed rates.`,
  };
}

function headlineRows(summary, opts, u, diag) {
  const rows = [];
  const mbPhases = diag?.material_balance?.computed ? diag.material_balance.phases : null;
  const add = (label, key, kind, digits = 0, fallback = null) => {
    const lv = lastValue(summary, key, opts);
    if (!lv && fallback && finite(fallback.value)) {
      const v = prtShow(kind, fallback.value, fallback.unit, u.system);
      rows.push([label, fx(v, digits), u.label(kind), `${key} is not in the summary; the simulator's well totals in the PRT at report step ${diag.material_balance.report_step}`]);
      return { value: v };
    }
    rows.push([label, lv ? fx(lv.value, digits) : EMPTY_VALUE, kind ? u.label(kind) : '', lv ? `${key} at ${dayToIso(summary, lv.day)}` : `${key} is not in the summary (the deck's SUMMARY section does not request it)`]);
    return lv;
  };
  const np = add('Cumulative oil produced', 'FOPT', 'oilVolume', 0, mbPhases && { value: mbPhases.oil.produced, unit: mbPhases.oil.unit });
  add('Cumulative water injected', 'FWIT', 'waterVolume', 0, mbPhases && { value: mbPhases.water.injected, unit: mbPhases.water.unit });
  add('Cumulative gas injected', 'FGIT', 'gasVolume', 0, mbPhases && { value: mbPhases.gas.injected, unit: mbPhases.gas.unit });
  add('Oil rate at the end', 'FOPR', 'oilRate');
  add('Field pressure at the end', 'FPR', 'pressure');
  add('Water cut at the end', 'FWCT', 'fraction', 3);
  add('GOR at the end', 'FGOR', 'gor', 3);
  const ooip = diag?.material_balance?.phases?.oil?.originally_in_place ?? diag?.balance?.initial?.original?.oil;
  const ooipUnit = diag?.material_balance?.phases?.oil?.unit ?? diag?.balance?.units?.oil ?? null;
  const ooipShown = finite(ooip) ? prtShow('oilVolume', ooip, ooipUnit, u.system) : null;
  rows.push(['Oil originally in place', finite(ooipShown) ? fx(ooipShown) : EMPTY_VALUE, u.label('oilVolume'), finite(ooip) ? 'Simulator balance sheet (PRT), stock tank' : diag ? 'Not printed: the deck does not ask for the FIP report' : NOT_REPORTED]);
  const rf = np && finite(ooipShown) && ooipShown > 0 ? np.value / ooipShown : null;
  rows.push(['Recovery factor to the end', finite(rf) ? `${(rf * 100).toFixed(2)}` : EMPTY_VALUE, 'percent', finite(rf) ? 'Cumulative oil produced / oil originally in place' : 'Needs the cumulative oil and the oil originally in place']);
  return rows;
}

/**
 * @param {{caseRow: object, run: object, summary: object, deckText?: ?string, form?: ?object,
 *   system?: string, organizationName?: ?string, build?: ?string}} a
 * @returns {?object} null without a completed run with a summary
 */
export function buildSimReportModel({ caseRow, run, summary, deckText = null, deckTextSha = null, form = null, system = 'oilfield', organizationName = null, build = null }) {
  if (!run || !summary) return null;
  const deck = deckText ? summarizeDeck(deckText) : null;
  const us = summaryUnitSystem(summary, deck?.unitSystem || null);
  const u = { ...simUnits(system), basis: `deck numbers read as ${us.system}: ${us.basis}` };
  const opts = { deckSystem: us.system, system };
  const fa = formAppliesToRun(form, run, caseRow);
  const diag = summary.diagnostics || null;
  const sw = sourceWords(form, fa.applies, deck);
  const krWords = krWordsOf(form, fa.applies, deck);

  const mb = materialBalance(diag, u);
  const sch = deck?.schedule;
  const historyEnd = sch?.historyControls && sch.lastDate ? sch.lastDate : null;
  const bhpRaw = bhpMatch({ summary, opts, historyEnd, form, formApplies: fa.applies });
  const bhp = bhpMatchSection(bhpRaw);
  const conv = convergenceRows(diag, summary);
  const flags = [];
  if (!diag) flags.push(`Material balance and convergence: ${NOT_REPORTED}. ${NOT_REPORTED_WHY}`);
  else {
    if (!mb.reported) flags.push(mb.text);
    else if (!mb.closes) flags.push(mb.text);
    if (diag.chops?.count) flags.push(`${fx(diag.chops.count)} time steps were cut after convergence failures.`);
    if (diag.messages?.errors) flags.push(`The simulator printed ${fx(diag.messages.errors)} error messages; read the log on the Runs tab.`);
  }
  if (bhp.applies && bhp.echo?.differ) flags.push(`The run's WBHPH differs from the observed bottomhole pressures of the builder form at ${bhp.echo.differ} of ${bhp.echo.checked} time steps: the simulator did not read the pressures as written. Generate the deck again and run it.`);
  if (summary.steps?.stride > 1) flags.push(`The plotted series is thinned to ${fx(summary.steps.points)} of ${fx(summary.steps.time_steps)} time steps; the CSV holds the same thinned series.`);
  if (us.system !== 'FIELD' && us.system !== 'METRIC') flags.push(`The deck is in ${us.system} units, which this app does not convert; values are shown as written.`);
  if (/assumed/.test(us.basis)) flags.push(`The deck unit system is ${us.basis}.`);
  if (!fa.applies) flags.push(`Builder inputs: not shown. ${fa.reason}`);
  if (deck?.includes?.length) flags.push(`The deck includes ${deck.includes.length} file(s) this report does not read (${deck.includes.join(', ')}); the deck summary covers the main file only.`);
  if (!deckText) flags.push('The deck text could not be read; the deck summary is missing.');
  const deckChanged = !!(deckText && deckTextSha && run?.deck_sha256 && deckTextSha !== run.deck_sha256);
  if (deckChanged) flags.push('The case\'s deck has changed since this run (its SHA-256 differs from the one the worker ran): "What the deck holds" describes the current deck, not the one that ran.');
  if (fa.applies && form?.krSource?.mode === 'scal' && krEditedKeys(form).length) flags.push(`The saturation functions were edited after they were taken from SCAL Studio (${krEditedKeys(form).join(', ')}).`);

  const cellText = deck?.dims ? `${fx(deck.dims.cells)} cells` : 'the grid of the deck';
  const assumptions = [
    `Black-oil model as the deck defines it (${deck?.phases?.join(', ') || 'phases not read'}): no compositional or thermal effects.`,
    `Grid resolution: ${cellText}${fa.applies ? ` of ${g(u.show('length', Number(form.grid.dx)), 4)} by ${g(u.show('length', Number(form.grid.dy)), 4)} ${u.label('length')}` : ''}. Results are averages over each cell; gradients finer than a cell (coning, near-well saturation fronts) are not resolved.`,
    fa.applies && form.structure?.mode !== 'surface' ? 'The builder grid is a layer-cake box: flat layers, no faults, no corner-point geometry.' : 'The grid geometry is the deck\'s own.',
    `PVT: ${sw.pvt}`,
    `Saturation functions: ${krWords} Two-phase tables; the three-phase oil relative permeability is ${threePhaseWords(deck, form, fa.applies)}; no hysteresis and no end-point scaling unless the deck says so.`,
    aquiferAssumption(deck, form, fa.applies),
    'Wells are controlled as the deck declares; no well economic limits or group controls are applied unless the deck holds them.',
    !historyEnd && !bhp.applies ? null : bhp.applies
      ? `History match: rates are honoured by construction (WCONHIST controls the producers on their observed rates); the bottomhole pressure is the test of the match, ${bhp.source === 'WBHPH' ? 'observed as WBHPH' : 'observed in the builder form'}, RMS ${fx(bhp.rms, 1)} ${u.label('pressure')}. No history-match quality threshold is applied: the numbers are printed for the reviewer.`
      : 'No bottomhole pressure was observed in the history: a rate history alone is matched by construction under WCONHIST and proves little.',
    'A single deterministic run: no uncertainty range. The material balance and convergence statements are the simulator\'s own printout as read by the worker.',
  ].filter(Boolean);

  return {
    title: REPORT_TITLE,
    appName: APP_NAME,
    identification: identificationPairs({ caseRow, form, organizationName, run, summary }),
    displayUnits: displayUnitsLine(system),
    system,
    deckSystem: us.system,
    unitBasis: us.basis,
    provenance: provenanceRows({ caseRow, run, summary, build }),
    deck: deck ? deckRows({ deck, run, summary, units: u, pvtWords: sw.pvt, krWords, diag }) : [['Deck', 'The deck text could not be read.']],
    wells: (deck?.wells || []).map((w) => [w.name, w.role, w.phase || EMPTY_VALUE, w.i != null ? `${w.i}, ${w.j}` : EMPTY_VALUE, finite(w.refDepth) ? fx(u.show('depth', w.refDepth)) : EMPTY_VALUE]),
    wellsHead: ['Well', 'Role in the deck', 'Preferred phase', 'Head I, J', `Reference depth (${u.label('depth')})`],
    inputs: fa.applies ? { rows: inputRows(form, u), note: 'The values the Model Builder wrote into the deck that ran (its SHA-256 matches). Source and quality as recorded with the case.' } : null,
    inputsWhy: fa.reason,
    headline: { head: ['Quantity', 'Value', 'Unit', 'Where it comes from'], rows: headlineRows(summary, opts, u, diag) },
    materialBalance: mb,
    bhpMatch: bhp,
    bhpMatchRaw: bhpRaw,
    convergence: conv,
    limits: { assumptions, flags, noFlagsText: 'No flag: the balance closes, no step was cut and the inputs are traced.' },
    footerWho: text(caseRow?.name),
    opts,
    diag,
    deckSummary: deck,
    deckChanged,
    formApplies: fa,
  };
}
