"""S3 gate: a deck generated by the Suite's Model Builder (engines/sim
composeDeck over Fluid Studio PVT + SCAL Corey tables) passes the worker's
own validation and runs to completion in flow with sane physics.

The fixture is the deterministic output of the default builder form —
regenerate with: GEN_SIM_FIXTURE=1 npx jest src/utils/__tests__/simDeckBuilder.test.js
(repo root). A drift between the fixture and the builder fails jest, so
this file always tests what the app actually generates."""
import os
import shutil
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from simworker import deck, results, runner  # noqa: E402

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "generated", "BUILT.DATA")
flow_missing = shutil.which("flow") is None
pytestmark = pytest.mark.skipif(
    flow_missing, reason="flow binary not on PATH (run inside the worker image)")


def test_generated_deck_passes_worker_validation(tmp_path):
    shutil.copy(FIXTURE, os.path.join(str(tmp_path), "BUILT.DATA"))
    deck.validate_bundle(str(tmp_path), "BUILT.DATA")  # must not raise


def test_generated_deck_runs_with_sane_physics(tmp_path):
    work = str(tmp_path)
    shutil.copy(FIXTURE, os.path.join(work, "BUILT.DATA"))
    outcome = runner.run_flow(work, "BUILT.DATA", lambda: False)
    assert outcome["exit_code"] == 0, (
        f"flow rejected the generated deck: {outcome['stderr_tail']}")

    case = results.find_summary_case(os.path.join(work, "out"))
    doc, blob = results.build_summary(case, "s3-gate", "sha")
    assert len(doc["days"]) > 50
    # The default form's producer targets 4000 STB/d.
    assert abs(doc["field"]["FOPR"][0] - 4000) < 1
    assert "PROD1" in doc["wells"] and "INJ1" in doc["wells"]
    assert "WBHP" in doc["wells"]["PROD1"]
    # Field pressure stays physical (psia, not garbage).
    assert 500 < doc["field"]["FPR"][-1] < 10000
