// Dev-only harness (/dev/decision-studio, DEV builds only; senior test T1,
// 2026-09-26): Decision Studio on real evidence without auth or a
// database. Two Monte Carlo runs on the Ekene demo case (mcRuns.json,
// generated by the engines runEpeMonteCarlo, seed 42, 1000 iterations), the
// hand-derived drill-or-farm-out tree (EMV 43) and the four-project
// portfolio from the brief model tests. Supabase is swapped for an
// in-memory table set while mounted and restored on unmount.

import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/customSupabaseClient';
import DecisionStudio from '@/pages/apps/DecisionStudio';
import MC from './mcRuns.json';

const DB = {
  epe_mc_runs: MC.map((r, i) => ({
    id: `mc${i + 1}aaaa-bbbb-cccc-dddd-eeeeffff000${i}`,
    created_at: `2026-09-2${4 + i}T10:00:00Z`,
    results: r.results,
    mc_config: r.mc_config,
    epe_run_configs: { config_name: r.name },
  })),
  saved_decision_tree_projects: [{
    id: '22223333-4444-5555-6666-777788889999', project_name: 'Ekene-11: drill or farm out',
    created_at: '2026-09-24T11:00:00Z', updated_at: '2026-09-24T11:00:00Z',
    inputs_data: { tree: {
      type: 'decision', label: 'Ekene-11 decision',
      branches: [
        { label: 'Drill', cost: 40, node: { type: 'chance', label: 'Outcome', branches: [
          { label: 'Success', probability: 0.3, node: { type: 'terminal', payoff: 300 } },
          { label: 'Dry', probability: 0.7, node: { type: 'terminal', payoff: -10 } },
        ] } },
        { label: 'Farm out', cost: 0, node: { type: 'terminal', payoff: 18 } },
      ],
    } },
  }],
  portfolios: [{ id: 'p1', name: 'FY27 Capital Plan', capex_limit: 450, created_at: '2026-09-24T12:00:00Z' }],
  portfolio_projects: [
    { id: 'A', portfolio_id: 'p1', name: 'Infill A', capex: 100, npv_p50: 60 },
    { id: 'B', portfolio_id: 'p1', name: 'Waterflood B', capex: 200, npv_p50: 100 },
    { id: 'C', portfolio_id: 'p1', name: 'Tie-back C', capex: 300, npv_p50: 120 },
    { id: 'D', portfolio_id: 'p1', name: 'Ekene-11', capex: 150, npv_p50: 90, source_type: 'epe_mc' },
  ],
};

function query(table) {
  const q = {};
  const chain = () => q;
  ['select', 'eq', 'order', 'limit', 'in', 'gte', 'lte', 'not', 'is', 'or', 'neq', 'range', 'insert', 'update', 'upsert', 'delete'].forEach((m) => { q[m] = chain; });
  const v = DB[table];
  const one = () => ({ data: Array.isArray(v) ? (v[0] ?? null) : (v ?? null), error: null });
  q.single = () => Promise.resolve(one());
  q.maybeSingle = () => Promise.resolve(one());
  q.then = (res, rej) => Promise.resolve({ data: Array.isArray(v) ? v : v ? [v] : [], error: null }).then(res, rej);
  return q;
}

export default function DecisionStudioHarness() {
  const [ready, setReady] = useState(false);
  useEffect(() => {
    const saved = supabase.from;
    supabase.from = (t) => query(t);
    setReady(true);
    return () => { supabase.from = saved; };
  }, []);
  return ready ? <div data-testid="ds-harness"><DecisionStudio userOverride={{ id: 'dev', email: 'harness@petrolord.dev' }} /></div> : null;
}
