// Well path engine: minimum-curvature positions from deviation-survey
// stations — the industry-standard trajectory definition. Validated
// against the Python oracle goldens (test-data/seismolord/wells/,
// generated by tools/validation/seismolord/wells/ whose reference is
// itself proven on a published worked example and analytic circular
// arcs) — see Seismolord-WELLS-PLAN.md Phase W0.
//
// Conventions (domain rules): inc/azi in degrees, azimuth clockwise
// from grid north (north = +Y, east = +X); TVD positive down below KB;
// TVDss = TVD − KB, positive down below the datum (= seismic datum).
// MD units are the caller's (metres in the app); the math is
// unit-agnostic. Zero dogleg takes the exact RF → 1 limit — no 0/0.
//
// Pure math, worker-safe, no I/O.

const DEG = Math.PI / 180;

/** Unit tangent {e, n, v} (east, north, down) of a station attitude. */
export function tangent(incDeg, aziDeg) {
  const i = incDeg * DEG;
  const a = aziDeg * DEG;
  return { e: Math.sin(i) * Math.sin(a), n: Math.sin(i) * Math.cos(a), v: Math.cos(i) };
}

/** Total angle change (radians) between two station attitudes. */
export function doglegRad(inc1, azi1, inc2, azi2) {
  const i1 = inc1 * DEG;
  const i2 = inc2 * DEG;
  const c = Math.cos(i2 - i1)
    - Math.sin(i1) * Math.sin(i2) * (1 - Math.cos((azi2 - azi1) * DEG));
  return Math.acos(Math.max(-1, Math.min(1, c)));
}

/** RF = (2/β)·tan(β/2); the β → 0 limit is exactly 1. */
export function ratioFactor(beta) {
  if (beta < 1e-9) return 1;
  return (2 / beta) * Math.tan(beta / 2);
}

/** Validate stations (clear domain errors — never a raw crash). */
function checkStations(stations) {
  if (!Array.isArray(stations) || stations.length < 2) {
    throw new Error('A well path needs at least 2 survey stations.');
  }
  for (let i = 0; i < stations.length; i++) {
    const s = stations[i];
    if (!s || !Number.isFinite(s.md) || !Number.isFinite(s.inc) || !Number.isFinite(s.azi)) {
      throw new Error(`Survey station ${i + 1} has non-numeric MD/inclination/azimuth.`);
    }
    if (s.inc < 0 || s.inc > 180) {
      throw new Error(`Survey station ${i + 1}: inclination ${s.inc}° is outside 0–180°.`);
    }
    if (i > 0 && !(s.md > stations[i - 1].md)) {
      throw new Error(`Measured depth must increase: station ${i} is at `
        + `${stations[i - 1].md} but station ${i + 1} is at ${s.md}.`);
    }
  }
}

/**
 * Minimum-curvature path through the stations.
 *
 * @param {{md:number, inc:number, azi:number}[]} stations ascending MD
 * @param {{surfaceX?: number, surfaceY?: number, kb?: number}} [opts]
 *   surface location (world metres) and KB elevation above datum
 * @returns {{md:number, x:number, y:number, tvd:number, tvdss:number}[]}
 *   one point per station; x/y world, tvd below KB, tvdss below datum
 */
export function computeWellPath(stations, { surfaceX = 0, surfaceY = 0, kb = 0 } = {}) {
  checkStations(stations);
  const out = [{
    md: stations[0].md, x: surfaceX, y: surfaceY, tvd: 0, tvdss: -kb,
  }];
  let e = 0;
  let n = 0;
  let v = 0;
  for (let i = 1; i < stations.length; i++) {
    const s1 = stations[i - 1];
    const s2 = stations[i];
    const dmd = s2.md - s1.md;
    const rf = ratioFactor(doglegRad(s1.inc, s1.azi, s2.inc, s2.azi));
    const t1 = tangent(s1.inc, s1.azi);
    const t2 = tangent(s2.inc, s2.azi);
    e += (dmd / 2) * (t1.e + t2.e) * rf;
    n += (dmd / 2) * (t1.n + t2.n) * rf;
    v += (dmd / 2) * (t1.v + t2.v) * rf;
    out.push({
      md: s2.md, x: surfaceX + e, y: surfaceY + n, tvd: v, tvdss: v - kb,
    });
  }
  return out;
}

/** Header-only vertical well (surface + TD): the same code path as the
 *  general method — a two-station 0°-inclination survey. */
export function verticalWellPath({ surfaceX = 0, surfaceY = 0, kb = 0, td }) {
  return computeWellPath(
    [{ md: 0, inc: 0, azi: 0 }, { md: td, inc: 0, azi: 0 }],
    { surfaceX, surfaceY, kb },
  );
}

/**
 * Position at an arbitrary MD by exact interpolation along the
 * minimum-curvature circular arc of the containing station interval
 * (zero dogleg degenerates to the straight segment) — what section /
 * traverse / 3D overlays sample in Phase W2.
 *
 * @param {{md:number, inc:number, azi:number}[]} stations
 * @param {{md, x, y, tvd, tvdss}[]} path computeWellPath(stations, …)
 * @param {number} md
 * @returns {?{md:number, x:number, y:number, tvd:number, tvdss:number}}
 *   null outside the surveyed MD range
 */
export function positionAtMd(stations, path, md) {
  if (!Number.isFinite(md) || md < stations[0].md
    || md > stations[stations.length - 1].md) return null;
  let i = 1;
  while (i < stations.length - 1 && stations[i].md < md) i += 1;
  const s1 = stations[i - 1];
  const s2 = stations[i];
  const p1 = path[i - 1];
  const dmd = s2.md - s1.md;
  const f = (md - s1.md) / dmd;
  const t1 = tangent(s1.inc, s1.azi);
  const t2 = tangent(s2.inc, s2.azi);
  const beta = doglegRad(s1.inc, s1.azi, s2.inc, s2.azi);
  let de;
  let dn;
  let dv;
  if (beta < 1e-9) {
    de = f * dmd * t1.e;
    dn = f * dmd * t1.n;
    dv = f * dmd * t1.v;
  } else {
    const r = dmd / beta;
    const sb = Math.sin(beta);
    const cb = Math.cos(beta);
    const fb = f * beta;
    const sfb = Math.sin(fb);
    const ofb = 1 - Math.cos(fb);
    de = r * (sfb * t1.e + ofb * ((t2.e - t1.e * cb) / sb));
    dn = r * (sfb * t1.n + ofb * ((t2.n - t1.n * cb) / sb));
    dv = r * (sfb * t1.v + ofb * ((t2.v - t1.v * cb) / sb));
  }
  return {
    md, x: p1.x + de, y: p1.y + dn, tvd: p1.tvd + dv, tvdss: p1.tvdss + dv,
  };
}
