// In-memory backend for the /dev/pore-pressure-studio harness and
// jest: the workstation drivable without auth or DB (the harness
// philosophy). Same interface as registryBackend.
//
// The seeded well IS the oracle goldens' synthetic well
// (packages/engines/test-data/porepressure/goldens.json, imported directly — the
// PetrophysicsStudio typewell precedent): 401 samples, hydrostatic to
// 2500 m below mudline then a 4 kPa/m overpressure ramp, transit time
// generated by INVERTING Eaton on the imposed PP profile. Running the
// engine with the goldens' own parameters must therefore reproduce
// goldens.well.pore_pressure_pa exactly — the e2e suite asserts those
// numbers straight off the screen. Density is stored in G/C3 and the
// depth log starts at the mudline so the prep conversions are
// exercised, not bypassed.
//
// PP-U1-003 (2026-10-01): the depth log is registry MD below the rotary
// table, as every real well's is: the synthetic mudline sits at
// MUDLINE_MD_M = air gap (KB 30 m above sea level) + water depth (100 m),
// and the seeded project carries that mudline MD, so the below-mudline
// depths the engine sees are the goldens' own and published curves land
// at their true MD.

import goldens from '../../../../../packages/engines/test-data/porepressure/goldens.json';
import { bindSaved } from './savedFixtures';

let seq = 0;
const nextId = (p) => { seq += 1; return `${p}-${seq}`; };

export const WELL = goldens.well;
export const AIR_GAP_M = 30;
export const MUDLINE_MD_M = AIR_GAP_M + WELL.params.water_depth_m;
const MD = WELL.z_bml_m.map((z) => z + MUDLINE_MD_M);

// U2-001: a deep resistivity generated as the sonic was, by inverting
// Eaton with the published resistivity exponent (1.2) on the imposed pore
// pressure against the trend R_n = 0.6 exp(2e-4 z): resistivity Eaton with
// these parameters must reproduce goldens.well.pore_pressure_pa
export const HARNESS_RES_NCT = Object.freeze({ r0OhmM: 0.6, bPerM: 2.0e-4 });
export const RES_OHMM = WELL.z_bml_m.map((z, i) => {
  const S = WELL.overburden_pa[i]; const Ph = WELL.hydrostatic_pa[i]; const PP = WELL.pore_pressure_pa[i];
  const ratio = S - Ph > 1 ? ((S - PP) / (S - Ph)) ** (1 / 1.2) : 1;
  return ratio * HARNESS_RES_NCT.r0OhmM * Math.exp(HARNESS_RES_NCT.bPerM * z);
});

// U2-005: a shale volume with five sand beds (VSH 0.15) in shale (0.85).
// The sonic stays the oracle's everywhere (so the goldens hold); the beds
// sit away from the depths the e2e picks and reads (500 to 2,000 m, 3,500 m).
export const SAND_BEDS_BML_M = Object.freeze([[600, 640], [1200, 1240], [1800, 1840], [2700, 2740], [3300, 3340]]);
export const VSH_HARNESS = WELL.z_bml_m.map((z) => (SAND_BEDS_BML_M.some(([a, b]) => z >= a && z <= b) ? 0.15 : 0.85));

export function makeInMemoryBackend({ layerCake = false, saved = null } = {}) {
  const wellId = nextId('well');
  const curveStore = new Map();
  const logs = [];

  const addLog = (mnemonic, unit, values) => {
    const logId = nextId('log');
    curveStore.set(logId, Float64Array.from(values));
    logs.push({
      id: logId,
      well_id: wellId,
      mnemonic,
      description: `${mnemonic} (oracle synthetic well)`,
      unit,
      start_md_m: MD[0],
      stop_md_m: MD[MD.length - 1],
      step_m: 10,
      n_samples: values.length,
      null_count: 0,
      source_file: 'packages/engines/test-data/porepressure/goldens.json',
      provenance: { synthetic: true },
      storage_path: `dev/${wellId}/${logId}.f32`,
    });
  };

  addLog('DEPT', 'M', MD);
  addLog('DT', 'US/M', WELL.dt_us_per_m);
  addLog('RHOB', 'G/C3', WELL.rho_kg_m3.map((r) => r / 1000.0));
  addLog('RT', 'OHMM', RES_OHMM);
  addLog('VSH', 'V/V', VSH_HARNESS);

  const wells = [{
    id: wellId,
    user_id: 'user-dev',
    organization_id: null,
    name: 'ORACLE PP-1',
    uwi: 'ORACLE PP-1',
    surface_x: 501000,
    surface_y: 6700200,
    kb_m: AIR_GAP_M,
    td_md_m: MD[MD.length - 1],
    crs_note: 'EPSG:32630 (demo)',
    units_note: `SI; depth = MD below RKB, mudline at ${MUDLINE_MD_M} m MD`,
    deviation: [],
    checkshots: [],
    created_at: new Date(2026, 6, 14).toISOString(),
    updated_at: new Date(2026, 6, 14).toISOString(),
    is_own: true,
  }];

  // project persistence survives page reloads via sessionStorage so
  // the e2e can prove restore; first load seeds the goldens' own
  // parameters so the harness lands on the verifiable state
  const PROJECT_KEY = 'pp.dev.project.v1';
  const P = WELL.params;
  const SEED_PROJECT = {
    id: 'pp-project-dev',
    name: 'Default project',
    params: {
      waterDepthM: P.water_depth_m,
      rhoSeawaterKgM3: P.rho_seawater,
      rhoFluidKgM3: P.rho_fluid,
      mudlineMdM: MUDLINE_MD_M,
      nct: {
        dtMlUsPerM: P.dt_ml_us_per_m,
        dtMaUsPerM: P.dt_ma_us_per_m,
        cPerM: P.c_nct_per_m,
      },
      method: 'eaton',
      eatonN: P.eaton_n,
      bowers: { A: 10, B: 0.75 },
      nu: P.nu,
      resNct: { ...HARNESS_RES_NCT },
      eatonNRes: 1.2,
    },
    picks: [],
    calibration: [],
    source: { kind: 'well' },
  };

  // one v1-samplable single-function model: v0 2000 m/s at sea level,
  // k 0.6 1/s — closed-form checkable (V at z bml = 2000 + 0.6(100+z))
  const VELOCITY_MODELS = [{
    id: 'vol-dev',
    name: 'DEMO 3D (calibrated)',
    velocity: { v0: 2000, k: 0.6 },
    calibration: { wells: 1, rms_ms: 2.1 },
  }];

  const LAYER_CAKE = {
    id: 'vol-lc',
    name: 'DEMO 3D layer cake',
    kind: 'layercake',
    velocity: { type: 'layercake', layers: [{ v0: 1800, k: 0, base_horizon_id: 'h1' }, { v0: 2600, k: 0.3 }] },
    calibration: null,
  };

  return {
    async listWells() { return [...wells]; },
    async listLogs(id) { return id === wellId ? [...logs] : []; },
    async downloadCurve(log) {
      const data = curveStore.get(log.id);
      if (!data) throw new Error(`No curve data for ${log.mnemonic}.`);
      return data;
    },
    async listVelocityModels() {
      // Seismolord U2-006 (?layercake=1): a two-layer cake whose boundary is
      // published at 1,000 ms TWT under the demo well
      return layerCake ? [...VELOCITY_MODELS, LAYER_CAKE] : [...VELOCITY_MODELS];
    },
    async layerCakeBoundariesAt(model, well) {
      if (model.id !== LAYER_CAKE.id) throw new Error('Unknown velocity model.');
      // a flat boundary: the same along any hole (the vertical harness well)
      return { boundaryTwtMs: [1000], names: ['Base layer 1 (TWT ms)'], note: 'Boundaries read at the wellhead (no deviation survey: a vertical well).', crsStatus: 'same', well: well.name };
    },
    // PP0: the account's Geoscience depth unit (the Mapping setting);
    // the fixture is SI so the oracle-anchored readout stays in metres
    async getDepthUnit() { return 'm'; },

    // overwrite-own publish against the in-memory log list, so the
    // e2e can drive publish + republish without a DB
    async publishCurves(id, preparedLogs, projectId) {
      if (id !== wellId) throw new Error('Unknown well.');
      const { staleOwnCurves } = await import('./publish');
      for (const stale of staleOwnCurves(logs, preparedLogs, projectId)) {
        const at = logs.findIndex((l) => l.id === stale.id);
        if (at >= 0) { curveStore.delete(stale.id); logs.splice(at, 1); }
      }
      const saved = [];
      for (const log of preparedLogs) {
        const logId = nextId('log');
        curveStore.set(logId, Float64Array.from(log.data));
        const row = {
          id: logId,
          well_id: wellId,
          mnemonic: log.mnemonic,
          description: log.description,
          unit: log.unit,
          start_md_m: log.startMdM,
          stop_md_m: log.stopMdM,
          step_m: log.stepM,
          n_samples: log.nSamples,
          null_count: log.nullCount,
          source_file: null,
          provenance: log.provenance,
          storage_path: `dev/${wellId}/${logId}.f32`,
        };
        logs.push(row);
        saved.push(row);
      }
      return saved;
    },

    async loadProject() {
      // PL5: `saved` opens a project as an earlier release saved it
      const seed = (saved && bindSaved(saved, wellId)) || SEED_PROJECT;
      try {
        const raw = window.sessionStorage.getItem(PROJECT_KEY);
        return raw ? JSON.parse(raw) : seed;
      } catch {
        return seed;
      }
    },

    async saveProject(patch) {
      const prev = (await this.loadProject()) || SEED_PROJECT;
      const next = { ...prev, ...patch, updated_at: new Date().toISOString() };
      try {
        window.sessionStorage.setItem(PROJECT_KEY, JSON.stringify(next));
      } catch { /* jsdom without storage — keep in-memory only */ }
      return next;
    },
  };
}
