// In-memory backend for the /dev/pore-pressure-studio harness and
// jest: the workstation drivable without auth or DB (the harness
// philosophy). Same interface as registryBackend.
//
// The seeded well IS the oracle goldens' synthetic well
// (test-data/porepressure/goldens.json, imported directly — the
// PetrophysicsStudio typewell precedent): 401 samples, hydrostatic to
// 2500 m below mudline then a 4 kPa/m overpressure ramp, transit time
// generated by INVERTING Eaton on the imposed PP profile. Running the
// engine with the goldens' own parameters must therefore reproduce
// goldens.well.pore_pressure_pa exactly — the e2e suite asserts those
// numbers straight off the screen. Density is stored in G/C3 and the
// depth log starts at the mudline so the prep conversions are
// exercised, not bypassed.

import goldens from '../../../../../test-data/porepressure/goldens.json';

let seq = 0;
const nextId = (p) => { seq += 1; return `${p}-${seq}`; };

export const WELL = goldens.well;

export function makeInMemoryBackend() {
  const wellId = nextId('well');
  const curveStore = new Map();
  const logs = [];

  const addLog = (mnemonic, unit, values) => {
    const logId = nextId('log');
    curveStore.set(logId, Float64Array.from(values));
    logs.push({
      id: logId,
      well_id: wellId,
      mnemonic,
      description: `${mnemonic} (oracle synthetic well)`,
      unit,
      start_md_m: WELL.z_bml_m[0],
      stop_md_m: WELL.z_bml_m[WELL.z_bml_m.length - 1],
      step_m: 10,
      n_samples: values.length,
      null_count: 0,
      source_file: 'test-data/porepressure/goldens.json',
      provenance: { synthetic: true },
      storage_path: `dev/${wellId}/${logId}.f32`,
    });
  };

  addLog('DEPT', 'M', WELL.z_bml_m);
  addLog('DT', 'US/M', WELL.dt_us_per_m);
  addLog('RHOB', 'G/C3', WELL.rho_kg_m3.map((r) => r / 1000.0));

  const wells = [{
    id: wellId,
    user_id: 'user-dev',
    organization_id: null,
    name: 'ORACLE PP-1',
    uwi: 'ORACLE PP-1',
    surface_x: 501000,
    surface_y: 6700200,
    kb_m: 30,
    td_md_m: WELL.z_bml_m[WELL.z_bml_m.length - 1],
    crs_note: 'EPSG:32630 (demo)',
    units_note: 'SI; depth = m below mudline',
    deviation: [],
    checkshots: [],
    created_at: new Date(2026, 6, 14).toISOString(),
    updated_at: new Date(2026, 6, 14).toISOString(),
    is_own: true,
  }];

  // project persistence survives page reloads via sessionStorage so
  // the e2e can prove restore; first load seeds the goldens' own
  // parameters so the harness lands on the verifiable state
  const PROJECT_KEY = 'pp.dev.project.v1';
  const P = WELL.params;
  const SEED_PROJECT = {
    id: 'pp-project-dev',
    name: 'Default project',
    params: {
      waterDepthM: P.water_depth_m,
      rhoSeawaterKgM3: P.rho_seawater,
      rhoFluidKgM3: P.rho_fluid,
      mudlineMdM: 0,
      nct: {
        dtMlUsPerM: P.dt_ml_us_per_m,
        dtMaUsPerM: P.dt_ma_us_per_m,
        cPerM: P.c_nct_per_m,
      },
      method: 'eaton',
      eatonN: P.eaton_n,
      bowers: { A: 10, B: 0.75 },
      nu: P.nu,
    },
    picks: [],
    calibration: [],
    source: { kind: 'well' },
  };

  return {
    async listWells() { return [...wells]; },
    async listLogs(id) { return id === wellId ? [...logs] : []; },
    async downloadCurve(log) {
      const data = curveStore.get(log.id);
      if (!data) throw new Error(`No curve data for ${log.mnemonic}.`);
      return data;
    },

    async loadProject() {
      try {
        const raw = window.sessionStorage.getItem(PROJECT_KEY);
        return raw ? JSON.parse(raw) : SEED_PROJECT;
      } catch {
        return SEED_PROJECT;
      }
    },

    async saveProject(patch) {
      const prev = (await this.loadProject()) || SEED_PROJECT;
      const next = { ...prev, ...patch, updated_at: new Date().toISOString() };
      try {
        window.sessionStorage.setItem(PROJECT_KEY, JSON.stringify(next));
      } catch { /* jsdom without storage — keep in-memory only */ }
      return next;
    },
  };
}
