import React, { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import {
  Bar, BarChart, CartesianGrid, Cell, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts';
import { format } from 'date-fns';
import { useToast } from '@/hooks/use-toast';
import {
  CHART_COLORS, CHART_MARGINS, CHART_TYPOGRAPHY, GRID_STYLE, LEGEND_PROPS, TOOLTIP_STYLE,
} from '@/utils/chartTheme';
import ChartLogo from '@/components/charts/ChartLogo';
import {
  COMMENT_STATUSES,
  SEVERITIES,
  SEVERITY_CHART_COLORS,
  countBy,
  isOverdue,
  isResolved,
  summarise,
} from '@/lib/peerReview';
import { exportToCSV } from '@/utils/exportUtils';
import { PeerReviewShell } from './components/PeerReviewShell';
import { EmptyState, ErrorState, Loading } from './components/SharedComponents';
import { usePeerReview } from './hooks/usePeerReview';
import { localDateOfInstant } from '../shared/instantDates';

/**
 * AS5 — reporting, from this organization's own rows.
 *
 * The page it replaces is the most dangerous thing the AS programme has
 * found. It offered twelve reports, and every one of them was
 * generated by `getMockReportData(reportId)`, a procedural fabricator:
 *
 *   case 1: return Array.from({length: 45}).map((_, i) => ({
 *     Comment_ID: `CMT-${1000 + i}`,
 *     Author: `Reviewer ${i % 5 + 1}`,
 *     Status: i % 3 === 0 ? 'Open' : ...
 *   }))
 *
 * Forty-five invented comments, thirty invented severities, all
 * plausible, none real. Each card had a Download button that handed the
 * result to a CSV writer which stamped it "<Report title> - Generated
 * on <today's date>" and saved it as
 * `comments_by_status_2026-09-17.csv`.
 *
 * A CSV outlives the app. It gets emailed, attached to an audit
 * response, filed as a record. Report 12 was titled "Full System Audit"
 * and described as a "Complete FDA CFR 21 Part 11 compliant extract of
 * all system actions" — a regulatory claim on a file of invented rows.
 * The same CFR 21 Part 11 wording appeared in Document Control, so it
 * came from the generator rather than from anyone's intent, which is
 * exactly why it needed finding rather than trusting.
 *
 * What is here instead is four cuts of the real register, and one
 * export of the rows actually on screen.
 */
export default function Reports() {
  const { toast } = useToast();
  const { reviews, comments, loading, error, refresh } = usePeerReview();
  const today = new Date();

  const summary = useMemo(() => summarise(reviews, comments, today),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [reviews, comments]);

  const byDiscipline = useMemo(() => countBy(comments, 'discipline'), [comments]);
  const byAsset = useMemo(() => countBy(reviews, 'project_asset'), [reviews]);

  const severityByStatus = useMemo(() => {
    const rows = new Map();
    comments.forEach((c) => {
      const key = c.severity || 'Unspecified';
      if (!rows.has(key)) rows.set(key, Object.fromEntries(COMMENT_STATUSES.map((s) => [s, 0])));
      if (rows.get(key)[c.status] !== undefined) rows.get(key)[c.status] += 1;
    });
    return [...rows.entries()].map(([name, counts]) => ({ name, ...counts }));
  }, [comments]);

  const presentStatuses = useMemo(
    () => COMMENT_STATUSES.filter((s) => summary.byStatus[s] > 0),
    [summary],
  );

  const exportComments = () => {
    if (!comments.length) {
      toast({ description: 'There is nothing to export: no comments have been raised.' });
      return;
    }
    const byId = new Map(reviews.map((r) => [r.id, r]));
    exportToCSV(comments.map((c) => {
      const r = byId.get(c.review_id);
      return {
        'Review code': r?.review_code || '',
        'Review title': r?.title || '',
        'Project or asset': r?.project_asset || '',
        Severity: c.severity || '',
        Status: c.status || '',
        Discipline: c.discipline || '',
        Comment: c.comment_text || '',
        Response: c.response_text || '',
        // ASC-0 (RC-8): the local calendar date of each stamp. Cutting
        // the ISO instant to ten characters printed the UTC date.
        Raised: localDateOfInstant(c.created_at),
        Responded: localDateOfInstant(c.responded_at),
        Verified: localDateOfInstant(c.verified_at),
        Resolved: isResolved(c) ? 'Yes' : 'No',
      };
    }), `peer-review-comments-${format(today, 'yyyy-MM-dd')}`);
  };

  const exportReviews = () => {
    if (!reviews.length) {
      toast({ description: 'There is nothing to export: the register is empty.' });
      return;
    }
    exportToCSV(reviews.map((r) => ({
      Code: r.review_code || '',
      Title: r.title || '',
      Type: r.review_type || '',
      'Project or asset': r.project_asset || '',
      Discipline: r.discipline || '',
      Stage: r.stage || '',
      Priority: r.priority || '',
      Decision: r.decision || '',
      Due: r.due_date || '',
      Overdue: isOverdue(r, today) ? 'Yes' : 'No',
      Comments: r.comments?.length ?? 0,
      'Unresolved comments': (r.comments || []).filter((c) => !isResolved(c)).length,
    })), `peer-review-register-${format(today, 'yyyy-MM-dd')}`);
  };

  if (loading) return <PeerReviewShell><Loading label="Loading reports..." /></PeerReviewShell>;
  if (error) return <PeerReviewShell><ErrorState error={error} onRetry={refresh} /></PeerReviewShell>;

  if (reviews.length === 0) {
    return (
      <PeerReviewShell>
        <EmptyState
          icon={<Download className="w-12 h-12" />}
          title="Nothing to report on yet"
          description="These reports count this organization's own reviews and comments. Raise some and they will appear here."
        />
      </PeerReviewShell>
    );
  }

  const axisTick = { fill: CHART_COLORS.axisText, fontSize: CHART_TYPOGRAPHY.axisFontSize };

  return (
    <PeerReviewShell>
      <div className="space-y-6 animate-in fade-in duration-500">
        <div className="flex flex-wrap justify-between items-center gap-3 bg-[hsl(var(--card))] p-4 rounded-xl border border-[hsl(var(--border))] shadow-sm">
          <div>
            <p className="text-sm">
              {summary.total} review{summary.total === 1 ? '' : 's'} and{' '}
              {summary.totalComments} comment{summary.totalComments === 1 ? '' : 's'},
              {' '}{summary.blockingComments} of them blocking closure, as at{' '}
              {format(today, 'd MMM yyyy')}.
            </p>
            <p className="text-xs text-[hsl(var(--muted-foreground))] mt-1">
              Counted from this organization&apos;s own rows.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" onClick={exportReviews}>
              <Download className="w-4 h-4 mr-2" /> Register (CSV)
            </Button>
            <Button onClick={exportComments}>
              <Download className="w-4 h-4 mr-2" /> Comments (CSV)
            </Button>
          </div>
        </div>

        <Card className="panel-elevation">
          <CardHeader className="border-b border-[hsl(var(--border))] pb-4">
            <CardTitle className="text-lg">Comment severity by disposition</CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            {comments.length === 0 ? (
              <p className="text-center text-[hsl(var(--muted-foreground))] py-10">
                No comments have been raised yet.
              </p>
            ) : (
              <div className="relative h-[340px] rounded-lg p-2" style={{ backgroundColor: CHART_COLORS.background }}>
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={severityByStatus} margin={CHART_MARGINS.legend}>
                    <CartesianGrid {...GRID_STYLE} vertical={false} />
                    <XAxis dataKey="name" stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <YAxis allowDecimals={false} stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <Tooltip contentStyle={TOOLTIP_STYLE} cursor={{ fill: CHART_COLORS.grid }} />
                    <Legend {...LEGEND_PROPS} />
                    {presentStatuses.map((s, i) => (
                      <Bar key={s} dataKey={s} stackId="status" name={s} barSize={44}
                        fill={['#dc2626', '#d97706', '#2563eb', '#059669', '#9f1239', '#94a3b8'][i % 6]} />
                    ))}
                  </BarChart>
                </ResponsiveContainer>
                <ChartLogo />
              </div>
            )}
          </CardContent>
        </Card>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card className="panel-elevation">
            <CardHeader className="border-b border-[hsl(var(--border))] pb-4">
              <CardTitle className="text-lg">Comments by discipline</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="relative h-[300px] rounded-lg p-2" style={{ backgroundColor: CHART_COLORS.background }}>
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={byDiscipline} layout="vertical" margin={CHART_MARGINS.compact}>
                    <CartesianGrid {...GRID_STYLE} horizontal={false} />
                    <XAxis type="number" allowDecimals={false} stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <YAxis dataKey="name" type="category" width={140}
                      stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <Tooltip contentStyle={TOOLTIP_STYLE} cursor={{ fill: CHART_COLORS.grid }} />
                    <Bar dataKey="count" name="Comments" fill="#2563eb" radius={[0, 4, 4, 0]} barSize={20} />
                  </BarChart>
                </ResponsiveContainer>
                <ChartLogo />
              </div>
            </CardContent>
          </Card>

          <Card className="panel-elevation">
            <CardHeader className="border-b border-[hsl(var(--border))] pb-4">
              <CardTitle className="text-lg">Reviews by project or asset</CardTitle>
            </CardHeader>
            <CardContent className="p-6">
              <div className="relative h-[300px] rounded-lg p-2" style={{ backgroundColor: CHART_COLORS.background }}>
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={byAsset} layout="vertical" margin={CHART_MARGINS.compact}>
                    <CartesianGrid {...GRID_STYLE} horizontal={false} />
                    <XAxis type="number" allowDecimals={false} stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <YAxis dataKey="name" type="category" width={140}
                      stroke={CHART_COLORS.axisLine} tick={axisTick} />
                    <Tooltip contentStyle={TOOLTIP_STYLE} cursor={{ fill: CHART_COLORS.grid }} />
                    <Bar dataKey="count" name="Reviews" fill="#059669" radius={[0, 4, 4, 0]} barSize={20} />
                  </BarChart>
                </ResponsiveContainer>
                <ChartLogo />
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="panel-elevation">
          <CardHeader className="border-b border-[hsl(var(--border))] pb-4">
            <CardTitle className="text-lg">Severity mix</CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <div className="flex flex-wrap gap-6">
              {SEVERITIES.map((s) => (
                <div key={s} className="flex items-center gap-3">
                  <span className="w-3 h-3 rounded-full" style={{ backgroundColor: SEVERITY_CHART_COLORS[s] }} />
                  <div>
                    <p className="text-sm font-medium">{s}</p>
                    <p className="text-2xl font-bold">{summary.bySeverity[s]}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </PeerReviewShell>
  );
}
