-- GENERATED by tools/consolidation/gen_policy_rewrites.py — do not hand-edit.
-- 159 policies rewritten onto canonical membership helpers.
-- Skipped (out of scope):
--   petrolord.org_members."org_members manage" (drilling-module namespace, out of scope)
--   petrolord.organizations."orgs read" (drilling-module namespace, out of scope)
--   petrolord.projects."projects write" (drilling-module namespace, out of scope)

-- hse.access_logs."Org members can read access logs"
drop policy if exists "Org members can read access logs" on hse."access_logs";
create policy "Org members can read access logs" on hse."access_logs"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.actions."Assignees and admins can update actions"
drop policy if exists "Assignees and admins can update actions" on hse."actions";
create policy "Assignees and admins can update actions" on hse."actions"
  as permissive for update
  to public
  using (((assigned_to = auth.uid()) OR (public.has_org_role(organization_id, ARRAY['manager'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text]))));

-- hse.actions."Org members can insert actions"
drop policy if exists "Org members can insert actions" on hse."actions";
create policy "Org members can insert actions" on hse."actions"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.actions."Org members can view actions"
drop policy if exists "Org members can view actions" on hse."actions";
create policy "Org members can view actions" on hse."actions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can create actions"
drop policy if exists "Users can create actions" on hse."actions";
create policy "Users can create actions" on hse."actions"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.actions."Users can manage actions for their org"
drop policy if exists "Users can manage actions for their org" on hse."actions";
create policy "Users can manage actions for their org" on hse."actions"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can update actions"
drop policy if exists "Users can update actions" on hse."actions";
create policy "Users can update actions" on hse."actions"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can view actions for their org"
drop policy if exists "Users can view actions for their org" on hse."actions";
create policy "Users can view actions for their org" on hse."actions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.audit_findings."Users can manage audit findings for their organization"
drop policy if exists "Users can manage audit findings for their organization" on hse."audit_findings";
create policy "Users can manage audit findings for their organization" on hse."audit_findings"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.audit_log."Only admins can view audit logs"
drop policy if exists "Only admins can view audit logs" on hse."audit_log";
create policy "Only admins can view audit logs" on hse."audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.audit_log."Users can view audit logs for their org"
drop policy if exists "Users can view audit logs for their org" on hse."audit_log";
create policy "Users can view audit logs for their org" on hse."audit_log"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.audit_logs."Org members can read audit logs"
drop policy if exists "Org members can read audit logs" on hse."audit_logs";
create policy "Org members can read audit logs" on hse."audit_logs"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.audit_schedule."Users can manage audit schedule for their organization"
drop policy if exists "Users can manage audit schedule for their organization" on hse."audit_schedule";
create policy "Users can manage audit schedule for their organization" on hse."audit_schedule"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.competency_records."Users can manage competency records for their organization"
drop policy if exists "Users can manage competency records for their organization" on hse."competency_records";
create policy "Users can manage competency records for their organization" on hse."competency_records"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.contractors."Users can manage contractors for their organization"
drop policy if exists "Users can manage contractors for their organization" on hse."contractors";
create policy "Users can manage contractors for their organization" on hse."contractors"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.environmental_records."Org members can read environmental records"
drop policy if exists "Org members can read environmental records" on hse."environmental_records";
create policy "Org members can read environmental records" on hse."environmental_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.exposure_log."Org members can read exposure logs"
drop policy if exists "Org members can read exposure logs" on hse."exposure_log";
create policy "Org members can read exposure logs" on hse."exposure_log"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.external_reports."Users can manage external reports for their organization"
drop policy if exists "Users can manage external reports for their organization" on hse."external_reports";
create policy "Users can manage external reports for their organization" on hse."external_reports"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_drills."Users can insert fire drills for their org"
drop policy if exists "Users can insert fire drills for their org" on hse."fire_drills";
create policy "Users can insert fire drills for their org" on hse."fire_drills"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_drills."Users can view fire drills for their org"
drop policy if exists "Users can view fire drills for their org" on hse."fire_drills";
create policy "Users can view fire drills for their org" on hse."fire_drills"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_equipment."Users can insert fire equipment for their org"
drop policy if exists "Users can insert fire equipment for their org" on hse."fire_equipment";
create policy "Users can insert fire equipment for their org" on hse."fire_equipment"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_equipment."Users can view fire equipment for their org"
drop policy if exists "Users can view fire equipment for their org" on hse."fire_equipment";
create policy "Users can view fire equipment for their org" on hse."fire_equipment"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_safety_records."Users can insert fire records for their org"
drop policy if exists "Users can insert fire records for their org" on hse."fire_safety_records";
create policy "Users can insert fire records for their org" on hse."fire_safety_records"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_safety_records."Users can view fire records for their org"
drop policy if exists "Users can view fire records for their org" on hse."fire_safety_records";
create policy "Users can view fire records for their org" on hse."fire_safety_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.health_records."Org members can read health records"
drop policy if exists "Org members can read health records" on hse."health_records";
create policy "Org members can read health records" on hse."health_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.internal_audits."Users can manage internal audits for their organization"
drop policy if exists "Users can manage internal audits for their organization" on hse."internal_audits";
create policy "Users can manage internal audits for their organization" on hse."internal_audits"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.project_members."Org Access Project Members"
drop policy if exists "Org Access Project Members" on hse."project_members";
create policy "Org Access Project Members" on hse."project_members"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.reports."Creators and admins can update reports"
drop policy if exists "Creators and admins can update reports" on hse."reports";
create policy "Creators and admins can update reports" on hse."reports"
  as permissive for update
  to public
  using (((created_by = auth.uid()) OR (public.has_org_role(organization_id, ARRAY['manager'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text]))));

-- hse.reports."Org members can insert reports"
drop policy if exists "Org members can insert reports" on hse."reports";
create policy "Org members can insert reports" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Org members can view reports"
drop policy if exists "Org members can view reports" on hse."reports";
create policy "Org members can view reports" on hse."reports"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.reports."Users can create reports for their org"
drop policy if exists "Users can create reports for their org" on hse."reports";
create policy "Users can create reports for their org" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Users can insert reports for their org"
drop policy if exists "Users can insert reports for their org" on hse."reports";
create policy "Users can insert reports for their org" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Users can update reports for their org"
drop policy if exists "Users can update reports for their org" on hse."reports";
create policy "Users can update reports for their org" on hse."reports"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- hse.reports."Users can view reports for their org"
drop policy if exists "Users can view reports for their org" on hse."reports";
create policy "Users can view reports for their org" on hse."reports"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.risk_register."Users can insert risks for their org"
drop policy if exists "Users can insert risks for their org" on hse."risk_register";
create policy "Users can insert risks for their org" on hse."risk_register"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.risk_register."Users can update risks for their org"
drop policy if exists "Users can update risks for their org" on hse."risk_register";
create policy "Users can update risks for their org" on hse."risk_register"
  as permissive for update
  to public
  using ((public.is_org_member(org_id)));

-- hse.risk_register."Users can view risks for their org"
drop policy if exists "Users can view risks for their org" on hse."risk_register";
create policy "Users can view risks for their org" on hse."risk_register"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.role_definitions."Only admins can modify roles"
drop policy if exists "Only admins can modify roles" on hse."role_definitions";
create policy "Only admins can modify roles" on hse."role_definitions"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.role_definitions."Users can view roles for their org"
drop policy if exists "Users can view roles for their org" on hse."role_definitions";
create policy "Users can view roles for their org" on hse."role_definitions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.roles."Org Access Roles"
drop policy if exists "Org Access Roles" on hse."roles";
create policy "Org Access Roles" on hse."roles"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.safety_inductions."Users can manage inductions for their organization"
drop policy if exists "Users can manage inductions for their organization" on hse."safety_inductions";
create policy "Users can manage inductions for their organization" on hse."safety_inductions"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.security_incidents."Org members can read security incidents"
drop policy if exists "Org members can read security incidents" on hse."security_incidents";
create policy "Org members can read security incidents" on hse."security_incidents"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.spill_records."Users can insert spill records for their org"
drop policy if exists "Users can insert spill records for their org" on hse."spill_records";
create policy "Users can insert spill records for their org" on hse."spill_records"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.spill_records."Users can view spill records for their org"
drop policy if exists "Users can view spill records for their org" on hse."spill_records";
create policy "Users can view spill records for their org" on hse."spill_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.spill_response."Users can insert spill response for their org"
drop policy if exists "Users can insert spill response for their org" on hse."spill_response";
create policy "Users can insert spill response for their org" on hse."spill_response"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.spill_response."Users can view spill response for their org"
drop policy if exists "Users can view spill response for their org" on hse."spill_response";
create policy "Users can view spill response for their org" on hse."spill_response"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.subscriptions."Only admins can modify subscription"
drop policy if exists "Only admins can modify subscription" on hse."subscriptions";
create policy "Only admins can modify subscription" on hse."subscriptions"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.subscriptions."Users can view their org subscription"
drop policy if exists "Users can view their org subscription" on hse."subscriptions";
create policy "Users can view their org subscription" on hse."subscriptions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.team_communications."Org Access Communications"
drop policy if exists "Org Access Communications" on hse."team_communications";
create policy "Org Access Communications" on hse."team_communications"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_members."Org Access Members"
drop policy if exists "Org Access Members" on hse."team_members";
create policy "Org Access Members" on hse."team_members"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_performance."Org Access Performance"
drop policy if exists "Org Access Performance" on hse."team_performance";
create policy "Org Access Performance" on hse."team_performance"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_projects."Org Access Projects"
drop policy if exists "Org Access Projects" on hse."team_projects";
create policy "Org Access Projects" on hse."team_projects"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_resources."Org Access Resources"
drop policy if exists "Org Access Resources" on hse."team_resources";
create policy "Org Access Resources" on hse."team_resources"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_tasks."Org Access Tasks"
drop policy if exists "Org Access Tasks" on hse."team_tasks";
create policy "Org Access Tasks" on hse."team_tasks"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.teams."Org Access Teams"
drop policy if exists "Org Access Teams" on hse."teams";
create policy "Org Access Teams" on hse."teams"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.waste_management."Org members can read waste records"
drop policy if exists "Org members can read waste records" on hse."waste_management";
create policy "Org members can read waste records" on hse."waste_management"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.access_audit_log."Org admins view access logs"
drop policy if exists "Org admins view access logs" on public."access_audit_log";
create policy "Org admins view access logs" on public."access_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.access_requests."Org Admins can manage all requests"
drop policy if exists "Org Admins can manage all requests" on public."access_requests";
create policy "Org Admins can manage all requests" on public."access_requests"
  as permissive for all
  to public
  using ((public.has_org_role(access_requests.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.alerts."Org members can insert alerts"
drop policy if exists "Org members can insert alerts" on public."alerts";
create policy "Org members can insert alerts" on public."alerts"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.alerts."Org members can update alerts"
drop policy if exists "Org members can update alerts" on public."alerts";
create policy "Org members can update alerts" on public."alerts"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.alerts."Users can view org alerts"
drop policy if exists "Users can view org alerts" on public."alerts";
create policy "Users can view org alerts" on public."alerts"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.analytics_insights."View org analytics"
drop policy if exists "View org analytics" on public."analytics_insights";
create policy "View org analytics" on public."analytics_insights"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.app_analytics_daily."Org admins view analytics"
drop policy if exists "Org admins view analytics" on public."app_analytics_daily";
create policy "Org admins view analytics" on public."app_analytics_daily"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.app_seat_assignments."Org admins can manage assignments"
drop policy if exists "Org admins can manage assignments" on public."app_seat_assignments";
create policy "Org admins can manage assignments" on public."app_seat_assignments"
  as permissive for all
  to public
  using ((public.has_org_role(app_seat_assignments.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.app_seat_assignments."Org members can view assignments"
drop policy if exists "Org members can view assignments" on public."app_seat_assignments";
create policy "Org members can view assignments" on public."app_seat_assignments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.billing_reports."Admins view reports"
drop policy if exists "Admins view reports" on public."billing_reports";
create policy "Admins view reports" on public."billing_reports"
  as permissive for select
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_audit_log."Org admins can insert audit log"
drop policy if exists "Org admins can insert audit log" on public."branding_audit_log";
create policy "Org admins can insert audit log" on public."branding_audit_log"
  as permissive for insert
  to public
  with check ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_audit_log."Org admins can read audit log"
drop policy if exists "Org admins can read audit log" on public."branding_audit_log";
create policy "Org admins can read audit log" on public."branding_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_presets."Org admins can manage presets"
drop policy if exists "Org admins can manage presets" on public."branding_presets";
create policy "Org admins can manage presets" on public."branding_presets"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_presets."Org members can read presets"
drop policy if exists "Org members can read presets" on public."branding_presets";
create policy "Org members can read presets" on public."branding_presets"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.bulk_import_jobs."Org admins manage bulk imports"
drop policy if exists "Org admins manage bulk imports" on public."bulk_import_jobs";
create policy "Org admins manage bulk imports" on public."bulk_import_jobs"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.compliance_rules."Org admins manage rules"
drop policy if exists "Org admins manage rules" on public."compliance_rules";
create policy "Org admins manage rules" on public."compliance_rules"
  as permissive for all
  to public
  using ((public.has_org_role(org_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.compliance_rules."Org members view rules"
drop policy if exists "Org members view rules" on public."compliance_rules";
create policy "Org members view rules" on public."compliance_rules"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.discount_codes."Admins manage discounts"
drop policy if exists "Admins manage discounts" on public."discount_codes";
create policy "Admins manage discounts" on public."discount_codes"
  as permissive for all
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.employee_app_access."Org Admins can manage app access"
drop policy if exists "Org Admins can manage app access" on public."employee_app_access";
create policy "Org Admins can manage app access" on public."employee_app_access"
  as permissive for all
  to public
  using ((public.has_org_role(employee_app_access.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.employee_storage."Org Admins can manage storage"
drop policy if exists "Org Admins can manage storage" on public."employee_storage";
create policy "Org Admins can manage storage" on public."employee_storage"
  as permissive for all
  to public
  using ((public.has_org_role(employee_storage.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.environment_emp_actions."Org Access EMP"
drop policy if exists "Org Access EMP" on public."environment_emp_actions";
create policy "Org Access EMP" on public."environment_emp_actions"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_facilities."Org Access Facilities"
drop policy if exists "Org Access Facilities" on public."environment_facilities";
create policy "Org Access Facilities" on public."environment_facilities"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_flaring_logs."Org Access Flaring"
drop policy if exists "Org Access Flaring" on public."environment_flaring_logs";
create policy "Org Access Flaring" on public."environment_flaring_logs"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_metrics."Users can view org environment metrics"
drop policy if exists "Users can view org environment metrics" on public."environment_metrics";
create policy "Users can view org environment metrics" on public."environment_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.environment_monitoring_results."Org Access Monitoring"
drop policy if exists "Org Access Monitoring" on public."environment_monitoring_results";
create policy "Org Access Monitoring" on public."environment_monitoring_results"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_obligations."Org Access Obligations"
drop policy if exists "Org Access Obligations" on public."environment_obligations";
create policy "Org Access Obligations" on public."environment_obligations"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_permits."Org Access Permits"
drop policy if exists "Org Access Permits" on public."environment_permits";
create policy "Org Access Permits" on public."environment_permits"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_spill_reports."Org Access Spills"
drop policy if exists "Org Access Spills" on public."environment_spill_reports";
create policy "Org Access Spills" on public."environment_spill_reports"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_studies."Org Access Studies"
drop policy if exists "Org Access Studies" on public."environment_studies";
create policy "Org Access Studies" on public."environment_studies"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_waste_manifests."Org Access Waste"
drop policy if exists "Org Access Waste" on public."environment_waste_manifests";
create policy "Org Access Waste" on public."environment_waste_manifests"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environmental_monitoring."Org members can insert env data"
drop policy if exists "Org members can insert env data" on public."environmental_monitoring";
create policy "Org members can insert env data" on public."environmental_monitoring"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.environmental_monitoring."Org members can view env data"
drop policy if exists "Org members can view env data" on public."environmental_monitoring";
create policy "Org members can view env data" on public."environmental_monitoring"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.fire_drills."Org Access Drills"
drop policy if exists "Org Access Drills" on public."fire_drills";
create policy "Org Access Drills" on public."fire_drills"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_emergency_response_plans."Org Access ERP"
drop policy if exists "Org Access ERP" on public."fire_emergency_response_plans";
create policy "Org Access ERP" on public."fire_emergency_response_plans"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_equipment_inventory."Org Access Equipment"
drop policy if exists "Org Access Equipment" on public."fire_equipment_inventory";
create policy "Org Access Equipment" on public."fire_equipment_inventory"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_equipment_maintenance."Org Access Maintenance"
drop policy if exists "Org Access Maintenance" on public."fire_equipment_maintenance";
create policy "Org Access Maintenance" on public."fire_equipment_maintenance"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_incident_investigation."Org Access Investigation"
drop policy if exists "Org Access Investigation" on public."fire_incident_investigation";
create policy "Org Access Investigation" on public."fire_incident_investigation"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_incidents."Org Access Incidents"
drop policy if exists "Org Access Incidents" on public."fire_incidents";
create policy "Org Access Incidents" on public."fire_incidents"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_safety_compliance."Org Access Compliance"
drop policy if exists "Org Access Compliance" on public."fire_safety_compliance";
create policy "Org Access Compliance" on public."fire_safety_compliance"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_safety_risks."Org Access Risks"
drop policy if exists "Org Access Risks" on public."fire_safety_risks";
create policy "Org Access Risks" on public."fire_safety_risks"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fitness_activities."Users can view org fitness (for leaderboard)"
drop policy if exists "Users can view org fitness (for leaderboard)" on public."fitness_activities";
create policy "Users can view org fitness (for leaderboard)" on public."fitness_activities"
  as permissive for select
  to public
  using ((public.is_org_member(fitness_activities.organization_id)));

-- public.hazard_assessments."Org members can manage hazards"
drop policy if exists "Org members can manage hazards" on public."hazard_assessments";
create policy "Org members can manage hazards" on public."hazard_assessments"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.hazard_assessments."Org members can view hazards"
drop policy if exists "Org members can view hazards" on public."hazard_assessments";
create policy "Org members can view hazards" on public."hazard_assessments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.health_metrics."Users can view org health metrics"
drop policy if exists "Users can view org health metrics" on public."health_metrics";
create policy "Users can view org health metrics" on public."health_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.health_profiles."Supervisors/Admins can view org health profiles"
drop policy if exists "Supervisors/Admins can view org health profiles" on public."health_profiles";
create policy "Supervisors/Admins can view org health profiles" on public."health_profiles"
  as permissive for select
  to public
  using ((public.has_org_role(health_profiles.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])));

-- public.incident_attachments."View attachments"
drop policy if exists "View attachments" on public."incident_attachments";
create policy "View attachments" on public."incident_attachments"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM incidents
  WHERE ((incidents.id = incident_attachments.incident_id) AND ((incidents.created_by = auth.uid()) OR (public.has_org_role(incidents.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])))))));

-- public.incidents."Incidents Insert Policy"
drop policy if exists "Incidents Insert Policy" on public."incidents";
create policy "Incidents Insert Policy" on public."incidents"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.incidents."Incidents Update Policy"
drop policy if exists "Incidents Update Policy" on public."incidents";
create policy "Incidents Update Policy" on public."incidents"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.invoices."Users can view invoices for their own org"
drop policy if exists "Users can view invoices for their own org" on public."invoices";
create policy "Users can view invoices for their own org" on public."invoices"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.leaderboard_history."View org history"
drop policy if exists "View org history" on public."leaderboard_history";
create policy "View org history" on public."leaderboard_history"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.leaderboard_scores."View org leaderboard"
drop policy if exists "View org leaderboard" on public."leaderboard_scores";
create policy "View org leaderboard" on public."leaderboard_scores"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.master_apps."Users can view apps their org has purchased"
drop policy if exists "Users can view apps their org has purchased" on public."master_apps";
create policy "Users can view apps their org has purchased" on public."master_apps"
  as permissive for select
  to public
  using (((EXISTS ( SELECT 1
   FROM (purchased_modules pm
     JOIN organization_members ou ON ((pm.organization_id = ou.organization_id)))
  WHERE ((ou.user_id = auth.uid()) AND (ou.status = 'active'::text) AND (pm.status = 'active'::text) AND (pm.expiry_date > now()) AND ((pm.app_uuid = master_apps.id) OR ((pm.app_uuid IS NULL) AND (pm.module_uuid = master_apps.module_id)))))) OR (auth.role() = 'service_role'::text)));

-- public.master_apps."Users can view purchased apps"
drop policy if exists "Users can view purchased apps" on public."master_apps";
create policy "Users can view purchased apps" on public."master_apps"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM (purchased_modules pm
     JOIN organization_members ou ON ((pm.organization_id = ou.organization_id)))
  WHERE ((ou.user_id = auth.uid()) AND (ou.status = 'active'::text) AND (pm.status = 'active'::text) AND (pm.expiry_date > now()) AND ((pm.app_uuid = master_apps.id) OR ((pm.app_uuid IS NULL) AND (pm.module_uuid = master_apps.module_id)))))));

-- public.moc_records."Org members can manage MOCs"
drop policy if exists "Org members can manage MOCs" on public."moc_records";
create policy "Org members can manage MOCs" on public."moc_records"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.moc_records."Org members can view MOCs"
drop policy if exists "Org members can view MOCs" on public."moc_records";
create policy "Org members can view MOCs" on public."moc_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.model_training_logs."Users can manage training logs for their org"
drop policy if exists "Users can manage training logs for their org" on public."model_training_logs";
create policy "Users can manage training logs for their org" on public."model_training_logs"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.model_training_logs."Users can view training logs for their org"
drop policy if exists "Users can view training logs for their org" on public."model_training_logs";
create policy "Users can view training logs for their org" on public."model_training_logs"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.module_access."Org members view access"
drop policy if exists "Org members view access" on public."module_access";
create policy "Org members view access" on public."module_access"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.org_settings."Users can view settings for their orgs"
drop policy if exists "Users can view settings for their orgs" on public."org_settings";
create policy "Users can view settings for their orgs" on public."org_settings"
  as permissive for select
  to public
  using (((public.is_org_member(org_id)) OR is_super_admin()));

-- public.organization_assets."Users can manage organization assets"
drop policy if exists "Users can manage organization assets" on public."organization_assets";
create policy "Users can manage organization assets" on public."organization_assets"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.organization_members."delete_organization_members"
drop policy if exists "delete_organization_members" on public."organization_members";
create policy "delete_organization_members" on public."organization_members"
  as permissive for delete
  to public
  using ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."insert_organization_members"
drop policy if exists "insert_organization_members" on public."organization_members";
create policy "insert_organization_members" on public."organization_members"
  as permissive for insert
  to public
  with check ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."update_organization_members"
drop policy if exists "update_organization_members" on public."organization_members";
create policy "update_organization_members" on public."organization_members"
  as permissive for update
  to public
  using ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."view_organization_members"
drop policy if exists "view_organization_members" on public."organization_members";
create policy "view_organization_members" on public."organization_members"
  as permissive for select
  to public
  using (((auth.uid() = user_id) OR (public.is_org_member(organization_members.organization_id))));

-- public.payment_methods."Org admins can manage payment methods"
drop policy if exists "Org admins can manage payment methods" on public."payment_methods";
create policy "Org admins can manage payment methods" on public."payment_methods"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.payments."Org members can view own payments"
drop policy if exists "Org members can view own payments" on public."payments";
create policy "Org members can view own payments" on public."payments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.peer_review_audit."Org members can view peer review audit"
drop policy if exists "Org members can view peer review audit" on public."peer_review_audit";
create policy "Org members can view peer review audit" on public."peer_review_audit"
  as permissive for select
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_review_comments."Org members can manage peer review comments"
drop policy if exists "Org members can manage peer review comments" on public."peer_review_comments";
create policy "Org members can manage peer review comments" on public."peer_review_comments"
  as permissive for all
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_review_comments."Org members can view peer review comments"
drop policy if exists "Org members can view peer review comments" on public."peer_review_comments";
create policy "Org members can view peer review comments" on public."peer_review_comments"
  as permissive for select
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_reviews."Org members can manage peer reviews"
drop policy if exists "Org members can manage peer reviews" on public."peer_reviews";
create policy "Org members can manage peer reviews" on public."peer_reviews"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.peer_reviews."Org members can view peer reviews"
drop policy if exists "Org members can view peer reviews" on public."peer_reviews";
create policy "Org members can view peer reviews" on public."peer_reviews"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.predictions."Users can manage predictions for their org"
drop policy if exists "Users can manage predictions for their org" on public."predictions";
create policy "Users can manage predictions for their org" on public."predictions"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.predictions."Users can view predictions for their org"
drop policy if exists "Users can view predictions for their org" on public."predictions";
create policy "Users can view predictions for their org" on public."predictions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.pricing_tiers."Admins manage pricing"
drop policy if exists "Admins manage pricing" on public."pricing_tiers";
create policy "Admins manage pricing" on public."pricing_tiers"
  as permissive for all
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.quick_report_media."View media"
drop policy if exists "View media" on public."quick_report_media";
create policy "View media" on public."quick_report_media"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM quick_reports
  WHERE ((quick_reports.id = quick_report_media.report_id) AND ((quick_reports.created_by_user_id = auth.uid()) OR (public.has_org_role(quick_reports.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])))))));

-- public.recommendations."Org members can insert recommendations"
drop policy if exists "Org members can insert recommendations" on public."recommendations";
create policy "Org members can insert recommendations" on public."recommendations"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.recommendations."Org members can update recommendations"
drop policy if exists "Org members can update recommendations" on public."recommendations";
create policy "Org members can update recommendations" on public."recommendations"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.recommendations."Users can view org recommendations"
drop policy if exists "Users can view org recommendations" on public."recommendations";
create policy "Users can view org recommendations" on public."recommendations"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.regulatory_authorities."Org Access Authorities"
drop policy if exists "Org Access Authorities" on public."regulatory_authorities";
create policy "Org Access Authorities" on public."regulatory_authorities"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.regulatory_obligations."Org Access Obligations"
drop policy if exists "Org Access Obligations" on public."regulatory_obligations";
create policy "Org Access Obligations" on public."regulatory_obligations"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.renewal_audit_log."Org admins can view renewal audit logs"
drop policy if exists "Org admins can view renewal audit logs" on public."renewal_audit_log";
create policy "Org admins can view renewal audit logs" on public."renewal_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.renewal_notifications."Org admins can view renewal notifications"
drop policy if exists "Org admins can view renewal notifications" on public."renewal_notifications";
create policy "Org admins can view renewal notifications" on public."renewal_notifications"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.renewal_reminders."Org admins view reminders"
drop policy if exists "Org admins view reminders" on public."renewal_reminders";
create policy "Org admins view reminders" on public."renewal_reminders"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.risk_kris."Org Access KRIs"
drop policy if exists "Org Access KRIs" on public."risk_kris";
create policy "Org Access KRIs" on public."risk_kris"
  as permissive for all
  to public
  using ((risk_id IN ( SELECT risk_register.id
   FROM risk_register
  WHERE (public.is_org_member(risk_register.org_id)))));

-- public.risk_mitigation_actions."Org Access Mitigation"
drop policy if exists "Org Access Mitigation" on public."risk_mitigation_actions";
create policy "Org Access Mitigation" on public."risk_mitigation_actions"
  as permissive for all
  to public
  using ((risk_id IN ( SELECT risk_register.id
   FROM risk_register
  WHERE (public.is_org_member(risk_register.org_id)))));

-- public.risk_register."Org Access Risks"
drop policy if exists "Org Access Risks" on public."risk_register";
create policy "Org Access Risks" on public."risk_register"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.risk_scenarios."Org Access Scenarios"
drop policy if exists "Org Access Scenarios" on public."risk_scenarios";
create policy "Org Access Scenarios" on public."risk_scenarios"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.safety_audits."Org admins/auditors can manage audits"
drop policy if exists "Org admins/auditors can manage audits" on public."safety_audits";
create policy "Org admins/auditors can manage audits" on public."safety_audits"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'auditor'::text, 'owner'::text])));

-- public.safety_audits."Org members can view audits"
drop policy if exists "Org members can view audits" on public."safety_audits";
create policy "Org members can view audits" on public."safety_audits"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.security_incidents."Admins/Security can update security incidents"
drop policy if exists "Admins/Security can update security incidents" on public."security_incidents";
create policy "Admins/Security can update security incidents" on public."security_incidents"
  as permissive for update
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text, 'security_manager'::text])));

-- public.security_incidents."Users can insert security incidents"
drop policy if exists "Users can insert security incidents" on public."security_incidents";
create policy "Users can insert security incidents" on public."security_incidents"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.security_incidents."Users can view org security incidents"
drop policy if exists "Users can view org security incidents" on public."security_incidents";
create policy "Users can view org security incidents" on public."security_incidents"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.site_locations."Users can insert their org locations"
drop policy if exists "Users can insert their org locations" on public."site_locations";
create policy "Users can insert their org locations" on public."site_locations"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.site_locations."Users can update their org locations"
drop policy if exists "Users can update their org locations" on public."site_locations";
create policy "Users can update their org locations" on public."site_locations"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.site_locations."Users can view their org locations"
drop policy if exists "Users can view their org locations" on public."site_locations";
create policy "Users can view their org locations" on public."site_locations"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.sites."Org admins can manage sites"
drop policy if exists "Org admins can manage sites" on public."sites";
create policy "Org admins can manage sites" on public."sites"
  as permissive for all
  to public
  using ((public.has_org_role(org_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.sites."Org members can view sites"
drop policy if exists "Org members can view sites" on public."sites";
create policy "Org members can view sites" on public."sites"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.subscriptions."Users can view their own org's subscription"
drop policy if exists "Users can view their own org's subscription" on public."subscriptions";
create policy "Users can view their own org's subscription" on public."subscriptions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.support_tickets."Org admins view org tickets"
drop policy if exists "Org admins view org tickets" on public."support_tickets";
create policy "Org admins view org tickets" on public."support_tickets"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.trend_analysis."View org trends"
drop policy if exists "View org trends" on public."trend_analysis";
create policy "View org trends" on public."trend_analysis"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.usage_metrics."Users can view their organization's usage"
drop policy if exists "Users can view their organization's usage" on public."usage_metrics";
create policy "Users can view their organization's usage" on public."usage_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.user_profiles."Org members view profiles"
drop policy if exists "Org members view profiles" on public."user_profiles";
create policy "Org members view profiles" on public."user_profiles"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- storage.objects."Admins View Proofs"
drop policy if exists "Admins View Proofs" on storage."objects";
create policy "Admins View Proofs" on storage."objects"
  as permissive for select
  to public
  using (((bucket_id = 'bank-transfer-proofs'::text) AND ((auth.role() = 'service_role'::text) OR (public.has_any_org_role(ARRAY['admin'::text, 'owner'::text])))));

