/**
 * @jest-environment node
 */
/**
 * SEIS-U1 (practitioner lens, PL2 and PL4): the hostile SEG-Y set through
 * the SEG-Y door and the real import pipeline.
 *
 * Every file is generated by e2e/fixtures/seis/hostile/segyWriter.mjs, the
 * same recipe that wrote the committed .sgy files the browser e2e imports.
 * Each block names its negative control: what the engines alone did with
 * the file on origin/main bf9cc1ebc.
 */
import zlib from 'node:zlib';
import { TextEncoder, TextDecoder } from 'node:util';
import { bufferReader } from '../engine/reader';
import { scanGeometry, readTextualHeader } from '../engine/segyScan';
import { gridFromScan } from '../engine/brickTranscodeV4';
import { DEFLATE_RAW, quantizeU8, dequantizeU8 } from '../engine/brickCodecV4';
import { NULL_VALUE } from '../engine/manifest';
import { memorySpool } from '../services/brickSpool';
import { convertToSpool } from '../services/conversionV4';
import { createImportJobManager, V4_STATUS } from '../services/importJobs';
import { createSliceWorkerHandler } from '../sources/sliceWorkerHandler';
import {
  inspectSegy, openSegyDoor, doorScanWarnings, depthDomainHint, needsTraceLattice,
} from '../lib/segyDoor';
import { writeSegy, HOSTILE_SEGY, amplitude } from '../../../../../e2e/fixtures/seis/hostile/segyWriter.mjs';

if (!global.TextEncoder) global.TextEncoder = TextEncoder;
if (!global.TextDecoder) global.TextDecoder = TextDecoder;

const ZLIB = {
  compression: DEFLATE_RAW,
  deflate: async (b) => new Uint8Array(zlib.deflateRawSync(b)),
  inflate: async (b) => new Uint8Array(zlib.inflateRawSync(b)),
};
const tick = () => new Promise((r) => { setImmediate(r); });
const fileOf = (name) => writeSegy(HOSTILE_SEGY[name].options);
const readerOf = (name) => bufferReader(fileOf(name).buffer);

/** The import dialog's scan, as the ingest worker runs it. */
async function doorScan(name, mapping = {}) {
  const { reader, door } = await openSegyDoor(readerOf(name));
  const scan = await scanGeometry(reader, mapping, {});
  const textLines = await readTextualHeader(reader);
  return {
    reader, door, scan, warnings: doorScanWarnings(door, scan), depthHint: depthDomainHint(textLines),
  };
}

describe('SEIS-U1-001 extended textual headers (rev 1 bytes 3505-3506)', () => {
  test('traces are read from after the extended headers, geometry is the file\'s', async () => {
    // negative control: the engines alone read the first extended header as trace 1
    const raw = await scanGeometry(readerOf('rev1_ext_textual.sgy'), {}, {});
    expect(raw.regular).toBe(false);
    expect(raw.il.max).toBeGreaterThan(1e9);

    const { door, scan, warnings } = await doorScan('rev1_ext_textual.sgy');
    expect(door.extTextHeaders).toBe(2);
    expect(scan.regular).toBe(true);
    expect(scan.il).toEqual({ min: 1001, max: 1008, step: 1, count: 8 });
    expect(scan.xl).toEqual({ min: 2001, max: 2006, step: 1, count: 6 });
    expect(scan.corners.first).toEqual({ x: 500000, y: 700000 });
    expect(warnings.join(' ')).toMatch(/2 extended textual headers \(6,400 bytes\) skipped; traces start at byte 10,001/);
  });

  test('a stale extended-header word whose traces start at 3601 is ignored with a note', async () => {
    const u8 = fileOf('rev1_ieee_clean.sgy');
    new DataView(u8.buffer).setInt16(3504, 3, false);
    const door = await inspectSegy(bufferReader(u8.buffer));
    expect(door.extTextHeaders).toBe(0);
    expect(door.warnings.join(' ')).toMatch(/announces 3 extended textual header\(s\).*ignored/);
  });
});

describe('SEIS-U1-003 headers that disagree stop the import (owner rule)', () => {
  test('binary samples-per-trace 30 against 40 in the trace headers is refused with the size that fits', async () => {
    // negative control: the engines computed 53 traces of garbage geometry
    const raw = await scanGeometry(readerOf('bin_ns_lies.sgy'), {}, {});
    expect(raw.totalTraces).toBe(53);
    expect(raw.warnings.join(' ')).toMatch(/Check the inline\/crossline byte positions/);

    await expect(inspectSegy(readerOf('bin_ns_lies.sgy'))).rejects.toThrow(
      /disagree on the number of samples per trace: the binary header says 30, the first trace header \(byte 115\) says 40\. The file size fits 40/,
    );
  });

  test('an unset binary interval takes the trace headers\' 4 ms, said as a warning', async () => {
    // negative control: the engines stored dt 0 (every time on the axis 0 ms)
    const raw = await scanGeometry(readerOf('bin_dt_zero.sgy'), {}, {});
    expect(raw.dtUs).toBe(0);
    expect(raw.warnings).toEqual([]);

    const { scan, warnings } = await doorScan('bin_dt_zero.sgy');
    expect(scan.dtUs).toBe(4000);
    expect(warnings.join(' ')).toMatch(/no sample interval; 4 ms was read from the trace headers \(byte 117\)/);
  });

  test('two different intervals, and none at all, are refused', async () => {
    const u8 = fileOf('rev1_ieee_clean.sgy');
    new DataView(u8.buffer).setInt16(3216, 2000, false);
    await expect(inspectSegy(bufferReader(u8.buffer))).rejects.toThrow(/binary header says 2 ms, the first trace header \(byte 117\) says 4 ms/);
    const none = writeSegy({ binDtUs: 0, traceDtNs: false });
    await expect(inspectSegy(bufferReader(none.buffer))).rejects.toThrow(/no time axis can be built/);
  });
});

describe('SEIS-U1-004 byte order and sample formats say what they are', () => {
  test('a little-endian rev 2 file is named as byte-swapped', async () => {
    // negative control: "Unsupported SEG-Y sample format code 1280"
    await expect(scanGeometry(readerOf('rev2_little_endian.sgy'), {}, {})).rejects.toThrow(/format code 1280/);
    await expect(inspectSegy(readerOf('rev2_little_endian.sgy'))).rejects.toThrow(/byte-swapped \(little-endian\).*format code 5 only when the bytes are reversed/);
  });

  test('two-byte integers name their format and the way out', async () => {
    await expect(inspectSegy(readerOf('fmt3_int16.sgy'))).rejects.toThrow(
      /2-byte two's complement integer \(format code 3\).*Export the volume again as 32-bit float SEG-Y/,
    );
  });

  test('rev 0 IBM with inline and crossline at bytes 9 and 21 imports under the preset', async () => {
    const { scan, door } = await doorScan('rev0_ibm_ebcdic_9_21.sgy', { ilByte: 9, xlByte: 21 });
    expect(door.revision).toBe(0);
    expect(scan.formatCode).toBe(1);
    expect(scan.regular).toBe(true);
    expect(scan.il.count * scan.xl.count).toBe(48);
  });
});

describe('SEIS-U1-006 coordinates the file does not have, or has in degrees', () => {
  test('all-zero coordinates are said, with the Local way out', async () => {
    const raw = await scanGeometry(readerOf('no_coordinates.sgy'), {}, {});
    expect(raw.warnings).toEqual([]);   // negative control: silent
    const { warnings } = await doorScan('no_coordinates.sgy');
    expect(warnings.join(' ')).toMatch(/no coordinates \(CDP and source X\/Y are zero\).*declare it Local/);
  });

  test('byte 89 = 3 (decimal degrees) is named', async () => {
    const { warnings, door } = await doorScan('degrees_coords.sgy');
    expect(door.coordUnits).toBe(3);
    expect(warnings.join(' ')).toMatch(/coordinates in decimal degrees \(byte 89 = 3\).*geographic CRS/);
  });

  test('state-plane feet with scalar 0 pass the door untouched', async () => {
    const { warnings, scan } = await doorScan('feet_state_plane_scalar0.sgy');
    expect(warnings).toEqual([]);
    expect(scan.measurementSystem).toBe(2);
    expect(scan.corners.first).toEqual({ x: 2200000, y: 13700000 });
  });
});

describe('SEIS-U1-005 a depth volume is declared, never read as time silently', () => {
  test('the PSDM textual header prefills Depth; a time header does not', async () => {
    const psdm = await doorScan('depth_psdm.sgy');
    expect(psdm.depthHint).toEqual(expect.objectContaining({ word: expect.stringMatching(/PSDM|DEPTH/) }));
    const clean = await doorScan('rev1_ieee_clean.sgy');
    expect(clean.depthHint).toBeNull();
  });
});

describe('SEIS-U1-007 a 2D line in the 3D door is pointed at the 2D Lines import', () => {
  test('one inline, forty crosslines', async () => {
    const { warnings } = await doorScan('line2d_cdp21.sgy');
    expect(warnings.join(' ')).toMatch(/this looks like a 2D line.*2D Lines section/);
  });
});

// ---- SEIS-U1-002: irregular outlines and crossline-sorted files import ----

function manager({ storage, rows, file, reader }) {
  return createImportJobManager({
    prepare: async ({ name }) => {
      rows.set('vol-1', { id: 'vol-1', status: V4_STATUS.CONVERTING, name: name || file.name });
      return {
        volumeId: 'vol-1', userId: 'user-1', name: name || file.name,
        ingestRec: { fingerprint: { algo: 'x' }, pipeline: 'v4' },
        crsPlan: { needsTransform: false, storeTag: 'UNKNOWN' }, customDefs: {},
      };
    },
    updateRow: async (id, patch) => { rows.set(id, { ...rows.get(id), ...patch }); return rows.get(id); },
    getRow: async (id) => rows.get(id) || null,
    openSpool: async () => memorySpool(),
    listSpools: async () => [],
    removeSpool: async () => {},
    convert: ({ scan, spool, onProgress }) => convertToSpool({
      reader, scan, spool, codec: ZLIB, brickSize: 8, levels: 2, onProgress,
    }),
    storage: {
      objects: new Map(),
      async upload(path, bytes) { this.objects.set(path, bytes.slice()); storage.set(path, bytes.slice()); return 'uploaded'; },
      async list() { return []; },
    },
    uploadOptions: {
      network: { isOnline: () => true, onOnline: () => () => {} },
      sleep: tick,
      retry: { attempts: 1, baseMs: 1, maxMs: 1 },
    },
    onBeforeUnload: () => () => {},
  });
}

async function importAndReadBack(name) {
  const u8 = fileOf(name);
  const { reader, scan } = await (async () => {
    const o = await openSegyDoor(bufferReader(u8.buffer));
    return { reader: o.reader, scan: await scanGeometry(o.reader, {}, {}) };
  })();
  const storage = new Map();
  const rows = new Map();
  const file = { name, size: u8.byteLength };
  const m = manager({ storage, rows, file, reader });
  const { done } = await m.start({ file, mapping: {}, scan });
  await done;
  const snap = m.getSnapshot()[0];
  if (snap.error) throw new Error(snap.error);
  const manifest = JSON.parse(new TextDecoder().decode(storage.get('user-1/vol-1/manifest.json')));

  const waiters = new Map();
  const handler = createSliceWorkerHandler((msg) => {
    if ((msg.type === 'result' || msg.type === 'error') && waiters.has(msg.id)) {
      waiters.get(msg.id)(msg);
      waiters.delete(msg.id);
    }
  }, {
    // the local view reads the same file through the default door reader
    makeFetcher: () => async (p) => {
      if (!storage.has(p)) throw new Error(`no object ${p}`);
      return storage.get(p).slice().buffer;
    },
    inflate: ZLIB.inflate,
  });
  let seq = 0;
  const call = async (msg) => {
    seq += 1;
    const reply = new Promise((resolve) => { waiters.set(seq, resolve); });
    handler.onMessage({ ...msg, id: seq });
    const r = await reply;
    if (r.type === 'error') throw new Error(`${r.code}: ${r.message}`);
    return r.value;
  };
  handler.onMessage({ type: 'init', budgetBytes: 64 * 1024 * 1024 });
  await call({
    type: 'openBricks', sourceId: 'V4', manifest, storagePath: 'user-1/vol-1', supabaseUrl: 'http://x', persistent: false,
  });
  return {
    manifest, rows, scan, call, blob: new Blob([u8]),
  };
}

describe('SEIS-U1-002 an irregular outline and a crossline-sorted survey import', () => {
  test('negative control: the conversion refused both, blaming the byte positions', async () => {
    const irr = await doorScan('irregular_outline.sgy');
    expect(() => gridFromScan(irr.scan)).toThrow(/Check the inline\/crossline byte positions/);
    const xs = await doorScan('crossline_sorted.sgy');
    expect(() => gridFromScan(xs.scan)).toThrow(/not inline-sorted/);
    expect(needsTraceLattice(irr.scan)).toBe(true);
    expect(needsTraceLattice(xs.scan)).toBe(true);
  });

  test('the dialog says what an irregular outline is instead of blaming the bytes', async () => {
    const { warnings } = await doorScan('irregular_outline.sgy');
    expect(warnings.join(' ')).toMatch(/12 of 48 inline and crossline positions hold no trace \(an irregular survey outline\)\. They import as nulls/);
    expect(warnings.join(' ')).not.toMatch(/^Grid is not regular/);
  });

  test.each(['irregular_outline.sgy', 'crossline_sorted.sgy'])('%s: v4 import, manifest geometry, every slice equal to the file', async (name) => {
    const {
      manifest, rows, call, blob,
    } = await importAndReadBack(name);
    expect(rows.get('vol-1').status).toBe(V4_STATUS.READY);
    expect(manifest.geometry.il).toEqual({ min: 1001, max: 1008, step: 1, count: 8 });
    expect(manifest.geometry.xl).toEqual({ min: 2001, max: 2006, step: 1, count: 6 });
    await call({ type: 'openLocal', sourceId: 'L', file: blob, mapping: {} });
    const { clip } = manifest.display;
    const u32 = (s) => new Uint32Array(s.data.buffer, s.data.byteOffset, s.data.length);
    for (let i = 0; i < 8; i++) {
      // eslint-disable-next-line no-await-in-loop
      const a = await call({ type: 'slice', sourceId: 'V4', orientation: 'inline', index: i });
      // eslint-disable-next-line no-await-in-loop
      const b = await call({ type: 'slice', sourceId: 'L', orientation: 'inline', index: i });
      const e = b.data.map((v) => dequantizeU8(quantizeU8(v, clip), clip));
      expect(u32(a)).toEqual(new Uint32Array(e.buffer));
    }
    // the local read is the file: a live trace carries the written amplitude, a dead cell is null
    const s0 = await call({ type: 'slice', sourceId: 'L', orientation: 'inline', index: 0 });
    const ns = 40;
    const at = (xlIdx, s) => s0.data[xlIdx * ns + s];
    expect(at(5, 20)).toBeCloseTo(amplitude(1001, 2006, 20, ns), 3);
    if (name === 'irregular_outline.sgy') expect(at(0, 20)).toBe(Math.fround(NULL_VALUE));
  });
});
