"""Generate the Pore Pressure Studio P0 goldens (deterministic,
stdlib-only — no RNG anywhere; rerunning must be byte-identical).

Writes test-data/porepressure/goldens.json: Gardner cases, an NCT fit
case, Eaton and Bowers tables, fracture-gradient cases, and a full
synthetic-well prognosis (hydrostatic upper section + overpressure
ramp) built forward-inverse-consistently: the transit-time log is
GENERATED by inverting Eaton on an imposed pore-pressure profile, so
the engine's Eaton forward pass must recover the imposed profile
exactly — no reference dataset needed, the physics closes on itself.

main() ASSERTS the anchors before writing (G2 fixture-v2 lesson — a
regeneration that breaks physics refuses to land):

  A1  Overburden with constant density: exact closed form
      S = rho_sw g WD + rho_b g z at every sample < 1e-9 rel.
  A2  Gardner rho->V->rho and V->rho->V round-trips < 1e-12 rel.
  A3  NCT least-squares fit recovers the generating (dt_ml, c)
      < 1e-9 rel (fit is exact on the log-transform).
  A4  Eaton: ratio = 1 gives PP = P_h exactly (any n); n = 1 gives the
      exact linear blend S - (S - P_h) * ratio.
  A5  Bowers loading sigma->V->sigma round-trip < 1e-12 rel.
  A6  Bowers unloading coincides with loading at sigma = sigma_max
      exactly, and everywhere when U = 1; round-trip < 1e-12 rel.
  A7  Fracture gradient at nu = 1/3: FG = (S + PP)/2 exactly.
  A8  Synthetic well: recovered PP matches the imposed profile
      < 1e-9 rel at every sample; S strictly increasing;
      P_h <= PP < FG < S on the ramp; PP = P_h above it.

Regenerate: python3 tools/validation/porepressure/genfixtures.py
"""

import json
import os
from math import exp

from oracle import (
    G_ACCEL, PA_PER_PSI, M_PER_FT,
    hydrostatic, overburden, gardner_rho, gardner_v,
    nct_dt, fit_nct, eaton,
    bowers_v_loading, bowers_sigma_loading,
    bowers_v_unloading, bowers_sigma_unloading,
    frac_pressure, eaton_K,
)

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "..",
                   "test-data", "porepressure", "goldens.json")

REL = lambda a, b: abs(a - b) / max(abs(a), abs(b), 1e-30)


def build_well():
    """Synthetic GoM-style well. WD 100 m; 0-4000 m below mudline at
    10 m; analytic density rho(z) = 1900 + 700(1 - e^{-0.0005 z});
    NCT dt_ml 656, dt_ma 220 us/m, c 6e-4; imposed PP = hydrostatic
    above 2500 m then a linear-in-z overpressure ramp of 4 kPa/m;
    Eaton n = 3; FG with nu = 0.4."""
    wd, rho_sw, rho_fl = 100.0, 1025.0, 1030.0
    dt_ml, dt_ma, c_nct, n_eaton, nu = 656.0, 220.0, 6.0e-4, 3.0, 0.4
    ramp_top, ramp_kpa_per_m = 2500.0, 4.0

    zs = [10.0 * i for i in range(401)]
    rhos = [1900.0 + 700.0 * (1.0 - exp(-5.0e-4 * z)) for z in zs]
    S = overburden(zs, rhos, wd, rho_sw)
    Ph = [hydrostatic(z, wd, rho_fl, rho_sw) for z in zs]
    PP = [ph + max(0.0, z - ramp_top) * ramp_kpa_per_m * 1000.0
          for z, ph in zip(zs, Ph)]

    dts, dtn = [], []
    for z, s, ph, pp in zip(zs, S, Ph, PP):
        base = nct_dt(z, dt_ml, dt_ma, c_nct)
        dtn.append(base)
        # mudline: S = P_h (0/0) — normally pressured by definition
        ratio = 1.0 if s == ph else ((s - pp) / (s - ph)) ** (1.0 / n_eaton)
        dts.append(base / ratio)

    K = eaton_K(nu)
    FG = [frac_pressure(s, pp, K) for s, pp in zip(S, PP)]
    return {
        "params": {"water_depth_m": wd, "rho_seawater": rho_sw,
                   "rho_fluid": rho_fl, "dt_ml_us_per_m": dt_ml,
                   "dt_ma_us_per_m": dt_ma, "c_nct_per_m": c_nct,
                   "eaton_n": n_eaton, "nu": nu,
                   "ramp_top_m": ramp_top,
                   "ramp_kpa_per_m": ramp_kpa_per_m},
        "z_bml_m": zs, "rho_kg_m3": rhos, "dt_us_per_m": dts,
        "dt_normal_us_per_m": dtn, "overburden_pa": S,
        "hydrostatic_pa": Ph, "pore_pressure_pa": PP,
        "frac_pressure_pa": FG,
    }


def main():
    # ---- A1 constant-density overburden
    zs = [0.0, 500.0, 1234.5, 3000.0]
    S = overburden(zs, [2200.0] * 4, 150.0, 1025.0)
    for z, s in zip(zs, S):
        exact = 1025.0 * G_ACCEL * 150.0 + 2200.0 * G_ACCEL * z
        assert REL(s, exact) < 1e-9, "A1"

    # ---- A2 Gardner round-trips
    for v in (1600.0, 2500.0, 4500.0):
        assert REL(gardner_v(gardner_rho(v)), v) < 1e-12, "A2"
    for rho in (2000.0, 2400.0, 2650.0):
        assert REL(gardner_rho(gardner_v(rho)), rho) < 1e-12, "A2"

    # ---- A3 NCT fit recovery
    gen = {"dt_ml": 650.0, "dt_ma": 220.0, "c": 7.0e-4}
    picks_z = [200.0 + 300.0 * i for i in range(12)]
    picks_dt = [nct_dt(z, gen["dt_ml"], gen["dt_ma"], gen["c"])
                for z in picks_z]
    fit = fit_nct(picks_z, picks_dt, gen["dt_ma"])
    assert REL(fit["dt_ml"], gen["dt_ml"]) < 1e-9, "A3"
    assert REL(fit["c"], gen["c"]) < 1e-9, "A3"

    # ---- A4 Eaton identities
    S0, Ph0 = 60e6, 30e6
    for n in (0.5, 1.0, 3.0, 5.0):
        assert eaton(S0, Ph0, 1.0, n) == Ph0, "A4"
    for r in (0.7, 0.9, 1.0):
        assert REL(eaton(S0, Ph0, r, 1.0), S0 - (S0 - Ph0) * r) < 1e-15, "A4"

    # ---- A5 Bowers loading round-trip
    A, B = 10.0, 0.75
    for sig in (5e6, 20e6, 60e6):
        v = bowers_v_loading(sig, A, B)
        assert REL(bowers_sigma_loading(v, A, B), sig) < 1e-12, "A5"

    # ---- A6 Bowers unloading
    smax = 50e6
    v_load = bowers_v_loading(smax, A, B)
    assert REL(bowers_v_unloading(smax, smax, A, B, 3.0), v_load) < 1e-15, "A6"
    for sig in (10e6, 30e6):
        assert REL(bowers_v_unloading(sig, smax, A, B, 1.0),
                   bowers_v_loading(sig, A, B)) < 1e-12, "A6"
        v = bowers_v_unloading(sig, smax, A, B, 3.0)
        assert REL(bowers_sigma_unloading(v, smax, A, B, 3.0), sig) < 1e-12, "A6"
        assert v > bowers_v_loading(sig, A, B), "A6 unloading sits above"

    # ---- A7 FG at nu = 1/3
    assert REL(frac_pressure(S0, Ph0, eaton_K(1.0 / 3.0)),
               (S0 + Ph0) / 2.0) < 1e-15, "A7"

    # ---- A8 synthetic well closes on itself
    well = build_well()
    p = well["params"]
    for i, z in enumerate(well["z_bml_m"]):
        s, ph = well["overburden_pa"][i], well["hydrostatic_pa"][i]
        ratio = well["dt_normal_us_per_m"][i] / well["dt_us_per_m"][i]
        rec = eaton(s, ph, ratio, p["eaton_n"])
        assert REL(rec, well["pore_pressure_pa"][i]) < 1e-9, "A8 recover"
        if i:
            assert s > well["overburden_pa"][i - 1], "A8 S monotone"
        pp, fg = well["pore_pressure_pa"][i], well["frac_pressure_pa"][i]
        if i == 0:
            # mudline: S = P_h = PP = FG by construction (ULP slack —
            # rho*g*wd vs g*(rho*wd) associate differently)
            assert REL(s, ph) < 1e-15 and REL(pp, fg) < 1e-15, \
                "A8 mudline degeneracy"
        else:
            assert ph <= pp + 1e-6 and pp < fg < s, "A8 ordering"
        if z <= p["ramp_top_m"]:
            assert pp == ph, "A8 hydrostatic segment exact"

    goldens = {
        "_meta": {
            "generator": "tools/validation/porepressure/genfixtures.py",
            "constants": {"G_ACCEL": G_ACCEL, "PA_PER_PSI": PA_PER_PSI,
                          "M_PER_FT": M_PER_FT},
        },
        "gardner": [
            {"v_ms": v, "rho_kg_m3": gardner_rho(v)}
            for v in (1600.0, 2000.0, 2500.0, 3200.0, 4500.0)
        ],
        "nct_fit": {"dt_ma": gen["dt_ma"], "picks_z_m": picks_z,
                    "picks_dt_us_per_m": picks_dt, "fitted": fit},
        "eaton": [
            {"S_pa": S0, "Ph_pa": Ph0, "ratio": r, "n": n,
             "pp_pa": eaton(S0, Ph0, r, n)}
            for r in (1.0, 0.95, 0.9, 0.8, 0.7)
            for n in (1.0, 3.0)
        ],
        "bowers_loading": [
            {"A": A, "B": B, "sigma_pa": sig,
             "v_ms": bowers_v_loading(sig, A, B)}
            for sig in (5e6, 12e6, 20e6, 35e6, 60e6)
        ],
        "bowers_unloading": [
            {"A": A, "B": B, "U": 3.0, "sigma_max_pa": smax,
             "sigma_pa": sig,
             "v_ms": bowers_v_unloading(sig, smax, A, B, 3.0)}
            for sig in (10e6, 20e6, 30e6, 40e6, 50e6)
        ],
        "frac_gradient": [
            {"S_pa": S0, "PP_pa": Ph0, "nu": nu,
             "fp_pa": frac_pressure(S0, Ph0, eaton_K(nu))}
            for nu in (0.25, 1.0 / 3.0, 0.4, 0.45)
        ],
        "well": well,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(goldens, f, indent=1, sort_keys=True)
        f.write("\n")
    print("anchors A1-A8 green; wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
