/**
 * Auto-match round trips: noisy synthetic data generated by the forward
 * model must be inverted back to the generating parameters. This is the
 * WT1 acceptance pattern for the fitting pipeline end to end
 * (model -> Stehfest -> derivative -> Levenberg-Marquardt).
 */
import { autoFitModel } from '../autoFit.js';
import { getModel, evaluateDrawdown, evaluateBuildup } from '../models/modelCatalog.js';

const model = getModel('homogeneous');
const RESERVOIR = { phi: 0.2, mu: 1, ct: 1e-5, rw: 0.3, h: 30, B: 1.2, q: 300, pi: 5000 };
const TRUTH = { k: 120, skin: 8, C: 0.02 };

const logspace = (a, b, n) =>
  Array.from({ length: n }, (_, i) => Math.pow(10, a + ((b - a) * i) / (n - 1)));

// deterministic multiplicative pseudo-noise, ~0.1% amplitude (a fraction of a
// psi at late time; the Bourdet derivative amplifies pressure noise by the
// smoothing-window factor, so this is already several percent on the derivative)
const noisy = (v, i) => v * (1 + 0.001 * Math.sin(12.9898 * (i + 1) + 4.898));

describe('autoFitModel drawdown round trip (k=120, s=8, C=0.02)', () => {
  const times = logspace(-2, 2, 60);
  const clean = evaluateDrawdown({ model, params: TRUTH, reservoir: RESERVOIR, times });
  const data = clean.map((p, i) => ({ t: p.t, dp: noisy(p.dp, i) }));
  const fit = autoFitModel({
    model,
    testType: 'drawdown',
    data,
    reservoir: RESERVOIR,
    initialParams: { k: 30, skin: 0, C: 0.005 },
  });

  test('converges', () => {
    expect(fit).toBeTruthy();
    expect(fit.converged).toBe(true);
    // SSR is set by the derivative-noise floor, not by model mismatch
    expect(fit.ssr).toBeLessThan(0.1);
  });

  test('recovers permeability within 3%', () => {
    expect(Math.abs(fit.params.k - TRUTH.k) / TRUTH.k).toBeLessThan(0.03);
  });

  test('recovers skin within 0.5', () => {
    expect(Math.abs(fit.params.skin - TRUTH.skin)).toBeLessThan(0.5);
  });

  test('recovers wellbore storage within 10%', () => {
    expect(Math.abs(fit.params.C - TRUTH.C) / TRUTH.C).toBeLessThan(0.1);
  });

  test('confidence intervals bracket the truth', () => {
    const [kLo, kHi] = fit.confidence95.k;
    expect(kLo).toBeLessThan(TRUTH.k * 1.03);
    expect(kHi).toBeGreaterThan(TRUTH.k * 0.97);
    expect(kLo).toBeGreaterThan(0);
    expect(kHi).toBeGreaterThan(kLo);
  });

  test('returns the fitted series aligned with the data', () => {
    expect(fit.fitSeries).toHaveLength(data.length);
    const mid = Math.floor(data.length / 2);
    expect(Math.abs(fit.fitSeries[mid].dp - data[mid].dp) / data[mid].dp).toBeLessThan(0.02);
  });
});

describe('autoFitModel buildup round trip', () => {
  const tp = 48;
  const dts = logspace(-2, 1.8, 50);
  const clean = evaluateBuildup({ model, params: TRUTH, reservoir: RESERVOIR, tp, dts });
  const data = clean.map((p, i) => ({ dt: p.dt, dp: noisy(p.dp, i) }));
  const fit = autoFitModel({
    model,
    testType: 'buildup',
    data,
    reservoir: RESERVOIR,
    tp,
    initialParams: { k: 400, skin: 2, C: 0.001 },
  });

  test('converges and recovers the generating parameters', () => {
    expect(fit.converged).toBe(true);
    expect(Math.abs(fit.params.k - TRUTH.k) / TRUTH.k).toBeLessThan(0.03);
    expect(Math.abs(fit.params.skin - TRUTH.skin)).toBeLessThan(0.5);
    expect(Math.abs(fit.params.C - TRUTH.C) / TRUTH.C).toBeLessThan(0.1);
  });
});

describe('autoFitModel input guards', () => {
  test('returns null for insufficient data', () => {
    expect(
      autoFitModel({ model, data: [{ t: 1, dp: 10 }], reservoir: RESERVOIR })
    ).toBeNull();
  });

  test('reports iteration progress', () => {
    const times = logspace(-1, 1, 20);
    const clean = evaluateDrawdown({ model, params: TRUTH, reservoir: RESERVOIR, times });
    const seen = [];
    autoFitModel({
      model,
      data: clean.map((p) => ({ t: p.t, dp: p.dp })),
      reservoir: RESERVOIR,
      initialParams: { k: 80, skin: 4, C: 0.01 },
      onIteration: (iter) => seen.push(iter),
    });
    expect(seen.length).toBeGreaterThan(0);
  });
});
