/**
 * WT9 RTA engines vs the committed fixtures. The oil FMB and linear-flow
 * fixtures are exact closed forms; the gas decline is generated by the
 * Python oracle's own PVT routes (tools/validation/welltest/oracle.py
 * gas_decline_fixture). Full gates in run-validation.mjs CASE 12.
 */
import fs from 'fs';
import path from 'path';
import {
  prepareProductionRows, materialBalanceTime, rateNormalizedSeries,
  flowingMaterialBalanceOil, flowingMaterialBalanceGas, transientLinearAnalysis,
} from '../rta.js';
import { buildGasPvtTable, makePseudoPressure } from '../gas.js';

const goldens = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'goldens.json'), 'utf8')
);

const relErr = (actual, expected) =>
  Math.abs(actual - expected) / Math.max(Math.abs(expected), 1e-300);

describe('WT9 material-balance time', () => {
  test('constant rate collapses to elapsed time exactly', () => {
    const rows = materialBalanceTime(prepareProductionRows(
      Array.from({ length: 10 }, (_, i) => ({ t: i + 1, q: 500, pwf: 3000 }))
    ));
    for (const r of rows) expect(r.te).toBeCloseTo(r.t, 10);
  });

  test('rows are cleaned, sorted and cumulated', () => {
    const rows = prepareProductionRows([
      { t: '5', q: '100', pwf: '3000' },
      { t: 2, q: 200, pwf: 3100 },
      { t: -1, q: 100, pwf: 3000 }, // dropped
      { t: 3, q: 0, pwf: 3000 }, // dropped (no rate)
    ]);
    expect(rows.map((r) => r.t)).toEqual([2, 5]);
    const te = materialBalanceTime(rows);
    expect(te[1].Q).toBeGreaterThan(te[0].Q);
  });
});

describe('WT9 flowing material balance', () => {
  test('oil FMB recovers N and J from the exact exponential decline', () => {
    const fx = goldens.fixtures.rtaOilDecline;
    const rowsTe = materialBalanceTime(prepareProductionRows(fx.rows));
    const fmb = flowingMaterialBalanceOil({ rowsTe, pi: fx.truth.pi, ct: fx.truth.ct });
    expect(relErr(fmb.N, fx.truth.N)).toBeLessThan(5e-3);
    expect(relErr(fmb.J, fx.truth.J)).toBeLessThan(5e-3);
    expect(fmb.r2).toBeGreaterThan(0.999999);
  });

  test('BDF data sits on a late unit slope against te', () => {
    const fx = goldens.fixtures.rtaOilDecline;
    const rowsTe = materialBalanceTime(prepareProductionRows(fx.rows));
    const series = rateNormalizedSeries(rowsTe, { pi: fx.truth.pi });
    const late = series.slice(-12);
    const slope = Math.log(late[late.length - 1].y / late[0].y) /
      Math.log(late[late.length - 1].x / late[0].x);
    expect(Math.abs(slope - 1)).toBeLessThan(0.02);
  });

  test('gas dynamic MB recovers G from the oracle-generated decline', () => {
    const fx = goldens.fixtures.rtaGasDecline;
    const pvt = makePseudoPressure(buildGasPvtTable({
      gasGravity: fx.truth.gasGravity, tempF: fx.truth.tempF, pMax: 7000,
    }));
    const rowsTe = materialBalanceTime(prepareProductionRows(fx.rows));
    const fmb = flowingMaterialBalanceGas({
      rowsTe, pi: fx.truth.pi, pvt, ctI: pvt.cgOf(fx.truth.pi),
    });
    expect(fmb.converged).toBe(true);
    expect(relErr(fmb.G, fx.truth.G)).toBeLessThan(0.02);
  });

  test('returns null instead of nonsense on insufficient or invalid data', () => {
    expect(flowingMaterialBalanceOil({ rowsTe: [], pi: 4800, ct: 1e-5 })).toBeNull();
    expect(flowingMaterialBalanceOil({
      rowsTe: materialBalanceTime(prepareProductionRows([{ t: 1, q: 10, pwf: 100 }])),
      pi: 4800,
      ct: 0,
    })).toBeNull();
  });
});

describe('WT9 transient linear flow', () => {
  test('recovers xf sqrt(k) exactly from the closed-form fixture', () => {
    const fx = goldens.fixtures.rtaLinearFlow;
    const lin = transientLinearAnalysis({
      rows: prepareProductionRows(fx.rows),
      pi: fx.truth.pi, B: fx.truth.B, mu: fx.truth.mu,
      phi: fx.truth.phi, ct: fx.truth.ct, h: fx.truth.h,
    });
    expect(relErr(lin.xfSqrtK, fx.truth.xfSqrtK)).toBeLessThan(1e-6);
  });
});
