"""Deterministic synthetic SEG-Y generator (dev-time oracle input).

Writes the three fixture volumes defined in model.py to
test-data/seismolord/segy/. Hand-rolls the SEG-Y bytes on purpose —
including the IBM 360 float encoding — so segyio remains a fully
independent reader in extract_goldens.py.

Run: tools/validation/seismolord/.venv/bin/python generate_segy.py
"""
import pathlib
import struct

import numpy as np

import model

REPO = pathlib.Path(__file__).resolve().parents[3]
OUT_DIR = REPO / 'test-data' / 'seismolord' / 'segy'


def ieee_to_ibm32(values: np.ndarray) -> np.ndarray:
    """Vectorised float -> IBM System/360 32-bit float, as big-endian uint32.

    IBM32: sign(1) | exponent(7, base-16, bias 64) | fraction(24),
    value = (-1)^s * 0.f * 16^(e-64), fraction normalised to [1/16, 1).
    """
    a = values.astype(np.float64)
    sign = np.where(a < 0, np.uint32(0x80000000), np.uint32(0))
    mag = np.abs(a)

    m2, e2 = np.frexp(mag)                    # mag = m2 * 2**e2, m2 in [0.5, 1)
    e16 = np.ceil(e2 / 4.0).astype(np.int64)  # base-16 exponent
    frac = mag / np.power(16.0, e16, dtype=np.float64)   # in [1/16, 1)
    fbits = np.round(frac * float(1 << 24)).astype(np.int64)

    carry = fbits >= (1 << 24)                # rounding overflowed to 1.0
    fbits = np.where(carry, fbits >> 4, fbits)
    e16 = np.where(carry, e16 + 1, e16)

    exp_field = np.clip(e16 + 64, 0, 127).astype(np.uint32)
    word = sign | (exp_field << 24) | fbits.astype(np.uint32)
    return np.where(mag == 0, np.uint32(0), word).astype('>u4')


def textual_header(spec: model.VolumeSpec) -> bytes:
    lines = [
        f'C01 PETROLORD SEISMOLORD VALIDATION VOLUME: {spec.name.upper()}',
        'C02 SYNTHETIC ANALYTIC DOME - DETERMINISTIC, NO NOISE SEED',
        f'C03 INLINES {spec.il0}-{spec.il0 + spec.n_il - 1} '
        f'XLINES {spec.xl0}-{spec.xl0 + spec.n_xl - 1} '
        f'NS {spec.ns} DT {spec.dt_us}US',
        f'C04 SAMPLE FORMAT CODE {spec.sample_format} '
        f'({"IBM FLOAT" if spec.sample_format == 1 else "IEEE FLOAT"})',
    ]
    if spec.lying_header:
        # Deliberate lie (domain rule: "the textual header lies") — real
        # positions are spec.il_byte/spec.xl_byte.
        lines.append('C05 INLINE BYTES 189-192 XLINE BYTES 193-196')
        lines.append(f'C06 POISON VALUE {model.POISON_ILXL} AT BYTES 189/193')
    else:
        lines.append(f'C05 INLINE BYTES {spec.il_byte} XLINE BYTES {spec.xl_byte}')
    lines.append(f'C07 COORD SCALAR {spec.coord_scalar} AT BYTE 71 (NEGATIVE = DIVIDE)')
    lines.append('C08 GENERATED BY tools/validation/seismolord/generate_segy.py')

    rows = []
    for i in range(40):
        text = lines[i] if i < len(lines) else f'C{i + 1:02d}'
        rows.append(text.ljust(80)[:80])
    return ''.join(rows).encode('cp037')      # EBCDIC


def binary_header(spec: model.VolumeSpec) -> bytes:
    buf = bytearray(400)
    struct.pack_into('>h', buf, 16, spec.dt_us)          # bytes 3217-3218
    struct.pack_into('>h', buf, 20, spec.ns)             # bytes 3221-3222
    struct.pack_into('>h', buf, 24, spec.sample_format)  # bytes 3225-3226
    struct.pack_into('>h', buf, 28, 1)                   # ensemble fold
    struct.pack_into('>h', buf, 30, 4)                   # trace sorting: stacked
    struct.pack_into('>h', buf, 54, 1)                   # measurement system: metres
    return bytes(buf)


def trace_header(spec: model.VolumeSpec, seq: int, il: int, xl: int,
                 x_m: float, y_m: float) -> bytes:
    buf = bytearray(240)

    def put32(byte_pos_1based: int, value: int):
        struct.pack_into('>i', buf, byte_pos_1based - 1, value)

    def put16(byte_pos_1based: int, value: int):
        struct.pack_into('>h', buf, byte_pos_1based - 1, value)

    put32(1, seq)                                   # trace sequence in line
    put32(5, seq)                                   # trace sequence in file
    put16(71, spec.coord_scalar)                    # coordinate scalar
    scale = abs(spec.coord_scalar)
    put32(73, int(round(x_m * scale)))              # source X
    put32(77, int(round(y_m * scale)))              # source Y
    put32(181, int(round(x_m * scale)))             # CDP X
    put32(185, int(round(y_m * scale)))             # CDP Y
    put16(115, spec.ns)
    put16(117, spec.dt_us)

    if spec.lying_header:
        put32(189, model.POISON_ILXL)               # poison the default bytes
        put32(193, model.POISON_ILXL)
    put32(spec.il_byte, il)                          # real positions win
    put32(spec.xl_byte, xl)
    return bytes(buf)


def write_volume(spec: model.VolumeSpec):
    amp = model.synth_traces(spec)                   # (n_il, n_xl, ns) float32
    xg, yg = model.world_coords(spec)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f'{spec.name}.sgy'
    with open(path, 'wb') as f:
        f.write(textual_header(spec))
        f.write(binary_header(spec))
        seq = 0
        for i in range(spec.n_il):                   # inline-sorted,
            for j in range(spec.n_xl):               # crossline fastest
                seq += 1
                il = spec.il0 + i
                xl = spec.xl0 + j
                f.write(trace_header(spec, seq, il, xl, xg[i, j], yg[i, j]))
                if spec.sample_format == 1:
                    f.write(ieee_to_ibm32(amp[i, j]).tobytes())
                else:
                    f.write(amp[i, j].astype('>f4').tobytes())
    size = path.stat().st_size
    expected = 3600 + spec.n_il * spec.n_xl * (240 + spec.ns * 4)
    assert size == expected, f'{path}: {size} != {expected}'
    print(f'wrote {path.relative_to(REPO)} ({size:,} bytes)')


if __name__ == '__main__':
    for spec in model.ALL_VOLUMES:
        write_volume(spec)
