export const MOCK_REVIEWS = [
  {
    id: 'rev-001',
    review_code: 'PR-2026-001',
    title: 'FDP Review - Alpha Field Phase 2',
    review_type: 'Field Development Plan',
    project_asset: 'Alpha Field',
    department: 'Development',
    discipline: 'Multidisciplinary',
    coordinator: 'Sarah Jenkins',
    lead_reviewer: 'Dr. Robert Chen',
    author: 'Michael Chang',
    stage: 'In Review',
    priority: 'Critical',
    due_date: '2026-04-15',
    decision: 'Pending',
    scope_description: 'Comprehensive review of the Alpha Field Phase 2 Development Plan prior to Final Investment Decision (FID). Focus on reservoir simulation updates and facility debottlenecking.',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-25T14:30:00Z',
    team: [
      { role: 'Coordinator', name: 'Sarah Jenkins' },
      { role: 'Lead Reviewer', name: 'Dr. Robert Chen' },
      { role: 'Reviewer (Reservoir)', name: 'Alice Wong' },
      { role: 'Reviewer (Facilities)', name: 'David Smith' },
      { role: 'Author', name: 'Michael Chang' },
      { role: 'Approver', name: 'Elena Rostova' }
    ],
    deliverables: [
      { id: 'd1', name: 'Alpha_FDP_RevB.pdf', version: 'B', status: 'Submitted', date: '2026-03-05' },
      { id: 'd2', name: 'Simulation_Results_Summary.pptx', version: 'A', status: 'Submitted', date: '2026-03-06' }
    ],
    meeting_notes: 'Kick-off meeting held on March 5th. All reviewers agreed on the schedule. Next checkpoint on April 1st.',
    attachments: [
      { name: 'TOR_Alpha_FDP.docx', type: 'Terms of Reference', uploaded_by: 'Sarah Jenkins' }
    ]
  },
  {
    id: 'rev-002',
    review_code: 'PR-2026-002',
    title: 'Annual Reserves Audit - Beta Asset',
    review_type: 'Reserves Audit',
    project_asset: 'Beta Asset',
    department: 'Reserves',
    discipline: 'Geoscience & Reservoir',
    coordinator: 'James Wilson',
    lead_reviewer: 'Amanda Clarke',
    author: 'Tom Hardy',
    stage: 'Verification',
    priority: 'High',
    due_date: '2026-03-30',
    decision: 'Approved with Conditions',
    scope_description: 'Independent audit of 1P, 2P, and 3P reserves for the Beta Asset year-end reporting.',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-03-28T11:00:00Z',
    team: [],
    deliverables: [],
    meeting_notes: '',
    attachments: []
  },
  {
    id: 'rev-003',
    review_code: 'PR-2026-003',
    title: 'Well Concept Review - Gamma-1',
    review_type: 'Well Concept',
    project_asset: 'Gamma Prospect',
    department: 'Drilling',
    discipline: 'Drilling Engineering',
    coordinator: 'Chris Evans',
    lead_reviewer: 'John Doe',
    author: 'Lisa Ray',
    stage: 'Draft',
    priority: 'Medium',
    due_date: '2026-05-10',
    decision: 'Pending',
    scope_description: 'Review of well trajectory, casing design, and mud program for Gamma-1 deepwater exploration well.',
    created_at: '2026-03-20T08:00:00Z',
    updated_at: '2026-03-21T09:00:00Z',
    team: [],
    deliverables: [],
    meeting_notes: '',
    attachments: []
  },
  {
    id: 'rev-004',
    review_code: 'PR-2026-004',
    title: 'Pipeline Routing Study - Delta',
    review_type: 'Facilities Study',
    project_asset: 'Delta Pipeline',
    department: 'Facilities',
    discipline: 'Pipeline Engineering',
    coordinator: 'Sarah Jenkins',
    lead_reviewer: 'Mark Johnson',
    author: 'Kevin Lee',
    stage: 'In Review',
    priority: 'Low',
    due_date: '2026-04-20',
    decision: 'Pending',
    scope_description: 'Review of proposed subsea pipeline routing to avoid identified geohazards.',
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-12T10:00:00Z',
    team: [],
    deliverables: [],
    meeting_notes: '',
    attachments: []
  },
  {
    id: 'rev-005',
    review_code: 'PR-2026-005',
    title: 'Gas Monetization Strategy',
    review_type: 'Commercial Strategy',
    project_asset: 'Epsilon Hub',
    department: 'Commercial',
    discipline: 'Economics',
    coordinator: 'James Wilson',
    lead_reviewer: 'Nancy Drew',
    author: 'Oliver Twist',
    stage: 'Closed',
    priority: 'High',
    due_date: '2026-03-25',
    decision: 'Approved',
    scope_description: 'Review of economic models comparing LNG export vs. domestic gas sales.',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-03-26T10:00:00Z',
    team: [],
    deliverables: [],
    meeting_notes: '',
    attachments: []
  },
  {
    id: 'rev-006',
    review_code: 'PR-2026-006',
    title: 'Production Optimization - Zeta',
    review_type: 'Production Ops',
    project_asset: 'Zeta Platform',
    department: 'Production',
    discipline: 'Production Engineering',
    coordinator: 'Chris Evans',
    lead_reviewer: 'Paul Atreides',
    author: 'Jessica Jones',
    stage: 'Closed',
    priority: 'Medium',
    due_date: '2026-02-15',
    decision: 'Approved',
    scope_description: 'Review of gas lift optimization recommendations and implementation plan.',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-02-16T10:00:00Z',
    team: [],
    deliverables: [],
    meeting_notes: '',
    attachments: []
  }
];

export const MOCK_COMMENTS = [
  {
    id: 'com-001',
    review_id: 'rev-001',
    author: 'Alice Wong',
    comment_text: 'Reservoir model grid resolution seems too coarse near the major fault blocks. Please run a sensitivity with a refined grid.',
    severity: 'Major',
    status: 'Open',
    discipline: 'Reservoir',
    response_text: '',
    responded_by: '',
    responded_at: null,
    verified_by: '',
    verified_at: null,
    created_at: '2026-03-26T09:00:00Z'
  },
  {
    id: 'com-002',
    review_id: 'rev-001',
    author: 'David Smith',
    comment_text: 'Compressor discharge temperature exceeds material limits in Scenario 3. Needs cooler resizing.',
    severity: 'Critical',
    status: 'Responded',
    discipline: 'Facilities',
    response_text: 'Agreed. Have updated the model with an interstage cooler (Doc Ref: Fac_Update_v2).',
    responded_by: 'Michael Chang',
    responded_at: '2026-03-27T10:00:00Z',
    verified_by: '',
    verified_at: null,
    created_at: '2026-03-25T11:00:00Z'
  },
  {
    id: 'com-003',
    review_id: 'rev-002',
    author: 'Amanda Clarke',
    comment_text: 'The 3P reserves estimate includes volumes below the structural spill point without seismic support.',
    severity: 'Critical',
    status: 'Closed',
    discipline: 'Geoscience',
    response_text: 'Volumes below spill point have been removed. Updated tables provided.',
    responded_by: 'Tom Hardy',
    responded_at: '2026-03-10T09:00:00Z',
    verified_by: 'Amanda Clarke',
    verified_at: '2026-03-12T10:00:00Z',
    created_at: '2026-03-05T09:00:00Z'
  },
  {
    id: 'com-004',
    review_id: 'rev-001',
    author: 'Dr. Robert Chen',
    comment_text: 'Typo on page 45 of the main report.',
    severity: 'Minor',
    status: 'Closed',
    discipline: 'General',
    response_text: 'Fixed.',
    responded_by: 'Michael Chang',
    responded_at: '2026-03-26T08:00:00Z',
    verified_by: 'Dr. Robert Chen',
    verified_at: '2026-03-27T08:00:00Z',
    created_at: '2026-03-25T09:00:00Z'
  }
];

export const MOCK_AUDIT = [
  { id: 'a1', review_id: 'rev-001', actor: 'Sarah Jenkins', action: 'Created Review', timestamp: '2026-03-01T10:00:00Z', details: 'Review initialized in Draft state.' },
  { id: 'a2', review_id: 'rev-001', actor: 'Sarah Jenkins', action: 'Changed Stage', timestamp: '2026-03-05T09:00:00Z', details: 'Moved from Draft to In Review.' },
  { id: 'a3', review_id: 'rev-001', actor: 'David Smith', action: 'Added Comment', timestamp: '2026-03-25T11:00:00Z', details: 'Added Critical comment.' },
  { id: 'a4', review_id: 'rev-001', actor: 'Michael Chang', action: 'Responded to Comment', timestamp: '2026-03-27T10:00:00Z', details: 'Provided author response.' }
];