// Ekene dynamic-field fixture gates (NextGen Reservoir course series).
// ============================================================================
// The fixtures in test-data/ekene-dynamic are GENERATED by
// tools/ekene-dynamic/generate.mjs, which runs the actual engines and records
// their outputs. These gates prove the engines still reproduce the committed
// goldens wherever the package travels (teaching datasets ARE the goldens):
//
//   1. DCA: primary-window fits recover the planted Arps parameters (R2 = 1)
//      and match the recorded fit verbatim; EURs match the closed forms.
//   2. MBAL: Havlena-Odeh on the committed history recovers the NG5 volumetric
//      STOIIP (the RC2 volumetrics-vs-material-balance reconciliation).
//   3. SCAL: the Welge construction matches the recorded front/breakthrough.
//   4. VRR: the ledger reproduces the recorded voidage series and targets.

import * as fs from 'fs';
import * as path from 'path';

import { fitArpsModel, calculateEUR } from '../engines/dca/arps.js';
import { computeMaterialBalance } from '../engines/mbal/mbalEngine.ts';
import { analyzeDisplacement, mobilityRatio } from '../engines/scal/fractionalFlow.js';
import { computeVRRSeries, summarizeVRR } from '../engines/waterflood/vrr.js';

// __dirname is available here because babel-jest transforms this file to CJS
// (import.meta is NOT usable in package tests — the N1 extraction gotcha).
const FIX = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'test-data', 'ekene-dynamic', name), 'utf8'));

const field = FIX('field.json');
const rates = FIX('rates.json');
const mbal = FIX('mbal.json');
const scal = FIX('scal.json');
const waterflood = FIX('waterflood.json');

// Relative-tolerance matcher (values span stb to psia; absolute digits don't fit all).
const expectRel = (actual, expected, relTol) => {
  const denom = Math.max(Math.abs(expected), 1e-12);
  expect(Math.abs(actual - expected) / denom).toBeLessThanOrEqual(relTol);
};

describe('Ekene static anchors (locked geoscience goldens)', () => {
  it('carries the NG5 volumetric booking unchanged', () => {
    expect(field.static.stoiip_stb).toBe(12139208.107496763);
    expect(field.static.grv_m3).toBe(22.26903564453125e6);
    expect(field.static.pore_m3).toBe(3.563045809312045e6);
    expect(field.static.oil_cells).toBe(169);
    expect(field.static.owc_m_tvd).toBe(1560);
    expect(field.static.boi_rb_stb).toBe(1.2);
    expect(field.static.swi).toBe(0.35);
  });

  it('keeps the well table byte-identical to the geoscience mapping fixture', () => {
    const w = Object.fromEntries(field.wells.map((r) => [r.name, r]));
    expect(w['Ekene-2'].x).toBe(2200);
    expect(w['Ekene-2'].y).toBe(1150);
    expect(w['Ekene-2'].top_sand_m).toBe(1565); // below the 1560 contact: wet, future injector
    expect(w['Ekene-4'].top_sand_m).toBe(1590);
    expect(w['Ekene-6'].top_sand_m).toBe(1546);
    expect(field.wells.filter((r) => r.role === 'producer')).toHaveLength(4);
  });
});

describe('DCA: planted declines recover through the real engine', () => {
  for (const well of rates.wells) {
    it(`${well.name} primary-window fit matches the recorded golden`, () => {
      const primary = well.monthly.filter((r) => r.date < rates.flood_start);
      const fit = fitArpsModel(
        primary.map((r) => ({ date: r.date, rate: r.oil_bpd })),
        'Auto-Select',
      );
      const g = well.engine_fit_primary_window;
      expect(fit.parameters.modelType).toBe(g.modelType);
      expectRel(fit.parameters.qi, g.qi, 1e-12);
      expectRel(fit.parameters.Di, g.Di, 1e-12);
      expect(fit.parameters.b).toBeCloseTo(g.b, 12);
      expect(fit.R2).toBeCloseTo(1, 9);
      // ...and the golden itself recovers the PLANTED truth.
      expectRel(g.qi, well.planted.qi_bpd, 1e-6);
      expectRel(g.Di, well.planted.di_per_day, 1e-6);
      expect(Math.abs(g.b - well.planted.b)).toBeLessThanOrEqual(1e-3);
    });

    it(`${well.name} EUR matches the recorded closed form`, () => {
      const p = well.planted;
      const eur = calculateEUR(
        p.qi_bpd, p.di_per_day, p.b,
        well.closed_form.econ_limit_bopd, p.model,
      );
      expectRel(eur, well.closed_form.eur_at_econ_limit_stb, 1e-12);
    });

    it(`${well.name} naive full-history fit stays recorded as the cautionary tale`, () => {
      // The flood response makes a single Arps through the whole history
      // invalid; the fixture records the plausible-looking-but-wrong result.
      const g = well.engine_fit_full_history_naive;
      expect(g.R2).toBeLessThan(0.95);
      expect(g.R2).toBeGreaterThan(0.5);
    });
  }
});

describe('MBAL: the history closes on the volumetric STOIIP', () => {
  it('recovers the NG5 booking through Havlena-Odeh', () => {
    const result = computeMaterialBalance(mbal.inputs);
    expectRel(result.estimated_ooip_stb, mbal.expected.estimated_ooip_stb, 1e-12);
    expectRel(result.estimated_ooip_stb, field.static.stoiip_stb, 1e-9);
    expect(result.r_squared).toBeCloseTo(1, 12);
    expectRel(result.regression_slope, mbal.expected.regression_slope, 1e-12);
  });

  it('closed-form pressure inversion reproduces the committed pressures', () => {
    // dp = Np / (N*(co + efwSlope) - Np*co) — the hand-checkable chain the
    // course teaches. Verified against every committed survey row.
    const d = mbal.design;
    const N = field.static.stoiip_stb;
    for (const row of mbal.inputs.production_data.slice(1)) {
      const dp = row.cum_oil_stb / (N * (d.co_per_psi + d.efw_slope_per_psi) - row.cum_oil_stb * d.co_per_psi);
      expectRel(d.pi_psia - dp, row.pressure_psia, 1e-12);
      expectRel(row.bo_rb_stb, 1.2 * (1 + d.co_per_psi * dp), 1e-12);
    }
  });

  it('stays above the bubble point throughout the history', () => {
    for (const row of mbal.inputs.production_data) {
      expect(row.pressure_psia).toBeGreaterThan(mbal.design.pb_psia);
    }
  });
});

describe('SCAL: the Welge construction matches the recorded goldens', () => {
  it('reproduces front saturation, breakthrough and mobility ratio', () => {
    const out = analyzeDisplacement({
      krSpec: scal.design.krSpec,
      muW: scal.design.muW_cp,
      muO: scal.design.muO_cp,
    });
    const g = scal.expected;
    expectRel(mobilityRatio(scal.design.krSpec, scal.design.muW_cp, scal.design.muO_cp), g.mobility_ratio, 1e-12);
    expectRel(out.bl.Swf, g.bl.Swf, 1e-12);
    expectRel(out.bl.fwf, g.bl.fwf, 1e-12);
    expectRel(out.bl.QiBt, g.bl.QiBt, 1e-12);
    expectRel(out.bl.SwAvgBt, g.bl.SwAvgBt, 1e-12);
    expectRel(out.bl.EDbt, g.bl.EDbt, 1e-12);
  });

  it('endpoints are consistent with the field description', () => {
    expect(scal.design.krSpec.Swc).toBe(field.static.swi);
  });
});

describe('VRR: the injection ledger reproduces its recorded series', () => {
  it('matches the recorded cumulative and per-month VRR', () => {
    const series = computeVRRSeries(waterflood.ledger_periods, waterflood.fvf);
    const summary = summarizeVRR(series);
    expectRel(summary.cumulativeVRR, waterflood.expected.cumulative_vrr, 1e-12);
    expectRel(summary.totalProducedVoidage, waterflood.expected.total_produced_voidage_rb, 1e-12);
    for (let i = 0; i < series.length; i++) {
      expectRel(series[i].instantaneousVRR, waterflood.expected.instantaneous_vrr_by_month[i].vrr, 1e-12);
    }
  });

  it('hits the designed start-up ramp exactly (0.85 to 1.05 over six months)', () => {
    const series = computeVRRSeries(waterflood.ledger_periods, waterflood.fvf);
    expectRel(series[0].instantaneousVRR, 0.85, 1e-12);
    expectRel(series[3].instantaneousVRR, 0.97, 1e-12);
    expectRel(series[6].instantaneousVRR, 1.05, 1e-12);
  });

  it('surveillance rows carry the Hall-plot injectivity kink on Ekene-4 only', () => {
    const injRows = waterflood.surveillance_rows.filter((r) => r.inj_bbl > 0);
    const ii = (r) => r.inj_bbl / (r.whp_psi - 2050);
    for (const r of injRows.filter((r) => r.well === 'Ekene-2')) {
      expectRel(ii(r), 0.5, 1e-9);
    }
    for (const r of injRows.filter((r) => r.well === 'Ekene-4')) {
      expectRel(ii(r), r.date >= '2025-01-01' ? 0.35 : 0.5, 1e-9);
    }
  });
});
