// Ekene dynamic-field fixture gates (NextGen Reservoir course series).
// ============================================================================
// The fixtures in test-data/ekene-dynamic are GENERATED by
// tools/ekene-dynamic/generate.mjs, which runs the actual engines and records
// their outputs. These gates prove the engines still reproduce the committed
// goldens wherever the package travels (teaching datasets ARE the goldens):
//
//   1. DCA: primary-window fits recover the planted Arps parameters (R2 = 1)
//      and match the recorded fit verbatim; EURs match the closed forms.
//   2. MBAL: Havlena-Odeh on the committed history recovers the NG5 volumetric
//      STOIIP (the RC2 volumetrics-vs-material-balance reconciliation).
//   3. SCAL: the Welge construction matches the recorded front/breakthrough.
//   4. VRR: the ledger reproduces the recorded voidage series and targets.

import * as fs from 'fs';
import * as path from 'path';

import { fitArpsModel, calculateEUR } from '../engines/dca/arps.js';
import { computeMaterialBalance } from '../engines/mbal/mbalEngine.ts';
import { analyzeDisplacement, mobilityRatio } from '../engines/scal/fractionalFlow.js';
import {
  computeJTable,
  averageJCurves,
  fitJPowerLaw,
  pcFromJ,
  swVsHeight,
  heightFromPc,
  LEVERETT_C,
} from '../engines/scal/scal.js';
import { computeVRRSeries, summarizeVRR } from '../engines/waterflood/vrr.js';

// __dirname is available here because babel-jest transforms this file to CJS
// (import.meta is NOT usable in package tests — the N1 extraction gotcha).
const FIX = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'test-data', 'ekene-dynamic', name), 'utf8'));

const field = FIX('field.json');
const rates = FIX('rates.json');
const mbal = FIX('mbal.json');
const scal = FIX('scal.json');
const waterflood = FIX('waterflood.json');

// Relative-tolerance matcher (values span stb to psia; absolute digits don't fit all).
const expectRel = (actual, expected, relTol) => {
  const denom = Math.max(Math.abs(expected), 1e-12);
  expect(Math.abs(actual - expected) / denom).toBeLessThanOrEqual(relTol);
};

describe('Ekene static anchors (locked geoscience goldens)', () => {
  it('carries the NG5 volumetric booking unchanged', () => {
    expect(field.static.stoiip_stb).toBe(12139208.107496763);
    expect(field.static.grv_m3).toBe(22.26903564453125e6);
    expect(field.static.pore_m3).toBe(3.563045809312045e6);
    expect(field.static.oil_cells).toBe(169);
    expect(field.static.owc_m_tvd).toBe(1560);
    expect(field.static.boi_rb_stb).toBe(1.2);
    expect(field.static.swi).toBe(0.35);
  });

  it('keeps the well table byte-identical to the geoscience mapping fixture', () => {
    const w = Object.fromEntries(field.wells.map((r) => [r.name, r]));
    expect(w['Ekene-2'].x).toBe(2200);
    expect(w['Ekene-2'].y).toBe(1150);
    expect(w['Ekene-2'].top_sand_m).toBe(1565); // below the 1560 contact: wet, future injector
    expect(w['Ekene-4'].top_sand_m).toBe(1590);
    expect(w['Ekene-6'].top_sand_m).toBe(1546);
    expect(field.wells.filter((r) => r.role === 'producer')).toHaveLength(4);
  });
});

describe('DCA: planted declines recover through the real engine', () => {
  for (const well of rates.wells) {
    it(`${well.name} primary-window fit matches the recorded golden`, () => {
      const primary = well.monthly.filter((r) => r.date < rates.flood_start);
      const fit = fitArpsModel(
        primary.map((r) => ({ date: r.date, rate: r.oil_bpd })),
        'Auto-Select',
      );
      const g = well.engine_fit_primary_window;
      expect(fit.parameters.modelType).toBe(g.modelType);
      expectRel(fit.parameters.qi, g.qi, 1e-12);
      expectRel(fit.parameters.Di, g.Di, 1e-12);
      expect(fit.parameters.b).toBeCloseTo(g.b, 12);
      expect(fit.R2).toBeCloseTo(1, 9);
      // ...and the golden itself recovers the PLANTED truth.
      expectRel(g.qi, well.planted.qi_bpd, 1e-6);
      expectRel(g.Di, well.planted.di_per_day, 1e-6);
      expect(Math.abs(g.b - well.planted.b)).toBeLessThanOrEqual(1e-3);
    });

    it(`${well.name} EUR matches the recorded closed form`, () => {
      const p = well.planted;
      const eur = calculateEUR(
        p.qi_bpd, p.di_per_day, p.b,
        well.closed_form.econ_limit_bopd, p.model,
      );
      expectRel(eur, well.closed_form.eur_at_econ_limit_stb, 1e-12);
    });

    it(`${well.name} naive full-history fit stays recorded as the cautionary tale`, () => {
      // The flood response makes a single Arps through the whole history
      // invalid; the fixture records the plausible-looking-but-wrong result.
      const g = well.engine_fit_full_history_naive;
      expect(g.R2).toBeLessThan(0.95);
      expect(g.R2).toBeGreaterThan(0.5);
    });
  }
});

describe('MBAL: the history closes on the volumetric STOIIP', () => {
  it('recovers the NG5 booking through Havlena-Odeh', () => {
    const result = computeMaterialBalance(mbal.inputs);
    expectRel(result.estimated_ooip_stb, mbal.expected.estimated_ooip_stb, 1e-12);
    expectRel(result.estimated_ooip_stb, field.static.stoiip_stb, 1e-9);
    expect(result.r_squared).toBeCloseTo(1, 12);
    expectRel(result.regression_slope, mbal.expected.regression_slope, 1e-12);
  });

  it('closed-form pressure inversion reproduces the committed pressures', () => {
    // dp = Np / (N*(co + efwSlope) - Np*co) — the hand-checkable chain the
    // course teaches. Verified against every committed survey row.
    const d = mbal.design;
    const N = field.static.stoiip_stb;
    for (const row of mbal.inputs.production_data.slice(1)) {
      const dp = row.cum_oil_stb / (N * (d.co_per_psi + d.efw_slope_per_psi) - row.cum_oil_stb * d.co_per_psi);
      expectRel(d.pi_psia - dp, row.pressure_psia, 1e-12);
      expectRel(row.bo_rb_stb, 1.2 * (1 + d.co_per_psi * dp), 1e-12);
    }
  });

  it('stays above the bubble point throughout the history', () => {
    for (const row of mbal.inputs.production_data) {
      expect(row.pressure_psia).toBeGreaterThan(mbal.design.pb_psia);
    }
  });
});

describe('SCAL: the Welge construction matches the recorded goldens', () => {
  it('reproduces front saturation, breakthrough and mobility ratio', () => {
    const out = analyzeDisplacement({
      krSpec: scal.design.krSpec,
      muW: scal.design.muW_cp,
      muO: scal.design.muO_cp,
    });
    const g = scal.expected;
    expectRel(mobilityRatio(scal.design.krSpec, scal.design.muW_cp, scal.design.muO_cp), g.mobility_ratio, 1e-12);
    expectRel(out.bl.Swf, g.bl.Swf, 1e-12);
    expectRel(out.bl.fwf, g.bl.fwf, 1e-12);
    expectRel(out.bl.QiBt, g.bl.QiBt, 1e-12);
    expectRel(out.bl.SwAvgBt, g.bl.SwAvgBt, 1e-12);
    expectRel(out.bl.EDbt, g.bl.EDbt, 1e-12);
  });

  it('endpoints are consistent with the field description', () => {
    expect(scal.design.krSpec.Swc).toBe(field.static.swi);
  });
});

describe('SCAL capillary: the Leverett plant collapses back through the engine', () => {
  const cap = () => scal.capillary;
  const jTrueAt = (Sw) => {
    const { a, b, Swirr } = cap().design.jTrue;
    return a * Math.pow((Sw - Swirr) / (1 - Swirr), -b);
  };

  it('regenerates each plug lab Pc table from the designed J curve', () => {
    for (const plug of cap().lab_pc) {
      const pc = pcFromJ(cap().design.jTrue, plug.sample, cap().design.swGrid);
      expect(pc.ok).toBe(true);
      expect(pc.rows.length).toBe(plug.rows.length);
      for (let i = 0; i < pc.rows.length; i++) {
        expectRel(pc.rows[i].Sw, plug.rows[i].Sw, 1e-12);
        expectRel(pc.rows[i].Pc_psi, plug.rows[i].Pc_psi, 1e-12);
      }
    }
  });

  it('collapses all three plugs to the one designed curve (the 1941 claim, exact)', () => {
    const jTables = cap().lab_pc.map((plug) => {
      const jt = computeJTable(plug.rows.map((r) => ({ Sw: r.Sw, Pc_psi: r.Pc_psi })), plug.sample);
      expect(jt.ok).toBe(true);
      return jt.rows;
    });
    for (let i = 0; i < jTables[0].length; i++) {
      const values = jTables.map((rows) => rows[i].J);
      expect(Math.max(...values) - Math.min(...values)).toBeLessThan(1e-9);
      expectRel(values[0], jTrueAt(jTables[0][i].Sw), 1e-9);
      expectRel(values[0], cap().expected.j_table_ek1p[i].J, 1e-12);
    }
  });

  it('the direct power-law fit recovers the plant exactly; the average refit carries the recorded interpolation drift', () => {
    const jt = computeJTable(
      cap().lab_pc[1].rows.map((r) => ({ Sw: r.Sw, Pc_psi: r.Pc_psi })),
      cap().lab_pc[1].sample,
    );
    const fit = fitJPowerLaw(jt.rows.map((r) => ({ Sw: r.Sw, J: r.J })), {
      Swirr: cap().design.jTrue.Swirr,
    });
    expect(fit.ok).toBe(true);
    expectRel(fit.a, cap().design.jTrue.a, 1e-6);
    expectRel(fit.b, cap().design.jTrue.b, 1e-6);
    expectRel(fit.a, cap().expected.fit_single_plug.a, 1e-12);
    expectRel(fit.b, cap().expected.fit_single_plug.b, 1e-12);

    const avg = averageJCurves(
      cap().lab_pc.map((plug) => {
        const rows = computeJTable(
          plug.rows.map((r) => ({ Sw: r.Sw, Pc_psi: r.Pc_psi })),
          plug.sample,
        ).rows;
        return { name: plug.name, jRows: rows.map((r) => ({ Sw: r.Sw, J: r.J })) };
      }),
      { Swirr: cap().design.jTrue.Swirr },
    );
    expect(avg.ok).toBe(true);
    // Resampling through the log-linear tabulated evaluator drifts the refit
    // off the plant (a ~0.34%, b ~1.03%); the recorded goldens pin the drift.
    expectRel(avg.fit.a, cap().expected.average_refit.a, 1e-9);
    expectRel(avg.fit.b, cap().expected.average_refit.b, 1e-9);
    expect(Math.abs(avg.fit.a - cap().design.jTrue.a)).toBeGreaterThan(1e-4);
  });

  it('reservoir Pc and the saturation-height profile match the recorded goldens', () => {
    const pc = pcFromJ(cap().design.jTrue, cap().design.reservoir, cap().design.swGrid);
    expect(pc.ok).toBe(true);
    for (let i = 0; i < pc.rows.length; i++) {
      expectRel(pc.rows[i].Pc_psi, cap().expected.reservoir_pc[i].Pc_psi, 1e-12);
    }
    const fluids = { gammaW: cap().design.gammaW, gammaHc: cap().design.gammaO_from_api32 };
    const sh = swVsHeight(cap().design.jTrue, cap().design.reservoir, fluids, cap().design.swGrid);
    expect(sh.ok).toBe(true);
    for (let i = 0; i < sh.rows.length; i++) {
      expectRel(sh.rows[i].h_ft, cap().expected.sw_vs_height[i].h_ft, 1e-12);
    }
  });

  it('entry pressure, FWL placement and the crest saturation reproduce the design story', () => {
    const e = cap().expected;
    const d = cap().design;
    const sigmaCos = d.reservoir.sigma_dyncm * Math.cos((d.reservoir.thetaDeg * Math.PI) / 180);
    const psiPerJ = sigmaCos / (LEVERETT_C * Math.sqrt(d.reservoir.k_md / d.reservoir.phi));
    expectRel(d.jTrue.a * psiPerJ, e.pc_entry_psi, 1e-12);
    const fluids = { gammaW: d.gammaW, gammaHc: d.gammaO_from_api32 };
    expectRel(heightFromPc(e.pc_entry_psi, fluids), e.h_entry_ft, 1e-12);
    expectRel(e.h_entry_ft * 0.3048, e.h_entry_m, 1e-12);
    expectRel(field.static.owc_m_tvd + e.h_entry_m, e.fwl_m_tvd, 1e-12);
    // The crest drains to the NG5 booking saturation: flat 0.35 is the
    // crest value, every metre below it is wetter.
    expect(Math.abs(e.sw_at_crest - field.static.swi)).toBeLessThan(0.002);
    expect(e.sw_avg_crest_column_trapz2000).toBeGreaterThan(field.static.swi);
    // Recompute the crest saturation from the recorded factors alone.
    const j = (e.h_crest_ft * cap().factors.grad_psi_per_ft) / psiPerJ;
    const sw = d.jTrue.Swirr + Math.pow(j / d.jTrue.a, -1 / d.jTrue.b) * (1 - d.jTrue.Swirr);
    expectRel(sw, e.sw_at_crest, 1e-12);
  });
});

describe('VRR: the injection ledger reproduces its recorded series', () => {
  it('matches the recorded cumulative and per-month VRR', () => {
    const series = computeVRRSeries(waterflood.ledger_periods, waterflood.fvf);
    const summary = summarizeVRR(series);
    expectRel(summary.cumulativeVRR, waterflood.expected.cumulative_vrr, 1e-12);
    expectRel(summary.totalProducedVoidage, waterflood.expected.total_produced_voidage_rb, 1e-12);
    for (let i = 0; i < series.length; i++) {
      expectRel(series[i].instantaneousVRR, waterflood.expected.instantaneous_vrr_by_month[i].vrr, 1e-12);
    }
  });

  it('hits the designed start-up ramp exactly (0.85 to 1.05 over six months)', () => {
    const series = computeVRRSeries(waterflood.ledger_periods, waterflood.fvf);
    expectRel(series[0].instantaneousVRR, 0.85, 1e-12);
    expectRel(series[3].instantaneousVRR, 0.97, 1e-12);
    expectRel(series[6].instantaneousVRR, 1.05, 1e-12);
  });

  it('surveillance rows carry the Hall-plot injectivity kink on Ekene-4 only', () => {
    const injRows = waterflood.surveillance_rows.filter((r) => r.inj_bbl > 0);
    const ii = (r) => r.inj_bbl / (r.whp_psi - 2050);
    for (const r of injRows.filter((r) => r.well === 'Ekene-2')) {
      expectRel(ii(r), 0.5, 1e-9);
    }
    for (const r of injRows.filter((r) => r.well === 'Ekene-4')) {
      expectRel(ii(r), r.date >= '2025-01-01' ? 0.35 : 0.5, 1e-9);
    }
  });
});
