/**
 * W2.2 trace-attribute oracles: scipy goldens (test-data/seismolord/
 * attributes/attributes_golden.json, generated by the Suite's
 * self-asserting tools/validation/seismolord/attributes/
 * gen_attributes.py) plus hand-computed edge cases. The golden recipe
 * is pinned in the generator header; the engine mirrors it exactly.
 */

import fs from 'fs';
import path from 'path';

import {
  analyticSignal, unwrapPhase, gradient1d, envelopeTrace, instPhaseTrace,
  instFrequencyTrace, sweetnessTrace, windowedRmsTrace, traceAgcTrace,
  halfWindowSamples, makeTraceCompute, ATTRIBUTE_DEFS,
} from '../engines/seismolord/attributes';
import { NULL_VALUE } from '../engines/seismolord/manifest';

const GOLDEN = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', 'test-data', 'seismolord', 'attributes', 'attributes_golden.json'),
  'utf8',
));

const NULL_LIM = 1.0e29;
const isNull = (v) => Math.abs(v) > NULL_LIM;

/** max |golden| over non-null samples — the tolerance scale. */
const scaleOf = (arr) => arr.reduce((m, v) => (isNull(v) ? m : Math.max(m, Math.abs(v))), 0);

/**
 * Compare engine output (float32) against a float64 golden:
 * - null masks must agree (with an optional carve-out near a decision
 *   boundary, e.g. sweetness' freq > 0 test);
 * - non-null values within scale-relative tolerance;
 * - `gate` restricts value comparison to samples where the attribute is
 *   numerically conditioned (low-envelope phase is meaningless).
 */
function compare(out, golden, { rtol = 1e-5, atol = 0, gate = null, boundary = null } = {}) {
  expect(out.length).toBe(golden.length);
  const scale = scaleOf(golden);
  for (let i = 0; i < out.length; i++) {
    const g = golden[i];
    const o = out[i];
    if (isNull(g) !== isNull(o)) {
      if (boundary && boundary(i)) continue;
      throw new Error(`null mask mismatch at ${i}: golden ${g}, engine ${o}`);
    }
    if (isNull(g)) continue;
    if (gate && !gate(i)) continue;
    const tol = rtol * scale + atol;
    if (Math.abs(o - g) > tol) {
      throw new Error(`sample ${i}: engine ${o} vs golden ${g} (tol ${tol})`);
    }
  }
}

describe('scipy goldens', () => {
  const { dt_us: dtUs, ns } = GOLDEN;

  for (const [name, raw] of Object.entries(GOLDEN.traces)) {
    const trace = Float64Array.from(raw);
    const g = GOLDEN.golden[name];
    const envMax = scaleOf(g.envelope);
    // phase/frequency are unconditioned where the analytic signal has no
    // energy; the oracle and engine agree bit-closely everywhere the
    // envelope carries signal
    const conditioned = (i) => !isNull(g.envelope[i]) && g.envelope[i] > 1e-3 * envMax;

    describe(name, () => {
      test('envelope', () => {
        const out = new Float32Array(ns);
        envelopeTrace(trace, out);
        compare(out, g.envelope, { rtol: 1e-5 });
      });

      test('instantaneous phase', () => {
        const out = new Float32Array(ns);
        instPhaseTrace(trace, out);
        compare(out, g.inst_phase, { atol: 1e-2, rtol: 0, gate: conditioned });
      });

      test('instantaneous frequency', () => {
        const out = new Float32Array(ns);
        instFrequencyTrace(trace, dtUs, out);
        compare(out, g.inst_freq, { atol: 1e-2, rtol: 1e-5, gate: conditioned });
      });

      test('sweetness', () => {
        const out = new Float32Array(ns);
        sweetnessTrace(trace, dtUs, out);
        // freq > 0 is a decision boundary, and env/sqrt(f) is
        // unconditioned as f -> 0: compare only where the frequency
        // carries signal (1 Hz floor), like the phase gate
        compare(out, g.sweetness, {
          rtol: 1e-4,
          gate: (i) => conditioned(i) && !isNull(g.inst_freq[i]) && g.inst_freq[i] > 1,
          boundary: (i) => !isNull(g.inst_freq[i]) && Math.abs(g.inst_freq[i]) < 1e-3,
        });
      });

      test('windowed RMS (80 ms)', () => {
        const out = new Float32Array(ns);
        windowedRmsTrace(trace, halfWindowSamples(80, dtUs), out);
        compare(out, g.rms_w80, { rtol: 1e-5 });
      });

      test('AGC amplitude (400 ms)', () => {
        const out = new Float32Array(ns);
        traceAgcTrace(trace, halfWindowSamples(400, dtUs), out);
        compare(out, g.agc_w400, { rtol: 1e-5 });
      });
    });
  }
});

describe('hand cases', () => {
  const NULLV = NULL_VALUE;

  test('halfWindowSamples: 80 ms at 4 ms dt -> 10 samples, floor of 1', () => {
    expect(halfWindowSamples(80, 4000)).toBe(10);
    expect(halfWindowSamples(400, 4000)).toBe(50);
    expect(halfWindowSamples(1, 4000)).toBe(1);
    expect(() => halfWindowSamples(0, 4000)).toThrow();
  });

  test('constant trace: windowed RMS and AGC reproduce the constant', () => {
    const trace = Float32Array.from({ length: 32 }, () => 3);
    const rms = new Float32Array(32);
    windowedRmsTrace(trace, 4, rms);
    const agc = new Float32Array(32);
    traceAgcTrace(trace, 4, agc);
    for (let i = 0; i < 32; i++) {
      expect(rms[i]).toBeCloseTo(3, 5);
      expect(agc[i]).toBeCloseTo(3, 5);
    }
  });

  test('nulls propagate through every attribute', () => {
    const trace = Float32Array.from([NULLV, 1, -2, 3, NULLV, 2, -1, NULLV]);
    for (const name of Object.keys(ATTRIBUTE_DEFS)) {
      const compute = makeTraceCompute(name, {}, { dtUs: 4000 });
      const out = new Float32Array(trace.length);
      compute(trace, out);
      for (const i of [0, 4, 7]) {
        expect(Math.abs(out[i])).toBeGreaterThan(NULL_LIM);
      }
    }
  });

  test('all-zero trace: AGC is zero, never NaN', () => {
    const trace = new Float32Array(16);
    const out = new Float32Array(16);
    traceAgcTrace(trace, 3, out);
    for (const v of out) expect(v).toBe(0);
  });

  test('envelope of a pure sinusoid is ~1 in the interior', () => {
    const ns = 256;
    const trace = Float64Array.from({ length: ns }, (_, i) => Math.sin(2 * Math.PI * 0.1 * i));
    const out = new Float32Array(ns);
    envelopeTrace(trace, out);
    for (let i = 40; i < ns - 40; i++) {
      expect(Math.abs(out[i] - 1)).toBeLessThan(0.05);
    }
  });

  test('unwrapPhase matches np.unwrap on a wrapped ramp', () => {
    const n = 50;
    const truth = Float64Array.from({ length: n }, (_, i) => i * 0.7);
    const wrapped = truth.map((p) => Math.atan2(Math.sin(p), Math.cos(p)));
    const un = unwrapPhase(wrapped);
    for (let i = 0; i < n; i++) {
      expect(un[i] - un[0]).toBeCloseTo(truth[i] - truth[0], 9);
    }
  });

  test('gradient1d matches np.gradient conventions', () => {
    const g = gradient1d(Float64Array.from([0, 1, 4, 9, 16]));
    expect(Array.from(g)).toEqual([1, 2, 4, 6, 7]);
  });

  test('analyticSignal imaginary part is the Hilbert transform of cos -> sin', () => {
    // 32 whole cycles in 256 samples: no spectral leakage, so the
    // analytic signal is exact to rounding
    const ns = 256;
    const trace = Float64Array.from({ length: ns }, (_, i) => Math.cos(2 * Math.PI * 0.125 * i));
    const { im } = analyticSignal(trace);
    for (let i = 0; i < ns; i++) {
      expect(im[i]).toBeCloseTo(Math.sin(2 * Math.PI * 0.125 * i), 9);
    }
  });

  test('unknown attribute and bad dt refuse loudly', () => {
    expect(() => makeTraceCompute('nope', {}, { dtUs: 4000 })).toThrow(/Unknown attribute/);
    expect(() => makeTraceCompute('envelope', {}, { dtUs: 0 })).toThrow(/positive dt/);
  });
});
