/**
 * W2.3 discontinuity oracles: the windowed semblance-variance engine
 * against an independent Python (numpy) implementation on a synthetic
 * faulted layer cube (test-data/seismolord/discontinuity/, generated by
 * the Suite's self-asserting gen_discontinuity.py), end-to-end through
 * runNeighborhoodJob over a real brick store, plus hand-computed edge
 * cases.
 */

import fs from 'fs';
import path from 'path';

import {
  varianceTrace, makeNeighborhoodCompute, DISCONTINUITY_DEFS,
} from '../engines/seismolord/discontinuity';
import { runNeighborhoodJob } from '../engines/seismolord/volumeJob';
import { NULL_VALUE } from '../engines/seismolord/manifest';
import { assembleTrace } from '../engines/seismolord/sliceAssembly';

const GOLDEN = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', 'test-data', 'seismolord', 'discontinuity', 'discontinuity_golden.json'),
  'utf8',
));

const NULL_LIM = 1.0e29;
const NULL_F32 = Math.fround(NULL_VALUE);
const isNull = (v) => Math.abs(v) > NULL_LIM;

const [NIL, NXL, NS] = GOLDEN.shape;
const B = 8;
const GRID = [Math.ceil(NIL / B), Math.ceil(NXL / B), Math.ceil(NS / B)];
const geom = { nIl: NIL, nXl: NXL, ns: NS, brickSize: B, grid: GRID };

/** Brick store laid out exactly as transcodeToBricks writes it. */
function buildBricks(cube) {
  const bricks = new Map();
  const [ni, nj, nk] = GRID;
  for (let i = 0; i < ni; i++) {
    for (let j = 0; j < nj; j++) {
      for (let k = 0; k < nk; k++) {
        bricks.set(`${i}-${j}-${k}`, new Float32Array(B * B * B).fill(NULL_VALUE));
      }
    }
  }
  for (let il = 0; il < NIL; il++) {
    for (let xl = 0; xl < NXL; xl++) {
      for (let k = 0; k < NS; k++) {
        const brick = bricks.get(
          `${Math.floor(il / B)}-${Math.floor(xl / B)}-${Math.floor(k / B)}`,
        );
        brick[((il % B) * B + (xl % B)) * B + (k % B)] = cube[il][xl][k];
      }
    }
  }
  return bricks;
}

describe('numpy golden, end-to-end through runNeighborhoodJob', () => {
  test('variance volume matches the independent implementation', async () => {
    const bricks = buildBricks(GOLDEN.cube);
    const outBricks = new Map();
    const { radius, compute } = makeNeighborhoodCompute(
      'variance',
      { windowMs: GOLDEN.params.window_ms, radius: GOLDEN.params.radius },
      { dtUs: GOLDEN.dt_us },
    );
    expect(radius).toBe(GOLDEN.params.radius);

    const fetches = [];
    const result = await runNeighborhoodJob({
      geom,
      radius,
      compute,
      fetchBrick: async (i, j, k) => {
        fetches.push(`${i}-${j}-${k}`);
        return bricks.get(`${i}-${j}-${k}`);
      },
      onBrick: ({ i, j, k, data }) => outBricks.set(`${i}-${j}-${k}`, data),
    });

    const getOut = async (i, j, k) => outBricks.get(`${i}-${j}-${k}`);
    let checked = 0;
    for (let il = 0; il < NIL; il++) {
      for (let xl = 0; xl < NXL; xl++) {
        const got = await assembleTrace(getOut, geom, il, xl);
        const want = GOLDEN.variance[il][xl];
        for (let t = 0; t < NS; t++) {
          if (isNull(want[t]) !== isNull(got[t])) {
            throw new Error(`null mask mismatch at (${il},${xl},${t})`);
          }
          if (!isNull(want[t])) {
            if (Math.abs(got[t] - want[t]) > 1e-6) {
              throw new Error(`(${il},${xl},${t}): engine ${got[t]} vs numpy ${want[t]}`);
            }
            checked += 1;
          }
        }
      }
    }
    expect(checked).toBeGreaterThan(NIL * NXL * NS * 0.9);

    // dead trace excluded from traceCount; stats live
    expect(result.traceCount).toBe(NIL * NXL - 1);
    expect(result.stats.live_samples).toBe(checked);
    expect(result.stats.min).toBeGreaterThanOrEqual(0);
    expect(result.stats.max).toBeLessThanOrEqual(1);
  });

  test('the fault is bright and the interior dark (physics, not just parity)', () => {
    const v = GOLDEN.variance;
    const layerT = 20;
    let faultMax = 0;
    let interiorMax = 0;
    for (let t = layerT - 2; t < layerT + 2; t++) {
      faultMax = Math.max(faultMax, v[5][GOLDEN.fault_xl - 1][t], v[5][GOLDEN.fault_xl][t]);
      interiorMax = Math.max(interiorMax, v[5][3][t]);
    }
    expect(faultMax).toBeGreaterThan(0.25);
    expect(interiorMax).toBeLessThan(0.1);
  });
});

describe('varianceTrace hand cases', () => {
  const F = (a) => Float32Array.from(a);

  test('identical traces are perfectly coherent (variance exactly 0)', () => {
    const tr = F([1, -2, 3, -1, 2, 0.5]);
    const out = new Float32Array(6);
    varianceTrace(tr, [tr, F(tr), F(tr)], 2, out);
    for (const v of out) expect(v).toBe(0);
  });

  test('fewer than 2 traces is meaningless -> all NULL', () => {
    const tr = F([1, 2, 3]);
    const out = new Float32Array(3);
    varianceTrace(tr, [tr], 1, out);
    for (const v of out) expect(v).toBe(NULL_F32);
  });

  test('silent window counts as coherent (0), not NaN', () => {
    const z = new Float32Array(4);
    const out = new Float32Array(4);
    varianceTrace(z, [z, new Float32Array(4)], 1, out);
    for (const v of out) expect(v).toBe(0);
  });

  test('center nulls propagate; opposite-sign pair maxes out at 1', () => {
    const a = F([1, NULL_VALUE, 1, 1]);
    const b = F([-1, -1, -1, -1]);
    const out = new Float32Array(4);
    varianceTrace(a, [a, b], 0, out);
    expect(out[1]).toBe(NULL_F32);
    // at t=0: sums cancel -> num 0 -> variance 1
    expect(out[0]).toBe(1);
  });

  test('registry validation refuses bad params', () => {
    expect(() => makeNeighborhoodCompute('nope', {}, { dtUs: 4000 })).toThrow(/Unknown discontinuity/);
    expect(() => makeNeighborhoodCompute('variance', {}, { dtUs: 0 })).toThrow(/positive dt/);
    expect(() => makeNeighborhoodCompute('variance', { windowMs: -1 }, { dtUs: 4000 })).toThrow(/not usable/);
    expect(DISCONTINUITY_DEFS.variance.neighborhood).toBe(true);
  });
});

describe('runNeighborhoodJob guards', () => {
  test('radius must fit inside the brick size', async () => {
    await expect(runNeighborhoodJob({
      geom, radius: B, compute: () => {}, fetchBrick: async () => {}, onBrick: () => {},
    })).rejects.toThrow(/below the brick size/);
  });
});
