// Ekene simulation-deck fixture gates (RC5, NextGen Reservoir course series).
// ============================================================================
// test-data/ekene-dynamic/sim.json is GENERATED by tools/ekene-dynamic/
// generate.mjs, which runs the actual engines and records their outputs. These
// gates re-run those engines against the committed goldens, so the deck the
// RC5 course teaches cannot drift from the deck the engines emit.
//
//   1. Structure: simple kriging of the six mapped tops reproduces the TOPS
//      array, and is EXACT at every well that sits on a cell centre.
//   2. Volumetrics: the engine behind the NG5 booking reproduces the deck's
//      oil volume, and the deck matches the booked VOLUME rather than the
//      booked AREA.
//   3. PVT / saturation functions: the designed fluid and the Corey curves
//      round-trip, and the designed fluid genuinely disagrees with the
//      correlation (a taught lesson, not a seeded value).
//   4. Wells: a trajectory intersects the grid into the committed connection
//      list; vertical wells connect every layer.
//   5. The deck: composeDeck reproduces the committed checksum, and
//      validateSpec refuses each broken spec it is supposed to refuse.

import * as fs from 'fs';
import * as path from 'path';
import { createHash } from 'crypto';

import { simpleKrige } from '../engines/earthmodeling/properties.js';
import { zoneVolumes } from '../engines/earthmodeling/volumes.js';
import { generatePvtTable } from '../engines/mbal/mbalEngine.ts';
import { coreyKr } from '../engines/scal/fractionalFlow.js';
import { columnTopDepth, gridDepthRange, gridCellCount } from '../engines/sim/emitGrid.js';
import { connectionsFromPath } from '../engines/sim/wellPath.js';
import { composeDeck, validateSpec } from '../engines/sim/composeDeck.js';
import { wellConnectionCount } from '../engines/sim/emitSchedule.js';

const FIX = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'test-data', 'ekene-dynamic', name), 'utf8'));

const field = FIX('field.json');
const waterflood = FIX('waterflood.json');
const sim = FIX('sim.json');
const D = sim.design;
const E = sim.expected;
const spec = sim.spec;

const M_TO_FT = 1 / 0.3048;
const cellCentreFieldXY = (i, j) => [(i - 1) * D.cellM, (j - 1) * D.cellM];

describe('RC5 deck structure: the six mapped tops, kriged', () => {
  it('reproduces the committed TOPS array from the central kriging engine', () => {
    const points = field.wells.map((w) => ({ x: w.x, y: w.y, v: w.top_sand_m }));
    const targets = [];
    for (let j = 1; j <= D.ny; j += 1) {
      for (let i = 1; i <= D.nx; i += 1) targets.push(cellCentreFieldXY(i, j));
    }
    const tops = simpleKrige(points, D.regionalMean_m, D.krig, targets).map((t) => t * M_TO_FT);
    expect(tops).toHaveLength(spec.grid.tops.length);
    tops.forEach((t, idx) => expect(t).toBeCloseTo(spec.grid.tops[idx], 9));
  });

  it('is an EXACT interpolator at every well that sits on a cell centre', () => {
    const onCentre = E.grid.well_tops.filter((r) => {
      const w = field.wells.find((x) => x.name === r.well);
      const [cx, cy] = cellCentreFieldXY(r.i, r.j);
      return Math.abs(cx - w.x) < 1e-9 && Math.abs(cy - w.y) < 1e-9;
    });
    expect(onCentre.length).toBe(5);
    // Not exactly zero: the deck stores tops in FEET, so reading a well's
    // depth back in metres is a unit round trip. The residual is machine
    // scale, which is the point — it is arithmetic, not structure.
    onCentre.forEach((r) => expect(Math.abs(r.delta_m)).toBeLessThan(1e-9));
    onCentre.forEach((r) => expect(Math.abs(r.delta_m)).toBeLessThan(Math.abs(
      E.grid.well_tops.find((x) => x.well === 'Ekene-2').delta_m) / 1e6));
  });

  it('names Ekene-2 as the one well the grid cannot honour, because it is off the lattice', () => {
    expect(E.grid.off_centre_wells).toEqual(['Ekene-2']);
    const e2 = E.grid.well_tops.find((r) => r.well === 'Ekene-2');
    expect(Math.abs(e2.delta_m)).toBeGreaterThan(0.5);
    expect(columnTopDepth(spec.grid, e2.i, e2.j) / M_TO_FT).toBeCloseTo(e2.deck_top_m, 9);
  });

  it('carries RC4 layer proportions scaled to the mapped net pay', () => {
    const sum = E.grid.layer_dz_ft.reduce((a, b) => a + b, 0);
    expect(sum).toBeCloseTo(E.grid.net_pay_ft, 9);
    expect(E.grid.layer_permx_md).toEqual(waterflood.layers.map((l) => l.k_md));
    const proportions = waterflood.layers.map((l) => l.h_ft / waterflood.layers.reduce((a, b) => a + b.h_ft, 0));
    E.grid.layer_dz_ft.forEach((dz, k) => expect(dz / sum).toBeCloseTo(proportions[k], 12));
  });

  it('reports the grid size and depth envelope the deck was composed against', () => {
    expect(gridCellCount(spec.grid)).toBe(E.grid.cell_count);
    expect(E.grid.cell_count).toBe(D.nx * D.ny * waterflood.layers.length);
    const range = gridDepthRange(spec.grid);
    expect(range.topMin).toBeCloseTo(E.grid.depth_range_ft.topMin, 9);
    expect(range.bottomMax).toBeCloseTo(E.grid.depth_range_ft.bottomMax, 9);
  });
});

describe('RC5 volumetrics: the deck against the booking', () => {
  const volumes = (thickness) => {
    const b = zoneVolumes(
      { dx: D.cellM, dy: D.cellM, nx: D.nx, ny: D.ny },
      thickness,
      thickness.map(() => 'SAND'),
      {
        ntg: thickness.map(() => 1),
        phi: thickness.map(() => field.static.phi),
        sw: thickness.map(() => field.static.swi),
      },
    ).SAND;
    return (b.hcpv_m3 / field.static.boi_rb_stb) * field.static.stb_per_m3;
  };
  const topsM = spec.grid.tops.map((t) => t / M_TO_FT);
  const dzM = E.grid.layer_dz_ft.map((d) => d / M_TO_FT);

  it('reproduces the deck volume under Eclipse cell-centre saturation', () => {
    const oil = topsM.map((t) => {
      let d = t;
      let acc = 0;
      dzM.forEach((dz) => { if (d + dz / 2 < field.static.owc_m_tvd) acc += dz; d += dz; });
      return acc;
    });
    expect(volumes(oil)).toBeCloseTo(E.volumetrics.centre_rule.stoiip_stb, 6);
  });

  it('matches the booked STOIIP to better than a tenth of a percent', () => {
    expect(Math.abs(E.volumetrics.centre_vs_booking_pct)).toBeLessThan(0.1);
    expect(E.volumetrics.booked_stoiip_stb).toBe(field.static.stoiip_stb);
  });

  it('pays for that volume match with a larger oil AREA than the booking', () => {
    expect(E.volumetrics.oil_cells_centre_rule).toBeGreaterThan(E.volumetrics.booked_oil_cells);
    expect(E.volumetrics.booked_oil_cells).toBe(169);
  });

  it('shows the two clipping conventions landing within a percent of each other', () => {
    expect(Math.abs(E.volumetrics.tapered_vs_booking_pct)).toBeLessThan(1);
    expect(E.volumetrics.column_tapered.stoiip_stb).toBeGreaterThan(E.volumetrics.centre_rule.stoiip_stb);
  });
});

describe('RC5 PVT and saturation functions', () => {
  it('returns Boi exactly at the initial pressure on the designed line', () => {
    expect(E.pvt.bo_at_pi).toBe(field.static.boi_rb_stb);
  });

  it('meets the undersaturated line exactly at the bubble point', () => {
    const atPb = E.pvt.pvto_records[E.pvt.pvto_records.length - 1];
    expect(atPb.bo).toBe(E.pvt.bo_at_pb);
    expect(atPb.undersat.length).toBeGreaterThan(0);
    expect(atPb.rs).toBeCloseTo(waterflood.fvf.Rs / 1000, 12);
  });

  it('reproduces the gas table from the central correlation path', () => {
    const gas = generatePvtTable({
      fluid_system: 'gas',
      gas_specific_gravity: 0.75,
      reservoir_temperature_f: 180,
      initial_pressure_psia: 3200,
      pressure_min_psia: D.gasTable.pMin,
      pressure_max_psia: D.gasTable.pMax,
      n_steps: D.gasTable.nSteps,
    });
    expect(gas.rows).toHaveLength(E.pvt.pvdg.length);
    gas.rows.forEach((r, idx) => {
      expect(r.Bg).toBeCloseTo(E.pvt.pvdg[idx].bg, 12);
      expect(r.gas_viscosity_cp).toBeCloseTo(E.pvt.pvdg[idx].mug, 12);
    });
    E.pvt.pvdg.forEach((r, idx) => { if (idx) expect(r.bg).toBeLessThan(E.pvt.pvdg[idx - 1].bg); });
  });

  it('records that the designed fluid and the correlated fluid genuinely disagree', () => {
    // Taught, never seeded: a deck whose PVT disagrees with the model it was
    // matched against is how a simulation study goes quietly wrong.
    expect(Math.abs(E.pvt.divergence_from_correlation.bo_gap_pct)).toBeGreaterThan(1);
    expect(E.pvt.divergence_from_correlation.correlated_rs_at_pb)
      .toBeGreaterThan(E.pvt.divergence_from_correlation.designed_rsi);
  });

  it('starts SWOF at Swc with zero water mobility and closes it at Sw = 1', () => {
    const kr = waterflood.design ? null : null;
    expect(E.satfn.swof_first_sw).toBe(0.35);
    expect(E.satfn.swof_last_sw).toBe(1);
    expect(E.satfn.swof[0].krw).toBe(0);
    const mid = E.satfn.swof[3];
    const engine = coreyKr(mid.Sw, { type: 'corey', Swc: 0.35, Sor: 0.25, krwMax: 0.3, kroMax: 0.9, nw: 2.5, no: 2.0 });
    expect(engine.krw).toBeCloseTo(mid.krw, 12);
    expect(engine.kro).toBeCloseTo(mid.krow, 12);
  });

  it('closes SGOF at Sg = 1 - Swc, which is the SPE1 axis lesson', () => {
    expect(E.satfn.sgof_last_sg).toBeCloseTo(1 - 0.35, 12);
    expect(E.satfn.sgof[0].Sg).toBe(0);
    expect(E.satfn.sgof[0].krg).toBe(0);
  });
});

describe('RC5 wells and trajectory', () => {
  it('connects every vertical well through all five layers', () => {
    spec.wells.filter((w) => !w.connections).forEach((w) => {
      expect(wellConnectionCount(w, spec.grid.nz)).toBe(E.wells.vertical_connection_count);
    });
  });

  it('reproduces the deviated connection list from the trajectory, cell for cell', () => {
    const dev = spec.wells.find((w) => w.name === E.wells.deviated.name);
    expect(dev).toBeTruthy();
    const fieldToDeckFt = (v) => (v + D.originOffsetM) * M_TO_FT;
    const ij = (x, y) => [
      Math.floor(fieldToDeckFt(x) / spec.grid.dx) + 1,
      Math.floor(fieldToDeckFt(y) / spec.grid.dy) + 1,
    ];
    const from = ij(D.deviated.from.x, D.deviated.from.y);
    const to = ij(D.deviated.to.x, D.deviated.to.y);
    expect({ i: from[0], j: from[1] }).toEqual(E.wells.deviated.from_cell);
    expect({ i: to[0], j: to[1] }).toEqual(E.wells.deviated.to_cell);
    const again = connectionsFromPath(
      [
        { x: fieldToDeckFt(D.deviated.from.x), y: fieldToDeckFt(D.deviated.from.y), depth: dev.connections[0] ? spec.grid.tops[(from[1] - 1) * D.nx + (from[0] - 1)] + 0.01 : 0 },
        { x: fieldToDeckFt(D.deviated.to.x), y: fieldToDeckFt(D.deviated.to.y), depth: spec.grid.tops[(to[1] - 1) * D.nx + (to[0] - 1)] + E.grid.net_pay_ft - 0.01 },
      ],
      spec.grid,
    );
    expect(again.map((c) => `${c.i},${c.j},${c.k}`)).toEqual(dev.connections.map((c) => `${c.i},${c.j},${c.k}`));
    expect(dev.connections).toHaveLength(E.wells.deviated.connection_count);
    expect(new Set(dev.connections.map((c) => `${c.i},${c.j}`)).size).toBe(E.wells.deviated.distinct_columns);
    expect(E.wells.deviated.distinct_columns).toBeGreaterThan(1);
  });

  it('keeps every well name inside the eight-character Eclipse limit', () => {
    spec.wells.forEach((w) => expect(w.name.length).toBeLessThanOrEqual(8));
  });
});

describe('RC5 history and the composed deck', () => {
  it('reproduces the RC4 ledger volumes when the history rates are put back over their months', () => {
    expect(E.history.total_oil_stb).toBeCloseTo(E.history.ledger_total_oil_stb, 6);
    expect(E.history.period_count).toBe(36);
    expect(E.history.first_period).toBe('2023-01-01');
  });

  it('composes to the committed deck, byte for byte', () => {
    const deck = composeDeck(spec);
    expect(createHash('sha256').update(deck).digest('hex')).toBe(E.deck.sha256);
    expect(deck.split('\n')).toHaveLength(E.deck.line_count);
  });

  it('emits the six sections in order', () => {
    const lines = composeDeck(spec).split('\n');
    const order = ['RUNSPEC', 'GRID', 'PROPS', 'SOLUTION', 'SUMMARY', 'SCHEDULE'].map((s) => lines.indexOf(s));
    order.forEach((v) => expect(v).toBeGreaterThan(-1));
    order.forEach((v, i) => { if (i) expect(v).toBeGreaterThan(order[i - 1]); });
  });

  it('writes one WCONHIST block per history period', () => {
    const lines = composeDeck(spec).split('\n');
    expect(lines.filter((l) => l.trim() === 'WCONHIST')).toHaveLength(E.history.period_count);
    expect(E.deck.wconhist_blocks).toBe(E.history.period_count);
  });

  it('accepts the Ekene spec', () => {
    expect(validateSpec(spec).ok).toBe(true);
    expect(E.validation.spec_is_valid).toBe(true);
  });

  it('refuses every broken spec the fixture records, and says why', () => {
    expect(E.validation.rejections.length).toBeGreaterThanOrEqual(7);
    E.validation.rejections.forEach((r) => {
      expect(Array.isArray(r.errors)).toBe(true);
      expect(r.errors.length).toBeGreaterThan(0);
    });
  });

  it('keeps each broken spec isolated to ONE rule', () => {
    // A case that cascades teaches the opposite of what it is for. Removing a
    // well from the spec used to raise 180 errors, because the history then
    // named five wells the model no longer had.
    E.validation.rejections.forEach((r) => {
      expect(r.errors.length).toBeLessThanOrEqual(2);
    });
    const single = E.validation.rejections.filter((r) => r.errors.length === 1);
    expect(single.length).toBeGreaterThanOrEqual(6);
  });

  it('still refuses a spec with a well outside the grid, run live', () => {
    const broken = { ...spec, wells: [{ ...spec.wells[0], i: D.nx + 5, connections: undefined }] };
    const v = validateSpec(broken);
    expect(v.ok).toBe(false);
    expect(v.errors.join(' ')).toMatch(/outside the grid/);
  });
});
