// Ekene flood-design gates (RC4, NextGen Reservoir course series).
// ============================================================================
// test-data/ekene-dynamic/waterflood.json is GENERATED by
// tools/ekene-dynamic/generate.mjs. The RC1-RC3 blocks of that fixture are
// gated by ekene.dynamic.test.js; this file gates the RC4 flood-design blocks
// by RE-RUNNING every engine on the fixture's own inputs and comparing against
// the recorded `expected`. Nothing here reads a number and asserts it equals
// itself: each gate closes a loop through an engine.
//
//   1. Per-well ledger rows rebuild the field periods exactly.
//   2. Allocation conserves injected volume exactly and books the out-of-zone
//      remainder; the two flood elements split a balanced field into an
//      over-injected and an under-injected half.
//   3. The pressure track is the closed-form tank inversion, the six-monthly
//      survey cadence misses the trough, and a linear Bo table interpolates
//      exactly.
//   4. The planted log-normal layer set recovers V = 0.5 and sigma = ln 2.
//   5. The five-spot forecasts reproduce their recorded summaries, and the
//      Hall plot recovers the planted injectivity index ONLY on pressure
//      above the reference.

import * as fs from 'fs';
import * as path from 'path';

import { computeVRRSeries } from '../engines/waterflood/vrr.js';
import {
  buildFieldPeriods,
  validateAllocation,
  allocateInjection,
  buildPatternPeriods,
  computeRollingVRR,
  findFillUp,
  attachPressure,
  interpolateFvfTrack,
  recommendPatternInjection,
} from '../engines/waterflood/vrrLedger.js';
import { analyzeWaterflood } from '../engines/waterflood/waterflood.js';
import { analyzeLayeredSweep } from '../engines/waterflood/layeredSweep.js';
import { forecastPattern } from '../engines/waterflood/patternForecast.js';

const FIX = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'test-data', 'ekene-dynamic', name), 'utf8'));

const field = FIX('field.json');
const scal = FIX('scal.json');
const wf = FIX('waterflood.json');
const E = wf.expected;

const near = (a, b, rel = 1e-12) => {
  if (b === 0) expect(Math.abs(a)).toBeLessThan(1e-12);
  else expect(Math.abs(a - b) / Math.abs(b)).toBeLessThan(rel);
};

describe('RC4 ledger rows', () => {
  it('per-well monthly rows rebuild the committed field periods exactly', () => {
    const periods = buildFieldPeriods(wf.ledger_rows);
    expect(periods).toHaveLength(wf.ledger_periods.length);
    let maxRel = 0;
    periods.forEach((p, i) => {
      const q = wf.ledger_periods[i];
      expect(p.label).toBe(q.label);
      for (const k of ['Np', 'Wp', 'Gp', 'Wi', 'Gi']) {
        const rel = q[k] === 0 ? Math.abs(p[k]) : Math.abs(p[k] - q[k]) / Math.abs(q[k]);
        maxRel = Math.max(maxRel, rel);
      }
    });
    expect(maxRel).toBeLessThan(1e-12);
    near(maxRel, E.rows_rebuild_periods_max_rel_diff, 1e-9);
  });

  it('the rebuilt periods reproduce the recorded cumulative VRR', () => {
    const series = computeVRRSeries(buildFieldPeriods(wf.ledger_rows), wf.fvf);
    near(series[series.length - 1].cumulativeVRR, E.cumulative_vrr);
  });
});

describe('RC4 allocation', () => {
  it('flags both injector rows as short of 1.0 without erroring', () => {
    const v = validateAllocation(wf.allocation);
    expect(v.ok).toBe(true);
    expect(v.errors).toHaveLength(0);
    expect(v.warnings).toHaveLength(2);
    expect(v.rowSums).toEqual(E.allocation.row_sums);
  });

  it('conserves injected volume EXACTLY: allocated + out-of-zone = injected', () => {
    const a = allocateInjection(wf.ledger_rows, wf.allocation);
    const total = wf.ledger_rows.reduce((s, r) => s + r.winj_stb, 0);
    const allocated = Object.values(a.perProducer).reduce((s, v) => s + v.winj_stb, 0);
    expect(total - (allocated + a.unallocated.winj_stb)).toBe(0);
    near(total, E.allocation.total_injected_bbl);
    near(allocated, E.allocation.allocated_bbl);
    near(a.unallocated.winj_stb, E.allocation.unallocated.winj_stb);
    Object.entries(E.allocation.per_producer).forEach(([well, v]) => {
      near(a.perProducer[well].winj_stb, v.winj_stb);
    });
  });

  it('splits a near-balanced field into an over- and an under-injected element', () => {
    wf.patterns.forEach((pattern, i) => {
      const periods = buildPatternPeriods(wf.ledger_rows, pattern, wf.allocation);
      const series = computeVRRSeries(periods, wf.fvf);
      const rolling = computeRollingVRR(series, 3);
      const exp = E.patterns[i];
      expect(pattern.name).toBe(exp.name);
      near(series[series.length - 1].cumulativeVRR, exp.cumulative_vrr);
      near(rolling[rolling.length - 1], exp.rolling3_last);
      expect(findFillUp(series)).toEqual(exp.fill_up);
    });
    expect(E.patterns[0].cumulative_vrr).toBeGreaterThan(1.15);
    expect(E.patterns[1].cumulative_vrr).toBeLessThan(0.7);
    expect(E.cumulative_vrr).toBeGreaterThan(1.0);
    expect(E.cumulative_vrr).toBeLessThan(1.05);
  });

  it('reproduces the per-pattern injection recommendation', () => {
    wf.patterns.forEach((pattern, i) => {
      const r = recommendPatternInjection(wf.ledger_rows, pattern, wf.allocation, wf.fvf, {
        targetVRR: 1.0,
        windowPeriods: 3,
      });
      const exp = E.patterns[i].recommendation;
      expect(r.withheld).toBe(false);
      near(r.currentVRR, exp.currentVRR);
      near(r.scale, exp.scale);
      expect(r.clamped).toBe(exp.clamped);
      near(r.recommendedWi, exp.recommendedWi);
    });
  });

  it('withholds pattern advice when no allocation routes to the producers', () => {
    const r = recommendPatternInjection(wf.ledger_rows, { name: 'Unrouted', producers: ['Ekene-9'] }, wf.allocation, wf.fvf, {});
    expect(r.withheld).toBe(true);
    expect(r.reason).toMatch(/allocation/i);
  });
});

describe('RC4 pressure surveillance', () => {
  const design = FIX('mbal.json').design;
  const N = field.static.stoiip_stb;
  const Boi = field.static.boi_rb_stb;

  it('the committed track is the closed-form tank inversion with injection', () => {
    const efw = design.efw_slope_per_psi;
    const co = design.co_per_psi;
    const dpOf = (Np, Wp, Wi) => (Np + ((Wp - Wi) * design.bw_rb_stb) / Boi) / (N * (co + efw) - Np * co);
    wf.pressure.track.forEach((row) => {
      near(design.pi_psia - dpOf(row.cum_np_stb, row.cum_wp_stb, row.cum_wi_bbl), row.p_end_psia);
    });
  });

  it('the break-even VRR is Boi/Bo(ledger), not 1.0', () => {
    near(wf.pressure.break_even_vrr, Boi / wf.fvf.Bo);
    expect(wf.pressure.break_even_vrr).toBeLessThan(1);
    const track = wf.pressure.track;
    const troughIdx = track.reduce((b, r, i) => (r.p_end_psia < track[b].p_end_psia ? i : b), 0);
    expect(track[troughIdx].label).toBe(E.pressure.trough_label);
  });

  it('a six-monthly survey cadence misses the true pressure trough', () => {
    const attached = attachPressure(wf.ledger_periods, wf.pressure.surveys);
    attached.forEach((r, i) => {
      near(r.pressure, E.pressure.attached[i].pressure);
    });
    const idx = attached.reduce((b, r, i) => (r.pressure < attached[b].pressure ? i : b), 0);
    expect(attached[idx].label).toBe(E.pressure.interpolated_trough_label);
    expect(attached[idx].label).not.toBe(E.pressure.trough_label);
    near(attached[idx].pressure - wf.pressure.track.find((t) => t.label === E.pressure.trough_label).p_end_psia,
      E.pressure.trough_missed_by_psi);
  });

  it('interpolates a LINEAR Bo table exactly, and the tracked VRR differs from the frozen one', () => {
    const attached = attachPressure(wf.ledger_periods, wf.pressure.surveys);
    const track = interpolateFvfTrack(wf.pressure.pvt_table, attached.map((r) => r.pressure));
    track.forEach((f, i) => near(f.Bo, E.pressure.fvf_track_bo[i]));
    expect(E.pressure.fvf_interpolation_max_rel_diff).toBeLessThan(1e-14);
    const tracked = computeVRRSeries(wf.ledger_periods.map((p, i) => ({ ...p, Bo: track[i].Bo })), wf.fvf);
    near(tracked[tracked.length - 1].cumulativeVRR, E.pressure.cumulative_vrr_tracked_bo);
    expect(E.pressure.cumulative_vrr_tracked_bo).not.toBe(E.pressure.cumulative_vrr_frozen_bo);
  });
});

describe('RC4 layered sweep', () => {
  it('the planted log-normal layer set recovers V = 0.5 and sigma = ln 2', () => {
    const r = analyzeLayeredSweep({
      layers: wf.layers.map((l) => ({ h: l.h_ft, k: l.k_md })),
      M: wf.layer_design.mobility_ratio,
      A: wf.layer_design.stiles_capacity_ratio,
    });
    expect(r.V.V).toBeCloseTo(0.5, 15);
    expect(r.V.sigma).toBeCloseTo(Math.log(2), 15);
    near(r.V.k50, wf.layer_design.k50_md, 1e-12);
    r.dykstraParsons.forEach((s, i) => {
      near(s.coverage, E.layered_sweep.dykstra_parsons[i].coverage);
      const wor = E.layered_sweep.dykstra_parsons[i].WOR;
      if (wor === 'Infinity') expect(s.WOR).toBe(Infinity);
      else near(s.WOR, wor);
    });
    r.stiles.forEach((s, i) => {
      near(s.coverage, E.layered_sweep.stiles[i].coverage);
      near(s.waterCut, E.layered_sweep.stiles[i].water_cut);
    });
  });

  it('the Stiles capacity ratio is the mobility ratio in surface units', () => {
    near(wf.layer_design.stiles_capacity_ratio, (wf.layer_design.mobility_ratio * wf.fvf.Bo) / wf.fvf.Bw);
  });

  it('at M > 1 Dykstra-Parsons is more pessimistic than Stiles at first breakthrough', () => {
    expect(wf.layer_design.mobility_ratio).toBeGreaterThan(1);
    expect(E.layered_sweep.dykstra_parsons[0].coverage).toBeLessThan(E.layered_sweep.stiles[0].coverage);
    near(E.layered_sweep.ev_first_breakthrough, E.layered_sweep.dykstra_parsons[0].coverage);
  });
});

describe('RC4 pattern forecast', () => {
  const spec = { krSpec: scal.design.krSpec, muW: scal.design.muW_cp, muO: scal.design.muO_cp };

  it('reproduces every recorded forecast case', () => {
    Object.entries(E.pattern_forecast).forEach(([name, exp]) => {
      const r = forecastPattern({ displacementSpec: spec, pattern: exp.inputs });
      expect(r.series).toHaveLength(exp.steps);
      near(r.summary.EAbt, exp.summary.EAbt);
      near(r.summary.Np_stb, exp.summary.Np_stb);
      near(r.summary.recoveryFactorOfFloodedOOIP, exp.summary.recoveryFactorOfFloodedOOIP);
      expect(r.summary.stopped).toBe(exp.summary.stopped);
      if (exp.summary.breakthrough_days === null) expect(r.summary.breakthrough_days).toBeNull();
      else near(r.summary.breakthrough_days, exp.summary.breakthrough_days);
      expect(name).toBeTruthy();
    });
  });

  it('the observed injection rate cannot flood the element in the 30-year horizon', () => {
    expect(E.pattern_forecast.observed.summary.breakthrough_days).toBeNull();
    expect(E.pattern_forecast.observed.summary.stopped).toBe('horizon');
    expect(E.pattern_forecast.design.summary.breakthrough_days).toBeGreaterThan(0);
  });

  it('free gas delays breakthrough by the fill-up volume', () => {
    expect(E.pattern_forecast.fillup.summary.breakthrough_days)
      .toBeGreaterThan(E.pattern_forecast.design.summary.breakthrough_days);
  });

  it('the observed Ekene-6 breakthrough implies a swept volume far below the element', () => {
    expect(E.channeling.implied_swept_fraction_of_element).toBeLessThan(0.05);
    near(
      E.channeling.implied_swept_pv_rb,
      (E.channeling.allocated_injection_bbl * wf.fvf.Bw) / (E.channeling.QiBt * E.channeling.EAbt),
    );
  });

  it('the field-unit pore volume differs from the exact metric one', () => {
    const pe = wf.pattern_element;
    near(pe.pv_field_units_rb, 7758 * pe.area_acres * pe.net_thickness_ft * pe.phi);
    expect(Math.abs(pe.pv_unit_rel_diff)).toBeGreaterThan(1e-5);
    expect(Math.abs(pe.pv_unit_rel_diff)).toBeLessThan(1e-3);
  });
});

describe('RC4 daily surveillance diagnostics', () => {
  const cfg = { bo: wf.fvf.Bo, bw: wf.fvf.Bw, bg: wf.fvf.Bg, rs: wf.fvf.Rs };

  it('the Hall plot recovers the planted injectivity index ONLY above the reference pressure', () => {
    const abs = analyzeWaterflood(wf.surveillance_rows, cfg);
    const ref = wf.design.injectivity_story.match(/(\d+) \+ inj_daily/);
    expect(ref).not.toBeNull();
    const refP = Number(ref[1]);
    const dp = analyzeWaterflood(
      wf.surveillance_rows.map((r) => ({ ...r, whp_psi: r.whp_psi == null ? null : r.whp_psi - refP })),
      cfg,
    );
    const e4abs = abs.hall_plots.find((h) => h.injector === 'Ekene-4');
    const e4dp = dp.hall_plots.find((h) => h.injector === 'Ekene-4');
    near(e4dp.slope_baseline, 1 / 0.5);
    near(e4dp.slope_last, 1 / 0.35);
    near(e4dp.slope_ratio, 0.5 / 0.35);
    near(e4abs.slope_ratio, E.surveillance.hall_absolute_pressure.find((h) => h.injector === 'Ekene-4').slope_ratio);
    expect(e4abs.slope_ratio).toBeLessThan(1.2);
    expect(abs.alerts.injectivity_issue).toHaveLength(0);
    expect(dp.alerts.injectivity_issue).toHaveLength(1);
  });

  it('the wrong config key case silently inflates VRR instead of erroring', () => {
    const right = analyzeWaterflood(wf.surveillance_rows, cfg);
    const wrong = analyzeWaterflood(wf.surveillance_rows, wf.fvf);
    near(right.kpis.vrr_avg, E.surveillance.cumulative_vrr_rows_as_days);
    near(wrong.kpis.vrr_avg / right.kpis.vrr_avg, E.surveillance.wrong_case_vrr_ratio);
    expect(E.surveillance.wrong_case_vrr_ratio).toBeGreaterThan(1.1);
  });

  it('reading monthly rows as daily rows shifts the cumulative VRR off the volume answer', () => {
    expect(E.surveillance.cumulative_vrr_rows_as_days).not.toBe(E.cumulative_vrr);
    const rel = Math.abs(E.surveillance.cumulative_vrr_rows_as_days - E.cumulative_vrr) / E.cumulative_vrr;
    expect(rel).toBeGreaterThan(1e-5);
    expect(rel).toBeLessThan(1e-3);
  });

  it('cross-correlation cannot separate two proportional injectors', () => {
    const a = analyzeWaterflood(wf.surveillance_rows, cfg);
    const byProducer = new Map();
    a.pattern_lags.forEach((p) => {
      if (!byProducer.has(p.producer)) byProducer.set(p.producer, []);
      byProducer.get(p.producer).push(p);
    });
    byProducer.forEach((pairs) => {
      if (pairs.length === 2) {
        expect(pairs[0].lag_days).toBe(pairs[1].lag_days);
        expect(Math.abs(pairs[0].corr - pairs[1].corr)).toBeLessThan(1e-9);
      }
    });
    expect(a.pattern_lags.map((p) => p.lag_days)).toEqual(E.surveillance.pattern_lags.map((p) => p.lag));
  });

  it('reproduces the recorded Chan classification', () => {
    const a = analyzeWaterflood(wf.surveillance_rows, cfg);
    near(a.chan.field.lateSlope, E.surveillance.chan.field.late_slope);
    expect(a.chan.field.classification.code).toBe(E.surveillance.chan.field.code);
    expect(a.chan.producers.map((p) => p.producer)).toEqual(E.surveillance.chan.producers.map((p) => p.producer));
    a.chan.producers.forEach((p, i) => {
      near(p.lateSlope, E.surveillance.chan.producers[i].late_slope);
      expect(p.classification.code).toBe(E.surveillance.chan.producers[i].code);
    });
  });
});
