// What the PVT of a Material Balance case really is, in words (H5).
//
// rb_run_configs.pvt_source can only hold 'correlated', 'lab_table' or
// 'mixed' (a check constraint), and the report printed that raw value. A
// table generated by "Prefill from correlations" is stored as a lab table,
// so the report said "lab_table" for numbers no laboratory measured.
//
// The origin of a generated table travels in the pvt_correlations jsonb,
// under one extra key the engine does not read. No schema change.
import { EMPTY_VALUE } from '@/lib/emptyValue';
import { describePvtOrigin, PVT_ORIGIN_KIND } from './pvtIntake';

export const PVT_TABLE_ORIGIN_KEY = 'lab_table_origin';

/** Names of the correlations the Material Balance engine can be set to. */
export const MBAL_CORRELATION_LABELS = {
  standing: 'Standing',
  vasquez_beggs: 'Vasquez-Beggs',
  glaso: 'Glaso',
  beggs_robinson: 'Beggs-Robinson',
  beal_standing: 'Beal-Standing',
  hall_yarborough: 'Hall-Yarborough',
  dranchuk_abou_kassem: 'Dranchuk-Abou-Kassem',
  mccain: 'McCain',
  lee_gonzalez_eakin: 'Lee-Gonzalez-Eakin',
};

const ROLES = [
  ['pb_rs_bo', 'Pb, Rs, Bo'],
  ['oil_viscosity', 'oil viscosity'],
  ['z_factor', 'Z'],
  ['gas_viscosity', 'gas viscosity'],
  ['water', 'water'],
];

const label = (key) => MBAL_CORRELATION_LABELS[key] ?? (key ? String(key).replace(/_/g, ' ') : null);

/** The origin block of a generated table, or null. */
export const tableOrigin = (cfg) => cfg?.pvt_correlations?.[PVT_TABLE_ORIGIN_KEY] ?? null;

/** pvt_correlations after a hand edit of a generated table. */
export function markTableEdited(correlations) {
  const origin = correlations?.[PVT_TABLE_ORIGIN_KEY];
  if (!origin || origin.edited) return correlations;
  return { ...correlations, [PVT_TABLE_ORIGIN_KEY]: { ...origin, edited: true } };
}

/** pvt_correlations with the origin removed (the table was cleared). */
export function clearTableOrigin(correlations) {
  if (!correlations || !(PVT_TABLE_ORIGIN_KEY in correlations)) return correlations;
  const { [PVT_TABLE_ORIGIN_KEY]: _gone, ...rest } = correlations;
  return rest;
}

const methodsText = (methods) => ROLES
  .filter(([role]) => methods?.[role]?.label)
  .map(([role, words]) => `${methods[role].label} (${words})`)
  .join('; ');

/**
 * One sentence for the report and the PVT tab.
 * @param {object|null} cfg an rb_run_configs row (the run's or the default)
 * @param {{isGas?: boolean}} [o] a gas case names no oil property
 */
export function describePvtSource(cfg, { isGas = false } = {}) {
  if (!cfg?.pvt_source) return EMPTY_VALUE;
  const corr = cfg.pvt_correlations ?? {};
  if (cfg.pvt_source === 'correlated') {
    const names = ROLES.filter(([role]) => corr[role]).map(([role, words]) => `${label(corr[role])} (${words})`);
    return names.length ? `Correlations: ${names.join('; ')}` : 'Correlations (engine defaults)';
  }
  const hasTable = Array.isArray(cfg.pvt_lab_table) && cfg.pvt_lab_table.length > 0;
  if (!hasTable) return 'Per-row PVT on the Data tab';
  const origin = tableOrigin(cfg);
  if (origin?.kind === PVT_ORIGIN_KIND) {
    // a table taken from a saved Fluid Systems Studio project through the pvt-1 contract
    return describePvtOrigin(origin, { isGas }).replace(/\.$/, '');
  }
  if (origin?.kind === 'correlation_prefill') {
    return [
      `Table built from correlations, with no lab data: ${methodsText(origin.methods)}`,
      origin.edited ? 'Rows were edited by hand after it was built.' : null,
    ].filter(Boolean).join('. ').replace(/\.\.$/, '.');
  }
  return 'Table entered on the PVT tab (origin not recorded)';
}

// ---- coverage of the PVT table ---------------------------------------------
// The engine interpolates inside the PVT table only. At a pressure outside
// it, a row with no PVT of its own gets the correlations of the run, with no
// word from the engine: the balance then mixes two PVT descriptions (and when
// the initial pressure is the one outside, Boi or Bgi comes from the
// correlations while every later state comes from the table). The app says
// so on the Run tab and in the Limits block of the report.

/**
 * @param {object|null} caseData the case with production_data
 * @param {object|null} cfg the run config of the run (or the default)
 * @returns {null|{min: number, max: number, outside: Array<{timestep_index: number, pressure_psia: number}>}}
 *   null when the run has no PVT table to cover anything
 */
export function pvtTableCoverage(caseData, cfg) {
  const table = (cfg?.pvt_lab_table ?? []).map((r) => Number(r?.pressure_psia)).filter((p) => Number.isFinite(p) && p > 0);
  if (cfg?.pvt_source === 'correlated' || table.length < 2) return null;
  const min = Math.min(...table);
  const max = Math.max(...table);
  const isGas = caseData?.fluid_system === 'gas';
  const ownPvt = (r) => (isGas ? (r.z_factor != null || r.bg_rb_mscf != null) : r.bo_rb_stb != null);
  const outside = (caseData?.production_data ?? [])
    .filter((r) => Number.isFinite(Number(r.pressure_psia)) && (Number(r.pressure_psia) > max + 1e-6 || Number(r.pressure_psia) < min - 1e-6) && !ownPvt(r))
    .map((r) => ({ timestep_index: r.timestep_index, pressure_psia: Number(r.pressure_psia) }));
  return { min, max, outside };
}

/** The sentence for a run whose table does not cover its pressures; null when it does. */
export function pvtCoverageWarning(caseData, cfg) {
  const c = pvtTableCoverage(caseData, cfg);
  if (!c || !c.outside.length) return null;
  const n = (v) => Math.round(v).toLocaleString('en-US');
  const steps = c.outside.map((o) => o.timestep_index);
  const list = steps.length > 8 ? `${steps.slice(0, 8).join(', ')} and ${steps.length - 8} more` : steps.join(', ');
  const initial = steps.includes(0) ? ' The initial state is one of them, so the initial volume factor and every later one come from different PVT descriptions.' : '';
  return `PVT table coverage: ${c.outside.length} timestep${c.outside.length === 1 ? '' : 's'} (${list}) lie${c.outside.length === 1 ? 's' : ''} outside the PVT table of the run (${n(c.min)} to ${n(c.max)} psia) and carry no PVT of their own. There the engine used the correlations of the run in place of the table.${initial} Extend the table to cover every pressure of the case, then run again.`;
}
