// What the PVT of a Material Balance case really is, in words (H5).
//
// rb_run_configs.pvt_source can only hold 'correlated', 'lab_table' or
// 'mixed' (a check constraint), and the report printed that raw value. A
// table generated by "Prefill from correlations" is stored as a lab table,
// so the report said "lab_table" for numbers no laboratory measured.
//
// The origin of a generated table travels in the pvt_correlations jsonb,
// under one extra key the engine does not read. No schema change.
import { EMPTY_VALUE } from '@/lib/emptyValue';

export const PVT_TABLE_ORIGIN_KEY = 'lab_table_origin';

/** Names of the correlations the Material Balance engine can be set to. */
export const MBAL_CORRELATION_LABELS = {
  standing: 'Standing',
  vasquez_beggs: 'Vasquez-Beggs',
  glaso: 'Glaso',
  beggs_robinson: 'Beggs-Robinson',
  beal_standing: 'Beal-Standing',
  hall_yarborough: 'Hall-Yarborough',
  dranchuk_abou_kassem: 'Dranchuk-Abou-Kassem',
  mccain: 'McCain',
  lee_gonzalez_eakin: 'Lee-Gonzalez-Eakin',
};

const ROLES = [
  ['pb_rs_bo', 'Pb, Rs, Bo'],
  ['oil_viscosity', 'oil viscosity'],
  ['z_factor', 'Z'],
  ['gas_viscosity', 'gas viscosity'],
  ['water', 'water'],
];

const label = (key) => MBAL_CORRELATION_LABELS[key] ?? (key ? String(key).replace(/_/g, ' ') : null);

/** The origin block of a generated table, or null. */
export const tableOrigin = (cfg) => cfg?.pvt_correlations?.[PVT_TABLE_ORIGIN_KEY] ?? null;

/** pvt_correlations after a hand edit of a generated table. */
export function markTableEdited(correlations) {
  const origin = correlations?.[PVT_TABLE_ORIGIN_KEY];
  if (!origin || origin.edited) return correlations;
  return { ...correlations, [PVT_TABLE_ORIGIN_KEY]: { ...origin, edited: true } };
}

/** pvt_correlations with the origin removed (the table was cleared). */
export function clearTableOrigin(correlations) {
  if (!correlations || !(PVT_TABLE_ORIGIN_KEY in correlations)) return correlations;
  const { [PVT_TABLE_ORIGIN_KEY]: _gone, ...rest } = correlations;
  return rest;
}

const methodsText = (methods) => ROLES
  .filter(([role]) => methods?.[role]?.label)
  .map(([role, words]) => `${methods[role].label} (${words})`)
  .join('; ');

/**
 * One sentence for the report and the PVT tab.
 * @param {object|null} cfg an rb_run_configs row (the run's or the default)
 */
export function describePvtSource(cfg) {
  if (!cfg?.pvt_source) return EMPTY_VALUE;
  const corr = cfg.pvt_correlations ?? {};
  if (cfg.pvt_source === 'correlated') {
    const names = ROLES.filter(([role]) => corr[role]).map(([role, words]) => `${label(corr[role])} (${words})`);
    return names.length ? `Correlations: ${names.join('; ')}` : 'Correlations (engine defaults)';
  }
  const hasTable = Array.isArray(cfg.pvt_lab_table) && cfg.pvt_lab_table.length > 0;
  if (!hasTable) return 'Per-row PVT on the Data tab';
  const origin = tableOrigin(cfg);
  if (origin?.kind === 'correlation_prefill') {
    return [
      `Table built from correlations, with no lab data: ${methodsText(origin.methods)}`,
      origin.edited ? 'Rows were edited by hand after it was built.' : null,
    ].filter(Boolean).join('. ').replace(/\.\.$/, '.');
  }
  return 'Table entered on the PVT tab (origin not recorded)';
}
