// Trace attributes (interpreter program Wave 2 / W2.2): the per-trace
// math behind derived attribute volumes. Complex-trace family via the
// analytic signal (Hilbert transform), windowed RMS and AGC amplitude.
// Validated against scipy goldens (test-data/seismolord/attributes/,
// generated by tools/validation/seismolord/attributes/gen_attributes.py
// in the Suite repo, which self-asserts its own math before writing
// anything). Every algorithm mirrors the oracle EXACTLY — same
// zero-fill, FFT padding, unwrap and gradient conventions.
//
// Conventions:
// - Input traces are brick-store amplitudes: Float32Array of ns samples,
//   nulls = NULL_VALUE (1.0e30). Null samples are zero-filled for the
//   transforms and the corresponding OUTPUT samples are NULL_VALUE —
//   nulls never enter statistics and never leave the trace as data.
// - Analytic signal recipe (the oracle pins it): zero-fill nulls,
//   zero-pad to nfft = nextpow2(ns), scipy.signal.hilbert weighting
//   (h[0] = h[nfft/2] = 1, h[1..nfft/2-1] = 2), inverse FFT, truncate
//   to ns. Identical to scipy.signal.hilbert(x, N=nfft)[:ns].
// - Instantaneous frequency follows numpy conventions exactly:
//   np.gradient(np.unwrap(np.angle(a))) / (2*pi*dt_s) — central
//   differences inside, one-sided at the edges, unwrap period 2*pi.
// - Float64 math throughout; the brick store casts to float32 on write.
// - Spectral decomposition follows horizonAmplitude.isofrequencyAt at every
//   sample (edge windows call it; interior windows use an equivalent
//   prefix-sum form, see spectralTrace); relative
//   acoustic impedance is the running sum high-passed by a centred boxcar
//   of the running sum. Both are pinned by test-data/seismolord/structure/
//   gen_structure.py.
//
// Pure math, worker-safe, no I/O.

import { fft, nextPow2 } from '../../lib/fft';
import { NULL_VALUE } from './manifest';
import { isofrequencyAt } from './horizonAmplitude';

/** Own-property preset lookup. `TABLE[key]` walks the prototype chain, so
 *  'constructor', 'toString', 'valueOf', 'hasOwnProperty' and '__proto__'
 *  are "found" in every object literal and walk through a falsy guard. */
const ownPreset = (table, key) => (typeof key === 'string' || typeof key === 'number') && Object.prototype.hasOwnProperty.call(table, key);


const NULL_LIM = 1.0e29;
// Math.* in hot loops is much slower inside jest's vm context; alias it once.
const M = Math;
const isNull = (v) => M.abs(v) > NULL_LIM;

/**
 * Analytic signal of one trace (nulls zero-filled, see recipe above).
 * @param {ArrayLike<number>} trace ns samples, nulls = NULL_VALUE
 * @returns {{re: Float64Array, im: Float64Array}} length ns
 */
export function analyticSignal(trace) {
  const ns = trace.length;
  const nfft = nextPow2(ns);
  const re = new Float64Array(nfft);
  const im = new Float64Array(nfft);
  for (let i = 0; i < ns; i++) {
    const v = trace[i];
    re[i] = isNull(v) ? 0 : v;
  }
  fft(re, im, false);
  // scipy.signal.hilbert weights: keep DC and Nyquist, double positive
  // frequencies, zero negative ones. nfft is a power of two, so even.
  const half = nfft / 2;
  for (let i = 1; i < half; i++) {
    re[i] *= 2;
    im[i] *= 2;
  }
  for (let i = half + 1; i < nfft; i++) {
    re[i] = 0;
    im[i] = 0;
  }
  fft(re, im, true);
  return { re: re.subarray(0, ns).slice(), im: im.subarray(0, ns).slice() };
}

/** np.unwrap with the default period 2*pi and discont pi, in place-safe. */
export function unwrapPhase(phase) {
  const out = Float64Array.from(phase);
  const twoPi = 2 * Math.PI;
  let correction = 0;
  for (let i = 1; i < out.length; i++) {
    const d = phase[i] - phase[i - 1];
    let dd = ((((d + Math.PI) % twoPi) + twoPi) % twoPi) - Math.PI;
    if (dd === -Math.PI && d > 0) dd = Math.PI;
    if (Math.abs(d) >= Math.PI) correction += dd - d;
    out[i] = phase[i] + correction;
  }
  return out;
}

/** np.gradient over a uniform unit grid: central inside, one-sided edges. */
export function gradient1d(y) {
  const n = y.length;
  const out = new Float64Array(n);
  if (n === 1) return out;
  out[0] = y[1] - y[0];
  out[n - 1] = y[n - 1] - y[n - 2];
  for (let i = 1; i < n - 1; i++) out[i] = (y[i + 1] - y[i - 1]) / 2;
  return out;
}

/** Write NULL_VALUE into out wherever the input sample was null. */
function maskNulls(trace, out) {
  for (let i = 0; i < trace.length; i++) {
    if (isNull(trace[i])) out[i] = NULL_VALUE;
  }
}

/**
 * Envelope (reflection strength): |analytic|.
 * @param {ArrayLike<number>} trace @param {Float32Array} out ns samples
 */
export function envelopeTrace(trace, out) {
  const { re, im } = analyticSignal(trace);
  for (let i = 0; i < trace.length; i++) out[i] = Math.hypot(re[i], im[i]);
  maskNulls(trace, out);
}

/** Instantaneous phase in degrees (-180..180]. */
export function instPhaseTrace(trace, out) {
  const { re, im } = analyticSignal(trace);
  for (let i = 0; i < trace.length; i++) {
    out[i] = (Math.atan2(im[i], re[i]) * 180) / Math.PI;
  }
  maskNulls(trace, out);
}

/**
 * Instantaneous frequency in Hz. Negative values (phase reversals /
 * low-energy zones) are kept as computed — clipping is a display choice.
 * @param {number} dtUs sample interval in microseconds
 */
export function instFrequencyTrace(trace, dtUs, out) {
  const { re, im } = analyticSignal(trace);
  const phase = new Float64Array(trace.length);
  for (let i = 0; i < trace.length; i++) phase[i] = Math.atan2(im[i], re[i]);
  const grad = gradient1d(unwrapPhase(phase));
  const scale = 1 / (2 * Math.PI * dtUs * 1e-6);
  for (let i = 0; i < trace.length; i++) out[i] = grad[i] * scale;
  maskNulls(trace, out);
}

/**
 * Sweetness = envelope / sqrt(instantaneous frequency); undefined
 * (NULL_VALUE) where the frequency is not positive.
 */
export function sweetnessTrace(trace, dtUs, out) {
  const ns = trace.length;
  const env = new Float32Array(ns);
  envelopeTrace(trace, env);
  const freq = new Float32Array(ns);
  instFrequencyTrace(trace, dtUs, freq);
  for (let i = 0; i < ns; i++) {
    if (isNull(env[i]) || isNull(freq[i]) || !(freq[i] > 0)) {
      out[i] = NULL_VALUE;
    } else {
      out[i] = env[i] / Math.sqrt(freq[i]);
    }
  }
}

/**
 * Windowed RMS amplitude: per sample, the RMS over
 * [s - halfWindow, s + halfWindow] clamped to the trace (edge windows
 * shrink), nulls excluded; all-null windows are NULL_VALUE. The same
 * windowing semantics as displayEnhance.agcGainMap, O(ns) prefix sums.
 * @param {number} halfWindow samples, >= 1
 */
export function windowedRmsTrace(trace, halfWindow, out) {
  if (!Number.isFinite(halfWindow) || halfWindow < 1) {
    throw new Error(`RMS half-window must be a positive sample count, got ${halfWindow}`);
  }
  const hw = Math.floor(halfWindow);
  const ns = trace.length;
  const sum2 = new Float64Array(ns + 1);
  const cnt = new Int32Array(ns + 1);
  for (let s = 0; s < ns; s++) {
    const v = trace[s];
    const ok = !isNull(v);
    sum2[s + 1] = sum2[s] + (ok ? v * v : 0);
    cnt[s + 1] = cnt[s] + (ok ? 1 : 0);
  }
  for (let s = 0; s < ns; s++) {
    const lo = Math.max(0, s - hw);
    const hi = Math.min(ns - 1, s + hw);
    const n = cnt[hi + 1] - cnt[lo];
    out[s] = n === 0 ? NULL_VALUE : Math.sqrt((sum2[hi + 1] - sum2[lo]) / n);
  }
  maskNulls(trace, out);
}

/**
 * AGC amplitude volume: each sample scaled by traceRms / windowRms so
 * the trace keeps its overall energy while local amplitude variation is
 * equalized — the stored-volume counterpart of the display-only AGC
 * gain map. Zero-energy windows contain only zero samples, which map
 * to 0; null samples stay NULL_VALUE.
 * @param {number} halfWindow samples, >= 1
 */
export function traceAgcTrace(trace, halfWindow, out) {
  const ns = trace.length;
  const wrms = new Float32Array(ns);
  windowedRmsTrace(trace, halfWindow, wrms);
  let sum = 0;
  let n = 0;
  for (let s = 0; s < ns; s++) {
    const v = trace[s];
    if (isNull(v)) continue;
    sum += v * v;
    n += 1;
  }
  const ref = n > 0 ? Math.sqrt(sum / n) : 0;
  for (let s = 0; s < ns; s++) {
    const v = trace[s];
    if (isNull(v)) {
      out[s] = NULL_VALUE;
    } else if (isNull(wrms[s]) || wrms[s] === 0) {
      out[s] = 0;
    } else {
      out[s] = (v * ref) / wrms[s];
    }
  }
}

/**
 * Spectral decomposition: at every sample z, the windowed amplitude
 * spectrum magnitude at freqHz with the horizon isofrequency recipe
 * (horizonAmplitude.isofrequencyAt: samples z +- hw clamped to the trace,
 * nulls zero-filled, Hann taper over the n actual samples, zero-pad to
 * nfft = nextpow2(4n), |X| at bin k = round(freqHz * nfft * dt_s)).
 * Null where the input sample is null.
 *
 * Fast path (same value in exact arithmetic): every interior window has the
 * same n = 2hw + 1, nfft and k, and the Hann taper is three complex
 * exponentials, 0.5 - 0.25 e^{i a m} - 0.25 e^{-i a m} with a = 2 pi/(n-1),
 * so X = sum_m w[m] x[s0+m] e^{-i w m} (w = 2 pi k/nfft) is
 *   0.5 A(w) - 0.25 A(w - a) - 0.25 A(w + a),
 *   A(b) = e^{i b s0} (P_b[s0 + n] - P_b[s0]),  P_b[s] = sum_{u<s} x[u] e^{-i b u},
 * three prefix sums per trace: O(1) per sample in place of an nfft-point
 * FFT (nfft = 512 for a 400 ms window at 4 ms). The shrinking edge windows
 * (at most 2hw samples per trace) still call isofrequencyAt. Gated equal
 * to isofrequencyAt within 1e-9 of the trace's peak spectral amplitude.
 *
 * @param {number} freqHz @param {number} hw half-window, samples (>= 2)
 * @param {number} dtUs sample interval in microseconds
 */
export function spectralTrace(trace, freqHz, hw, dtUs, out) {
  const ns = trace.length;
  const dtS = dtUs * 1e-6;
  const NULL_F32 = M.fround(NULL_VALUE);
  // isofrequencyAt recognises nulls as the float32 null; normalise any
  // |v| > 1e29 to it so float64 inputs behave the same
  const at = (s) => (isNull(trace[s]) ? NULL_F32 : trace[s]);
  const n = 2 * hw + 1;
  const interior = n >= 4 && ns >= n;
  let P = null;
  let w = 0;
  let a = 0;
  if (interior) {
    const nfft = nextPow2(4 * n);
    const k = M.min(nfft / 2, M.max(0, M.round(freqHz * nfft * dtS)));
    w = (2 * M.PI * k) / nfft;
    a = (2 * M.PI) / (n - 1);
    // P[f] for f = 0: w, 1: w - a, 2: w + a; interleaved re, im
    P = new Float64Array(6 * (ns + 1));
    const bs = [w, w - a, w + a];
    for (let u = 0; u < ns; u++) {
      const x = isNull(trace[u]) ? 0 : trace[u];
      const o = 6 * u;
      for (let f = 0; f < 3; f++) {
        const ph = bs[f] * u;
        P[o + 6 + 2 * f] = P[o + 2 * f] + x * M.cos(ph);
        P[o + 7 + 2 * f] = P[o + 2 * f + 1] - x * M.sin(ph);
      }
    }
  }
  const bs = [w, w - a, w + a];
  const cf = [0.5, -0.25, -0.25];
  for (let z = 0; z < ns; z++) {
    if (isNull(trace[z])) { out[z] = NULL_VALUE; continue; }
    if (!interior || z - hw < 0 || z + hw > ns - 1) {
      const v = isofrequencyAt(at, ns, z, { freqHz, hw, dtS });
      out[z] = v === NULL_F32 ? NULL_VALUE : v;
      continue;
    }
    // the centre sample is live, so the window is never all-null
    const s0 = z - hw;
    let re = 0;
    let im = 0;
    for (let f = 0; f < 3; f++) {
      const dr = P[6 * (s0 + n) + 2 * f] - P[6 * s0 + 2 * f];
      const di = P[6 * (s0 + n) + 2 * f + 1] - P[6 * s0 + 2 * f + 1];
      const ph = bs[f] * s0;
      const c = M.cos(ph);
      const sn = M.sin(ph);
      re += cf[f] * (dr * c - di * sn);
      im += cf[f] * (dr * sn + di * c);
    }
    out[z] = M.hypot(re, im);
  }
}

/**
 * Relative acoustic impedance: the running sum of the trace (nulls as 0),
 * high-passed by subtracting the centred boxcar mean of the running sum
 * over [s - hw, s + hw] clamped to the trace (edge windows shrink). Null
 * where the input sample is null.
 * @param {number} hw half-window, samples (>= 1)
 */
export function raiTrace(trace, hw, out) {
  const ns = trace.length;
  const c = new Float64Array(ns);
  let acc = 0;
  for (let s = 0; s < ns; s++) {
    const v = trace[s];
    if (!isNull(v)) acc += v;
    c[s] = acc;
  }
  const pre = new Float64Array(ns + 1);
  for (let s = 0; s < ns; s++) pre[s + 1] = pre[s] + c[s];
  for (let s = 0; s < ns; s++) {
    const lo = M.max(0, s - hw);
    const hi = M.min(ns - 1, s + hw);
    out[s] = c[s] - (pre[hi + 1] - pre[lo]) / (hi - lo + 1);
  }
  maskNulls(trace, out);
}

/**
 * Attribute registry — one entry per derived-volume attribute. `params`
 * documents the tunables (ms so the UI is sample-rate independent);
 * makeTraceCompute converts to samples against the volume's dt.
 */
export const ATTRIBUTE_DEFS = {
  envelope: {
    key: 'envelope', label: 'Envelope (reflection strength)', unit: 'amp', params: {},
  },
  inst_phase: {
    key: 'inst_phase', label: 'Instantaneous phase', unit: 'deg', params: {},
  },
  inst_freq: {
    key: 'inst_freq', label: 'Instantaneous frequency', unit: 'Hz', params: {},
  },
  sweetness: {
    key: 'sweetness', label: 'Sweetness', unit: 'amp/√Hz', params: {},
  },
  rms: {
    key: 'rms',
    label: 'RMS amplitude',
    unit: 'amp',
    params: { windowMs: { label: 'Window length (ms)', default: 80, min: 4, max: 1000 } },
  },
  agc: {
    key: 'agc',
    label: 'AGC amplitude',
    unit: 'amp',
    params: { windowMs: { label: 'Window length (ms)', default: 500, min: 20, max: 2000 } },
  },
  spectral: {
    key: 'spectral',
    label: 'Spectral decomposition',
    unit: 'amp',
    params: {
      freqHz: { label: 'Frequency (Hz)', default: 30, min: 2, max: 250 },
      windowMs: { label: 'Window length (ms)', default: 40, min: 8, max: 400 },
    },
  },
  rai: {
    key: 'rai',
    label: 'Relative acoustic impedance',
    unit: 'rel',
    params: { lowCutMs: { label: 'Trend window (ms)', default: 200, min: 20, max: 2000 } },
  },
};

/** Window length in ms -> half-window in samples (>= 1). */
export function halfWindowSamples(windowMs, dtUs) {
  const dtMs = dtUs / 1000;
  if (!(windowMs > 0) || !(dtMs > 0)) {
    throw new Error(`Window ${windowMs} ms is not usable at dt ${dtMs} ms.`);
  }
  return Math.max(1, Math.round(windowMs / 2 / dtMs));
}

/**
 * Build the per-trace compute for a registry attribute.
 * @param {string} name ATTRIBUTE_DEFS key
 * @param {Object} params user params (windowMs where applicable)
 * @param {{dtUs: number}} volume sampling
 * @returns {(trace: Float32Array, out: Float32Array) => void}
 */
export function makeTraceCompute(name, params, { dtUs }) {
  const def = ownPreset(ATTRIBUTE_DEFS, name) ? ATTRIBUTE_DEFS[name] : undefined;
  if (!def) throw new Error(`Unknown attribute "${name}".`);
  if (!(dtUs > 0)) throw new Error(`Attribute compute needs a positive dt, got ${dtUs}.`);
  switch (name) {
    case 'envelope':
      return (trace, out) => envelopeTrace(trace, out);
    case 'inst_phase':
      return (trace, out) => instPhaseTrace(trace, out);
    case 'inst_freq':
      return (trace, out) => instFrequencyTrace(trace, dtUs, out);
    case 'sweetness':
      return (trace, out) => sweetnessTrace(trace, dtUs, out);
    case 'rms': {
      const hw = halfWindowSamples(params?.windowMs ?? def.params.windowMs.default, dtUs);
      return (trace, out) => windowedRmsTrace(trace, hw, out);
    }
    case 'agc': {
      const hw = halfWindowSamples(params?.windowMs ?? def.params.windowMs.default, dtUs);
      return (trace, out) => traceAgcTrace(trace, hw, out);
    }
    case 'spectral': {
      const freqHz = params?.freqHz ?? def.params.freqHz.default;
      const nyquist = 1 / (2 * dtUs * 1e-6);
      if (!(freqHz > 0) || !(freqHz <= nyquist)) {
        throw new Error(`Frequency ${freqHz} Hz is outside the usable range up to ${nyquist} Hz for this sample interval.`);
      }
      const hw = M.max(2, halfWindowSamples(params?.windowMs ?? def.params.windowMs.default, dtUs));
      return (trace, out) => spectralTrace(trace, freqHz, hw, dtUs, out);
    }
    case 'rai': {
      const hw = halfWindowSamples(params?.lowCutMs ?? def.params.lowCutMs.default, dtUs);
      return (trace, out) => raiTrace(trace, hw, out);
    }
    default:
      throw new Error(`Unknown attribute "${name}".`);
  }
}
