// Discontinuity attribute (interpreter program Wave 2 / W2.3): windowed
// semblance-based variance over a lateral trace neighborhood — the
// fault-detection workhorse. High variance = low local waveform
// coherence = a lateral break (fault, channel edge, noise).
//
// Recipe (pinned by the Python oracle goldens in
// test-data/seismolord/discontinuity/, generated by the Suite's
// self-asserting tools/validation/seismolord/attributes/
// gen_discontinuity.py):
// - neighborhood: the (2r+1)^2 traces centred on (il, xl), clipped to
//   the survey; dead traces (all-null) are simply absent;
// - per output sample t, over vertical lags w in [-hw, +hw] with
//   t+w inside the trace: every LIVE (trace, sample) pair contributes;
//   with n_w live values x_i at lag w,
//     num += (sum_i x_i)^2 / n_w
//     den += sum_i x_i^2
// - semblance = num / den (den == 0, an all-zero window, counts as
//   perfectly coherent); variance = 1 - semblance, clamped to [0, 1];
// - output is NULL where the CENTER sample is null, or when fewer than
//   2 live traces cover the neighborhood (variance of one trace is
//   meaningless).
//
// Pure math, worker-safe, no I/O.

import { NULL_VALUE } from './manifest';

/** Own-property preset lookup. `TABLE[key]` walks the prototype chain, so
 *  'constructor', 'toString', 'valueOf', 'hasOwnProperty' and '__proto__'
 *  are "found" in every object literal and walk through a falsy guard. */
const ownPreset = (table, key) => (typeof key === 'string' || typeof key === 'number') && Object.prototype.hasOwnProperty.call(table, key);


// Module-level alias: hot loops call M.* (a bare global Math lookup is
// markedly slower inside sandboxed runners such as jest's vm context; the
// aligner below ran 18x slower in detectFaults when it moved here without it).
const M = Math;
const NULL_LIM = 1.0e29;
const isNull = (v) => M.abs(v) > NULL_LIM;

/**
 * Windowed semblance variance for one output trace.
 *
 * @param {Float32Array} center the (il, xl) trace, ns samples
 * @param {Float32Array[]} neighborhood ALL live traces of the
 *   neighborhood INCLUDING the center (order irrelevant)
 * @param {number} halfWindow vertical half-window in samples, >= 0
 * @param {Float32Array} out ns samples
 */
export function varianceTrace(center, neighborhood, halfWindow, out) {
  const ns = center.length;
  if (neighborhood.length < 2) {
    out.fill(NULL_VALUE);
    return;
  }
  const hw = M.max(0, M.floor(halfWindow));
  const nTr = neighborhood.length;

  // Per-lag prefix sums over the neighborhood: sum, sum of squares and
  // live count per sample row, so each output sample is O(hw) not
  // O(hw * traces).
  const rowSum = new Float64Array(ns);
  const rowSum2 = new Float64Array(ns);
  const rowN = new Int32Array(ns);
  for (let i = 0; i < nTr; i++) {
    const tr = neighborhood[i];
    for (let s = 0; s < ns; s++) {
      const v = tr[s];
      if (isNull(v)) continue;
      rowSum[s] += v;
      rowSum2[s] += v * v;
      rowN[s] += 1;
    }
  }

  for (let t = 0; t < ns; t++) {
    if (isNull(center[t])) {
      out[t] = NULL_VALUE;
      continue;
    }
    let num = 0;
    let den = 0;
    const w0 = M.max(0, t - hw);
    const w1 = M.min(ns - 1, t + hw);
    for (let w = w0; w <= w1; w++) {
      const n = rowN[w];
      if (n === 0) continue;
      num += (rowSum[w] * rowSum[w]) / n;
      den += rowSum2[w];
    }
    if (den === 0) {
      out[t] = 0;                       // silent window: perfectly coherent
      continue;
    }
    const variance = 1 - num / den;
    out[t] = variance < 0 ? 0 : variance > 1 ? 1 : variance;
  }
}

/**
 * Dip steering for semblance: returns a copy of `other` in which every
 * sample t is taken from t + lag(t), lag(t) in [-maxLag, maxLag] being the
 * shift that maximises the normalised cross-correlation with `center`
 * over the window [t - hw, t + hw] (ties keep the smaller |lag|). Local
 * dip and small time steps (velocity shadows under a fault, tuning) are
 * aligned away; a fault throw larger than maxLag still leaves a misfit.
 * Nulls are treated as zero amplitude while correlating.
 */
export function makeAligner(ns, hw, maxLag) {
  const nl = 2 * maxLag + 1;
  const pre = new Float64Array(nl * (ns + 1));
  const preC = new Float64Array(ns + 1);
  const preO = new Float64Array(ns + 1);
  const val = (tr, t) => (t < 0 || t >= ns || isNull(tr[t]) ? 0 : tr[t]);
  return (center, other) => {
    for (let t = 0; t < ns; t++) {
      const c = val(center, t);
      const o = val(other, t);
      preC[t + 1] = preC[t] + c * c;
      preO[t + 1] = preO[t] + o * o;
      for (let q = 0; q < nl; q++) {
        pre[q * (ns + 1) + t + 1] = pre[q * (ns + 1) + t] + c * val(other, t + q - maxLag);
      }
    }
    const out = new Float32Array(ns);
    for (let t = 0; t < ns; t++) {
      const w0 = M.max(0, t - hw);
      const w1 = M.min(ns, t + hw + 1);
      const ec = preC[w1] - preC[w0];
      let best = 0;
      let bestCc = -Infinity;
      for (let q = 0; q < nl; q++) {
        const lag = q - maxLag;
        const a0 = M.min(ns, M.max(0, w0 + lag));
        const a1 = M.min(ns, M.max(0, w1 + lag));
        const eo = preO[a1] - preO[a0];
        const cc = (pre[q * (ns + 1) + w1] - pre[q * (ns + 1) + w0]) / M.sqrt(ec * eo + 1e-30);
        if (cc > bestCc + 1e-9 || (M.abs(cc - bestCc) <= 1e-9 && M.abs(lag) < M.abs(best))) {
          bestCc = cc;
          best = lag;
        }
      }
      out[t] = isNull(center[t]) ? center[t] : val(other, t + best);
    }
    return out;
  };
}

/** Discontinuity registry (neighborhood attributes — these run through
 *  runNeighborhoodJob, not the per-trace pipeline). */
export const DISCONTINUITY_DEFS = {
  variance: {
    key: 'variance',
    label: 'Variance (discontinuity)',
    unit: 'frac',
    neighborhood: true,
    params: {
      windowMs: { label: 'Vertical window (ms)', default: 40, min: 4, max: 400 },
      radius: { label: 'Trace radius', default: 1, min: 1, max: 2 },
      dipSteerMs: { label: 'Dip steering (ms, 0 = off)', default: 0, min: 0, max: 40 },
    },
  },
  /** Regional attribute: computed a brick column at a time by
   *  discontinuityJobs.makeDiscontinuityJob (faultDetect's stage 1). */
  fault_likelihood: {
    key: 'fault_likelihood',
    label: 'Fault likelihood',
    unit: 'frac',
    neighborhood: true,
    regional: true,
    params: {
      windowMs: { label: 'Semblance window (ms)', default: 24, min: 8, max: 120 },
    },
  },
};

/**
 * Build the neighborhood compute for a discontinuity attribute.
 * @param {string} name DISCONTINUITY_DEFS key
 * @param {Object} params {windowMs, radius}
 * @param {{dtUs: number}} volume sampling
 * @returns {{radius: number,
 *   compute: (getTrace: (il:number, xl:number) => ?Float32Array,
 *             il: number, xl: number, out: Float32Array) => void}}
 *   getTrace returns null outside the survey; all-null traces count as
 *   dead and are excluded by the compute
 */
export function makeNeighborhoodCompute(name, params, { dtUs }) {
  const def = ownPreset(DISCONTINUITY_DEFS, name) ? DISCONTINUITY_DEFS[name] : undefined;
  if (!def) throw new Error(`Unknown discontinuity attribute "${name}".`);
  if (def.regional) throw new Error(`"${name}" is a regional attribute: build it with makeDiscontinuityJob.`);
  if (!(dtUs > 0)) throw new Error(`Discontinuity compute needs a positive dt, got ${dtUs}.`);
  const dtMs = dtUs / 1000;
  const windowMs = params?.windowMs ?? def.params.windowMs.default;
  if (!(windowMs > 0)) throw new Error(`Vertical window ${windowMs} ms is not usable.`);
  const hw = M.max(1, M.round(windowMs / 2 / dtMs));
  const radius = M.max(1, M.min(4, M.floor(params?.radius ?? def.params.radius.default)));
  // dip steering: each neighbour is aligned to the centre by up to maxLag
  // samples before semblance (faultDetect's aligner), so dipping
  // reflectors stop reading as discontinuity
  const dipSteerMs = M.max(0, params?.dipSteerMs ?? def.params.dipSteerMs.default);
  const maxLag = M.round(dipSteerMs / dtMs);
  let aligner = null;
  let alignerNs = -1;

  const isLive = (tr) => {
    for (let s = 0; s < tr.length; s++) {
      if (!isNull(tr[s])) return true;
    }
    return false;
  };

  return {
    radius,
    compute: (getTrace, il, xl, out) => {
      const center = getTrace(il, xl);
      if (!center) {
        out.fill(NULL_VALUE);
        return;
      }
      const hood = [];
      for (let di = -radius; di <= radius; di++) {
        for (let dj = -radius; dj <= radius; dj++) {
          const tr = getTrace(il + di, xl + dj);
          if (!tr || !isLive(tr)) continue;
          if (maxLag > 0 && (di !== 0 || dj !== 0)) {
            if (alignerNs !== center.length) {
              aligner = makeAligner(center.length, hw, maxLag);
              alignerNs = center.length;
            }
            hood.push(aligner(center, tr));
          } else hood.push(tr);
        }
      }
      varianceTrace(center, hood, hw, out);
    },
  };
}
