// LAS-driven synthetics engine (Geoscience G5 deferred item): synthetic
// seismograms from sonic/density logs, statistical wavelet extraction and
// cross-correlation bulk shift — the numerics behind the seismic-to-well
// tie display. Validated against the Python oracle goldens
// (test-data/seismolord/synthetics/, generated by
// tools/validation/seismolord/synthetics/gen_synthetics.py which
// self-asserts its own math before writing anything). Every algorithm
// here mirrors the oracle EXACTLY — same sample placement, gap policy,
// taper, FFT length and smoothing.
//
// Conventions:
// - Z/time increases downward; TWT in ms; sonic slowness in US/M
//   (velocity m/s = 1e6 / dt); density g/cc; impedance v*rho (m/s·g/cc).
// - SEG normal polarity: an impedance INCREASE is a positive amplitude.
// - Gaps: a sample is a gap when it is not finite (the LAS parser maps
//   NULL -> NaN), |v| >= 9.0e29 (the seismic null 1.0E+30), or a raw LAS
//   null (-999.25, -999, -9999, -9999.25). Engine outputs carry gaps as
//   NaN; amplitude arrays are Float32Array end-to-end (TWT coordinate
//   series are float64, like grid geometry).
// - Convolution 'same': gaps zero-filled, and the returned validity mask
//   is the INPUT sample's validity — a convolved value whose own RC
//   sample was a gap is display-only smear and pen-breaks in the UI.
// - T(z) is CALLER-PROVIDED (mdToTvdss / tvdssToTwt functions): the
//   engine never mixes time-depth sources — provenance stays with
//   makeTvdssToTwt (engine/wellSection.js) and is surfaced in the UI.
//
// Pure math, worker-safe, no I/O.

// isGap / rickerWavelet / convolveSame moved verbatim to
// src/lib/waveform.js at the second consumer (Rock Physics Studio
// wedge modeling, G6.3); re-exported here so the synthetics API and
// its goldens are unchanged. Relative path: this module also runs
// inside synthetics.worker.js.
import { isGap, rickerWavelet, convolveSame } from '../../lib/waveform';

export { isGap, rickerWavelet, convolveSame };

/**
 * Sonic slowness (US/M) -> velocity (m/s): v = 1e6 / dt.
 * Gaps and non-positive slownesses become NaN.
 * @param {ArrayLike<number>} dtUsPerM
 * @returns {Float32Array}
 */
export function slownessToVelocity(dtUsPerM) {
  const out = new Float32Array(dtUsPerM.length);
  for (let i = 0; i < dtUsPerM.length; i++) {
    const v = dtUsPerM[i];
    out[i] = isGap(v) || v <= 0 ? NaN : 1e6 / v;
  }
  return out;
}

/**
 * Acoustic impedance Z = v * rho, gap-propagating. Density may be a
 * curve or a constant (the constant-density fallback — RC then reduces
 * to the velocity contrast; the UI notes the provenance).
 *
 * @param {ArrayLike<number>} velocity m/s
 * @param {ArrayLike<number>|number} density g/cc curve or constant
 * @param {{despike?: boolean}} [opts] despike: 3-point median filter on
 *   samples whose both neighbours are valid (edges kept as-is)
 * @returns {Float32Array}
 */
export function computeImpedance(velocity, density, { despike = false } = {}) {
  const constRho = typeof density === 'number' ? density : null;
  if (constRho === null && density.length !== velocity.length) {
    throw new Error(`Velocity and density curves differ in length `
      + `(${velocity.length} vs ${density.length}) — resample them onto one MD grid first.`);
  }
  const out = new Float32Array(velocity.length);
  for (let i = 0; i < velocity.length; i++) {
    const v = velocity[i];
    const r = constRho ?? density[i];
    out[i] = isGap(v) || isGap(r) || v <= 0 || r <= 0 ? NaN : v * r;
  }
  if (!despike) return out;
  const sp = new Float32Array(out);
  for (let i = 1; i < out.length - 1; i++) {
    const a = out[i - 1];
    const b = out[i];
    const c = out[i + 1];
    if (isGap(a) || isGap(b) || isGap(c)) continue;
    sp[i] = Math.max(Math.min(a, b), Math.min(Math.max(a, b), c)); // median3
  }
  return sp;
}

/**
 * TWT (ms) of every MD sample through caller-provided converters — the
 * engine stays pure and never chooses a T(z) source itself.
 *
 * @param {ArrayLike<number>} mdArray sample MDs (metres)
 * @param {(mdM: number) => ?number} mdToTvdss null outside the survey
 * @param {(tvdssM: number) => ?number} tvdssToTwt e.g. makeTvdssToTwt().toTwtMs
 * @returns {Float64Array} TWT ms per sample, NaN where either converter
 *   returned null/NaN
 */
export function mdSeriesToTwt(mdArray, mdToTvdss, tvdssToTwt) {
  const out = new Float64Array(mdArray.length);
  for (let i = 0; i < mdArray.length; i++) {
    const md = mdArray[i];
    const z = isGap(md) ? null : mdToTvdss(md);
    const t = z == null || !Number.isFinite(z) ? null : tvdssToTwt(z);
    out[i] = t == null || !Number.isFinite(t) ? NaN : t;
  }
  return out;
}

/**
 * Resample an irregular TWT series onto the uniform seismic grid
 * (t_i = i * dtMs) by linear interpolation, gap-preserving: samples
 * whose TWT is a gap are dropped first; an output sample is NaN outside
 * the covered range or when either bracketing input VALUE is a gap.
 *
 * @param {ArrayLike<number>} twtMs per input sample (may contain gaps)
 * @param {ArrayLike<number>} values aligned values (may contain gaps)
 * @param {number} dtMs @param {number} ns output length
 * @returns {Float32Array}
 */
export function resampleToDt(twtMs, values, dtMs, ns) {
  if (twtMs.length !== values.length) {
    throw new Error(`TWT and value series differ in length (${twtMs.length} vs ${values.length}).`);
  }
  const t = [];
  const v = [];
  for (let k = 0; k < twtMs.length; k++) {
    if (isGap(twtMs[k])) continue;
    t.push(twtMs[k]);
    v.push(values[k]);
  }
  const out = new Float32Array(ns).fill(NaN);
  if (t.length < 2) return out;
  for (let k = 1; k < t.length; k++) {
    if (!(t[k] > t[k - 1])) {
      throw new Error(`Sample ${k + 1}: the time-depth relationship is not strictly `
        + `increasing (${t[k - 1].toFixed(2)} ms then ${t[k].toFixed(2)} ms) — check the `
        + 'checkshots / velocity model.');
    }
  }
  let j = 0;
  for (let i = 0; i < ns; i++) {
    const ti = i * dtMs;
    if (ti < t[0] || ti > t[t.length - 1]) continue;
    while (j < t.length - 2 && t[j + 1] < ti) j++;
    if (isGap(v[j]) || isGap(v[j + 1])) continue;
    const f = (ti - t[j]) / (t[j + 1] - t[j]);
    out[i] = v[j] + f * (v[j + 1] - v[j]);
  }
  return out;
}

/**
 * Adjacent-sample reflection coefficients, gap-propagating:
 * rc[i] = (Z[i] - Z[i-1]) / (Z[i] + Z[i-1]); rc[0] is a gap (no
 * interface above the first sample). SEG normal polarity falls out:
 * impedance increase -> positive RC.
 *
 * @param {ArrayLike<number>} imp impedance on the uniform TWT grid
 * @returns {Float32Array}
 */
export function reflectivity(imp) {
  const out = new Float32Array(imp.length).fill(NaN);
  for (let i = 1; i < imp.length; i++) {
    const a = imp[i - 1];
    const b = imp[i];
    if (isGap(a) || isGap(b) || a + b === 0) continue;
    out[i] = (b - a) / (b + a);
  }
  return out;
}



// ---- FFT (private): iterative radix-2 Cooley-Tukey, float64 -------------

function fft(re, im, invert) {
  const n = re.length;
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {
      const tr = re[i]; re[i] = re[j]; re[j] = tr;
      const ti = im[i]; im[i] = im[j]; im[j] = ti;
    }
  }
  for (let len = 2; len <= n; len <<= 1) {
    const ang = ((invert ? 1 : -1) * 2 * Math.PI) / len;
    const wr = Math.cos(ang);
    const wi = Math.sin(ang);
    for (let i = 0; i < n; i += len) {
      let cr = 1;
      let ci = 0;
      for (let j = 0; j < len / 2; j++) {
        const ur = re[i + j];
        const ui = im[i + j];
        const vr = re[i + j + len / 2] * cr - im[i + j + len / 2] * ci;
        const vi = re[i + j + len / 2] * ci + im[i + j + len / 2] * cr;
        re[i + j] = ur + vr;
        im[i + j] = ui + vi;
        re[i + j + len / 2] = ur - vr;
        im[i + j + len / 2] = ui - vi;
        const ncr = cr * wr - ci * wi;
        ci = cr * wi + ci * wr;
        cr = ncr;
      }
    }
  }
  if (invert) {
    for (let i = 0; i < n; i++) {
      re[i] /= n;
      im[i] /= n;
    }
  }
}

/**
 * Statistical (autocorrelation) wavelet extraction — the exact oracle
 * recipe, so the result matches the golden bit-closely:
 * 1. per trace: zero-fill gaps, demean over VALID samples;
 * 2. biased autocorrelation r[k] = (1/ns) sum x[i]x[i+k] to lag
 *    nlag = round(waveletLengthMs/2/dtMs), averaged across traces;
 * 3. Hann half-taper h[k] = 0.5(1 + cos(pi k/(nlag+1))) on the lags;
 * 4. wrap into nfft = nextpow2(8*(2nlag+1)); FFT; power = max(Re, 0);
 * 5. amplitude = sqrt(power), circularly boxcar-smoothed with half-width
 *    round(smoothHz/df) bins (df = 1000/(nfft*dtMs) Hz);
 * 6. zero-phase wavelet = Re(IFFT(amplitude)) unwrapped to lags
 *    -nlag..nlag, Hann-tapered again, peak-normalized to 1.
 *
 * @param {Array<ArrayLike<number>>} traces seismic traces at/near the well
 * @param {number} dtMs
 * @param {{waveletLengthMs?: number, smoothHz?: number}} [opts]
 * @returns {Float32Array} zero-phase wavelet, length 2*nlag + 1
 */
export function extractStatisticalWavelet(traces, dtMs, {
  waveletLengthMs = 120, smoothHz = 5,
} = {}) {
  if (!Array.isArray(traces) || traces.length === 0) {
    throw new Error('Wavelet extraction needs at least one seismic trace.');
  }
  if (!(dtMs > 0)) throw new Error('Wavelet extraction needs a positive sample rate.');
  const nlag = Math.round(waveletLengthMs / 2 / dtMs);
  if (traces.some((t) => !t || t.length < nlag + 1)) {
    throw new Error(`Traces are too short for a ${waveletLengthMs} ms wavelet `
      + `(need at least ${nlag + 1} samples).`);
  }
  const nw = 2 * nlag + 1;

  const r = new Float64Array(nlag + 1);
  for (const tr of traces) {
    const ns = tr.length;
    const x = new Float64Array(ns);
    let sum = 0;
    let count = 0;
    for (let i = 0; i < ns; i++) {
      if (!isGap(tr[i])) {
        sum += tr[i];
        count++;
      }
    }
    const mean = count ? sum / count : 0;
    for (let i = 0; i < ns; i++) x[i] = isGap(tr[i]) ? 0 : tr[i] - mean;
    for (let k = 0; k <= nlag; k++) {
      let acc = 0;
      for (let i = 0; i + k < ns; i++) acc += x[i] * x[i + k];
      r[k] += acc / ns;
    }
  }
  for (let k = 0; k <= nlag; k++) r[k] /= traces.length;

  const h = new Float64Array(nlag + 1);
  for (let k = 0; k <= nlag; k++) h[k] = 0.5 * (1 + Math.cos((Math.PI * k) / (nlag + 1)));

  let nfft = 1;
  while (nfft < 8 * nw) nfft *= 2;
  const re = new Float64Array(nfft);
  const im = new Float64Array(nfft);
  re[0] = r[0] * h[0];
  for (let k = 1; k <= nlag; k++) {
    re[k] = r[k] * h[k];
    re[nfft - k] = r[k] * h[k];
  }
  fft(re, im, false);
  let amp = new Float64Array(nfft);
  for (let i = 0; i < nfft; i++) amp[i] = Math.sqrt(Math.max(re[i], 0));

  const df = 1000 / (nfft * dtMs);
  const bs = Math.round(smoothHz / df);
  if (bs > 0) {
    const sm = new Float64Array(nfft);
    for (let i = 0; i < nfft; i++) {
      let acc = 0;
      for (let k = -bs; k <= bs; k++) acc += amp[(((i + k) % nfft) + nfft) % nfft];
      sm[i] = acc / (2 * bs + 1);
    }
    amp = sm;
  }

  const im2 = new Float64Array(nfft);
  fft(amp, im2, true);
  const wav = new Float64Array(nw);
  wav[nlag] = amp[0];
  for (let k = 1; k <= nlag; k++) {
    wav[nlag + k] = amp[k];
    wav[nlag - k] = amp[nfft - k];
  }
  let peak = 0;
  for (let k = 0; k < nw; k++) {
    wav[k] *= h[Math.abs(k - nlag)];
    peak = Math.max(peak, Math.abs(wav[k]));
  }
  const out = new Float32Array(nw);
  for (let k = 0; k < nw; k++) out[k] = peak > 0 ? wav[k] / peak : wav[k];
  return out;
}

/**
 * Normalized cross-correlation bulk shift between the synthetic and the
 * real trace. POSITIVE lag = the seismic event is LATER: shift the
 * synthetic DOWN by lagMs to match (display-only; nothing is written to
 * the velocity model — W3 wellTie.js owns calibration).
 *
 * Per lag, only mutually valid overlapping samples enter the sums and
 * the normalization, so nulls in either trace never bias a lag.
 *
 * @param {ArrayLike<number>} synthetic
 * @param {ArrayLike<number>} seismic same dt, may differ in length
 * @param {number} dtMs @param {number} maxLagMs
 * @param {{minOverlap?: number}} [opts]
 * @returns {?{lagMs: number, corr: number,
 *   series: {lagMs: number, corr: number}[]}} null when no lag has
 *   enough overlapping energy to correlate
 */
export function suggestBulkShift(synthetic, seismic, dtMs, maxLagMs, { minOverlap = 8 } = {}) {
  if (!(dtMs > 0) || !(maxLagMs > 0)) {
    throw new Error('Bulk shift needs a positive sample rate and search window.');
  }
  const L = Math.round(maxLagMs / dtMs);
  const n = synthetic.length;
  let best = null;
  const series = [];
  for (let lag = -L; lag <= L; lag++) {
    let num = 0;
    let ss = 0;
    let tt = 0;
    let count = 0;
    for (let i = 0; i < n; i++) {
      const j = i + lag;
      if (j < 0 || j >= seismic.length) continue;
      const a = synthetic[i];
      const b = seismic[j];
      if (isGap(a) || isGap(b)) continue;
      num += a * b;
      ss += a * a;
      tt += b * b;
      count++;
    }
    if (count < minOverlap || ss === 0 || tt === 0) continue;
    const corr = num / Math.sqrt(ss * tt);
    series.push({ lagMs: lag * dtMs, corr });
    if (!best || corr > best.corr) best = { lagMs: lag * dtMs, corr };
  }
  return best ? { ...best, series } : null;
}

/**
 * Full pipeline: sonic (+ optional density) on an MD grid -> synthetic
 * seismogram on the volume's TWT grid. T(z) is caller-provided (never
 * chosen here — provenance stays with makeTvdssToTwt).
 *
 * @param {Object} p
 * @param {ArrayLike<number>} p.dtCurve sonic slowness, US/M
 * @param {?ArrayLike<number>} [p.rhobCurve] density, g/cc (null -> constant)
 * @param {number} [p.constantRhoGcc] fallback density (default 2.3)
 * @param {?ArrayLike<number>} [p.mdArray] explicit sample MDs (irregular
 *   logs, step_m = null) — otherwise mdStartM/mdStepM build the grid
 * @param {number} [p.mdStartM] @param {number} [p.mdStepM]
 * @param {(mdM: number) => ?number} p.mdToTvdss
 * @param {(tvdssM: number) => ?number} p.tvdssToTwt
 * @param {number} p.dtMs seismic sample rate @param {number} p.ns samples
 * @param {ArrayLike<number>} p.wavelet odd-length, centre = zero lag
 * @param {boolean} [p.despike]
 * @returns {{mdArray: Float64Array, twtMs: Float64Array,
 *   velocity: Float32Array, impedance: Float32Array,
 *   impedanceTime: Float32Array, rc: Float32Array,
 *   synthetic: Float32Array, validity: Uint8Array}}
 */
export function buildSynthetic({
  dtCurve, rhobCurve = null, constantRhoGcc = 2.3,
  mdArray = null, mdStartM = null, mdStepM = null,
  mdToTvdss, tvdssToTwt, dtMs, ns, wavelet, despike = false,
}) {
  if (!dtCurve || !dtCurve.length) {
    throw new Error('A synthetic needs a sonic (DT) curve — this well has none selected.');
  }
  if (dtCurve.length < 2) {
    throw new Error('The sonic curve has a single sample — a synthetic needs at least 2.');
  }
  let md;
  if (mdArray) {
    if (mdArray.length !== dtCurve.length) {
      throw new Error(`The depth vector (${mdArray.length} samples) does not match the `
        + `sonic curve (${dtCurve.length} samples).`);
    }
    md = Float64Array.from(mdArray);
  } else {
    if (!Number.isFinite(mdStartM) || !(mdStepM > 0)) {
      throw new Error('The sonic log has no usable MD grid (start/step missing and no '
        + 'depth vector) — re-import the LAS file.');
    }
    md = new Float64Array(dtCurve.length);
    for (let i = 0; i < md.length; i++) md[i] = mdStartM + i * mdStepM;
  }
  for (let i = 1; i < md.length; i++) {
    if (!(md[i] > md[i - 1])) {
      throw new Error(`Depth sample ${i + 1}: MD ${md[i]} does not increase `
        + `(previous ${md[i - 1]}) — the depth vector must be strictly ascending.`);
    }
  }

  let validSonic = 0;
  for (let i = 0; i < dtCurve.length; i++) if (!isGap(dtCurve[i]) && dtCurve[i] > 0) validSonic++;
  if (validSonic < 2) {
    throw new Error('The sonic curve has fewer than 2 valid samples — everything is null.');
  }
  if (rhobCurve) {
    let validRho = 0;
    for (let i = 0; i < rhobCurve.length; i++) if (!isGap(rhobCurve[i]) && rhobCurve[i] > 0) validRho++;
    if (validRho === 0) {
      throw new Error('The density curve has no valid samples — deselect it to use the '
        + 'constant-density fallback.');
    }
  }

  const velocity = slownessToVelocity(dtCurve);
  const impedance = computeImpedance(velocity, rhobCurve || constantRhoGcc, { despike });
  const twtMs = mdSeriesToTwt(md, mdToTvdss, tvdssToTwt);
  let hasTime = 0;
  for (let i = 0; i < twtMs.length; i++) if (!isGap(twtMs[i])) hasTime++;
  if (hasTime < 2) {
    throw new Error('No time-depth relationship covers this log interval — add checkshots '
      + 'or a velocity model for the volume.');
  }
  const impedanceTime = resampleToDt(twtMs, impedance, dtMs, ns);
  const rc = reflectivity(impedanceTime);
  const { data: synthetic, valid: validity } = convolveSame(rc, wavelet);
  return {
    mdArray: md, twtMs, velocity, impedance, impedanceTime, rc, synthetic, validity,
  };
}
