// The sample well of Decline Curve Analysis (DCA-U1, PL11): Ekene-1's
// primary decline from the engines' test data
// (packages/engines/test-data/ekene-dynamic/rates.json, generated by
// tools/ekene-dynamic): a planted exponential of 120 bopd and 0.0012 per day
// (43.83 %/yr nominal), monthly from 2020-01 to 2022-12, gas at 400 scf/STB.
// Its closed form reaches the 10 bopd limit at 91,666.7 STB from first
// production. It is labelled sample wherever it shows.
import { v4 as uuidv4 } from 'uuid';
import { DCA_PAYLOAD_VERSION } from './dcaModel';

export const SAMPLE_WELL_NAME = 'Ekene-1 (sample)';
export const SAMPLE_TRUTH = Object.freeze({
  qi: 120, diPerDay: 0.0012, b: 0, startDate: '2020-01-01', months: 36, econLimit: 10, eurClosedForm: 91666.66666666667,
  source: 'packages/engines/test-data/ekene-dynamic/rates.json (Ekene-1, primary window)',
});

const DAY = 86400000;

/** The 36 monthly rows, as the engines' generator writes them. */
export function sampleRows() {
  const t0 = Date.UTC(2020, 0, 1);
  return Array.from({ length: SAMPLE_TRUTH.months }, (_, i) => {
    const t = Date.UTC(2020, i, 1);
    const oil = SAMPLE_TRUTH.qi * Math.exp(-SAMPLE_TRUTH.diPerDay * ((t - t0) / DAY));
    return { date: new Date(t).toISOString().slice(0, 10), oilRate: oil, gasRate: oil * 0.4, waterRate: 0, rate: oil };
  });
}

/** A new well object holding the sample data, ready to add to a project. */
export function sampleWell(projectId = null) {
  const data = sampleRows();
  return {
    id: uuidv4(),
    name: SAMPLE_WELL_NAME,
    type: 'oil',
    sample: true,
    projectId,
    notes: 'Sample data: Ekene-1 primary decline from the Petrolord engines test data. Not field data.',
    tags: ['sample'],
    identification: { company: '', field: 'Ekene (sample)', licence: 'Sample', reservoir: 'Ekene sand (sample)', analyst: '' },
    data,
    dataMeta: {
      fileName: 'Ekene-1 sample (engines test data)',
      rowCount: data.length,
      rowsInFile: data.length,
      skipped: 0,
      importedAt: null,
      dateRange: { start: data[0].date, end: data[data.length - 1].date },
      readBack: null,
    },
    analysis: { fitWindow: { startDate: data[0].date, endDate: data[data.length - 1].date } },
    payloadVersion: DCA_PAYLOAD_VERSION,
  };
}
