// Renders src/design/theme.css from src/design/tokens.js.
//
// Every selector is scoped under [data-pl-theme], so the stylesheet is inert
// for any app that has not opted in: the global :root/.dark variables in
// src/index.css keep driving the 100+ legacy dark consoles untouched.
import {
  THEMES, SHADOWS, FONTS, SHADCN_ALIASES, CHART_SERIES, CHART_SURFACE,
  hexToHslTriplet, hexToRgbChannels,
} from './tokens.js';

export const LIGHT_SELECTORS = [
  '[data-pl-theme="light"]',
  '[data-pl-theme] [data-canvas="light"]',
  '[data-pl-theme] [data-canvas="chart"]',
];
export const DARK_SELECTORS = [
  '[data-pl-theme="dark"]',
  '[data-pl-theme] [data-canvas="dark"]',
];

function themeBlock(name) {
  const roles = THEMES[name];
  const lines = [];
  lines.push('  /* roles as "R G B" channels for rgb(var(--pl-x) / <alpha>) */');
  for (const [role, hex] of Object.entries(roles)) {
    lines.push(`  --pl-${role}: ${hexToRgbChannels(hex)};`);
  }
  lines.push('  --pl-chart-surface: ' + hexToRgbChannels(CHART_SURFACE) + ';');
  for (const [k, v] of Object.entries(SHADOWS[name])) lines.push(`  --pl-shadow-${k}: ${v};`);
  lines.push(`  --pl-font-display: ${FONTS.display};`);
  lines.push(`  --pl-font-sans: ${FONTS.sans};`);
  lines.push(`  --pl-font-mono: ${FONTS.mono};`);
  lines.push('  /* the shadcn variables from src/index.css, re-pointed inside the scope */');
  for (const [shadcn, role] of Object.entries(SHADCN_ALIASES)) {
    lines.push(`  --${shadcn}: ${hexToHslTriplet(roles[role])};`);
  }
  CHART_SERIES.forEach((hex, i) => lines.push(`  --chart-${i + 1}: ${hexToHslTriplet(hex)};`));
  lines.push('  --radius: 0.75rem;');
  lines.push(`  color-scheme: ${name};`);
  return lines.join('\n');
}

export function renderThemeCss() {
  return [
    '/* GENERATED by scripts/design/build-theme-css.mjs from src/design/tokens.js.',
    '   Do not edit by hand; change tokens.js and re-run the script.',
    '   Scoped: nothing here applies outside an element carrying data-pl-theme',
    '   (set by <ThemedApp>). See docs/scope/DesignSystem.md. */',
    '',
    `${LIGHT_SELECTORS.join(',\n')} {`,
    themeBlock('light'),
    '}',
    '',
    `${DARK_SELECTORS.join(',\n')} {`,
    themeBlock('dark'),
    '}',
    '',
    '/* base text and canvas; :where() keeps specificity at zero so any utility',
    '   class on the same element wins */',
    ':where([data-pl-theme]) {',
    '  color: rgb(var(--pl-text));',
    '  font-family: var(--pl-font-sans);',
    '  -webkit-font-smoothing: antialiased;',
    '}',
    ':where([data-pl-root]) {',
    '  background-color: rgb(var(--pl-bg));',
    '  min-height: 100%;',
    '}',
    ':where([data-pl-theme] [data-canvas]) {',
    '  background-color: rgb(var(--pl-bg));',
    '  color: rgb(var(--pl-text));',
    '}',
    ':where([data-pl-theme] [data-canvas="chart"]) {',
    '  background-color: rgb(var(--pl-chart-surface));',
    '}',
    ':where([data-pl-theme] :focus-visible) {',
    '  outline: 2px solid rgb(var(--pl-focus));',
    '  outline-offset: 2px;',
    '}',
    '',
  ].join('\n');
}
