/**
 * G1.2 acceptance: engine/lasParse.js matches the committed lasio
 * goldens BIT-FOR-BIT (packages/engines/test-data/wells/, generated by
 * tools/validation/wells/oracle.py — lasio is the independent reference
 * implementation).
 *
 * Comparator contract (packages/engines/test-data/wells/README.md): curve samples are
 * little-endian float32; LAS nulls are NaN; NaN==NaN, every other
 * sample must be bit-identical. sum_finite_f64 in the golden JSON was
 * produced by numpy's pairwise summation, so the engine's sequential
 * sum is asserted exactly against the same sequential sum of the golden
 * samples, and only within float tolerance of the oracle's figure.
 */
import fs from 'fs';
import path from 'path';

import { parseLas } from '@/pages/apps/WellDataManager/engine/lasParse';

const DATA_DIR = path.join(__dirname, '..', '..', '..', '..', '..', 'packages', 'engines', 'test-data', 'wells');

const FIXTURES = ['basic_20', 'feet_20', 'irregular_20', 'nullheavy_20', 'quirks_20', 'wrapped_12'];

const loadGolden = (name) =>
  JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'goldens', `${name}.json`), 'utf8'));

const loadLas = (name) =>
  fs.readFileSync(path.join(DATA_DIR, 'las', `${name}.las`), 'utf8');

const loadF32 = (name, mnemonic) => {
  const buf = fs.readFileSync(path.join(DATA_DIR, 'goldens', `${name}.${mnemonic}.f32`));
  return new Float32Array(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
};

/** Bit-identical with NaN==NaN: compare the u32 views, allowing any
 *  NaN payload to match any other NaN. Returns first mismatch or -1. */
const firstBitMismatch = (a, b) => {
  if (a.length !== b.length) return Math.min(a.length, b.length);
  const ua = new Uint32Array(a.buffer, a.byteOffset, a.length);
  const ub = new Uint32Array(b.buffer, b.byteOffset, b.length);
  for (let i = 0; i < a.length; i++) {
    if (ua[i] !== ub[i] && !(Number.isNaN(a[i]) && Number.isNaN(b[i]))) return i;
  }
  return -1;
};

const sequentialFiniteSum = (data) => {
  let sum = 0;
  let any = false;
  for (let i = 0; i < data.length; i++) {
    if (Number.isFinite(data[i])) { sum += data[i]; any = true; }
  }
  return any ? sum : null;
};

describe.each(FIXTURES)('golden fixture %s', (name) => {
  const golden = loadGolden(name);
  const parsed = parseLas(loadLas(name));

  test('file-level metadata matches lasio', () => {
    expect(parsed.version).toBe(golden.version);
    expect(parsed.wrap).toBe(golden.wrap);
    expect(parsed.nullValue).toBe(golden.null_value);
    expect(parsed.depthUnit).toBe(golden.depth_unit);
  });

  test('~Well items match lasio (incl. the LAS 1.2 colon swap)', () => {
    for (const [mnem, item] of Object.entries(golden.well)) {
      expect(parsed.well[mnem]).toBeDefined();
      expect(parsed.well[mnem].unit).toBe(item.unit);
      expect(parsed.well[mnem].value).toBe(item.value);
      expect(parsed.well[mnem].descr).toBe(item.descr);
    }
  });

  test('curve set and per-curve metadata match lasio', () => {
    expect(parsed.curves.map((c) => c.mnemonic))
      .toEqual(golden.curves.map((c) => c.mnemonic));
    golden.curves.forEach((gc, i) => {
      const pc = parsed.curves[i];
      expect(pc.unit).toBe(gc.unit);
      expect(pc.descr).toBe(gc.descr);
      expect(pc.nSamples).toBe(gc.n_samples);
      expect(pc.nullCount).toBe(gc.null_count);
      expect(pc.firstFinite).toBe(gc.first_finite);
      expect(pc.lastFinite).toBe(gc.last_finite);
    });
  });

  test.each(golden.curves.map((c) => c.mnemonic))('curve %s samples are bit-identical', (mnemonic) => {
    const pc = parsed.curves.find((c) => c.mnemonic === mnemonic);
    const gold = loadF32(name, mnemonic);
    expect(pc.data.length).toBe(gold.length);
    expect(firstBitMismatch(pc.data, gold)).toBe(-1);
  });

  test('finite-sum checksums agree', () => {
    golden.curves.forEach((gc, i) => {
      const pc = parsed.curves[i];
      // exactly equal to the same sequential sum over the golden bits
      expect(pc.sumFiniteF64).toBe(sequentialFiniteSum(loadF32(name, gc.mnemonic)));
      // and within float tolerance of numpy's pairwise figure
      if (gc.sum_finite_f64 === null) {
        expect(pc.sumFiniteF64).toBeNull();
      } else {
        const rel = Math.abs(pc.sumFiniteF64 - gc.sum_finite_f64)
          / Math.max(1, Math.abs(gc.sum_finite_f64));
        expect(rel).toBeLessThan(1e-12);
      }
    });
  });
});
