-- ============================================================================
-- MEMBERSHIP CONSOLIDATION (suite-wide) — Geoscience-ROADMAP §6.1 convergence
-- path, scheduled alongside G5. SHARED-TABLE CHANGE: second-engineer review
-- required (Petrolord_Database_Conventions).
--
-- End state: public.organization_members (+ organization_apps) is the ONLY
-- membership store. The deprecated tables organization_users and
-- public.org_members (frozen by deprecation triggers since G1.1) are
-- backfilled into organization_members and DROPPED, replaced by name-
-- compatible security_invoker VIEWS so the currently-deployed production SPA
-- keeps resolving org context until the next prod build upload (same
-- compatibility-view pattern as the seismic_wells retirement, G1.4→G1.5).
--
-- Live-state audit findings this migration is built on (2026-07-13):
--   * organization_users: 1 row missing from organization_members (backfilled
--     below); org_members: 0 rows.
--   * 162 RLS policies across public/hse/storage referenced the legacy tables
--     directly in their expressions (the "one function" story only held for
--     geoscience/EPE/econ). They are rewritten here onto SECURITY DEFINER
--     helpers — generated by tools/consolidation/gen_policy_rewrites.py from
--     the live catalog dump (tools/consolidation/catalog/), audited, and
--     inlined below. 3 petrolord.* policies are out of scope (the drilling
--     module's own petrolord.org_members is a different table).
--   * ~20 SQL functions referenced the legacy tables; rewritten or dropped
--     below. handle_new_user (the only auth.users trigger) already writes
--     canonical tables and needs no change.
--
-- Role-vocabulary note: the legacy tables kept admin-ness in a separate
-- user_role column (org creators: role='owner', user_role='org_admin').
-- organization_members has a single role column where creators are 'owner',
-- so every rewritten role array also accepts 'owner'. Helper role checks
-- also require status='active' (canonical semantics; legacy checks were
-- mostly status-blind but every live legacy row is 'active').
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1. Backfill legacy membership rows into organization_members.
--    full_name/email come from auth.users (organization_members requires
--    them); role carries over; joined_at falls back to the legacy created_at.
-- ----------------------------------------------------------------------------
insert into public.organization_members
  (organization_id, user_id, full_name, email, role, status, joined_at,
   created_at, updated_at)
select
  ou.organization_id,
  ou.user_id,
  coalesce(au.raw_user_meta_data->>'full_name', au.email, 'Unknown'),
  coalesce(au.email, 'unknown+' || ou.user_id || '@petrolord.invalid'),
  coalesce(ou.role, 'member'),
  coalesce(lower(ou.status), 'active'),
  coalesce(ou.created_at, now()),
  coalesce(ou.created_at, now()),
  now()
from public.organization_users ou
left join auth.users au on au.id = ou.user_id
where not exists (
  select 1 from public.organization_members m
  where m.organization_id = ou.organization_id and m.user_id = ou.user_id
)
on conflict (organization_id, email) do nothing;

insert into public.organization_members
  (organization_id, user_id, full_name, email, role, status, joined_at,
   created_at, updated_at)
select
  om.org_id,
  om.user_id,
  coalesce(au.raw_user_meta_data->>'full_name', au.email, 'Unknown'),
  coalesce(au.email, 'unknown+' || om.user_id || '@petrolord.invalid'),
  coalesce(om.role, 'member'),
  'active',
  coalesce(om.joined_at, om.invited_at, now()),
  coalesce(om.joined_at, om.invited_at, now()),
  now()
from public.org_members om
left join auth.users au on au.id = om.user_id
where om.user_id is not null and om.org_id is not null
  and not exists (
    select 1 from public.organization_members m
    where m.organization_id = om.org_id and m.user_id = om.user_id
  )
on conflict (organization_id, email) do nothing;

-- Backfill completeness assert: every legacy (org, user) pair must now exist
-- canonically. Aborts the whole migration if not.
do $$
declare v_missing integer;
begin
  select count(*) into v_missing from (
    select ou.organization_id as org, ou.user_id as usr
      from public.organization_users ou where ou.user_id is not null
    union
    select om.org_id, om.user_id
      from public.org_members om
     where om.user_id is not null and om.org_id is not null
  ) legacy
  where not exists (
    select 1 from public.organization_members m
    where m.organization_id = legacy.org and m.user_id = legacy.usr
  );
  if v_missing > 0 then
    raise exception 'membership backfill incomplete: % legacy pair(s) missing from organization_members', v_missing;
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 2. Canonical membership helpers. SECURITY DEFINER (postgres owns the table,
--    so these bypass organization_members RLS — no policy recursion), STABLE,
--    pinned search_path. These are the ONLY membership predicates RLS may use.
-- ----------------------------------------------------------------------------
create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.organization_members om
    where om.organization_id = is_org_member.org_id
      and om.user_id = auth.uid()
      and coalesce(lower(om.status), 'active') = 'active'
  );
$$;
comment on function public.is_org_member(uuid) is
  'True when auth.uid() is an active member of the org (organization_members '
  'is the single canonical membership table since 20260713300000). The ONLY '
  'membership predicate RLS policies may use, together with has_org_role/'
  'has_any_org_role/my_org_id/is_org_admin_of.';

create or replace function public.has_org_role(org_id uuid, roles text[])
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.organization_members om
    where om.organization_id = has_org_role.org_id
      and om.user_id = auth.uid()
      and coalesce(lower(om.status), 'active') = 'active'
      and om.role = any (has_org_role.roles)
  );
$$;
comment on function public.has_org_role(uuid, text[]) is
  'Role-gated membership check against the canonical organization_members '
  'table. Rewritten legacy policies preserve their original role arrays plus '
  '''owner'' (see 20260713300000 header).';

create or replace function public.has_any_org_role(roles text[])
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select exists (
    select 1 from public.organization_members om
    where om.user_id = auth.uid()
      and coalesce(lower(om.status), 'active') = 'active'
      and om.role = any (has_any_org_role.roles)
  );
$$;

create or replace function public.my_org_id()
returns uuid
language sql stable security definer
set search_path to 'public'
as $$
  select om.organization_id
  from public.organization_members om
  where om.user_id = auth.uid()
    and coalesce(lower(om.status), 'active') = 'active'
  order by om.joined_at nulls last, om.created_at
  limit 1;
$$;
comment on function public.my_org_id() is
  'Null-safe "my organization" scalar for RLS (replaces the legacy '
  '(SELECT organization_id FROM organization_users ... LIMIT 1) pattern; '
  'unlike get_my_organization_id() it never raises).';

create or replace function public.is_org_admin_of(check_org_id uuid)
returns boolean
language sql stable security definer
set search_path to 'public'
as $$
  select public.has_org_role(check_org_id,
                             array['owner','admin','org_admin','super_admin']);
$$;

-- ----------------------------------------------------------------------------
-- 3. RLS policy rewrites (generated; see header). 159 policies.
-- ----------------------------------------------------------------------------
-- 159 policies rewritten onto canonical membership helpers.
-- Skipped (out of scope):
--   petrolord.org_members."org_members manage" (drilling-module namespace, out of scope)
--   petrolord.organizations."orgs read" (drilling-module namespace, out of scope)
--   petrolord.projects."projects write" (drilling-module namespace, out of scope)

-- hse.access_logs."Org members can read access logs"
drop policy if exists "Org members can read access logs" on hse."access_logs";
create policy "Org members can read access logs" on hse."access_logs"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.actions."Assignees and admins can update actions"
drop policy if exists "Assignees and admins can update actions" on hse."actions";
create policy "Assignees and admins can update actions" on hse."actions"
  as permissive for update
  to public
  using (((assigned_to = auth.uid()) OR (public.has_org_role(organization_id, ARRAY['manager'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text]))));

-- hse.actions."Org members can insert actions"
drop policy if exists "Org members can insert actions" on hse."actions";
create policy "Org members can insert actions" on hse."actions"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.actions."Org members can view actions"
drop policy if exists "Org members can view actions" on hse."actions";
create policy "Org members can view actions" on hse."actions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can create actions"
drop policy if exists "Users can create actions" on hse."actions";
create policy "Users can create actions" on hse."actions"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.actions."Users can manage actions for their org"
drop policy if exists "Users can manage actions for their org" on hse."actions";
create policy "Users can manage actions for their org" on hse."actions"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can update actions"
drop policy if exists "Users can update actions" on hse."actions";
create policy "Users can update actions" on hse."actions"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- hse.actions."Users can view actions for their org"
drop policy if exists "Users can view actions for their org" on hse."actions";
create policy "Users can view actions for their org" on hse."actions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.audit_findings."Users can manage audit findings for their organization"
drop policy if exists "Users can manage audit findings for their organization" on hse."audit_findings";
create policy "Users can manage audit findings for their organization" on hse."audit_findings"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.audit_log."Only admins can view audit logs"
drop policy if exists "Only admins can view audit logs" on hse."audit_log";
create policy "Only admins can view audit logs" on hse."audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.audit_log."Users can view audit logs for their org"
drop policy if exists "Users can view audit logs for their org" on hse."audit_log";
create policy "Users can view audit logs for their org" on hse."audit_log"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.audit_logs."Org members can read audit logs"
drop policy if exists "Org members can read audit logs" on hse."audit_logs";
create policy "Org members can read audit logs" on hse."audit_logs"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.audit_schedule."Users can manage audit schedule for their organization"
drop policy if exists "Users can manage audit schedule for their organization" on hse."audit_schedule";
create policy "Users can manage audit schedule for their organization" on hse."audit_schedule"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.competency_records."Users can manage competency records for their organization"
drop policy if exists "Users can manage competency records for their organization" on hse."competency_records";
create policy "Users can manage competency records for their organization" on hse."competency_records"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.contractors."Users can manage contractors for their organization"
drop policy if exists "Users can manage contractors for their organization" on hse."contractors";
create policy "Users can manage contractors for their organization" on hse."contractors"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.environmental_records."Org members can read environmental records"
drop policy if exists "Org members can read environmental records" on hse."environmental_records";
create policy "Org members can read environmental records" on hse."environmental_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.exposure_log."Org members can read exposure logs"
drop policy if exists "Org members can read exposure logs" on hse."exposure_log";
create policy "Org members can read exposure logs" on hse."exposure_log"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.external_reports."Users can manage external reports for their organization"
drop policy if exists "Users can manage external reports for their organization" on hse."external_reports";
create policy "Users can manage external reports for their organization" on hse."external_reports"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_drills."Users can insert fire drills for their org"
drop policy if exists "Users can insert fire drills for their org" on hse."fire_drills";
create policy "Users can insert fire drills for their org" on hse."fire_drills"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_drills."Users can view fire drills for their org"
drop policy if exists "Users can view fire drills for their org" on hse."fire_drills";
create policy "Users can view fire drills for their org" on hse."fire_drills"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_equipment."Users can insert fire equipment for their org"
drop policy if exists "Users can insert fire equipment for their org" on hse."fire_equipment";
create policy "Users can insert fire equipment for their org" on hse."fire_equipment"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_equipment."Users can view fire equipment for their org"
drop policy if exists "Users can view fire equipment for their org" on hse."fire_equipment";
create policy "Users can view fire equipment for their org" on hse."fire_equipment"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.fire_safety_records."Users can insert fire records for their org"
drop policy if exists "Users can insert fire records for their org" on hse."fire_safety_records";
create policy "Users can insert fire records for their org" on hse."fire_safety_records"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.fire_safety_records."Users can view fire records for their org"
drop policy if exists "Users can view fire records for their org" on hse."fire_safety_records";
create policy "Users can view fire records for their org" on hse."fire_safety_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.health_records."Org members can read health records"
drop policy if exists "Org members can read health records" on hse."health_records";
create policy "Org members can read health records" on hse."health_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.internal_audits."Users can manage internal audits for their organization"
drop policy if exists "Users can manage internal audits for their organization" on hse."internal_audits";
create policy "Users can manage internal audits for their organization" on hse."internal_audits"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.project_members."Org Access Project Members"
drop policy if exists "Org Access Project Members" on hse."project_members";
create policy "Org Access Project Members" on hse."project_members"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.reports."Creators and admins can update reports"
drop policy if exists "Creators and admins can update reports" on hse."reports";
create policy "Creators and admins can update reports" on hse."reports"
  as permissive for update
  to public
  using (((created_by = auth.uid()) OR (public.has_org_role(organization_id, ARRAY['manager'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text]))));

-- hse.reports."Org members can insert reports"
drop policy if exists "Org members can insert reports" on hse."reports";
create policy "Org members can insert reports" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Org members can view reports"
drop policy if exists "Org members can view reports" on hse."reports";
create policy "Org members can view reports" on hse."reports"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.reports."Users can create reports for their org"
drop policy if exists "Users can create reports for their org" on hse."reports";
create policy "Users can create reports for their org" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Users can insert reports for their org"
drop policy if exists "Users can insert reports for their org" on hse."reports";
create policy "Users can insert reports for their org" on hse."reports"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- hse.reports."Users can update reports for their org"
drop policy if exists "Users can update reports for their org" on hse."reports";
create policy "Users can update reports for their org" on hse."reports"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- hse.reports."Users can view reports for their org"
drop policy if exists "Users can view reports for their org" on hse."reports";
create policy "Users can view reports for their org" on hse."reports"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.risk_register."Users can insert risks for their org"
drop policy if exists "Users can insert risks for their org" on hse."risk_register";
create policy "Users can insert risks for their org" on hse."risk_register"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.risk_register."Users can update risks for their org"
drop policy if exists "Users can update risks for their org" on hse."risk_register";
create policy "Users can update risks for their org" on hse."risk_register"
  as permissive for update
  to public
  using ((public.is_org_member(org_id)));

-- hse.risk_register."Users can view risks for their org"
drop policy if exists "Users can view risks for their org" on hse."risk_register";
create policy "Users can view risks for their org" on hse."risk_register"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.role_definitions."Only admins can modify roles"
drop policy if exists "Only admins can modify roles" on hse."role_definitions";
create policy "Only admins can modify roles" on hse."role_definitions"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.role_definitions."Users can view roles for their org"
drop policy if exists "Users can view roles for their org" on hse."role_definitions";
create policy "Users can view roles for their org" on hse."role_definitions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.roles."Org Access Roles"
drop policy if exists "Org Access Roles" on hse."roles";
create policy "Org Access Roles" on hse."roles"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.safety_inductions."Users can manage inductions for their organization"
drop policy if exists "Users can manage inductions for their organization" on hse."safety_inductions";
create policy "Users can manage inductions for their organization" on hse."safety_inductions"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- hse.security_incidents."Org members can read security incidents"
drop policy if exists "Org members can read security incidents" on hse."security_incidents";
create policy "Org members can read security incidents" on hse."security_incidents"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.spill_records."Users can insert spill records for their org"
drop policy if exists "Users can insert spill records for their org" on hse."spill_records";
create policy "Users can insert spill records for their org" on hse."spill_records"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.spill_records."Users can view spill records for their org"
drop policy if exists "Users can view spill records for their org" on hse."spill_records";
create policy "Users can view spill records for their org" on hse."spill_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.spill_response."Users can insert spill response for their org"
drop policy if exists "Users can insert spill response for their org" on hse."spill_response";
create policy "Users can insert spill response for their org" on hse."spill_response"
  as permissive for insert
  to public
  with check ((public.is_org_member(org_id)));

-- hse.spill_response."Users can view spill response for their org"
drop policy if exists "Users can view spill response for their org" on hse."spill_response";
create policy "Users can view spill response for their org" on hse."spill_response"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- hse.subscriptions."Only admins can modify subscription"
drop policy if exists "Only admins can modify subscription" on hse."subscriptions";
create policy "Only admins can modify subscription" on hse."subscriptions"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text])));

-- hse.subscriptions."Users can view their org subscription"
drop policy if exists "Users can view their org subscription" on hse."subscriptions";
create policy "Users can view their org subscription" on hse."subscriptions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- hse.team_communications."Org Access Communications"
drop policy if exists "Org Access Communications" on hse."team_communications";
create policy "Org Access Communications" on hse."team_communications"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_members."Org Access Members"
drop policy if exists "Org Access Members" on hse."team_members";
create policy "Org Access Members" on hse."team_members"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_performance."Org Access Performance"
drop policy if exists "Org Access Performance" on hse."team_performance";
create policy "Org Access Performance" on hse."team_performance"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_projects."Org Access Projects"
drop policy if exists "Org Access Projects" on hse."team_projects";
create policy "Org Access Projects" on hse."team_projects"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_resources."Org Access Resources"
drop policy if exists "Org Access Resources" on hse."team_resources";
create policy "Org Access Resources" on hse."team_resources"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.team_tasks."Org Access Tasks"
drop policy if exists "Org Access Tasks" on hse."team_tasks";
create policy "Org Access Tasks" on hse."team_tasks"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.teams."Org Access Teams"
drop policy if exists "Org Access Teams" on hse."teams";
create policy "Org Access Teams" on hse."teams"
  as permissive for all
  to public
  using ((org_id = public.my_org_id()));

-- hse.waste_management."Org members can read waste records"
drop policy if exists "Org members can read waste records" on hse."waste_management";
create policy "Org members can read waste records" on hse."waste_management"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.access_audit_log."Org admins view access logs"
drop policy if exists "Org admins view access logs" on public."access_audit_log";
create policy "Org admins view access logs" on public."access_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.access_requests."Org Admins can manage all requests"
drop policy if exists "Org Admins can manage all requests" on public."access_requests";
create policy "Org Admins can manage all requests" on public."access_requests"
  as permissive for all
  to public
  using ((public.has_org_role(access_requests.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.alerts."Org members can insert alerts"
drop policy if exists "Org members can insert alerts" on public."alerts";
create policy "Org members can insert alerts" on public."alerts"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.alerts."Org members can update alerts"
drop policy if exists "Org members can update alerts" on public."alerts";
create policy "Org members can update alerts" on public."alerts"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.alerts."Users can view org alerts"
drop policy if exists "Users can view org alerts" on public."alerts";
create policy "Users can view org alerts" on public."alerts"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.analytics_insights."View org analytics"
drop policy if exists "View org analytics" on public."analytics_insights";
create policy "View org analytics" on public."analytics_insights"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.app_analytics_daily."Org admins view analytics"
drop policy if exists "Org admins view analytics" on public."app_analytics_daily";
create policy "Org admins view analytics" on public."app_analytics_daily"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.app_seat_assignments."Org admins can manage assignments"
drop policy if exists "Org admins can manage assignments" on public."app_seat_assignments";
create policy "Org admins can manage assignments" on public."app_seat_assignments"
  as permissive for all
  to public
  using ((public.has_org_role(app_seat_assignments.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.app_seat_assignments."Org members can view assignments"
drop policy if exists "Org members can view assignments" on public."app_seat_assignments";
create policy "Org members can view assignments" on public."app_seat_assignments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.billing_reports."Admins view reports"
drop policy if exists "Admins view reports" on public."billing_reports";
create policy "Admins view reports" on public."billing_reports"
  as permissive for select
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_audit_log."Org admins can insert audit log"
drop policy if exists "Org admins can insert audit log" on public."branding_audit_log";
create policy "Org admins can insert audit log" on public."branding_audit_log"
  as permissive for insert
  to public
  with check ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_audit_log."Org admins can read audit log"
drop policy if exists "Org admins can read audit log" on public."branding_audit_log";
create policy "Org admins can read audit log" on public."branding_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_presets."Org admins can manage presets"
drop policy if exists "Org admins can manage presets" on public."branding_presets";
create policy "Org admins can manage presets" on public."branding_presets"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.branding_presets."Org members can read presets"
drop policy if exists "Org members can read presets" on public."branding_presets";
create policy "Org members can read presets" on public."branding_presets"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.bulk_import_jobs."Org admins manage bulk imports"
drop policy if exists "Org admins manage bulk imports" on public."bulk_import_jobs";
create policy "Org admins manage bulk imports" on public."bulk_import_jobs"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.compliance_rules."Org admins manage rules"
drop policy if exists "Org admins manage rules" on public."compliance_rules";
create policy "Org admins manage rules" on public."compliance_rules"
  as permissive for all
  to public
  using ((public.has_org_role(org_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.compliance_rules."Org members view rules"
drop policy if exists "Org members view rules" on public."compliance_rules";
create policy "Org members view rules" on public."compliance_rules"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.discount_codes."Admins manage discounts"
drop policy if exists "Admins manage discounts" on public."discount_codes";
create policy "Admins manage discounts" on public."discount_codes"
  as permissive for all
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.employee_app_access."Org Admins can manage app access"
drop policy if exists "Org Admins can manage app access" on public."employee_app_access";
create policy "Org Admins can manage app access" on public."employee_app_access"
  as permissive for all
  to public
  using ((public.has_org_role(employee_app_access.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.employee_storage."Org Admins can manage storage"
drop policy if exists "Org Admins can manage storage" on public."employee_storage";
create policy "Org Admins can manage storage" on public."employee_storage"
  as permissive for all
  to public
  using ((public.has_org_role(employee_storage.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.environment_emp_actions."Org Access EMP"
drop policy if exists "Org Access EMP" on public."environment_emp_actions";
create policy "Org Access EMP" on public."environment_emp_actions"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_facilities."Org Access Facilities"
drop policy if exists "Org Access Facilities" on public."environment_facilities";
create policy "Org Access Facilities" on public."environment_facilities"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_flaring_logs."Org Access Flaring"
drop policy if exists "Org Access Flaring" on public."environment_flaring_logs";
create policy "Org Access Flaring" on public."environment_flaring_logs"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_metrics."Users can view org environment metrics"
drop policy if exists "Users can view org environment metrics" on public."environment_metrics";
create policy "Users can view org environment metrics" on public."environment_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.environment_monitoring_results."Org Access Monitoring"
drop policy if exists "Org Access Monitoring" on public."environment_monitoring_results";
create policy "Org Access Monitoring" on public."environment_monitoring_results"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_obligations."Org Access Obligations"
drop policy if exists "Org Access Obligations" on public."environment_obligations";
create policy "Org Access Obligations" on public."environment_obligations"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_permits."Org Access Permits"
drop policy if exists "Org Access Permits" on public."environment_permits";
create policy "Org Access Permits" on public."environment_permits"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_spill_reports."Org Access Spills"
drop policy if exists "Org Access Spills" on public."environment_spill_reports";
create policy "Org Access Spills" on public."environment_spill_reports"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_studies."Org Access Studies"
drop policy if exists "Org Access Studies" on public."environment_studies";
create policy "Org Access Studies" on public."environment_studies"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environment_waste_manifests."Org Access Waste"
drop policy if exists "Org Access Waste" on public."environment_waste_manifests";
create policy "Org Access Waste" on public."environment_waste_manifests"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.environmental_monitoring."Org members can insert env data"
drop policy if exists "Org members can insert env data" on public."environmental_monitoring";
create policy "Org members can insert env data" on public."environmental_monitoring"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.environmental_monitoring."Org members can view env data"
drop policy if exists "Org members can view env data" on public."environmental_monitoring";
create policy "Org members can view env data" on public."environmental_monitoring"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.fire_drills."Org Access Drills"
drop policy if exists "Org Access Drills" on public."fire_drills";
create policy "Org Access Drills" on public."fire_drills"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_emergency_response_plans."Org Access ERP"
drop policy if exists "Org Access ERP" on public."fire_emergency_response_plans";
create policy "Org Access ERP" on public."fire_emergency_response_plans"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_equipment_inventory."Org Access Equipment"
drop policy if exists "Org Access Equipment" on public."fire_equipment_inventory";
create policy "Org Access Equipment" on public."fire_equipment_inventory"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_equipment_maintenance."Org Access Maintenance"
drop policy if exists "Org Access Maintenance" on public."fire_equipment_maintenance";
create policy "Org Access Maintenance" on public."fire_equipment_maintenance"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_incident_investigation."Org Access Investigation"
drop policy if exists "Org Access Investigation" on public."fire_incident_investigation";
create policy "Org Access Investigation" on public."fire_incident_investigation"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_incidents."Org Access Incidents"
drop policy if exists "Org Access Incidents" on public."fire_incidents";
create policy "Org Access Incidents" on public."fire_incidents"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_safety_compliance."Org Access Compliance"
drop policy if exists "Org Access Compliance" on public."fire_safety_compliance";
create policy "Org Access Compliance" on public."fire_safety_compliance"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fire_safety_risks."Org Access Risks"
drop policy if exists "Org Access Risks" on public."fire_safety_risks";
create policy "Org Access Risks" on public."fire_safety_risks"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.fitness_activities."Users can view org fitness (for leaderboard)"
drop policy if exists "Users can view org fitness (for leaderboard)" on public."fitness_activities";
create policy "Users can view org fitness (for leaderboard)" on public."fitness_activities"
  as permissive for select
  to public
  using ((public.is_org_member(fitness_activities.organization_id)));

-- public.hazard_assessments."Org members can manage hazards"
drop policy if exists "Org members can manage hazards" on public."hazard_assessments";
create policy "Org members can manage hazards" on public."hazard_assessments"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.hazard_assessments."Org members can view hazards"
drop policy if exists "Org members can view hazards" on public."hazard_assessments";
create policy "Org members can view hazards" on public."hazard_assessments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.health_metrics."Users can view org health metrics"
drop policy if exists "Users can view org health metrics" on public."health_metrics";
create policy "Users can view org health metrics" on public."health_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.health_profiles."Supervisors/Admins can view org health profiles"
drop policy if exists "Supervisors/Admins can view org health profiles" on public."health_profiles";
create policy "Supervisors/Admins can view org health profiles" on public."health_profiles"
  as permissive for select
  to public
  using ((public.has_org_role(health_profiles.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])));

-- public.incident_attachments."View attachments"
drop policy if exists "View attachments" on public."incident_attachments";
create policy "View attachments" on public."incident_attachments"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM incidents
  WHERE ((incidents.id = incident_attachments.incident_id) AND ((incidents.created_by = auth.uid()) OR (public.has_org_role(incidents.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])))))));

-- public.incidents."Incidents Insert Policy"
drop policy if exists "Incidents Insert Policy" on public."incidents";
create policy "Incidents Insert Policy" on public."incidents"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.incidents."Incidents Update Policy"
drop policy if exists "Incidents Update Policy" on public."incidents";
create policy "Incidents Update Policy" on public."incidents"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.invoices."Users can view invoices for their own org"
drop policy if exists "Users can view invoices for their own org" on public."invoices";
create policy "Users can view invoices for their own org" on public."invoices"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.leaderboard_history."View org history"
drop policy if exists "View org history" on public."leaderboard_history";
create policy "View org history" on public."leaderboard_history"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.leaderboard_scores."View org leaderboard"
drop policy if exists "View org leaderboard" on public."leaderboard_scores";
create policy "View org leaderboard" on public."leaderboard_scores"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.master_apps."Users can view apps their org has purchased"
drop policy if exists "Users can view apps their org has purchased" on public."master_apps";
create policy "Users can view apps their org has purchased" on public."master_apps"
  as permissive for select
  to public
  using (((EXISTS ( SELECT 1
   FROM (purchased_modules pm
     JOIN organization_members ou ON ((pm.organization_id = ou.organization_id)))
  WHERE ((ou.user_id = auth.uid()) AND (ou.status = 'active'::text) AND (pm.status = 'active'::text) AND (pm.expiry_date > now()) AND ((pm.app_uuid = master_apps.id) OR ((pm.app_uuid IS NULL) AND (pm.module_uuid = master_apps.module_id)))))) OR (auth.role() = 'service_role'::text)));

-- public.master_apps."Users can view purchased apps"
drop policy if exists "Users can view purchased apps" on public."master_apps";
create policy "Users can view purchased apps" on public."master_apps"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM (purchased_modules pm
     JOIN organization_members ou ON ((pm.organization_id = ou.organization_id)))
  WHERE ((ou.user_id = auth.uid()) AND (ou.status = 'active'::text) AND (pm.status = 'active'::text) AND (pm.expiry_date > now()) AND ((pm.app_uuid = master_apps.id) OR ((pm.app_uuid IS NULL) AND (pm.module_uuid = master_apps.module_id)))))));

-- public.moc_records."Org members can manage MOCs"
drop policy if exists "Org members can manage MOCs" on public."moc_records";
create policy "Org members can manage MOCs" on public."moc_records"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.moc_records."Org members can view MOCs"
drop policy if exists "Org members can view MOCs" on public."moc_records";
create policy "Org members can view MOCs" on public."moc_records"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.model_training_logs."Users can manage training logs for their org"
drop policy if exists "Users can manage training logs for their org" on public."model_training_logs";
create policy "Users can manage training logs for their org" on public."model_training_logs"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.model_training_logs."Users can view training logs for their org"
drop policy if exists "Users can view training logs for their org" on public."model_training_logs";
create policy "Users can view training logs for their org" on public."model_training_logs"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.module_access."Org members view access"
drop policy if exists "Org members view access" on public."module_access";
create policy "Org members view access" on public."module_access"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.org_settings."Users can view settings for their orgs"
drop policy if exists "Users can view settings for their orgs" on public."org_settings";
create policy "Users can view settings for their orgs" on public."org_settings"
  as permissive for select
  to public
  using (((public.is_org_member(org_id)) OR is_super_admin()));

-- public.organization_assets."Users can manage organization assets"
drop policy if exists "Users can manage organization assets" on public."organization_assets";
create policy "Users can manage organization assets" on public."organization_assets"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.organization_members."delete_organization_members"
drop policy if exists "delete_organization_members" on public."organization_members";
create policy "delete_organization_members" on public."organization_members"
  as permissive for delete
  to public
  using ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."insert_organization_members"
drop policy if exists "insert_organization_members" on public."organization_members";
create policy "insert_organization_members" on public."organization_members"
  as permissive for insert
  to public
  with check ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."update_organization_members"
drop policy if exists "update_organization_members" on public."organization_members";
create policy "update_organization_members" on public."organization_members"
  as permissive for update
  to public
  using ((public.has_org_role(organization_members.organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.organization_members."view_organization_members"
drop policy if exists "view_organization_members" on public."organization_members";
create policy "view_organization_members" on public."organization_members"
  as permissive for select
  to public
  using (((auth.uid() = user_id) OR (public.is_org_member(organization_members.organization_id))));

-- public.payment_methods."Org admins can manage payment methods"
drop policy if exists "Org admins can manage payment methods" on public."payment_methods";
create policy "Org admins can manage payment methods" on public."payment_methods"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.payments."Org members can view own payments"
drop policy if exists "Org members can view own payments" on public."payments";
create policy "Org members can view own payments" on public."payments"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.peer_review_audit."Org members can view peer review audit"
drop policy if exists "Org members can view peer review audit" on public."peer_review_audit";
create policy "Org members can view peer review audit" on public."peer_review_audit"
  as permissive for select
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_review_comments."Org members can manage peer review comments"
drop policy if exists "Org members can manage peer review comments" on public."peer_review_comments";
create policy "Org members can manage peer review comments" on public."peer_review_comments"
  as permissive for all
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_review_comments."Org members can view peer review comments"
drop policy if exists "Org members can view peer review comments" on public."peer_review_comments";
create policy "Org members can view peer review comments" on public."peer_review_comments"
  as permissive for select
  to public
  using ((review_id IN ( SELECT peer_reviews.id
   FROM peer_reviews
  WHERE (public.is_org_member(peer_reviews.org_id)))));

-- public.peer_reviews."Org members can manage peer reviews"
drop policy if exists "Org members can manage peer reviews" on public."peer_reviews";
create policy "Org members can manage peer reviews" on public."peer_reviews"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.peer_reviews."Org members can view peer reviews"
drop policy if exists "Org members can view peer reviews" on public."peer_reviews";
create policy "Org members can view peer reviews" on public."peer_reviews"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.predictions."Users can manage predictions for their org"
drop policy if exists "Users can manage predictions for their org" on public."predictions";
create policy "Users can manage predictions for their org" on public."predictions"
  as permissive for all
  to public
  using ((public.is_org_member(organization_id)));

-- public.predictions."Users can view predictions for their org"
drop policy if exists "Users can view predictions for their org" on public."predictions";
create policy "Users can view predictions for their org" on public."predictions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.pricing_tiers."Admins manage pricing"
drop policy if exists "Admins manage pricing" on public."pricing_tiers";
create policy "Admins manage pricing" on public."pricing_tiers"
  as permissive for all
  to public
  using ((public.has_any_org_role(ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.quick_report_media."View media"
drop policy if exists "View media" on public."quick_report_media";
create policy "View media" on public."quick_report_media"
  as permissive for select
  to public
  using ((EXISTS ( SELECT 1
   FROM quick_reports
  WHERE ((quick_reports.id = quick_report_media.report_id) AND ((quick_reports.created_by_user_id = auth.uid()) OR (public.has_org_role(quick_reports.organization_id, ARRAY['admin'::text, 'owner'::text, 'supervisor'::text])))))));

-- public.recommendations."Org members can insert recommendations"
drop policy if exists "Org members can insert recommendations" on public."recommendations";
create policy "Org members can insert recommendations" on public."recommendations"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.recommendations."Org members can update recommendations"
drop policy if exists "Org members can update recommendations" on public."recommendations";
create policy "Org members can update recommendations" on public."recommendations"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.recommendations."Users can view org recommendations"
drop policy if exists "Users can view org recommendations" on public."recommendations";
create policy "Users can view org recommendations" on public."recommendations"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.regulatory_authorities."Org Access Authorities"
drop policy if exists "Org Access Authorities" on public."regulatory_authorities";
create policy "Org Access Authorities" on public."regulatory_authorities"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.regulatory_obligations."Org Access Obligations"
drop policy if exists "Org Access Obligations" on public."regulatory_obligations";
create policy "Org Access Obligations" on public."regulatory_obligations"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.renewal_audit_log."Org admins can view renewal audit logs"
drop policy if exists "Org admins can view renewal audit logs" on public."renewal_audit_log";
create policy "Org admins can view renewal audit logs" on public."renewal_audit_log"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.renewal_notifications."Org admins can view renewal notifications"
drop policy if exists "Org admins can view renewal notifications" on public."renewal_notifications";
create policy "Org admins can view renewal notifications" on public."renewal_notifications"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text])));

-- public.renewal_reminders."Org admins view reminders"
drop policy if exists "Org admins view reminders" on public."renewal_reminders";
create policy "Org admins view reminders" on public."renewal_reminders"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.risk_kris."Org Access KRIs"
drop policy if exists "Org Access KRIs" on public."risk_kris";
create policy "Org Access KRIs" on public."risk_kris"
  as permissive for all
  to public
  using ((risk_id IN ( SELECT risk_register.id
   FROM risk_register
  WHERE (public.is_org_member(risk_register.org_id)))));

-- public.risk_mitigation_actions."Org Access Mitigation"
drop policy if exists "Org Access Mitigation" on public."risk_mitigation_actions";
create policy "Org Access Mitigation" on public."risk_mitigation_actions"
  as permissive for all
  to public
  using ((risk_id IN ( SELECT risk_register.id
   FROM risk_register
  WHERE (public.is_org_member(risk_register.org_id)))));

-- public.risk_register."Org Access Risks"
drop policy if exists "Org Access Risks" on public."risk_register";
create policy "Org Access Risks" on public."risk_register"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.risk_scenarios."Org Access Scenarios"
drop policy if exists "Org Access Scenarios" on public."risk_scenarios";
create policy "Org Access Scenarios" on public."risk_scenarios"
  as permissive for all
  to public
  using ((public.is_org_member(org_id)));

-- public.safety_audits."Org admins/auditors can manage audits"
drop policy if exists "Org admins/auditors can manage audits" on public."safety_audits";
create policy "Org admins/auditors can manage audits" on public."safety_audits"
  as permissive for all
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'auditor'::text, 'owner'::text])));

-- public.safety_audits."Org members can view audits"
drop policy if exists "Org members can view audits" on public."safety_audits";
create policy "Org members can view audits" on public."safety_audits"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.security_incidents."Admins/Security can update security incidents"
drop policy if exists "Admins/Security can update security incidents" on public."security_incidents";
create policy "Admins/Security can update security incidents" on public."security_incidents"
  as permissive for update
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text, 'security_manager'::text])));

-- public.security_incidents."Users can insert security incidents"
drop policy if exists "Users can insert security incidents" on public."security_incidents";
create policy "Users can insert security incidents" on public."security_incidents"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.security_incidents."Users can view org security incidents"
drop policy if exists "Users can view org security incidents" on public."security_incidents";
create policy "Users can view org security incidents" on public."security_incidents"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.site_locations."Users can insert their org locations"
drop policy if exists "Users can insert their org locations" on public."site_locations";
create policy "Users can insert their org locations" on public."site_locations"
  as permissive for insert
  to public
  with check ((public.is_org_member(organization_id)));

-- public.site_locations."Users can update their org locations"
drop policy if exists "Users can update their org locations" on public."site_locations";
create policy "Users can update their org locations" on public."site_locations"
  as permissive for update
  to public
  using ((public.is_org_member(organization_id)));

-- public.site_locations."Users can view their org locations"
drop policy if exists "Users can view their org locations" on public."site_locations";
create policy "Users can view their org locations" on public."site_locations"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.sites."Org admins can manage sites"
drop policy if exists "Org admins can manage sites" on public."sites";
create policy "Org admins can manage sites" on public."sites"
  as permissive for all
  to public
  using ((public.has_org_role(org_id, ARRAY['org_admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.sites."Org members can view sites"
drop policy if exists "Org members can view sites" on public."sites";
create policy "Org members can view sites" on public."sites"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- public.subscriptions."Users can view their own org's subscription"
drop policy if exists "Users can view their own org's subscription" on public."subscriptions";
create policy "Users can view their own org's subscription" on public."subscriptions"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.support_tickets."Org admins view org tickets"
drop policy if exists "Org admins view org tickets" on public."support_tickets";
create policy "Org admins view org tickets" on public."support_tickets"
  as permissive for select
  to public
  using ((public.has_org_role(organization_id, ARRAY['admin'::text, 'owner'::text, 'super_admin'::text])));

-- public.trend_analysis."View org trends"
drop policy if exists "View org trends" on public."trend_analysis";
create policy "View org trends" on public."trend_analysis"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.usage_metrics."Users can view their organization's usage"
drop policy if exists "Users can view their organization's usage" on public."usage_metrics";
create policy "Users can view their organization's usage" on public."usage_metrics"
  as permissive for select
  to public
  using ((public.is_org_member(organization_id)));

-- public.user_profiles."Org members view profiles"
drop policy if exists "Org members view profiles" on public."user_profiles";
create policy "Org members view profiles" on public."user_profiles"
  as permissive for select
  to public
  using ((public.is_org_member(org_id)));

-- storage.objects."Admins View Proofs"
drop policy if exists "Admins View Proofs" on storage."objects";
create policy "Admins View Proofs" on storage."objects"
  as permissive for select
  to public
  using (((bucket_id = 'bank-transfer-proofs'::text) AND ((auth.role() = 'service_role'::text) OR (public.has_any_org_role(ARRAY['admin'::text, 'owner'::text])))));


-- ----------------------------------------------------------------------------
-- 4. Function rewrites off the legacy tables.
-- ----------------------------------------------------------------------------
create or replace function public.get_my_organization_id()
returns uuid
language plpgsql security definer
set search_path to 'public'
as $$
declare org_id uuid;
begin
  org_id := public.my_org_id();
  if org_id is null then
    raise exception 'User not found in any organization';
  end if;
  return org_id;
end;
$$;

create or replace function public.get_my_organization_role()
returns text
language plpgsql security definer
set search_path to 'public'
as $$
declare v_role text;
begin
  select om.role into v_role
  from public.organization_members om
  where om.user_id = auth.uid()
    and coalesce(lower(om.status), 'active') = 'active'
  order by om.joined_at nulls last, om.created_at
  limit 1;
  return v_role;
end;
$$;

create or replace function public.get_users_for_organization(org_id uuid)
returns table(user_id uuid, email text, modules text[], role text,
              user_created_at timestamptz, user_last_sign_in_at timestamptz)
language plpgsql security definer
set search_path to 'public'
as $$
begin
  return query
  select
    u.id,
    u.email::text,
    coalesce((select array_agg(distinct oa.module_id)
                from public.organization_apps oa
               where oa.organization_id = get_users_for_organization.org_id
                 and oa.module_id is not null), array[]::text[]),
    om.role::text,
    u.created_at,
    u.last_sign_in_at
  from public.organization_members om
  join auth.users u on om.user_id = u.id
  where om.organization_id = get_users_for_organization.org_id;
end;
$$;

-- check_hse_access: the previous body read organizations.modules /
-- is_hse_only / hse_enabled — columns renamed *_legacy in the organizations
-- renovation — so its non-super-admin path has been erroring at runtime.
-- Rewritten onto organization_members + the modern entitlement store
-- (purchased_modules), preserving the original tier intent (premium >
-- free_vip when multiple modules > free_basic; access always granted while
-- HSE is a free platform).
create or replace function public.check_hse_access(p_user_id uuid)
returns jsonb
language plpgsql security definer
set search_path to 'public'
as $$
declare
  v_org_id uuid;
  v_access_level text;
  v_is_hse_only boolean;
  v_module_count integer;
  v_has_premium boolean;
begin
  if public.is_super_admin() then
    return jsonb_build_object(
      'access_level', 'premium', 'has_hse_access', true,
      'email_limit', -1, 'image_limit', -1, 'video_limit', -1,
      'is_hse_only', false);
  end if;

  select om.organization_id into v_org_id
  from public.organization_members om
  where om.user_id = p_user_id
    and coalesce(lower(om.status), 'active') = 'active'
  limit 1;

  if v_org_id is null then
    return jsonb_build_object('access_level', 'none', 'has_hse_access', false);
  end if;

  select coalesce(o.is_hse_only_legacy, false) into v_is_hse_only
  from public.organizations o where o.id = v_org_id;

  select count(distinct pm.module_id),
         bool_or(pm.module_id ilike 'hse%' and pm.module_id <> 'hse_free')
    into v_module_count, v_has_premium
  from public.purchased_modules pm
  where pm.organization_id = v_org_id
    and pm.status = 'active'
    and (pm.expiry_date is null or pm.expiry_date > now());

  v_access_level := 'free_basic';
  if coalesce(v_has_premium, false) then
    v_access_level := 'premium';
  elsif coalesce(v_module_count, 0) > 1 then
    v_access_level := 'free_vip';
  end if;

  return jsonb_build_object(
    'access_level', v_access_level,
    'has_hse_access', true,
    'email_limit', case when v_access_level = 'premium' then -1 else 25 end,
    'image_limit', case when v_access_level = 'premium' then -1 else 5 end,
    'video_limit', case when v_access_level = 'premium' then -1 else 0 end,
    'is_hse_only', coalesce(v_is_hse_only, false));
end;
$$;

create or replace function public.enable_hse_for_organization(p_user_id uuid)
returns void
language plpgsql security definer
set search_path to 'public'
as $$
declare
  v_org_id uuid;
  v_role text;
begin
  select om.organization_id, om.role into v_org_id, v_role
  from public.organization_members om
  where om.user_id = p_user_id
    and coalesce(lower(om.status), 'active') = 'active'
  limit 1;

  if v_org_id is null then
    raise exception 'User does not belong to an organization';
  end if;

  if v_role not in ('owner', 'admin', 'org_admin', 'super_admin') then
    raise exception 'Only organization admins can enable HSE';
  end if;

  -- Previous body updated organizations.hse_enabled / subscribed_modules /
  -- modules — columns renamed *_legacy in the organizations renovation, so it
  -- has been erroring at runtime. Modern provisioning mirrors
  -- handle_new_user: hse_status flag + organization_apps + purchased_modules.
  update public.organizations set hse_status = 'ACTIVE' where id = v_org_id;

  insert into public.organization_apps
    (organization_id, app_id, module_id, seats_allocated, seats_used, status, created_at)
  select v_org_id, 'hse', 'hse_free', 999, 0, 'ACTIVE', now()
  where not exists (
    select 1 from public.organization_apps
    where organization_id = v_org_id and app_id = 'hse' and module_id = 'hse_free');

  insert into public.purchased_modules
    (organization_id, module_id, module_name, status, subscription_status,
     purchase_date, seats_allocated, auto_renew)
  select v_org_id, 'hse_free', 'HSE Free Tier', 'active', 'active', now(), 999, false
  where not exists (
    select 1 from public.purchased_modules
    where organization_id = v_org_id and module_id = 'hse_free');

  update public.users
  set subscribed_modules = (
        select array_agg(distinct x)
        from unnest(array_append(coalesce(subscribed_modules, array[]::text[]), 'hse_free')) t(x))
  where organization_id = v_org_id;

  insert into public.app_activity_log (user_id, app_name, action, timestamp)
  values (p_user_id, 'suite', 'enable_hse_free', now());
end;
$$;

create or replace function public.add_user_to_organization(p_user_id uuid, p_org_id uuid, p_role text)
returns void
language plpgsql security definer
set search_path to 'public'
as $$
declare
  v_email text;
  v_name text;
begin
  if exists (select 1 from public.organization_members
             where organization_id = p_org_id and user_id = p_user_id) then
    return;
  end if;

  select au.email, coalesce(au.raw_user_meta_data->>'full_name', au.email)
    into v_email, v_name
  from auth.users au where au.id = p_user_id;

  if v_email is null then
    raise exception 'add_user_to_organization: user % not found', p_user_id;
  end if;

  insert into public.organization_members
    (organization_id, user_id, full_name, email, role, status, joined_at,
     created_at, updated_at)
  values (p_org_id, p_user_id, v_name, v_email, coalesce(p_role, 'member'),
          'active', now(), now(), now())
  on conflict (organization_id, email)
  do update set user_id = excluded.user_id,
                role = excluded.role,
                status = 'active',
                joined_at = coalesce(public.organization_members.joined_at, now()),
                updated_at = now();
end;
$$;

create or replace function public.handle_new_super_admin()
returns trigger
language plpgsql security definer
set search_path to 'public'
as $$
begin
  if new.email = any(array['info@petrolord.com','ayoasaolu@gmail.com','ayodejiasaolu1@gmail.com']) then
    update public.organization_members
    set role = 'super_admin', updated_at = now()
    where user_id = new.id;
  end if;
  return new;
end;
$$;

create or replace function hse.has_org_access(org_id uuid)
returns boolean
language sql security definer
set search_path to 'public'
as $$
  select public.is_org_member(has_org_access.org_id) or public.is_super_admin();
$$;

create or replace function public.delete_organization(org_id_to_delete uuid)
returns void
language plpgsql security definer
set search_path to 'public'
as $$
begin
  if not is_super_admin() then
    raise exception 'Only Super Admins can delete organizations.';
  end if;

  delete from public.transactions where organization_id = org_id_to_delete;
  delete from public.invoices where organization_id = org_id_to_delete;
  delete from public.subscriptions where organization_id = org_id_to_delete;
  delete from public.organization_members where organization_id = org_id_to_delete;
  delete from public.organizations where id = org_id_to_delete;
end;
$$;

create or replace function public.assign_app_seat(p_organization_id uuid, p_app_id text, p_user_id uuid)
returns jsonb
language plpgsql security definer
set search_path to 'public', 'auth'
as $$
declare
  v_caller       uuid := auth.uid();
  v_is_admin     boolean;
  v_app_active   boolean;
  v_cap          integer;
  v_used         integer;
  v_next         integer;
begin
  -- 1. Authorize caller (server-side call has no JWT -> auth.uid() null -> allow).
  v_is_admin :=
       v_caller is null
    or exists (select 1 from public.users u
                where u.id = v_caller and u.is_super_admin is true)
    or exists (select 1 from public.organization_members om
                where om.user_id = v_caller and om.organization_id = p_organization_id
                  and coalesce(lower(om.status),'active') = 'active'
                  and om.role = any (array['owner','admin','org_admin','super_admin']));

  if not v_is_admin then
    return jsonb_build_object('status','error','reason','not_authorized');
  end if;

  -- 2. App must be purchased & active for the org; read its cap (NULL = unlimited).
  select true, pm.seats_allocated
    into v_app_active, v_cap
    from public.purchased_modules pm
   where pm.organization_id = p_organization_id
     and pm.app_id = p_app_id
     and pm.status = 'active'
   order by pm.seats_allocated desc nulls first
   limit 1;

  if not coalesce(v_app_active, false) then
    return jsonb_build_object('status','error','reason','app_not_purchased');
  end if;

  -- 3. Target must be a member of the org.
  if not exists (
        select 1 from public.organization_members
         where organization_id = p_organization_id and user_id = p_user_id
        union all
        select 1 from public.users
         where organization_id = p_organization_id and id = p_user_id
  ) then
    return jsonb_build_object('status','error','reason','user_not_member');
  end if;

  -- 4. Idempotent: already assigned -> success no-op.
  if exists (select 1 from public.app_seat_assignments
              where organization_id = p_organization_id and app_id = p_app_id and user_id = p_user_id) then
    return jsonb_build_object('status','success','already_assigned',true);
  end if;

  -- 5. Cap check (NULL cap = unlimited).
  select count(*) into v_used
    from public.app_seat_assignments
   where organization_id = p_organization_id and app_id = p_app_id;

  if v_cap is not null and v_used >= v_cap then
    return jsonb_build_object('status','error','reason','seat_limit_reached',
                              'allocated', v_cap, 'used', v_used);
  end if;

  -- 6. Assign: next seat number = max+1.
  select coalesce(max(seat_number),0) + 1 into v_next
    from public.app_seat_assignments
   where organization_id = p_organization_id and app_id = p_app_id;

  insert into public.app_seat_assignments
        (organization_id, app_id, user_id, seat_number, assigned_by, is_admin_seat, created_at, updated_at)
  values (p_organization_id, p_app_id, p_user_id, v_next, v_caller, false, now(), now());

  return jsonb_build_object('status','success','seat_number',v_next,
                            'allocated', v_cap, 'used', v_used + 1);
end;
$$;

create or replace function public.unassign_app_seat(p_organization_id uuid, p_app_id text, p_user_id uuid)
returns jsonb
language plpgsql security definer
set search_path to 'public', 'auth'
as $$
declare
  v_caller   uuid := auth.uid();
  v_is_admin boolean;
  v_removed  integer;
begin
  v_is_admin :=
       v_caller is null
    or exists (select 1 from public.users u
                where u.id = v_caller and u.is_super_admin is true)
    or exists (select 1 from public.organization_members om
                where om.user_id = v_caller and om.organization_id = p_organization_id
                  and coalesce(lower(om.status),'active') = 'active'
                  and om.role = any (array['owner','admin','org_admin','super_admin']));

  if not v_is_admin then
    return jsonb_build_object('status','error','reason','not_authorized');
  end if;

  delete from public.app_seat_assignments
   where organization_id = p_organization_id and app_id = p_app_id and user_id = p_user_id;
  get diagnostics v_removed = row_count;

  return jsonb_build_object('status','success','removed', v_removed);
end;
$$;

create or replace function public.admin_purge_orphan_users(p_dry_run boolean default true, p_inactivity_days integer default 60)
returns jsonb
language plpgsql security definer
set search_path to 'public', 'auth'
as $$
declare
  v_protected_emails text[] := array[
    'info@petrolord.com',
    'ayoasaolu@gmail.com',
    'ayodejiasaolu1@gmail.com',
    'support@petrolord.com',
    'talent@techtainmentcamp.com'
  ];
  v_cutoff    timestamptz := now() - make_interval(days => p_inactivity_days);
  v_fk        record;
  v_pass      integer := 0;
  v_progress  boolean;
  v_cnt       bigint;
  v_remaining bigint;
  v_report    jsonb;
begin
  -- 1. Protected users: super-admins + explicit preserve list (same as org purge).
  create temp table _protected_users on commit drop as
    select u.id
      from auth.users u
     where lower(u.email) = any (select lower(e) from unnest(v_protected_emails) e)
        or coalesce((u.raw_user_meta_data->>'is_super_admin')::boolean, false) = true
    union
    select pu.id from public.users pu where pu.is_super_admin is true
    union
    select om.user_id from public.organization_members om
     where om.role = 'super_admin' and om.user_id is not null;

  -- 2. Every user that belongs to ANY org (canonical membership + users mirror).
  create temp table _members on commit drop as
    select user_id from public.organization_members where user_id is not null
    union
    select id from public.users where organization_id is not null;

  -- 3. Orphan candidates: org-less, not protected, inactive (or never signed in).
  create temp table _orphans on commit drop as
    select u.id as user_id, u.email, u.last_sign_in_at, u.created_at
      from auth.users u
     where not exists (select 1 from _members m where m.user_id = u.id)
       and u.id not in (select id from _protected_users)
       and (u.last_sign_in_at is null or u.last_sign_in_at < v_cutoff);

  -- 4. Single-column public FK graph (child -> parent) for the orphan sweep.
  create temp table _fk on commit drop as
    select tc.table_schema  as child_schema,  tc.table_name  as child_tbl,  kcu.column_name as child_col,
           ccu.table_schema as parent_schema, ccu.table_name as parent_tbl, ccu.column_name as parent_col
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name = tc.constraint_name and kcu.constraint_schema = tc.constraint_schema
      join information_schema.constraint_column_usage ccu
        on ccu.constraint_name = tc.constraint_name and ccu.constraint_schema = tc.constraint_schema
     where tc.constraint_type = 'FOREIGN KEY'
       and tc.table_schema = 'public'
       and ccu.table_schema = 'public'
       and tc.constraint_name in (
             select constraint_name
               from information_schema.key_column_usage
              where constraint_schema = 'public'
              group by constraint_name
             having count(*) = 1
           );

  -- 5. EXECUTION (only when p_dry_run = false).
  if not p_dry_run then
    set local session_replication_role = 'replica';

    delete from public.users where id in (select user_id from _orphans);

    v_pass := 0;
    loop
      v_pass := v_pass + 1;
      v_progress := false;
      for v_fk in select * from _fk loop
        execute format(
          'delete from %1$I.%2$I c
             where c.%3$I is not null
               and not exists (select 1 from %4$I.%5$I p where p.%6$I = c.%3$I)',
          v_fk.child_schema, v_fk.child_tbl, v_fk.child_col,
          v_fk.parent_schema, v_fk.parent_tbl, v_fk.parent_col
        );
        get diagnostics v_cnt = row_count;
        if v_cnt > 0 then v_progress := true; end if;
      end loop;
      exit when v_progress = false;
      exit when v_pass >= 50;
    end loop;

    set local session_replication_role = 'origin';

    select count(*) into v_remaining
      from public.users where id in (select user_id from _orphans);
    if v_remaining > 0 then
      raise exception
        'Orphan purge incomplete: % public.users row(s) survived. Rolling back.', v_remaining;
    end if;
  end if;

  -- 6. Report (same shape in dry-run and execution mode).
  select jsonb_build_object(
    'dry_run', p_dry_run,
    'inactivity_days', p_inactivity_days,
    'cutoff', v_cutoff,
    'summary', jsonb_build_object(
      'orphan_user_count', (select count(*) from _orphans)
    ),
    'auth_users_to_delete', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', o.user_id,
        'email', o.email,
        'last_sign_in_at', o.last_sign_in_at,
        'created_at', o.created_at
      ) order by o.email)
      from _orphans o
    ), '[]'::jsonb)
  ) into v_report;

  return v_report;
end;
$$;

-- admin_purge_test_orgs: same body as before with the legacy-table unions
-- removed from _protected_users and _members (sections 1 and 2); everything
-- else is unchanged.
create or replace function public.admin_purge_test_orgs(p_dry_run boolean default true, p_inactivity_days integer default 60)
returns jsonb
language plpgsql security definer
set search_path to 'public', 'auth'
as $$
declare
  v_protected_emails text[] := array[
    'info@petrolord.com',
    'ayoasaolu@gmail.com',
    'ayodejiasaolu1@gmail.com',
    'support@petrolord.com',
    'talent@techtainmentcamp.com'
  ];
  v_cutoff       timestamptz := now() - make_interval(days => p_inactivity_days);
  v_tbl          record;
  v_fk           record;
  v_pass         integer := 0;
  v_progress     boolean;
  v_cnt          bigint;
  v_remaining    bigint;
  v_report       jsonb;
begin
  create temp table _protected_users on commit drop as
    select u.id
      from auth.users u
     where lower(u.email) = any (select lower(e) from unnest(v_protected_emails) e)
        or coalesce((u.raw_user_meta_data->>'is_super_admin')::boolean, false) = true
    union
    select pu.id from public.users pu where pu.is_super_admin is true
    union
    select om.user_id from public.organization_members om
     where om.role = 'super_admin' and om.user_id is not null;

  create temp table _members on commit drop as
    select organization_id as org_id, user_id from public.organization_members where user_id is not null
    union
    select organization_id, id from public.users where organization_id is not null;

  create temp table _org_stats on commit drop as
    select o.id   as org_id,
           o.name,
           o.organization_type,
           count(distinct m.user_id)               as member_count,
           max(au.last_sign_in_at)                 as last_sign_in,
           bool_or(p.id is not null)               as has_protected_member
      from public.organizations o
      left join _members m         on m.org_id = o.id
      left join auth.users au      on au.id = m.user_id
      left join _protected_users p on p.id = m.user_id
     group by o.id, o.name, o.organization_type;

  create temp table _candidates on commit drop as
    select org_id
      from _org_stats
     where organization_type <> 'internal'
       and has_protected_member = false
       and (last_sign_in is null or last_sign_in < v_cutoff);

  create temp table _org_tables on commit drop as
    select distinct t.table_schema, t.table_name, x.column_name
      from (
            select c.table_schema, c.table_name, c.column_name
              from information_schema.columns c
             where c.table_schema = 'public'
               and c.column_name in ('organization_id', 'org_id')
            union
            select tc.table_schema, tc.table_name, kcu.column_name
              from information_schema.table_constraints tc
              join information_schema.key_column_usage kcu
                on kcu.constraint_name = tc.constraint_name
               and kcu.constraint_schema = tc.constraint_schema
              join information_schema.constraint_column_usage ccu
                on ccu.constraint_name = tc.constraint_name
               and ccu.constraint_schema = tc.constraint_schema
             where tc.constraint_type = 'FOREIGN KEY'
               and ccu.table_schema = 'public'
               and ccu.table_name = 'organizations'
           ) x
      join information_schema.tables t
        on t.table_schema = x.table_schema
       and t.table_name = x.table_name
       and t.table_type = 'BASE TABLE'
     where x.table_name <> 'organizations';

  create temp table _fk on commit drop as
    select tc.table_schema  as child_schema,  tc.table_name  as child_tbl,  kcu.column_name as child_col,
           ccu.table_schema as parent_schema, ccu.table_name as parent_tbl, ccu.column_name as parent_col
      from information_schema.table_constraints tc
      join information_schema.key_column_usage kcu
        on kcu.constraint_name = tc.constraint_name and kcu.constraint_schema = tc.constraint_schema
      join information_schema.constraint_column_usage ccu
        on ccu.constraint_name = tc.constraint_name and ccu.constraint_schema = tc.constraint_schema
     where tc.constraint_type = 'FOREIGN KEY'
       and tc.table_schema = 'public'
       and ccu.table_schema = 'public'
       and tc.constraint_name in (
             select constraint_name
               from information_schema.key_column_usage
              where constraint_schema = 'public'
              group by constraint_name
             having count(*) = 1
           );

  create temp table _affected (org_id uuid, table_name text, column_name text, rows bigint)
    on commit drop;

  for v_tbl in select table_schema, table_name, column_name from _org_tables loop
    execute format(
      'insert into _affected (org_id, table_name, column_name, rows)
         select %1$I, %2$L, %3$L, count(*)
           from %4$I.%2$I
          where %1$I in (select org_id from _candidates)
          group by %1$I',
      v_tbl.column_name, v_tbl.table_name, v_tbl.column_name, v_tbl.table_schema
    );
  end loop;

  create temp table _auth_to_delete on commit drop as
    select distinct m.user_id
      from _members m
     where m.org_id in (select org_id from _candidates)
       and m.user_id is not null
       and m.user_id not in (select id from _protected_users)
       and not exists (
             select 1 from _members m2
              where m2.user_id = m.user_id
                and m2.org_id not in (select org_id from _candidates)
           );

  if not p_dry_run then
    set local session_replication_role = 'replica';

    for v_tbl in select table_schema, table_name, column_name from _org_tables loop
      execute format(
        'delete from %1$I.%2$I where %3$I in (select org_id from _candidates)',
        v_tbl.table_schema, v_tbl.table_name, v_tbl.column_name
      );
    end loop;

    v_pass := 0;
    loop
      v_pass := v_pass + 1;
      v_progress := false;

      for v_fk in select * from _fk loop
        execute format(
          'delete from %1$I.%2$I c
             where c.%3$I is not null
               and not exists (select 1 from %4$I.%5$I p where p.%6$I = c.%3$I)',
          v_fk.child_schema, v_fk.child_tbl, v_fk.child_col,
          v_fk.parent_schema, v_fk.parent_tbl, v_fk.parent_col
        );
        get diagnostics v_cnt = row_count;
        if v_cnt > 0 then
          v_progress := true;
        end if;
      end loop;

      exit when v_progress = false;
      exit when v_pass >= 50;
    end loop;

    delete from public.users where id in (select user_id from _auth_to_delete);

    delete from public.organizations where id in (select org_id from _candidates);

    set local session_replication_role = 'origin';

    for v_tbl in select table_schema, table_name, column_name from _org_tables loop
      execute format(
        'select count(*) from %1$I.%2$I where %3$I in (select org_id from _candidates)',
        v_tbl.table_schema, v_tbl.table_name, v_tbl.column_name
      ) into v_remaining;

      if v_remaining > 0 then
        raise exception
          'Purge incomplete: % row(s) remain in %.% (column %). '
          'Rolling back — no changes committed.',
          v_remaining, v_tbl.table_schema, v_tbl.table_name, v_tbl.column_name;
      end if;
    end loop;
  end if;

  select jsonb_build_object(
    'dry_run', p_dry_run,
    'inactivity_days', p_inactivity_days,
    'cutoff', v_cutoff,
    'summary', jsonb_build_object(
      'candidate_org_count', (select count(*) from _candidates),
      'total_dependent_rows', coalesce((select sum(rows) from _affected), 0),
      'auth_users_to_delete', (select count(*) from _auth_to_delete)
    ),
    'candidate_orgs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'org_id', s.org_id,
        'name', s.name,
        'organization_type', s.organization_type,
        'member_count', s.member_count,
        'last_sign_in', s.last_sign_in,
        'dependent_rows', coalesce((select sum(a.rows) from _affected a where a.org_id = s.org_id), 0),
        'members', coalesce((
          select jsonb_agg(jsonb_build_object(
            'user_id', m.user_id,
            'email', au.email,
            'last_sign_in_at', au.last_sign_in_at
          ) order by au.email)
          from _members m
          join auth.users au on au.id = m.user_id
          where m.org_id = s.org_id
        ), '[]'::jsonb)
      ) order by s.name)
      from _org_stats s
      where s.org_id in (select org_id from _candidates)
    ), '[]'::jsonb),
    'tables_affected', coalesce((
      select jsonb_agg(jsonb_build_object('table', table_name, 'column', column_name, 'rows', total)
                       order by total desc)
      from (
        select table_name, column_name, sum(rows) as total
          from _affected
         group by table_name, column_name
        having sum(rows) > 0
      ) t
    ), '[]'::jsonb),
    'auth_users_to_delete', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', d.user_id, 'email', au.email, 'last_sign_in_at', au.last_sign_in_at
      ) order by au.email)
      from _auth_to_delete d
      join auth.users au on au.id = d.user_id
    ), '[]'::jsonb),
    'excluded_orgs', coalesce((
      select jsonb_agg(jsonb_build_object(
        'org_id', s.org_id,
        'name', s.name,
        'reason', case
                    when s.organization_type = 'internal' then 'internal org'
                    when s.has_protected_member then 'has protected/super-admin member'
                    else 'active within cutoff'
                  end)
        order by s.name)
      from _org_stats s
      where s.org_id not in (select org_id from _candidates)
    ), '[]'::jsonb)
  ) into v_report;

  return v_report;
end;
$$;

-- Dead / one-off functions that only existed for the legacy tables:
--   handle_hse_signup    — orphaned (no trigger references it; the only
--                          auth.users trigger is handle_new_user, which
--                          already writes organization_members +
--                          organization_apps) and it inserts into the frozen
--                          organization_users, so it could never run anyway.
--   migrate_petrolord_users / migrate_suite_users_to_hse — one-shot legacy
--                          data fixers for organization_users.
drop function if exists public.handle_hse_signup();
drop function if exists public.migrate_petrolord_users();
drop function if exists public.migrate_suite_users_to_hse();

-- ----------------------------------------------------------------------------
-- 5. Drop the stragglers. Policies ON these tables (and the deprecation
--    triggers) go with them. Plain DROP (no CASCADE) so any remaining
--    dependency aborts the migration loudly instead of silently dropping
--    dependent objects.
-- ----------------------------------------------------------------------------
drop table public.organization_users;
drop table public.org_members;
drop function if exists public.block_organization_users_writes();
drop function if exists public.block_org_members_writes();

-- ----------------------------------------------------------------------------
-- 6. Name-compatible read-only views so the currently-deployed production SPA
--    (which still reads organization_users / org_members directly) keeps
--    working until the next prod upload. security_invoker => the querying
--    user's organization_members RLS applies, matching the legacy tables'
--    own-row/own-org visibility. Views with computed columns are not
--    auto-updatable, so legacy writes keep failing — same as under the old
--    deprecation triggers. DROP these in a follow-up migration once the
--    consolidated frontend build is live in production.
-- ----------------------------------------------------------------------------
create view public.organization_users
with (security_invoker = true) as
select
  om.id,
  om.organization_id,
  om.user_id,
  coalesce((select array_agg(distinct oa.module_id)
              from public.organization_apps oa
             where oa.organization_id = om.organization_id
               and oa.module_id is not null), array[]::text[]) as modules,
  om.role,
  om.created_at,
  coalesce((select array_agg(distinct oa.app_id)
              from public.organization_apps oa
             where oa.organization_id = om.organization_id
               and oa.app_id is not null), array[]::text[]) as apps,
  om.role as user_role,
  om.status,
  om.updated_at::timestamp as updated_at
from public.organization_members om;

comment on view public.organization_users is
  'COMPATIBILITY VIEW (membership consolidation 20260713300000): read-only '
  'projection of organization_members for the pre-consolidation production '
  'SPA. Do not use in new code — query organization_members / helpers. '
  'Scheduled to be dropped after the next production upload.';

create view public.org_members
with (security_invoker = true) as
select
  om.id,
  om.organization_id as org_id,
  om.user_id,
  om.role,
  om.invited_at,
  om.joined_at,
  null::uuid as invited_by
from public.organization_members om;

comment on view public.org_members is
  'COMPATIBILITY VIEW (membership consolidation 20260713300000): read-only '
  'projection of organization_members. Do not use in new code. Scheduled to '
  'be dropped after the next production upload.';

-- Supabase default privileges auto-grant full DML on new objects, and the
-- simple columns of these views are auto-updatable — force them read-only.
revoke all on public.organization_users from anon, authenticated, service_role;
revoke all on public.org_members from anon, authenticated, service_role;
grant select on public.organization_users to anon, authenticated, service_role;
grant select on public.org_members to anon, authenticated, service_role;

comment on table public.organization_members is
  'THE canonical membership table (consolidation 20260713300000). Entitlements '
  'live in organization_apps / purchased_modules; RLS must use is_org_member/'
  'has_org_role/has_any_org_role/my_org_id/is_org_admin_of, never this table '
  'directly.';

commit;
