#!/usr/bin/env python3
"""Independent oracle for the Economics capital portfolio optimizer
(engines/economics/portfolio.js). Emits committed goldens to
test-data/economics/goldens/portfolio_cases.json.

INDEPENDENCE DISCIPLINE. This file is written from the METHOD STATEMENTS the
engine documents (the ProspectRiskEngine risking convention, the 0/1
knapsack, the normal approximation with an average pairwise correlation)
and NOT by transcribing the JavaScript:

  risked EMV        EMV = pos * npv_p50 minus (1 minus pos) * fail_cost, pos
                    the chance of success in [0, 1] (default 1; values outside
                    the domain are clamped to it; a non-numeric pos is the
                    default), fail_cost the expected loss on failure, >= 0
                    (default 0; a negative entry is 0). A missing NPV is 0.

  success spread    the success-case standard deviation is the explicit
                    npv_stddev when it is a positive number; otherwise
                    (P10 minus P90) / 2.5631 when P10 > P90, 2.5631 being
                    twice the 90 percent normal quantile; otherwise 0.

  mixture moments   with probability pos the project is normal(npv_p50, sd)
                    and otherwise a point mass at minus fail_cost, so
                    mean = pos mu minus (1 minus pos) c and
                    E[X^2] = pos (sd^2 + mu^2) + (1 minus pos) c^2,
                    variance = E[X^2] minus mean^2. Exact.

  portfolio risk    under one average pairwise correlation rho (clamped to
                    [0, 1], a non-numeric entry is 0):
                    Var = sum var_i + rho ((sum sd_i)^2 minus sum var_i),
                    mean = sum mean_i, P(NPV < 0) = Phi(minus mean / sd)
                    through math.erf (exact to double precision; the engine
                    uses the Abramowitz and Stegun 7.1.26 erf, 1.5e-7 max
                    absolute error, which is the gate tolerance on probLoss),
                    P90 = mean minus 1.2816 sd, P10 = mean + 1.2816 sd, and
                    the independent spread sqrt(sum var_i) is reported
                    beside the correlated one. With sd = 0 the loss
                    probability is 1 when the mean is negative and 0
                    otherwise.

  knapsack          the 0/1 knapsack maximising summed risked EMV under the
                    capex limit is solved by BRUTE FORCE over every subset of
                    the positive-EMV projects (2^n subsets, n <= 16), where
                    the engine runs a dynamic programme. Projects with EMV
                    <= 0 are never forced in (leaving capital unspent is
                    always allowed), so they are simply not candidates. A
                    negative limit is 0. The golden lists EVERY subset that
                    attains the optimum, so a tie is a tie and not a hidden
                    convention.

  quantisation      the engine's documented rule: when the limit and every
                    candidate capex are integers and the limit is at most
                    5000, the grid is 1 $MM and the knapsack is exact;
                    otherwise the grid is limit / 2000 per cell, each project
                    weighs max(1, round(capex / cell)) cells (round half up,
                    as JavaScript rounds), a project heavier than the whole
                    grid is skipped, and a set is feasible when its cell
                    weights sum to at most round(limit / cell). The oracle
                    solves BOTH problems by brute force, the EXACT one
                    (sum of actual capex <= limit) and the QUANTISED one the
                    engine actually solves, and the golden carries both with
                    the gap and a flag saying whether quantisation changed
                    the chosen set. A free project (capex 0) weighs one cell
                    on the grid, which the exact problem does not charge:
                    see the freeProject cases and FINDINGS-decision.md.

  frontier          on the quantised grid: for each budget b of cells from 0,
                    best(b) is the largest EMV of a set weighing at most b;
                    the frontier lists every b at which best(b) rises, with
                    the EMV and the ACTUAL capex of the sets attaining it
                    (all of them, since at a tie the engine may report any).
                    best(0) = 0 with the empty set, so every frontier begins
                    at (0, 0).

  arithmetic        EMVs, capex sums, means and variances are exact
                    fractions.Fraction values of the binary inputs the
                    engine receives (Fraction(float) is exact), emitted as
                    full-precision floats. Square roots and the normal CDF
                    are double precision.

  seeded cases      the random project sets are generated by mulberry32
                    (the generator in lib/stats/stats.js) replicated here in
                    uint32 arithmetic (Math.imul as a masked 32-bit product,
                    every step masked to 32 bits, then divided by
                    4294967296). Seeds are stated on each case and the
                    projects themselves are written into the golden, so the
                    gate never needs the generator.

All money is USD millions ($MM), the engine's documented unit; the rawDollars
case feeds dollars deliberately to exercise the quantised grid, and its EMV is
in whatever unit its NPVs were typed in (the engine never converts).

stdlib only. Regenerate (deterministic, byte identical):
    python3 tools/validation/economics/oracle_portfolio.py
"""
import json
import math
import os
from fractions import Fraction as F

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', '..', '..', 'test-data', 'economics',
                                    'goldens', 'portfolio_cases.json'))

Z90 = F(1.2816)
SPREAD_DIVISOR = F(2.5631)


def out(x):
    if isinstance(x, bool) or x is None or isinstance(x, str):
        return x
    if isinstance(x, F):
        return float(x)
    if isinstance(x, (int, float)):
        return x
    if isinstance(x, dict):
        return {k: out(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [out(v) for v in x]
    raise TypeError(type(x))


def num(v):
    """A numeric field as an exact Fraction, or None when it is not a number."""
    if v is None or isinstance(v, bool):
        return None
    if isinstance(v, F):
        return v
    if isinstance(v, (int, float)):
        if isinstance(v, float) and not math.isfinite(v):
            return None
        return F(v)
    return None


# ---------------------------------------------------------------------
# Project-level quantities.
# ---------------------------------------------------------------------

def pos_of(p):
    v = num(p.get('pos', 1))
    if v is None:
        return F(1)
    return min(F(1), max(F(0), v))


def fail_cost_of(p):
    v = num(p.get('fail_cost', 0))
    return max(F(0), v) if v is not None else F(0)


def npv_of(p):
    v = num(p.get('npv_p50', 0))
    return v if v is not None else F(0)


def emv(p):
    pos = pos_of(p)
    return pos * npv_of(p) - (1 - pos) * fail_cost_of(p)


def success_sd(p):
    sd = num(p.get('npv_stddev'))
    if sd is not None and sd > 0:
        return sd
    p10, p90 = num(p.get('npv_p10')), num(p.get('npv_p90'))
    if p10 is not None and p90 is not None and p10 > p90:
        return (p10 - p90) / SPREAD_DIVISOR
    return F(0)


def moments(p):
    pos, c, mu = pos_of(p), fail_cost_of(p), npv_of(p)
    sd = success_sd(p)
    mean = pos * mu - (1 - pos) * c
    second = pos * (sd * sd + mu * mu) + (1 - pos) * c * c
    return mean, max(F(0), second - mean * mean)


def phi(x):
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def rho_of(v):
    r = num(v)
    if r is None:
        return F(0)
    return min(F(1), max(F(0), r))


def risk(selected, correlation=0):
    rho = rho_of(correlation)
    mean = F(0)
    var_sum = F(0)
    sd_sum = 0.0
    for p in selected:
        m, v = moments(p)
        mean += m
        var_sum += v
        sd_sum += math.sqrt(float(v))
    cross = max(0.0, sd_sum * sd_sum - float(var_sum))
    variance = float(var_sum) + float(rho) * cross
    sd = math.sqrt(max(0.0, variance))
    if sd > 0:
        prob_loss = phi(-float(mean) / sd)
    else:
        prob_loss = 1.0 if mean < 0 else 0.0
    return {
        'emv': mean, 'stdDev': sd, 'probLoss': prob_loss,
        'p90': float(mean) - float(Z90) * sd, 'p10': float(mean) + float(Z90) * sd,
        'correlation': rho, 'independentStdDev': math.sqrt(float(var_sum)),
    }


# ---------------------------------------------------------------------
# Knapsack by brute force, exact and on the engine's grid.
# ---------------------------------------------------------------------

def js_round(x):
    """JavaScript Math.round: half rounds toward positive infinity."""
    return math.floor(x + 0.5)


def capex_of(p):
    v = num(p.get('capex', 0))
    return v if v is not None else F(0)


def is_integer(v):
    return v is not None and v.denominator == 1


def grid(limit, candidates):
    all_int = is_integer(limit) and all(is_integer(capex_of(p)) for p in candidates)
    if all_int and limit <= 5000:
        resolution = 1.0
    else:
        resolution = max(1e-9, float(limit) / 2000)
    cells = js_round(float(limit) / resolution)
    return resolution, cells


def subsets(items):
    n = len(items)
    for mask in range(1 << n):
        yield [items[i] for i in range(n) if mask >> i & 1]


def set_record(sel, rho):
    ids = [p['id'] for p in sel]
    return {
        'ids': ids,
        'capex': sum((capex_of(p) for p in sel), F(0)),
        'emv': sum((emv(p) for p in sel), F(0)),
        'npvSuccess': sum((npv_of(p) for p in sel), F(0)),
        'risk': risk(sel, rho),
    }


def optimize(projects, capex_limit, correlation=0):
    lim = num(capex_limit)
    limit = max(F(0), lim) if lim is not None else F(0)
    # Only projects with a strictly positive risked EMV can ever improve a
    # maximum, so they are the only candidates; the engine's own candidate
    # filter (capex > 0 or EMV > 0) is wider but never changes an optimum.
    positive = [p for p in projects if emv(p) > 0]
    grid_candidates = [p for p in projects if capex_of(p) > 0 or emv(p) > 0]
    resolution, cells = grid(limit, grid_candidates)
    weights = {p['id']: max(1, js_round(float(capex_of(p)) / resolution)) for p in positive}
    on_grid = [p for p in positive if weights[p['id']] <= cells]

    # Exact problem.
    exact_best = F(0)
    exact_sets = []
    for sel in subsets(positive):
        c = sum((capex_of(p) for p in sel), F(0))
        if c > limit:
            continue
        e = sum((emv(p) for p in sel), F(0))
        if e > exact_best:
            exact_best, exact_sets = e, [sel]
        elif e == exact_best:
            exact_sets.append(sel)

    # Quantised problem and its frontier.
    quant_best = F(0)
    quant_sets = []
    by_weight = {}
    for sel in subsets(on_grid):
        w = sum(weights[p['id']] for p in sel)
        if w > cells:
            continue
        e = sum((emv(p) for p in sel), F(0))
        if e > quant_best:
            quant_best, quant_sets = e, [sel]
        elif e == quant_best:
            quant_sets.append(sel)
        by_weight.setdefault(w, []).append((e, sel))
    frontier = []
    last = F(-1)
    for w in range(cells + 1):
        here = by_weight.get(w, [])
        best_here = max((e for e, _ in here), default=F(-1))
        if best_here > last:
            caps = sorted({sum((capex_of(p) for p in sel), F(0)) for e, sel in here if e == best_here})
            frontier.append({'weight': w, 'emv': best_here, 'capexCandidates': caps})
            last = best_here

    exact_recs = sorted((set_record(s, correlation) for s in exact_sets), key=lambda r: r['ids'])
    quant_recs = sorted((set_record(s, correlation) for s in quant_sets), key=lambda r: r['ids'])
    changed = {tuple(r['ids']) for r in exact_recs} != {tuple(r['ids']) for r in quant_recs}
    return {
        'limit': limit, 'resolution': resolution, 'cells': cells,
        'weights': {p['id']: weights[p['id']] for p in positive},
        'exact': {'optimalEmv': exact_best, 'optimalSets': exact_recs},
        'quantized': {'optimalEmv': quant_best, 'optimalSets': quant_recs, 'frontier': frontier},
        'quantizationGap': quant_best - exact_best,
        'setChanged': changed,
    }


# ---------------------------------------------------------------------
# Seeded project sets.
# ---------------------------------------------------------------------

def mulberry32(seed):
    a = seed & 0xFFFFFFFF

    def imul(x, y):
        return (x * y) & 0xFFFFFFFF

    def rng():
        nonlocal a
        a = (a + 0x6D2B79F5) & 0xFFFFFFFF
        t = a
        t = imul(t ^ (t >> 15), t | 1)
        t = (t ^ ((t + imul(t ^ (t >> 7), t | 61)) & 0xFFFFFFFF)) & 0xFFFFFFFF
        return ((t ^ (t >> 14)) & 0xFFFFFFFF) / 4294967296
    return rng


def seeded_projects(seed, n, capex_lo, capex_hi, decimals=0):
    """Projects from mulberry32(seed): capex uniform in [capex_lo, capex_hi]
    at the stated decimals, NPV a multiple of capex, pos in [0.15, 1], a
    fail cost that is a share of capex, and P10 / P90 around the P50."""
    rng = mulberry32(seed)
    ps = []
    scale = 10 ** decimals
    for i in range(n):
        capex = math.floor((capex_lo + rng() * (capex_hi - capex_lo)) * scale + 0.5) / scale
        npv = round(capex * (0.4 + 2.2 * rng()), 1)
        pos = round(0.15 + 0.85 * rng(), 2)
        fail = round(capex * (0.2 + 0.6 * rng()), 1)
        p10 = round(npv * (1.3 + 0.5 * rng()), 1)
        p90 = round(npv * (0.3 + 0.4 * rng()), 1)
        ps.append({'id': 'S%d_%02d' % (seed, i + 1), 'name': 'Seed %d project %d' % (seed, i + 1),
                   'capex': capex, 'npv_p50': npv, 'pos': pos, 'fail_cost': fail,
                   'npv_p10': p10, 'npv_p90': p90})
    return ps


# ---------------------------------------------------------------------
# Cases.
# ---------------------------------------------------------------------

def P(name, capex, npv, **extra):
    d = {'id': name, 'name': name, 'capex': capex, 'npv_p50': npv}
    d.update(extra)
    return d


CLASSIC = [P('A', 100, 60), P('B', 200, 100), P('C', 300, 120), P('D', 150, 90)]
RISK_A = {'npv_p50': 100, 'npv_p10': 160, 'npv_p90': 40, 'pos': 1}
RISK_B = {'npv_p50': 80, 'npv_p10': 130, 'npv_p90': 30, 'pos': 1}


def emv_cases():
    cases = []

    def add(cid, desc, p):
        cases.append({'id': cid, 'description': desc, 'project': p, 'expected': {'emv': emv(p)}})

    add('unrisked', 'Suite: pos and fail_cost absent; EMV is the NPV (250).', P('a', 100, 250))
    add('risked', 'Suite: 0.3 * 300 minus 0.7 * 50 = 55.', P('a', 100, 300, pos=0.3, fail_cost=50))
    add('posAboveOneClamps', 'pos 1.4 is clamped to 1; EMV is the NPV.', P('a', 10, 80, pos=1.4, fail_cost=30))
    add('posBelowZeroClamps', 'pos -0.2 is clamped to 0; EMV is minus the fail cost.', P('a', 10, 80, pos=-0.2, fail_cost=30))
    add('negativeFailCostIsZero', 'A negative fail cost is 0.', P('a', 10, 80, pos=0.5, fail_cost=-30))
    add('missingNpvIsZero', 'No NPV at all; EMV is minus (1 minus pos) times the fail cost.', {'id': 'a', 'capex': 10, 'pos': 0.25, 'fail_cost': 8})
    add('nonNumericPosIsDefault', 'A non-numeric pos is the default 1.', P('a', 10, 80, pos='n/a', fail_cost=30))
    add('posZero', 'pos 0; EMV is exactly minus the fail cost.', P('a', 10, 80, pos=0, fail_cost=30))
    return cases


def sd_cases():
    cases = []

    def add(cid, desc, p):
        cases.append({'id': cid, 'description': desc, 'project': p, 'expected': {'sd': success_sd(p)}})

    add('explicitStddev', 'Suite: npv_stddev 40 wins over the percentiles.', {'npv_stddev': 40, 'npv_p10': 200, 'npv_p90': 50})
    add('percentileFallback', 'Suite: (200 minus 50) / 2.5631.', {'npv_p10': 200, 'npv_p90': 50})
    add('neither', 'Suite: nothing entered; 0.', {})
    add('invertedPercentiles', 'P10 below P90 is not a spread; 0.', {'npv_p10': 50, 'npv_p90': 200})
    add('equalPercentiles', 'P10 equal to P90; 0.', {'npv_p10': 50, 'npv_p90': 50})
    add('zeroStddevFallsBack', 'npv_stddev 0 is not positive, so the percentiles are used.', {'npv_stddev': 0, 'npv_p10': 200, 'npv_p90': 50})
    add('negativeStddevFallsBack', 'A negative npv_stddev is ignored in favour of the percentiles.', {'npv_stddev': -5, 'npv_p10': 120, 'npv_p90': 20})
    return cases


def moments_cases():
    cases = []

    def add(cid, desc, p):
        m, v = moments(p)
        cases.append({'id': cid, 'description': desc, 'project': p, 'expected': {'mean': m, 'variance': v}})

    add('mixture', 'Suite: pos 0.5, success N(100, 20), failure -40: mean 30, variance 5100.', {'npv_p50': 100, 'npv_stddev': 20, 'pos': 0.5, 'fail_cost': 40})
    add('sure', 'Suite: a sure project with no spread has zero variance.', {'npv_p50': 100})
    add('percentileRisked', 'pos 0.6 with P10 / P90 spread and a fail cost.', {'npv_p50': 120, 'npv_p10': 200, 'npv_p90': 60, 'pos': 0.6, 'fail_cost': 35})
    add('failureOnly', 'pos 0: a point mass at minus the fail cost; zero variance.', {'npv_p50': 120, 'npv_stddev': 30, 'pos': 0, 'fail_cost': 35})
    add('binaryNoSpread', 'pos 0.5 with no success spread: variance is the Bernoulli spread ((mu + c)^2 / 4).', {'npv_p50': 60, 'pos': 0.5, 'fail_cost': 20})
    return cases


def risk_cases():
    cases = []

    def add(cid, desc, selected, correlation=0, raw=None):
        cases.append({'id': cid, 'description': desc, 'selected': selected,
                      'correlation': raw if raw is not None else correlation,
                      'expected': risk(selected, correlation)})

    a = {'npv_p50': 100, 'npv_stddev': 20, 'pos': 0.5, 'fail_cost': 40}
    b = {'npv_p50': 50, 'npv_stddev': 10}
    add('suiteIndependent', 'Suite: means 30 + 50 = 80, variances 5100 + 100, P(loss) = Phi(minus 80 / sqrt 5200).', [a, b])
    add('deterministicProfit', 'Suite: a sure profitable project has zero loss probability.', [{'npv_p50': 10}])
    add('deterministicLoss', 'A sure loss with zero spread has loss probability 1.', [{'npv_p50': -10}])
    add('empty', 'No projects: everything 0.', [])
    add('expectedLoss', 'A portfolio whose mean is negative with spread: P(loss) above one half.', [{'npv_p50': 40, 'npv_stddev': 30, 'pos': 0.3, 'fail_cost': 50}, b])
    for r in (0, 0.25, 0.5, 0.6, 0.75, 0.8, 1):
        add('correlation_%s' % str(r).replace('.', 'p'), 'Suite E5 pair (100 / 160 / 40 and 80 / 130 / 30) at rho %s.' % r, [RISK_A, RISK_B], r)
    add('clampAbove', 'Suite: rho 5 is clamped to 1.', [RISK_A, RISK_B], 5)
    add('clampBelow', 'Suite: rho -3 is clamped to 0.', [RISK_A, RISK_B], -3)
    add('nanIsZero', 'Suite: a non-numeric rho is 0 (the gate passes NaN for the string).', [RISK_A, RISK_B], 'NaN', raw='NaN')
    add('singleProject', 'Suite: one project has nothing to correlate with; rho 0.9 changes nothing.', [RISK_A], 0.9)
    add('threeRisked', 'Three risked projects with mixed spreads at rho 0.35.',
        [{'npv_p50': 100, 'npv_stddev': 20, 'pos': 0.5, 'fail_cost': 40},
         {'npv_p50': 120, 'npv_p10': 200, 'npv_p90': 60, 'pos': 0.6, 'fail_cost': 35},
         {'npv_p50': 50, 'npv_stddev': 10}], 0.35)
    return cases


def optimize_cases():
    cases = []

    def add(cid, desc, projects, limit, correlation=0, note=None):
        rec = {'id': cid, 'description': desc, 'projects': projects, 'capexLimit': limit,
               'correlation': correlation, 'expected': optimize(projects, limit, correlation)}
        if note:
            rec['note'] = note
        cases.append(rec)

    add('classic450', 'Suite: A(100, 60) B(200, 100) C(300, 120) D(150, 90) at 450: A + B + D, capex 450, EMV 250.', CLASSIC, 450)
    add('riskedVsSure', 'Suite: X (npv 300, pos 0.2, fail 50: EMV 20) loses to sure Y (50) at the same capex.',
        [P('X', 100, 300, pos=0.2, fail_cost=50), P('Y', 100, 50)], 100)
    add('negativeNeverForced', 'Suite: a negative-EMV project is never taken even with capital to spare.',
        [P('bad', 50, -20), P('good', 50, 30)], 200)
    add('rawDollars', 'Suite: the classic set typed in dollars (capex times 1e6, limit 450e6); the grid quantises to 225000 per cell and the same set wins.',
        [dict(p, capex=p['capex'] * 1e6) for p in CLASSIC], 450e6)
    add('threadedCorrelation_0', 'Suite E5: two projects at limit 20, rho 0.', [P('1', 10, 100, npv_p10=160, npv_p90=40, pos=1), P('2', 10, 80, npv_p10=130, npv_p90=30, pos=1)], 20, 0)
    add('threadedCorrelation_0p7', 'Suite E5: the same at rho 0.7; same set, same EMV, wider spread.', [P('1', 10, 100, npv_p10=160, npv_p90=40, pos=1), P('2', 10, 80, npv_p10=130, npv_p90=30, pos=1)], 20, 0.7)
    add('tieIdenticalProjects', 'Tie: two identical projects and room for one; either set is optimal.',
        [P('twinA', 100, 50), P('twinB', 100, 50)], 100)
    add('tieDifferentComposition', 'Tie: {A} at capex 100 and {B, C} at capex 100 both reach EMV 80.',
        [P('A', 100, 80), P('B', 40, 40), P('C', 60, 40)], 100)
    add('zeroEmvExcluded', 'A project whose risked EMV is exactly 0 (pos 0.5, npv 40, fail 40) is never taken.',
        [P('zero', 30, 40, pos=0.5, fail_cost=40), P('good', 50, 30)], 500)
    add('negativeEmvHugeBudget', 'A negative risked EMV stays out however large the budget.',
        [P('neg', 20, 100, pos=0.1, fail_cost=60), P('good', 50, 30), P('better', 70, 45)], 10000)
    add('limitBelowEveryProject', 'Every project costs more than the limit: the empty portfolio, EMV 0, frontier (0, 0).',
        [P('A', 50, 60), P('B', 80, 100)], 30)
    add('limitZero', 'Limit 0: nothing fits.', CLASSIC, 0)
    add('limitNegative', 'A negative limit is 0.', CLASSIC, -100)
    add('exactFit', 'The optimum uses the whole budget exactly (A + B + D = 450 at limit 450 is already that; here B + C = 500 at 500).',
        [P('A', 100, 60), P('B', 200, 130), P('C', 300, 170), P('D', 150, 90)], 500)
    add('freeProjectZeroLimit', 'A free project (capex 0) with positive EMV at limit 0: the exact problem takes it; the grid charges it one cell it does not have.',
        [P('free', 0, 10)], 0, note='disagreement: see FINDINGS-decision.md, free project on the grid')
    add('freeProjectTightLimit', 'A free project beside A(100, 60) at limit 100: exact takes both (70); the grid weighs the free project one cell and must drop something.',
        [P('free', 0, 10), P('A', 100, 60)], 100, note='disagreement: see FINDINGS-decision.md, free project on the grid')
    add('freeProjectSlack', 'The same free project with one cell of slack (limit 101): both problems take both.',
        [P('free', 0, 10), P('A', 100, 60)], 101)
    add('gridOvershoot', 'Limit 6000 (grid 3 per cell): A(4000) weighs 1333 cells and B(2002) 667, so A + B fits the grid at 2000 cells although its capex is 6002; the exact optimum is A + C at 5995.',
        [P('A', 4000, 500), P('B', 2002, 300), P('C', 1995, 280)], 6000,
        note='disagreement: see FINDINGS-decision.md, grid overshoot; the engine reports a portfolio 2 $MM over the limit')
    add('gridUndershoot', 'Limit 6000 (grid 3 per cell): three projects of 1499 and one of 1502 total 5999 and fit exactly, but each rounds up to 500 or 501 cells (2001 > 2000), so the grid must drop one.',
        [P('W', 1499, 200), P('X', 1499, 210), P('Y', 1499, 220), P('Z', 1502, 230)], 6000,
        note='disagreement: see FINDINGS-decision.md, grid undershoot; the engine leaves a feasible project out')
    add('nonIntegerLimit', 'The classic set at limit 450.5: the grid is 0.22525 per cell and A + B + D still wins.', CLASSIC, 450.5)
    add('mixedRiskedRho0p3', 'Five risked projects with spreads at rho 0.3, exact grid.',
        [P('R1', 120, 200, pos=0.4, fail_cost=60, npv_p10=320, npv_p90=110),
         P('R2', 80, 90, pos=0.9, fail_cost=20, npv_p10=140, npv_p90=50),
         P('R3', 200, 260, pos=0.55, fail_cost=90, npv_stddev=70),
         P('R4', 60, 40, pos=1),
         P('R5', 150, 300, pos=0.25, fail_cost=120, npv_p10=450, npv_p90=180)], 330, 0.3)
    add('seeded6', 'mulberry32 seed 6001: six integer-capex projects, limit 320, exact grid.', seeded_projects(6001, 6, 40, 200), 320)
    add('seeded10decimal', 'mulberry32 seed 1002: ten one-decimal capex projects, limit 500.5, quantised grid of 0.25025.', seeded_projects(1002, 10, 20, 180, 1), 500.5, 0.2)
    add('seeded16large', 'mulberry32 seed 1601: sixteen integer projects with capex 100 to 900, limit 7200 (above 5000, so the grid is 3.6 per cell).', seeded_projects(1601, 16, 100, 900), 7200, 0.15)
    add('seeded16exact', 'mulberry32 seed 1602: sixteen integer projects with capex 10 to 200, limit 900, exact grid.', seeded_projects(1602, 16, 10, 200), 900)
    return cases


def main():
    golden = {
        'description': (
            'Economics capital portfolio goldens: risked EMV, success-case spread, exact success / '
            'failure mixture moments, the normal-approximation portfolio risk summary with an average '
            'pairwise correlation, and the 0/1 knapsack over the capex limit with its efficient frontier. '
            'Independent stdlib oracle (tools/validation/economics/oracle_portfolio.py): the knapsack is '
            'solved by brute force over every subset, both EXACTLY (sum of capex within the limit) and on '
            'the engine\'s documented QUANTISED grid, and every optimize case carries both answers, the '
            'gap between them and whether quantisation changed the chosen set; every optimal set is '
            'listed so ties are explicit; the frontier is on the grid with every capex a tied set could '
            'report. P(loss) is through math.erf, so the gate allows the engine\'s 1.5e-7 Abramowitz and '
            'Stegun error. All money is USD millions ($MM) except rawDollars, which is typed in dollars '
            'on purpose. pos is 0 to 1; correlation is 0 to 1; a correlation given as the string NaN '
            'means the gate passes NaN. Every case in the Suite\'s '
            'src/utils/__tests__/portfolioOptimizer.test.js is here, plus seeded random sets (mulberry32, '
            'seed on the case), ties, a zero-EMV and a negative-EMV project, free projects, and limits '
            'below every project.'
        ),
        'projectEmv': emv_cases(),
        'successStdDev': sd_cases(),
        'projectMoments': moments_cases(),
        'riskMetrics': risk_cases(),
        'optimize': optimize_cases(),
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump(out(golden), f, indent=1, sort_keys=True)
        f.write('\n')
    counts = {k: len(v) for k, v in golden.items() if isinstance(v, list)}
    print('wrote %s: %s (total %d)' % (OUT, counts, sum(counts.values())))
    for c in golden['optimize']:
        e = c['expected']
        print('  %-26s res %-10g cells %5d exact %-12g quant %-12g gap %-10g changed %s sets %d/%d' % (
            c['id'], e['resolution'], e['cells'], float(e['exact']['optimalEmv']),
            float(e['quantized']['optimalEmv']), float(e['quantizationGap']), e['setChanged'],
            len(e['exact']['optimalSets']), len(e['quantized']['optimalSets'])))


if __name__ == '__main__':
    main()
