/**
 * W2.5 horizon-window analytics oracles: interval (A-to-B) statistics
 * against hand-computed truths (the windowStat null/clamp semantics
 * extended to stratal windows), and the isofrequency kernel against the
 * numpy goldens (test-data/seismolord/isofrequency/, generated by the
 * Suite's self-asserting gen_isofrequency.py), plus a brick-store
 * end-to-end pass for both extractors.
 */

import fs from 'fs';
import path from 'path';

import {
  intervalStat, INTERVAL_MODES, bricksForIntervalAttribute,
  extractIntervalAttribute, isofrequencyAt, extractHorizonIsofrequency,
} from '../engines/seismolord/horizonAmplitude';
import { NULL_VALUE } from '../engines/seismolord/manifest';

const GOLDEN = JSON.parse(fs.readFileSync(
  path.join(__dirname, '..', 'test-data', 'seismolord', 'isofrequency', 'isofrequency_golden.json'),
  'utf8',
));

const NULL_F32 = Math.fround(NULL_VALUE);
const NULL_LIM = 1.0e29;
const isNull = (v) => Math.abs(v) > NULL_LIM;
const atOf = (arr) => (s) => Math.fround(arr[s]);

describe('intervalStat', () => {
  const trace = Float32Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
  const at = (s) => trace[s];

  test('A-to-B window is inclusive and order-free', () => {
    // samples 2..5 -> mean 4.5, rms sqrt((9+16+25+36)/4)
    expect(intervalStat(at, 8, 2, 5, 'mean')).toBeCloseTo(4.5, 12);
    expect(intervalStat(at, 8, 5, 2, 'mean')).toBeCloseTo(4.5, 12);
    expect(intervalStat(at, 8, 2, 5, 'rms')).toBeCloseTo(Math.sqrt(86 / 4), 12);
    expect(intervalStat(at, 8, 2, 5, 'max_abs')).toBe(6);
  });

  test('fractional picks round like windowStat; window clamps at trace ends', () => {
    expect(intervalStat(at, 8, 1.6, 5.4, 'mean')).toBeCloseTo(4.5, 12);  // 2..5
    expect(intervalStat(at, 8, -3, 1, 'mean')).toBeCloseTo(1.5, 12);      // 0..1
    expect(intervalStat(at, 8, 6, 99, 'mean')).toBeCloseTo(7.5, 12);      // 6..7
  });

  test('nulls are excluded; all-null and missing picks are null', () => {
    const gappy = Float32Array.from([1, NULL_VALUE, 3, NULL_VALUE]);
    expect(intervalStat(atOf(gappy), 4, 0, 3, 'mean')).toBeCloseTo(2, 6);
    const dead = new Float32Array(4).fill(NULL_VALUE);
    expect(intervalStat(atOf(dead), 4, 0, 3, 'mean')).toBe(NULL_F32);
    expect(intervalStat(at, 8, NaN, 3, 'mean')).toBe(NULL_F32);
  });

  test('coincident picks reduce to the single sample', () => {
    expect(intervalStat(at, 8, 3, 3, 'mean')).toBe(4);
  });
});

describe('isofrequency kernel vs numpy goldens', () => {
  const { dt_us: dtUs, hw } = GOLDEN;
  const dtS = dtUs * 1e-6;

  test('every golden case matches', () => {
    for (const g of GOLDEN.golden) {
      const trace = Float64Array.from(GOLDEN.traces[g.trace]);
      const got = isofrequencyAt((s) => Math.fround(trace[s]), trace.length, g.z, {
        freqHz: g.freq_hz, hw, dtS,
      });
      if (isNull(g.value)) {
        if (!isNull(got)) {
          throw new Error(`${g.trace} z=${g.z} f=${g.freq_hz}: engine ${got}, golden null`);
        }
      } else if (Math.abs(got - g.value) > 1e-5 * Math.max(1, Math.abs(g.value))) {
        throw new Error(`${g.trace} z=${g.z} f=${g.freq_hz}: engine ${got} vs numpy ${g.value}`);
      }
    }
  });

  test('frequency selectivity: 30 Hz cosine reads strongest at 30 Hz', () => {
    const tr = Float64Array.from(GOLDEN.traces.cos30);
    const at = (s) => Math.fround(tr[s]);
    const v = (f) => isofrequencyAt(at, tr.length, 32, { freqHz: f, hw, dtS });
    expect(v(30)).toBeGreaterThan(4 * v(60));
    // the 17-sample Hann mainlobe is ~29 Hz wide, so 15 Hz sees real
    // leakage — the peak still wins, just not by 4x
    expect(v(30)).toBeGreaterThan(v(15));
  });
});

describe('brick-store end-to-end', () => {
  // 5x6 traces, 16 samples, brickSize 4
  const NIL = 5;
  const NXL = 6;
  const NS = 16;
  const B = 4;
  const geom = { nIl: NIL, nXl: NXL, ns: NS, brickSize: B, grid: [2, 2, 4] };
  const value = (il, xl, k) => Math.fround(Math.sin(k * 0.9 + il) + 0.1 * xl);

  const bricks = new Map();
  for (let i = 0; i < 2; i++) {
    for (let j = 0; j < 2; j++) {
      for (let k = 0; k < 4; k++) {
        bricks.set(`${i}-${j}-${k}`, new Float32Array(B * B * B).fill(NULL_VALUE));
      }
    }
  }
  for (let il = 0; il < NIL; il++) {
    for (let xl = 0; xl < NXL; xl++) {
      for (let k = 0; k < NS; k++) {
        bricks.get(`${Math.floor(il / B)}-${Math.floor(xl / B)}-${Math.floor(k / B)}`)[
          ((il % B) * B + (xl % B)) * B + (k % B)] = value(il, xl, k);
      }
    }
  }
  const fetched = [];
  const getBrick = async (i, j, k) => {
    fetched.push(`${i}-${j}-${k}`);
    return bricks.get(`${i}-${j}-${k}`);
  };

  const picksA = new Float32Array(NIL * NXL).fill(3);
  const picksB = new Float32Array(NIL * NXL).fill(9);
  picksB[0] = NULL_VALUE;                    // B missing at one cell

  test('interval extraction matches the per-cell kernel; preflight covers the fetches', async () => {
    fetched.length = 0;
    const out = await extractIntervalAttribute(getBrick, geom, picksA, picksB, { mode: 'rms' });
    for (let il = 0; il < NIL; il++) {
      for (let xl = 0; xl < NXL; xl++) {
        const cell = il * NXL + xl;
        if (cell === 0) {
          expect(out[cell]).toBe(NULL_F32);
          continue;
        }
        let sum = 0;
        for (let s = 3; s <= 9; s++) sum += value(il, xl, s) ** 2;
        expect(out[cell]).toBeCloseTo(Math.sqrt(sum / 7), 5);
      }
    }
    // fetch-once, and exactly the preflight's keys
    expect(new Set(fetched).size).toBe(fetched.length);
    const preflight = new Set(bricksForIntervalAttribute(geom, picksA, picksB)
      .map(({ i, j, k }) => `${i}-${j}-${k}`));
    expect(new Set(fetched)).toEqual(preflight);
  });

  test('isofrequency extraction produces live values at live picks', async () => {
    const picks = new Float32Array(NIL * NXL).fill(8);
    picks[7] = NULL_VALUE;
    const out = await extractHorizonIsofrequency(getBrick, geom, picks, {
      freqHz: 30, window: 4, dtUs: 4000,
    });
    expect(out[7]).toBe(NULL_F32);
    let live = 0;
    for (let c = 0; c < out.length; c++) {
      if (!isNull(out[c])) {
        expect(out[c]).toBeGreaterThanOrEqual(0);
        live += 1;
      }
    }
    expect(live).toBe(NIL * NXL - 1);
  });

  test('parameter validation refuses loudly', async () => {
    const picks = new Float32Array(NIL * NXL).fill(8);
    await expect(extractHorizonIsofrequency(getBrick, geom, picks, {
      freqHz: 200, window: 4, dtUs: 4000,      // beyond 125 Hz Nyquist
    })).rejects.toThrow(/outside/);
    await expect(extractHorizonIsofrequency(getBrick, geom, picks, {
      freqHz: 30, window: 1, dtUs: 4000,
    })).rejects.toThrow(/at least 2/);
    await expect(extractIntervalAttribute(getBrick, geom, picksA, picksB, { mode: 'value' }))
      .rejects.toThrow(/Unknown interval mode/);
    expect(INTERVAL_MODES.map((m) => m.key)).toEqual(['rms', 'mean', 'max_abs']);
  });
});
