// Discontinuity attribute (interpreter program Wave 2 / W2.3): windowed
// semblance-based variance over a lateral trace neighborhood — the
// fault-detection workhorse. High variance = low local waveform
// coherence = a lateral break (fault, channel edge, noise).
//
// Recipe (pinned by the Python oracle goldens in
// test-data/seismolord/discontinuity/, generated by the Suite's
// self-asserting tools/validation/seismolord/attributes/
// gen_discontinuity.py):
// - neighborhood: the (2r+1)^2 traces centred on (il, xl), clipped to
//   the survey; dead traces (all-null) are simply absent;
// - per output sample t, over vertical lags w in [-hw, +hw] with
//   t+w inside the trace: every LIVE (trace, sample) pair contributes;
//   with n_w live values x_i at lag w,
//     num += (sum_i x_i)^2 / n_w
//     den += sum_i x_i^2
// - semblance = num / den (den == 0, an all-zero window, counts as
//   perfectly coherent); variance = 1 - semblance, clamped to [0, 1];
// - output is NULL where the CENTER sample is null, or when fewer than
//   2 live traces cover the neighborhood (variance of one trace is
//   meaningless).
//
// Pure math, worker-safe, no I/O.

import { NULL_VALUE } from './manifest';

const NULL_LIM = 1.0e29;
const isNull = (v) => Math.abs(v) > NULL_LIM;

/**
 * Windowed semblance variance for one output trace.
 *
 * @param {Float32Array} center the (il, xl) trace, ns samples
 * @param {Float32Array[]} neighborhood ALL live traces of the
 *   neighborhood INCLUDING the center (order irrelevant)
 * @param {number} halfWindow vertical half-window in samples, >= 0
 * @param {Float32Array} out ns samples
 */
export function varianceTrace(center, neighborhood, halfWindow, out) {
  const ns = center.length;
  if (neighborhood.length < 2) {
    out.fill(NULL_VALUE);
    return;
  }
  const hw = Math.max(0, Math.floor(halfWindow));
  const nTr = neighborhood.length;

  // Per-lag prefix sums over the neighborhood: sum, sum of squares and
  // live count per sample row, so each output sample is O(hw) not
  // O(hw * traces).
  const rowSum = new Float64Array(ns);
  const rowSum2 = new Float64Array(ns);
  const rowN = new Int32Array(ns);
  for (let i = 0; i < nTr; i++) {
    const tr = neighborhood[i];
    for (let s = 0; s < ns; s++) {
      const v = tr[s];
      if (isNull(v)) continue;
      rowSum[s] += v;
      rowSum2[s] += v * v;
      rowN[s] += 1;
    }
  }

  for (let t = 0; t < ns; t++) {
    if (isNull(center[t])) {
      out[t] = NULL_VALUE;
      continue;
    }
    let num = 0;
    let den = 0;
    const w0 = Math.max(0, t - hw);
    const w1 = Math.min(ns - 1, t + hw);
    for (let w = w0; w <= w1; w++) {
      const n = rowN[w];
      if (n === 0) continue;
      num += (rowSum[w] * rowSum[w]) / n;
      den += rowSum2[w];
    }
    if (den === 0) {
      out[t] = 0;                       // silent window: perfectly coherent
      continue;
    }
    const variance = 1 - num / den;
    out[t] = variance < 0 ? 0 : variance > 1 ? 1 : variance;
  }
}

/** Discontinuity registry (neighborhood attributes — these run through
 *  runNeighborhoodJob, not the per-trace pipeline). */
export const DISCONTINUITY_DEFS = {
  variance: {
    key: 'variance',
    label: 'Variance (discontinuity)',
    unit: 'frac',
    neighborhood: true,
    params: {
      windowMs: { label: 'Vertical window (ms)', default: 40, min: 4, max: 400 },
      radius: { label: 'Trace radius', default: 1, min: 1, max: 2 },
    },
  },
};

/**
 * Build the neighborhood compute for a discontinuity attribute.
 * @param {string} name DISCONTINUITY_DEFS key
 * @param {Object} params {windowMs, radius}
 * @param {{dtUs: number}} volume sampling
 * @returns {{radius: number,
 *   compute: (getTrace: (il:number, xl:number) => ?Float32Array,
 *             il: number, xl: number, out: Float32Array) => void}}
 *   getTrace returns null outside the survey; all-null traces count as
 *   dead and are excluded by the compute
 */
export function makeNeighborhoodCompute(name, params, { dtUs }) {
  const def = DISCONTINUITY_DEFS[name];
  if (!def) throw new Error(`Unknown discontinuity attribute "${name}".`);
  if (!(dtUs > 0)) throw new Error(`Discontinuity compute needs a positive dt, got ${dtUs}.`);
  const dtMs = dtUs / 1000;
  const windowMs = params?.windowMs ?? def.params.windowMs.default;
  if (!(windowMs > 0)) throw new Error(`Vertical window ${windowMs} ms is not usable.`);
  const hw = Math.max(1, Math.round(windowMs / 2 / dtMs));
  const radius = Math.max(1, Math.min(4, Math.floor(params?.radius ?? def.params.radius.default)));

  const isLive = (tr) => {
    for (let s = 0; s < tr.length; s++) {
      if (!isNull(tr[s])) return true;
    }
    return false;
  };

  return {
    radius,
    compute: (getTrace, il, xl, out) => {
      const center = getTrace(il, xl);
      if (!center) {
        out.fill(NULL_VALUE);
        return;
      }
      const hood = [];
      for (let di = -radius; di <= radius; di++) {
        for (let dj = -radius; dj <= radius; dj++) {
          const tr = getTrace(il + di, xl + dj);
          if (tr && isLive(tr)) hood.push(tr);
        }
      }
      varianceTrace(center, hood, hw, out);
    },
  };
}
